### ISSUE TITLE
Is this limited to scripting game logic at the moment?

### ISSUE THREAD

**Issue by crispy4004** [20tab/UnrealEnginePython#1]
Excited by the prospect of using Python to automate actions in the editor like moving files around, assigning materials, importing meshes, querying asset data, and communicating with external python tools.  I'm wondering if any of this is possible with the current state of this plug-in.  Using python in conjunction with blueprints sounds like a great augmentation, but the most potential I see here is making up for Unreal4's lack of a more general scripting interface.

Really awesome work btw!  I'll be watching this.

**Comment by 20tab** [comment]
Hi, thanks for your interest, our idea is to add a 'python shell' in the editor from which you can run custom scripts (or direct commands).

Currently the api already allows heavy introspection, what is missing is running code from the editor (and not the runtime) but it will be an easy addition (maybe even tomorrow)

We plan to announce the first public release of the project before the GDC

**Comment by rdeioris** [comment]
Here it is:  https://github.com/20tab/UnrealEnginePython/blob/master/PythonConsole.md

i close the issue since from now on editor scripting is a core feature

**Comment by crispy4004** [comment]
Thanks for the Update!  I've been experimenting with the plugin over the past two weeks and I have to say it's really great being able to use Python in the engine.  I was actually able use python's xml-rpc module to communicate with the engine from another python console.

I don't know if this is possible yet, but have you by any chance attempted to perform any of the Asset Type Actions (re-importing, assigning skeletons, importing LODs, etc) to uAssets in the Content Browser?  Probably too early for me to be trying any of this, but I just thought I'd ask before continuing and getting stuck.

**Comment by rdeioris** [comment]
I am about to push an update with an asset importer. this should be another step forward :)

**Comment by rdeioris** [comment]
Asset importer has been pushed: https://github.com/20tab/UnrealEnginePython/blob/master/PythonConsole.md#asset-importing
