### ISSUE TITLE
How to call python method through uobject?

### ISSUE THREAD

**Issue by emin63** [20tab/UnrealEnginePython#104]
Thanks for this wonderful plugin!

As I work more with this I find myself stuck in the following situation:

  1. I have a python class, Foo, representing a UE4 object.
  2. Foo has a UE4 property OtherActor which will be set inside blueprint to be another instance of a UE4 object mapped to the Foo python class.
  3. I want a python method inside Foo to take OtherActor and call a python method.

Basically I want something like

```
class Foo:
    def tell_other_go_boom(self):
        self.uobject.OtherActor.go_boom(5)

    def go_boom(self, delay):
        ue.log('Will go boom in %s seconds' % str(delay)

```

I've read the docs and tried various hacks but can't find a way to make this happen. The closest I've come is creating a custom event in Blueprint called GoBoomEvent and having that use CallPythonActorMethod with method name go_boom. I guess that works but it seems really ugly. Is there a better way?

Thanks.

**Comment by rdeioris** [comment]
You are rirght, the docs does not mention it :(

```py
import unreal_engine as ue

class Foo:
    def tell_other_go_boom(self):
        self.uobject.OtherActor.get_py_proxy().go_boom(5)

    def go_boom(self, delay):
        ue.log('Will go boom in %s seconds' % str(delay))
```

self.uobject is a reference to the PyActor UObject, but instead you want to access its proxy class (the Foo one). The get_py_proxy() method returns the python custom class object mapped to an actor. Feel free to make a pull request in the README for this usage :)

**Comment by emin63** [comment]
Thanks, that worked great. I am submitted a pull request with a discussion of this in the README so I'm closing this issue.
