### ISSUE TITLE
python27 unreal_engine.exec () error!

### ISSUE THREAD

**Issue by sun5471** [20tab/UnrealEnginePython#106]
>>> ue.exec('test.py')
invalid syntax (<string>, line 1)

**Comment by rdeioris** [comment]
Hi, it looks like your report has been truncted/escaped, use triple quotes for pasting python code.

By the way paste the first line of test.py

**Comment by sun5471** [comment]
When I not pass any parameters or pass the sample py,that is still an error
```
>>> import unreal_engine as ue
>>> ue.exec
invalid syntax (<string>, line 1)
```
I think something is conflict,and I have modified the python api exec function name, The error disappeared. But ue4 crash.
 When Debug run to FUnrealEnginePythonModule::RunFile->fclose(fd) ,Ue4 triggered a breakpoint and crash!
Have someone test  success in Python27?

**Comment by rdeioris** [comment]
Hi, does it work with python3 ? (you do not need to install python3, you can take the binary embedded version)

**Comment by sun5471** [comment]
I use Python3.5 to test can be work,But Python2.7 prompt the error above.

**Comment by rdeioris** [comment]
Ok, thanks for reporting, maybe i broke something during latest packaging. I'll check it soon

**Comment by rdeioris** [comment]
This has been fixed in latest commit, unfortunately a ugly hack has been required as 'exec' (being a reserved builtin keywords) fakes the parser. So on python2 you have to use ue.py_exec(file)

**Comment by osstony** [comment]
Before this gets widely used could we possibly have the name of the exec function be exec_ instead? The underscore at the end is common convention used elsewhere to get around the reserved keyword issue.

**Comment by rdeioris** [comment]
@osstony  ok, i'll add it instead of py_exec
