### ISSUE TITLE
Calling get_material_vector_parameter results in segfault

### ISSUE THREAD

**Issue by matthewkapfhammer** [20tab/UnrealEnginePython#107]
Win 10
UE-4.14.3
UnrealEnginePython_20170115_python27.zip

I finally hit a use case that required calling get_material_vector_parameter and it's causing a segfault for some reason:
```python
material_instance.get_material_vector_parameter(parameter_name)
```
I doubled checked the type and I get a segfault on both:
```
        Color_Base: MaterialExpressionVectorParameter
        Color_Tip: MaterialExpressionVectorParameter
```

If you can't repro, let me know if there's a log/crash report worth sending.

Cheers,
MK

**Comment by rdeioris** [comment]
Can you try withe latest binaries (20170117) ?

**Comment by matthewkapfhammer** [comment]
Working now. Cheers!
