### ISSUE TITLE
ERROR: UBT ERROR: Failed to produce item: ... libUE4Editor-UnrealEnginePython.so

### ISSUE THREAD

**Issue by frimalance** [20tab/UnrealEnginePython#109]
Hello.
We have a Unreal on Linux Centos 7 that can build C++ projects.
I added the Plugins folder, imported the UnrealEnginePython, made the change to "python27" and tried to run the project again.  I got errors. As you stated, I post the related log lines as an issue:

In file included from /usr/include/python2.7/Python.h:8:
In file included from /usr/include/python2.7/pyconfig.h:6:
/usr/include/python2.7/pyconfig-64.h:1182:9: error: '_POSIX_C_SOURCE' macro
      redefined [-Werror,-Wmacro-redefined]
#define _POSIX_C_SOURCE 200112L
        ^
/usr/include/features.h:168:10: note: previous definition is here
# define _POSIX_C_SOURCE        200809L
         ^
In file included from /home/plalancette/Documents/Unreal Projects/MyProject/Plugins/UnrealEnginePython/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/UnrealEnginePython/Module.UnrealEnginePython.cpp:2:
In file included from /home/plalancette/Documents/Unreal Projects/MyProject/Plugins/UnrealEnginePython/Source/UnrealEnginePython/Private/UnrealEnginePythonPrivatePCH.h:22:
In file included from /usr/include/python2.7/Python.h:8:
In file included from /usr/include/python2.7/pyconfig.h:6:
/usr/include/python2.7/pyconfig-64.h:1204:9: error: '_XOPEN_SOURCE' macro
      redefined [-Werror,-Wmacro-redefined]
#define _XOPEN_SOURCE 600
        ^
/usr/include/features.h:170:10: note: previous definition is here
# define _XOPEN_SOURCE  700
         ^
2 errors generated.
In file included from /home/plalancette/Documents/Unreal Projects/MyProject/Plugins/UnrealEnginePython/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/UnrealEnginePython/Module.UnrealEnginePython.cpp:11:
/home/plalancette/Documents/Unreal Projects/MyProject/Plugins/UnrealEnginePython/Source/UnrealEnginePython/Private/UEPyEditor.cpp:406:91: error: 
      too many arguments to function call, expected 3, have 4
  ...ObjectTools::DuplicateSingleObject(u_object, pgn, refused_packages, false);
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                  ^~~~~
Editor/UnrealEd/Public/ObjectTools.h:149:2: note: 'DuplicateSingleObject'
      declared here
        UNREALED_API UObject* DuplicateSingleObject(UObject* Object, con...
        ^
<command line>:73:22: note: expanded from here
#define UNREALED_API DLLIMPORT
                     ^
Runtime/Core/Public/Linux/LinuxPlatform.h:82:21: note: expanded from macro
      'DLLIMPORT'
#define DLLIMPORT                       __attribute__((visibility("default")))
                                        ^
3 errors generated.
ERROR: UBT ERROR: Failed to produce item: /home/plalancette/Documents/Unreal Projects/MyProject/Plugins/UnrealEnginePython/Binaries/Linux/libUE4Editor-UnrealEnginePython.so
Total build time: 377.38 seconds
LogHAL: Child 12234 is no longer running (zombie), Wait()ing immediately.
LogHAL: Child 12234's return code is 5.
LogInit:Warning: Still incompatible or missing module: libUE4Editor-UnrealEnginePython.so
LogInit:Warning: Still incompatible or missing module: libUE4Editor-PythonConsole.so

**Comment by frimalance** [comment]
It work.

In my:

/home/plalancette/Documents/Unreal Projects/MyProject/Plugins/UnrealEnginePython/Source/UnrealEnginePython/Private/UEPyEditor.cpp

I add:

/* Define to activate features from IEEE Stds 1003.1-2001 */
**# undef _POSIX_C_SOURCE**
#define _POSIX_C_SOURCE 200112L

/* Define to the level of X/Open that your system supports */
**# undef _XOPEN_SOURCE**
#define _XOPEN_SOURCE 600

in
 /home/plalancette/Documents/Unreal Projects/MyProject/Plugins/UnrealEnginePython/Source/UnrealEnginePython/Private/UEPyEditor.cpp

I change:

UObject *new_asset = ObjectTools::DuplicateSingleObject(u_object, pgn, refused_packages, false);

for:

UObject *new_asset = ObjectTools::DuplicateSingleObject(u_object, pgn, refused_packages);

And now, all seem to work.

**Comment by rdeioris** [comment]
Hi, thanks for reporting.

I need to update the Linux build procedure as i did for windows and mac. In the mean time do you want to make a pull request for your patch ?

**Comment by frimalance** [comment]
I am more a 3D script-er than a programmer. I have little to no experience GIT and little interest to make a pull. You will update it eventually. It is fine with me.


.
Pierre Lalancette
Directeur Technique / Technical Director
.
T  +1 (418) 529-9697    M      frimastudio.com<http://frimastudio.com>


Ce courriel pourrait contenir des renseignements confidentiels ou privilégiés. Si vous n'êtes pas le véritable destinataire, veuillez nous en aviser immédiatement. Merci.
This email may contain confidential or privileged information. If you are not the intended recipient, please notify us immediately. Thank you.

________________________________
De : rdeioris <notifications@github.com>
Envoyé : 23 janvier 2017 13:50:16
À : 20tab/UnrealEnginePython
Cc : Pierre Lalancette; Author
Objet : Re: [20tab/UnrealEnginePython] ERROR: UBT ERROR: Failed to produce item: ... libUE4Editor-UnrealEnginePython.so (#109)


Hi, thanks for reporting.

I need to update the Linux build procedure as i did for windows and mac. In the mean time do you want to make a pull request for your patch ?

-

**Comment by rdeioris** [comment]
@frimalance no problem, i will soon update the linux build system with your patch too. Thanks again
