### ISSUE TITLE
Accessing Plugin Properties

### ISSUE THREAD

**Issue by matthewkapfhammer** [20tab/UnrealEnginePython#110]
Is there an existing way to access the installed plugins to do the following?
- Get a list of all installed plugins.
- Access a plugin to get its "Plugin Properties".

Thanks!
MK

**Comment by rdeioris** [comment]
HI, for listing plugin i think we can use this:

https://docs.unrealengine.com/latest/INT/API/Runtime/Projects/Interfaces/IPluginManager/GetDiscoveredPlugins/index.html

for properties this is what we can get from the api

https://docs.unrealengine.com/latest/INT/API/Runtime/Projects/Interfaces/IPlugin/index.html

or you mean something different for "plugin properties" ?

**Comment by matthewkapfhammer** [comment]
Yes. I'm mostly after the installed plugin name, version, and content. 

It looks like IPlugin::GetDescriptor should return that info and as json, too:
https://docs.unrealengine.com/latest/INT/Programming/Plugins/index.html#plugindescriptorfiles

```json
{
    "FileVersion" : 3,

    "FriendlyName" : "UObject Example Plugin",
    "Version" : 1,
    "FriendlyVersion" : "1.0",
    "Description" : "An example of a plugin which declares its own UObject type. This can be used as a starting point when creating your own plugin.",
    "Category" : "Programming Examples.Plugins",

    "Modules" :
    [
        {
            "Name" : "UObjectPlugin",
            "Type" : "Developer"
        }
    ]
}
```

**Comment by rdeioris** [comment]
Hi, the plugin API has been pushed:

https://github.com/20tab/UnrealEnginePython/blob/master/docs/Plugin_API.md

**Comment by matthewkapfhammer** [comment]
Thanks!!
