### ISSUE TITLE
Accessing EditorAppearance>Units 

### ISSUE THREAD

**Issue by matthewkapfhammer** [20tab/UnrealEnginePython#112]
Has access to the "Editor Appearance"> "Units" properties been exposed in the API yet?

Scroll to the images in: https://answers.unrealengine.com/questions/303842/change-editor-units-from-centimeters-to-meters.html

**Comment by rdeioris** [comment]
Here it is: https://github.com/20tab/UnrealEnginePython/blob/master/docs/Settings.md
