### ISSUE TITLE
exec not working

### ISSUE THREAD

**Issue by frimalance** [20tab/UnrealEnginePython#113]
With the Python for Unreal on Centos7 linux, I am unable to run a external script: 

>>> import unreal_engine as ue
>>> ue.exec('ue_site.py')
**invalid syntax (<string>, line 1)**

But it will run at start up:

LogPython: This is the ue_site.py file that runs at start up 
LogPython: **ue_site Python module successfully imported**

'exec' is the only command I can make to work. Any Idea what I am doing wrong?

**Comment by rdeioris** [comment]
Unfortunately on python2 we canot use 'exec'. Use 'py_exec' like described here:

https://github.com/20tab/UnrealEnginePython/issues/106

if you pull the latest code you should be able to use it.

Note: very probably it will be renamed exec_ before an official release

**Comment by frimalance** [comment]
py_exec worked fine.  I missed that one. Thanks.
