### ISSUE TITLE
Undo

### ISSUE THREAD

**Issue by sinokgr** [20tab/UnrealEnginePython#114]
Hi guys,

Is there any way to support the undo system? I've set a few materials for example using python, and I then wanted to go back, but I couldn't.

Cheers,
Nick

**Comment by rdeioris** [comment]
The Transactions api has been implemented in latest code:

https://github.com/20tab/UnrealEnginePython/blob/master/docs/Transactions_API.md

**Comment by sinokgr** [comment]
Ooops, sorry @rdeioris . I was away for quite some time so I probably missed that. Thanks
