### ISSUE TITLE
Reference Viewer

### ISSUE THREAD

**Issue by CountZer0** [20tab/UnrealEnginePython#115]
Is there a way to access the Reference Viewer or even just find out if an asset is referenced by any other objects via UEPython? This would be handy to find unused assets in a project. Thanks.

**Comment by rdeioris** [comment]
Assets dependencies/references functions have been added:

https://github.com/20tab/UnrealEnginePython/blob/master/docs/ManagingAssets.md#asset-dependenciesreferencers
