### ISSUE TITLE
Support for ScriptStructs

### ISSUE THREAD

**Issue by matthewkapfhammer** [20tab/UnrealEnginePython#116]
Hiya,

In https://github.com/20tab/UnrealEnginePython/blob/master/docs/uobject_API.md, you note that "currently structs are not supported". 

I have a top level parameter on a component that returns "<unreal_engine.UObject 'ScriptStruct' (0x00000230E7F08B80) UClass 'Class'>" for the get_class method. I can still run the get_property method on that UObject and it still returns data, but none of it matches the GUI, e.g. No matter what is in the GUI's value I get a return value of -7.58797674668e-35 for a property on the object of the ScriptStruct class. 

I was wondering if support for querying ScriptStruct params is something on your radar and if not, that you could maybe add a NotImplementedError or something appropriate to let users know that the data isn't accurate yet.

Thank you!
MK

**Comment by rdeioris** [comment]
Hi, it is heavily worked, it should be ready soon. Currently the data you get are from the UScriptStruct class not its "instance", so they are basically useless. An unreal_engine.UScriptStruct class has been created out of the UObject concept.

**Comment by matthewkapfhammer** [comment]
Oh, cool. It's doesn't sound like it makes a lot of sense to bother with the NotImplementedError in that case. If you're tracking progress elsewhere, I see no reason not to close this issue.

Cheers,
MK

**Comment by rdeioris** [comment]
Hi, structs support has been finally merged: https://github.com/20tab/UnrealEnginePython/blob/master/README.md#the-automagic-uclass-ustruct-and-uenums-mappers

**Comment by matthewkapfhammer** [comment]
This is working well. 

Thanks!
