### ISSUE TITLE
get_material_scalar_parameter returns inaccurate value for MaterialExpressionStaticSwitchParameter

### ISSUE THREAD

**Issue by matthewkapfhammer** [20tab/UnrealEnginePython#117]
Win 10
UE-4.14.3
UnrealEnginePython_20170117_4_14_python27.zip

Hi,

In #103, I missed the fact that get_material_scalar_parameter always returns 0.0 when querying params of the MaterialExpressionStaticSwitchParameter class type regardless of the actual value. The material instance was created from a material that was built from blueprint. 

I can't send a full repro, but this is essentially what I'm doing:
```python
        all_components = actor.get_components()
        component = all_components[0]
        material_instance = component.get_property('Material')
        material_parent = material_instance.Parent
        expr = material_parent.Expressions[0]
        for expression in material_parent.Expressions:
            parameter_group = expression.Group
            parameter_name = expression.ParameterName
            expression_type = expression.get_class().get_name()
            if expression_type == 'MaterialExpressionStaticSwitchParameter':
                parameter_value = material_instance.get_material_scalar_parameter(parameter_name)
```

Do you think that this another case of the default class values being accessed, instead of the class instance?

Thanks!
MK

**Comment by rdeioris** [comment]
Hi, i have added get_material_static_switch_parameter(name) for accessing 'MaterialExpressionStaticSwitchParameter'

**Comment by matthewkapfhammer** [comment]
That's working well for 'MaterialExpressionStaticSwitchParameter'. And it also seems to work for 'MaterialExpressionStaticBoolParameter' as well. 

Thanks!
