### ISSUE TITLE
Crash when spawning a blueprint object on interaction with object

### ISSUE THREAD

**Issue by Mann-Rob** [20tab/UnrealEnginePython#118]
Hi Bit of a noob when it comes to working with unreal hoping someone can point me in the right direction with this. 

I've set up a player ineteractive object, which includes the following python code: 

```
def interact(self):        
        self._debug("Interacting with python Object: %s" % self.Name)
        #chip_class = ue.find_class("BP_Isolinear_Chip_Command")
        a_iso_chip = ue.load_object(Blueprint, "/Game/Trek_Assets/Interior/Items/Isolinear_chips/BP_Isolinear_Chip_Command.BP_Isolinear_Chip_Command")  
        a_iso_chip.set_actor_location(-103.0, -145.0, 96.0)
        self._debug("Actor Test: %s" % a_iso_chip)
        self.uobject.get_owner().Python_Reverse_Call("This Variable was returned by Python")
```
Note: _debug is a substitute for pythons print function. 

My goal is to get the blueprint object to spawn in at a certain position, the rest of the code works fine until i try to use set_actor_location or 
`self.uobject.actor_spawn(a_iso_chip, FVector(-103.0, -145.0, 96.0), FRotator(0, 0, 0))`

In both instances i'm getting hard crashes with no error logs or information to help me debug, im hoping im just missing something obvious which someone can point out or if i need to rethink my approach

Cheers

**Comment by rdeioris** [comment]
Hi, first of all actors must be spawned in the world. Otherwise you cannot set their properties. In addition to this, a Blueprint object, represent the "serialized asset", while instead you want the class represented by it:


```python
a_iso_chip = ue.load_object(Blueprint, "/Game/Trek_Assets/Interior/Items/Isolinear_chips/BP_Isolinear_Chip_Command.BP_Isolinear_Chip_Command")
self.uobject.actor_spawn(a_iso_chip.GeneratedClass, FVector(-103.0, -145.0, 96.0), FRotator(0, 0, 0))
```

So, the key here is using the GeneratedClass property of the Blueprint class

**Comment by rdeioris** [comment]
I have added special notes for blueprint spawning: https://github.com/20tab/UnrealEnginePython/blob/master/README.md#spawning-notes

i will try to make the actor_spawn function smarter so it will recognize Blueprint class and will throw an exception

**Comment by Mann-Rob** [comment]
Thank you, thats worked perfectly now just what i needed
