### ISSUE TITLE
Trying this out for 4.15

### ISSUE THREAD

**Issue by daeilkim** [20tab/UnrealEnginePython#120]
I don't know if there has been any work on testing this plugin for 4.15, but there seems to be a bunch of errors that I ran into when compiling from source in windows. 

![capture](https://cloud.githubusercontent.com/assets/3966792/22839005/96648d50-ef95-11e6-9762-f3ee288be9b2.PNG)

I know it's still in preview, but thought it'd be worth bringing these to light, especially if they are easy fixes.

**Comment by rdeioris** [comment]
I am working on it right now :)

**Comment by rdeioris** [comment]
Pull the latest code and it should work (albeit a lot of warnings will be spit out about my plain c-like usage of #ifdef)

**Comment by daeilkim** [comment]
it works! 👍
