### ISSUE TITLE
Access Violations, Out of memory Exceptions when using as_dict()

### ISSUE THREAD

**Issue by MeMaMoo** [20tab/UnrealEnginePython#127]
Hi,

Using UE4.15, and the code for UnrealEnginePython checked out within the last hour:

I've just started trying to use UnrealEnginePython, and it looks great.

I'm not sure if the issue I'm having is something I'm doing wrong, or is an actual bug.  I've tried to debug it, but have so far had no luck.

With the game not-running (also seems to occur when it's running, but mainly I'm trying it when it's not), if I do a little script in the python console debug window such as:

import unreal_engine as ue
ue.find_object("TextRenderActor").as_dict()

I get various crashes, depending on what types are in the properties.

If it is a String, it seems to have a Out Of Memory error (is trying to allocate a -ve amount of memory)
If it is a UObjectPropertyBase, I get an access violation (appears that the value retrieved from GetObjectPropertyValue_InContainer is invalid.

I was able to reproduce the Access violation very easily by creating a new C++/Third Person project, adding UnrealPython to it, starting the editor, and typing the above script into the python console (with the game not running).

The other issue (with a string, was in a more complete project, but I'm thinking that perhaps they're related).  If you'd like that one as well please let me know, and I'll spend some time creating a cut down project.

Thanks for your time,
- Mark

**Comment by rdeioris** [comment]
Hi Mark, briefly looking as as_dict() it looks like it needs some work for be aligned with latest development. I will put down a related test suite as soon as possible. Thanks for reporting.

**Comment by rdeioris** [comment]
So, basically running as_dict() on plain classes wan not valid because, well, they are no instances :) The new implementation (feel free to pull the latest code) ensures to call as_dict() on the class default object:

```python
# note: faster than using find_object
from unreal_engine.classes import TextRenderActor

# returns dictionary of class default object
print(TextRenderActor.as_dict())

actor = ue.get_editor_world().actor_spawn(TextRenderActor)
# returns dictionary of the spawned actor
print(actor.as_dict())
```
