### ISSUE TITLE
Creating new folders

### ISSUE THREAD

**Issue by MatzeOGH** [20tab/UnrealEnginePython#128]
Hi there,
I was tying out the plugin and as a test I wanted to setup some kind of folder structure for a unreal project. 
As far as I understand it this kind of feature isn't supported.
To be fair I'm really new to python and don't fully understand how everything is working yet.

**Comment by rdeioris** [comment]
Hi, check this doc:  https://github.com/20tab/UnrealEnginePython/blob/master/docs/ManagingAssets.md

as you can see directories are created on-demand.

If you need to manually create them (out of the packages/assets contexts) you can use the python os.mkdir()

**Comment by MatzeOGH** [comment]
oh. thanks

**Comment by ekermer** [comment]
Hi,
may I suggest to integrate some managing for folders too? At least a function for deleting folders will be useful. Otherwise you are constantly changing between the unreal /Game/ path-convention and the systems-path-convetion (C:/...).
