### ISSUE TITLE
Custom Enum Values

### ISSUE THREAD

**Issue by LarsGroh** [20tab/UnrealEnginePython#130]
I created an enum in the editor and added some values to it.
When I import it and try to access tha values they show up as this:
```
>>>  from unreal_engine.enums import MyCustomEnum
>>>  ue.log(MyCustomEnum.enum_values())
[u'NewEnumerator0', u'NewEnumerator1', u'NewEnumerator2']
```

Hence I can only use them as MyCustomEnum.NewEnumerator0, even though the real value names are:
"House", "Tree", "Cat".

Am I doing this wrong?

**Comment by rdeioris** [comment]
Until 4.14 there is the DisplayName properties in the enum class:

```python
from unreal_engine.enums import MyCustomEnum
ue.log(MyCustomEnum.DisplayNames)
```

in 4.15 has been replaced with a MapProperty.

I think the UObject class could be extended to return the enum value automatically

**Comment by LarsGroh** [comment]
Thanks for the reply -  I am using 4.15
Can you elaborate a bit more?

When I try to call  DisplayNames, I get:
In asset 'None', there is an enum property of type 'MyCustomEnum' with an invalid value of 'DisplayNames'

I would I access the MapProperty?

**Comment by rdeioris** [comment]
currently the MapProperty is not supported (i think it would need a mapping to a python dictonary but i am not sure about it). The main problem is that enum names are stored in metadatas, so once you build the project that values are lost. I can expose the displayname in the editor, but on runtime you will need some other solution.

**Comment by rdeioris** [comment]
In the man time, i am investigating if the new map can be of use for solving the issue

**Comment by rdeioris** [comment]
Can you try if with the latest code works ?

Basically user defined names can be supported only in 4.15.

You can access them with .enum_names() or directly with EnumClass.EnumName like with properties
