### ISSUE TITLE
Loading my project using IntelPython 3.5 after successfully building it fails.

### ISSUE THREAD

**Issue by kafeak** [20tab/UnrealEnginePython#131]
Intel Distribution for Python 3.5 Update 2 <Windows 10> Unreal Engine 4.14.3
**_This is the call stack when I debug with Visual Studio 2015:_**
 	ucrtbase.dll!00007ffbc0eeea1e()	Unknown
 	python35.dll!000000006f751159()	Unknown
 	python35.dll!000000006f74f84c()	Unknown
>	UE4Editor-UnrealEnginePython.dll!FUnrealEnginePythonModule::StartupModule() Line 92	C++
 	UE4Editor-Core.dll!FModuleManager::LoadModuleWithFailureReason(const FName InModuleName, EModuleLoadResult & OutFailureReason, const bool bWasReloaded) Line 485	C++
 	UE4Editor-Projects.dll!FModuleDescriptor::LoadModulesForPhase(ELoadingPhase::Type LoadingPhase, const TArray<FModuleDescriptor,FDefaultAllocator> & Modules, TMap<FName,enum EModuleLoadResult,FDefaultSetAllocator,TDefaultMapKeyFuncs<FName,enum EModuleLoadResult,0> > & ModuleLoadErrors) Line 409	C++
 	UE4Editor-Projects.dll!FPluginManager::LoadModulesForEnabledPlugins(const ELoadingPhase::Type LoadingPhase) Line 592	C++
 	UE4Editor.exe!FEngineLoop::LoadStartupModules() Line 2229	C++
 	UE4Editor.exe!FEngineLoop::PreInit(const wchar_t * CmdLine) Line 1668	C++
 	UE4Editor.exe!GuardedMain(const wchar_t * CmdLine, HINSTANCE__ * hInInstance, HINSTANCE__ * hPrevInstance, int nCmdShow) Line 113	C++
 	UE4Editor.exe!GuardedMainWrapper(const wchar_t * CmdLine, HINSTANCE__ * hInInstance, HINSTANCE__ * hPrevInstance, int nCmdShow) Line 126	C++
 	UE4Editor.exe!WinMain(HINSTANCE__ * hInInstance, HINSTANCE__ * hPrevInstance, char * __formal, int nCmdShow) Line 202	C++

**Comment by rdeioris** [comment]
Hi, never used Intel Python but i did not get if your module simply fails to load or generate a crash

**Comment by kafeak** [comment]
It used to give me a message saying it fails to load to module, now it just crashes and gives me the option to debug. I'm using 4.14.3 version of unreal engine and on windows 10, but the problem goes away with 3.5 from python.org. Problem is I want to use scipy, which needs Intel Math Kernel Library, that's neatly bundled in Intel Distribution for Python among numerous other performance increasing libraries and scientific python libraries.

**Comment by rdeioris** [comment]
Ok, i,ll try investigating it

**Comment by rdeioris** [comment]
Ok, it took

**Comment by rdeioris** [comment]
Can we close it ?
