### ISSUE TITLE
support for UE4 console commands

### ISSUE THREAD

**Issue by MatzeOGH** [20tab/UnrealEnginePython#133]
I'd like to create a QT application that executes some UE4 console commands by clicking some buttons.
Is there a way of doing that currently?

**Comment by rdeioris** [comment]
Currently it is not available, but it is an easy addition:

'''
UWorld->Exec(context, string)
'''

**Comment by MatzeOGH** [comment]
Oh thanks for pointing me in the right direction. 
I,ll create a pull request if you don't mind

**Comment by rdeioris** [comment]
Yes, no problem for me, thanks

**Comment by MatzeOGH** [comment]
I think that I'm not doing it correctly. I'm probably not getting the uworld I need because neither Play() nor execute_command() do anything. The log part works just fine and is only for debugging 

```
PyObject *py_ue_execute_console(ue_PyUObject *self, PyObject *args)
{
	ue_py_check(self);

	UWorld *world = ue_get_uworld(self);
	if (!world)
		return PyErr_Format(PyExc_Exception, "unable to retrieve UWorld from uobject");

	PyObject *py_message;
	if (!PyArg_ParseTuple(args, "O:log", &py_message)) {
		return NULL;
	}

	PyObject *stringified = PyObject_Str(py_message);
	if (!stringified)
		return PyErr_Format(PyExc_Exception, "argument cannot be casted to string");

	char *message = PyUnicode_AsUTF8(stringified);
	FString Command = FString::Printf(TEXT("%s"), UTF8_TO_TCHAR(message));
	world->Exec(world, *Command);
	UE_LOG(LogPython, Log, TEXT("%s"), *Command);
	Py_DECREF(stringified);

	Py_INCREF(Py_None);
	return Py_None;
}
```

```
import unreal_engine as ue

world = ue.get_editor_world()
world.play()
world.execute_command('showdebug')
```

**Comment by rdeioris** [comment]
When you play() the running world will be the PIE. I strongly suggest you to not use the editor_world as the context but an actor in the level.

**Comment by MatzeOGH** [comment]
any tips on how to get a proper world context?

**Comment by unbit** [comment]
Hi, any actor can access its world with get_world()

**Comment by rdeioris** [comment]
Hi, would you like to make a pull request or you want me to manually include the patch ?

**Comment by MatzeOGH** [comment]
I really like to but I never got it working. 
None of my attempts were successful.

**Comment by rdeioris** [comment]
Ok, i'll work on it, do not worry

**Comment by MatzeOGH** [comment]
the console variable wasn't really the problem. I failed to retrieve the UWorld for the editor

**Comment by rdeioris** [comment]
the console_exec(string) command has been added:

```python
import unreal_engine as ue

ue.get_editor_world().console_exec('your command')
```
