### ISSUE TITLE
Python Home Config Value Relative Value

### ISSUE THREAD

**Issue by osstony** [20tab/UnrealEnginePython#142]
Hello,

I need to set the value in the Python/Home DefaultEngine.ini config value to be relative to the project. For example /Game/Scripts/python27. Currently it doesn't seem to support this and the editor will crash with no warning when Py_Initialize is called. What would be the best way to get this supported? Is there an Unreal Engine way of converting paths to absolute and leaving alone paths that are already absolute? 

Also, is there a better way we can protect the engine from hard crashing when python isn't initialized properly?

Thank you!

**Comment by rdeioris** [comment]
If i remember correctly the engine starts with its cwd mapped to the path of the executable and does not change. What about using relative paths ?

```ini
[Python]
Home = ../Content/Scripts/....
```

**Comment by osstony** [comment]
@rdeioris that seems to work but unfortunately I am not distributing the plugin and scripts with the Engine but rather with the project. I am storing the necessary python scripts inside of the game's content directory.  Any other thoughts? I'm looking for a solution that will work for both relative and absolute paths so that this could be officially supported.

**Comment by osstony** [comment]
@rdeioris actually the files for PythonHome I currently have living in /Content/Scripts shouldn't live there anyhow. What I would prefer is to have them live in the Plugin directory. Is there any convention for getting the plugin directory in a config file? I've googled looking for info on any kind of tokens but I haven't found anything. What I was hoping was something like {CurrentPluginRoot}/...

**Comment by rdeioris** [comment]
No idea, i will check it soon

**Comment by osstony** [comment]
@rdeioris in the meantime I created a simple way to add in tokens if they aren't supported by default in Unreal. I tried to use curly braces {} but Unreal seems to strip them out. Perhaps there is some sort of token system I'm missing?
