### ISSUE TITLE
fixes for fedora linux

### ISSUE THREAD

**Issue by hartsantler** [20tab/UnrealEnginePython#148]
on the latest fedora with the latest unreal engine i had to make these changes to get it to compile.

line 97 from UEPyFTransform.cpp, `return NULL` is not allowed.

```c++
static int ue_py_ftransform_init(ue_PyFTransform *self, PyObject *args, PyObject *kwargs) {
	PyObject *py_translation = nullptr;
	PyObject *py_rotation = nullptr;
	PyObject *py_scale = nullptr;
	if (!PyArg_ParseTuple(args, "|OOO:__init__", &py_translation, &py_rotation, &py_scale)) {
		//return NULL; // not allowed by -Wnull-conversion
		return 0;
	}
```
line 140 from UnrealEnginePython.Build.cs
```c#
            if (pythonHome == "")
            {
                PublicIncludePaths.Add("/usr/include/python3.5m");
                PublicAdditionalLibraries.Add("/usr/lib64/libpython3.5m.so");  // fixed for fedora
            }
```

**Comment by rdeioris** [comment]
just as a side note, which version of fedora are you using ? i would like to start making linux packages too

**Comment by hartsantler** [comment]
i'm using fedora 25.
never had any problems with fpm, its a good packager.
https://github.com/jordansissel/fpm
