### ISSUE TITLE
Introduce native support for FVector and FRotator

### ISSUE THREAD

**Issue by rdeioris** [20tab/UnrealEnginePython#15]
Now that we have a solid base to work on, we can stop using single tuple for native types and introducing
wrapper for FVector and FRotator. This will remove the need for math features in the unreal_engine api

**Comment by rdeioris** [comment]
Add FHitResult, FTransform and FColor too

**Comment by 20tab** [comment]
Update: implemented FTransform, FVector, FRotator, FHitResult. Working on FColor
