### ISSUE TITLE
Static Mesh destroyed after save package

### ISSUE THREAD

**Issue by LarsGroh** [20tab/UnrealEnginePython#150]
Hi,
when I do the following my Static Mesh is suddenly totally empty:

```
import unreal_engine as ue
from unreal_engine.classes import StaticMesh
asset = ue.load_object(StaticMesh, PATH_TO_STATIC_MESH)
package_name = asset.get_outer().get_name()
asset.save_package(package_name)
```
Note: it did work in UE 4.13 and now I updated to 4.15

Regards,
Lars

**Comment by unbit** [comment]
Hi, you are not required to pass the name to save_package(). It will automatically use the right one.

By the way, you should use get_path_name() instead of get_name()

**Comment by LarsGroh** [comment]
Thanks...that solved it.
Not sure why this was different in the previous versions of Unreal - I used the exact code!
But I am actually not sure which version of the plugin that was.

**Comment by LarsGroh** [comment]
Hi,
just a note on this:

If the asset has not been saved yet (and therefore does not exist on the file system) "asset.save_package()" does not do anything. You need to pass the file path:
asset.save_package(asset.get_outer().get_path_name())
Then the asset will be saved to the file system.

**Comment by rdeioris** [comment]
@LarsGroh right, but you should try to use factories when creating new assets, they assign a package name on allocation

**Comment by LarsGroh** [comment]
@rdeioris Could you elaborate a little more on this as I actually realised that the empty Mesh issue persists. I am importing a large number of FBX files as static meshes using this code:

```
def import_static_mesh(filename, asset_path):
    factory = ue.find_class('PyFbxFactory')
    fbx_import_ui_class = ue.find_class('FbxImportUI')
    fbx_import_ui = ue.new_object(fbx_import_ui_class)
    ue.log('importing ' + filename + ' to ' + asset_path)
    # set import options
    ue.set_fbx_import_option(fbx_import_ui)
    asset = ue.import_asset(filename, asset_path, factory)
    return asset
```

I noticed there was an update to importing FBX files. So also tried the approach of this example with the same result that the mesh is sudennly empty when saving the package:
https://github.com/20tab/UnrealEnginePython/blob/master/examples/kaiju_builder.py#L20

**Comment by rdeioris** [comment]
Check this (work in progress, but should cover your needs) https://github.com/20tab/UnrealEnginePython/blob/master/tutorials/YourFirstAutomatedPipeline.md

**Comment by LarsGroh** [comment]
Thanks for the link to the tutorial. Very interesting and it demonstrates how much is possible and I will definitely need a lot of it in the future.

But I can't see where or when you are actually saving the imported assets. You can actually see in your screenshots of the content browser that the assets are marked un-saved. As I stated before I tried the FBX import approach that is showcased in your tutorial, but when I try to save the package by script, the mesh is suddenly empty.

**Comment by rdeioris** [comment]
I mean something like this:

```python
factory = PyFbxFactory()
static_mesh = factory.factory_import_object('yourfile', '/Game/Somewhere')

# do anything you need with static_mesh and finally save it

static_mesh.save_package()
```

The relevant part in the tutorial is at the end of this section: https://github.com/20tab/UnrealEnginePython/blob/master/tutorials/YourFirstAutomatedPipeline.md#creating-the-materials

**Comment by LarsGroh** [comment]
Thanks for the reply!
I will give it another go.

**Comment by rdeioris** [comment]
Does it work for you ? Please remember to close the issue  :)

**Comment by heylenz** [comment]
hi! I test save_package was not work!
```python
asset= ue.get_selected_assets()[0]
#print(xx.get_outer().get_full_name())
asset.save_package()
```
can not save package to disk!  in python console i found log
Moving 'E:/Work/workspace/Saved/None244824204606B754412D58B696F4421C.tmp' to 'None'
Finished SavePackage None

**Comment by rdeioris** [comment]
That 'None' is pretty strange.

Can you report the whole output of:
```python
asset = ue.get_selected_assets()[0]
ue.log(asset.get_full_name())
asset.save_package()
```

**Comment by heylenz** [comment]
output
```
AnimSequence /Game/Cinematics/episode002/FBX/EP002_SC001/EP002_SC001_fbx_GeRui_finaly.EP002_SC001_fbx_GeRui_finaly
Save=37.15ms
Moving 'E:/Work/workspace/Saved/None3DE080A84C5C624F68A6EFA755399E23.tmp' to 'None'
Finished SavePackage None
```

**Comment by rdeioris** [comment]
Ok, i was able to reproduce it. the Filename of the UPackage looks empty, if you use 

```python
asset.save_package(asset.get_path_name())
```
it should work, but obviously is not so elegant (and it is verry error-prone).

I will try to understand what is going on

**Comment by heylenz** [comment]
unreal engine will broken!
```
asset.save_package(asset.get_path_name())
```

**Comment by rdeioris** [comment]
Is it possible you are working over a just imported asset ? until you do not save the data the package filename will be empty

**Comment by rdeioris** [comment]
If you clone the latest code the save_package() will now managaed unsaved packages by automatically asigning a file to them

**Comment by heylenz** [comment]
yes! I use just import asset and not save! I try to save to disk,but not working!
```python
anim_factory = PyFbxFactory()
animation = anim_factory.factory_import_object(fbx_path, anim_destination)
```
I will try clone latest code!

**Comment by heylenz** [comment]
build master branch! can save_package! thanks!

**Comment by heylenz** [comment]
build master branch! can asset.save_package(） ！ thanks!
