### ISSUE TITLE
get and set blueprint nodes missing pins

### ISSUE THREAD

**Issue by hartsantler** [20tab/UnrealEnginePython#153]
using `mynode = mygraph.graph_add_node_variable_set("myvar", None, x, y)` returns a blueprint node, but its missing its pins.  `mynode.node_pins()` returns an empty array.  I tried `node_find_pin("output")` and some other names, but could not figure out how to attach its input or output to other nodes.

**Comment by rdeioris** [comment]
Hi, are you using the latest code ? this was an issue fixed in latest binary release

**Comment by hartsantler** [comment]
my code is out of sync by at least a week, so i'll update now and try again.

**Comment by hartsantler** [comment]
i just checked, and this works with the latest source.
