### ISSUE TITLE
set_name will not update a K2Node_MathExpression

### ISSUE THREAD

**Issue by hartsantler** [20tab/UnrealEnginePython#155]
```python
from unreal_engine.classes import K2Node_MathExpression
n = mygraph.graph_add_node(K2Node_MathExpression, 0,0)
n.set_name("1==1")
```

calling `set_name` on a blueprint node will not update a MathExpression node.  Maybe some extra update is required, on line 2559 of `UnrealEngine/Engine/Source/Editor/BlueprintGraph/Private/K2Node_MathExpression.cpp` i found:

```c++
void UK2Node_MathExpression::OnRenameNode(const FString& NewName)
{
	RebuildExpression(NewName);
	CachedNodeTitle.MarkDirty();
}
```

**Comment by rdeioris** [comment]
Like this:

```python
n = mygraph.graph_add_node(K2Node_MathExpression, 0,0)
n.Expression = '(3 + 7 + 11)'
n.post_edit_change()
```

**Comment by hartsantler** [comment]
i tried above and now the expression is updated, and shown on the blueprint node in the editor, but the `ReturnValue` pin is missing, and only appears after double clicking the expression and hitting enter.

Should i call `node_allocate_default_pins` after setting the expression?

**Comment by hartsantler** [comment]
i also tried using `ue.blueprint_mark_as_structurally_modified(bp)` after `n.post_edit_change()` but the `ReturnValue` pin is still missing.

right clicking the node in the blueprint editor and selecting "Refresh Nodes" will make the `ReturnValue` pin appear.

**Comment by rdeioris** [comment]
Hi, i have just added the node_reconstruct() method
