### ISSUE TITLE
how to create a ForLoopWithBreak blueprint node

### ISSUE THREAD

**Issue by hartsantler** [20tab/UnrealEnginePython#156]
i searched through the unreal source code, and could not find dedicated K2Nodes for the different types of for loops.  Instead they are implemented as macros, which i'm not sure how to construct with the python API.

```python
n = mygraph.graph_add_node(K2Node_MacroInstance, 0,0)
n.set_name("ForLoopWithBreak")
n.post_edit_change()  ## nothing happens
```
UnrealEngine/Engine/Source/Editor/BlueprintGraph/Private/K2Node_MacroInstance.cpp:
```c++
  331  		FName MacroName = FName(*MacroGraph->GetName());
  332  		if(	MacroName == TEXT("ForLoop" ) ||
  333: 			MacroName == TEXT("ForLoopWithBreak") ||
  334  			MacroName == TEXT("WhileLoop") )
  335  		{
```

**Comment by rdeioris** [comment]
Sorry fot he late, it took me a bit to undertand how the macro system works (you need latest code for the node_allocate_default_pins() function):

https://github.com/20tab/UnrealEnginePython/blob/master/docs/Graph_API.md#add-a-foreachloop-macro-node

**Comment by hartsantler** [comment]
thanks again Robb.
