### ISSUE TITLE
make a set variable blueprint node an "Array"

### ISSUE THREAD

**Issue by hartsantler** [20tab/UnrealEnginePython#159]
the current python API allows you to create a new blueprint set variable node like this.
`ue.blueprint_add_member_variable(myblueprint, "myvar", "int")`
the last argument allows you to define a type, but there seems to be no way currently to also mark it an array of the declared type.  

maybe an extension to the API like this would make sense:
`ue.blueprint_add_member_variable(myblueprint, "myvar", "int", array=True)`

**Comment by rdeioris** [comment]
https://github.com/20tab/UnrealEnginePython/blob/master/Source/UnrealEnginePython/Private/UEPyEditor.cpp#L988 The is_array argument is already there :)
