### ISSUE TITLE
Add support for ENums

### ISSUE THREAD

**Issue by rdeioris** [20tab/UnrealEnginePython#16]
Introduce unreal_engine.enums (or something similar) to get access to ENum, like we already do with classes:

https://github.com/20tab/UnrealEnginePython/blob/master/README.md#the-automagic-uclass-mapper

**Comment by Tadinu** [comment]
@rdeioris Currently, is there support for import enums in namespace like:

https://api.unrealengine.com/INT/API/Runtime/Engine/Engine/EWorldType__Type/index.html

Currently, it seems we could not run `from unreal_engine.enums import EWorldType`

**Comment by Tadinu** [comment]
@rdeioris Currently, is there support for import enums in namespace like?

https://api.unrealengine.com/INT/API/Runtime/Engine/Engine/EWorldType__Type/index.html

Currently, it seems we could not run from `unreal_engine.enums import EWorldType`.

**Comment by Tadinu** [comment]
@rdeioris Currently, is there support for import enums in namespace like:
`from unreal_engine.enums import EWorldType.Type`
https://api.unrealengine.com/INT/API/Runtime/Engine/Engine/EWorldType__Type/index.html

Thanks!

**Comment by Tadinu** [comment]
@rdeioris Currently, is there support for importing `enums` in `namespace` like:
`from unreal_engine.enums import EWorldType.Type`
https://api.unrealengine.com/INT/API/Runtime/Engine/Engine/EWorldType__Type/index.html

Thanks!
