### ISSUE TITLE
destroy_actor_component?

### ISSUE THREAD

**Issue by glenwrhodes** [20tab/UnrealEnginePython#160]
Since components can be added easily with

`newcomp = self.uobject.get_owner().add_actor_component(ue.find_class('StaticMeshComponent'), 'component')`

would it be feasible / easy enough to create the reverse?  Something like:
`self.uobject.get_owner().destroy_actor_component(newcomp)`

I've tried forcing a call to K2_DestroyComponent, but it didn't seem to work:

`newcomp.call('K2_DestroyComponent')
`
caused UE4 to complain that the component doesn't have permission to destroy itself. 

Any ideas?

Thanks!

**Comment by rdeioris** [comment]
destroy_actor_component(component) has been added.

Thanks for reporting.

**Comment by glenwrhodes** [comment]
Fantastic! Thank you!
