### ISSUE TITLE
Support for playing raw audio data?

### ISSUE THREAD

**Issue by Jay2645** [20tab/UnrealEnginePython#164]
Hello! I'm working on integrating [Google's Python code for the Google Assistant](https://github.com/googlesamples/assistant-sdk-python) into Unreal. I have a working prototype [here](https://github.com/Jay2645/Unreal-Google-Assistant) which uses this plugin to execute Google's Python code.

The issue is that it appears Google Assistant uses Python's [sounddevice](https://pypi.python.org/pypi/sounddevice) module, which uses the raw computer hardware for sound. 
Ideally, of course, there should be a way to "read" and "write" raw audio data via Unreal, in the same way as you would use the SoundDevice module. I'm familiar with `play_sound_at_location` and the like, but it appears they only take a `USoundBase` that might as well have been assigned via C++, and doesn't support sending any kind native Python objects.

In C++, I'd use a [USoundWaveProcedural](https://docs.unrealengine.com/latest/INT/API/Runtime/Engine/Sound/USoundWaveProcedural/index.html) to enqueue the raw audio data as it came in. I could do it in Python via reflection, but the more I thought about it, the more I figured I should just write the code in C++ and expose it to Python.

Before I get started on that, though, is there a way that's already implemented to accomplish this within the plugin? If not, would you be okay with me creating a pull request to add this sort of functionality into the plugin itself?

**Comment by rdeioris** [comment]
Hi @Jay2645, absolutely feel free to extend https://github.com/20tab/UnrealEnginePython/blob/master/Source/UnrealEnginePython/Private/UEPyAudio.cpp adding your required features.

Just as a note, try to use the new template based utility functions when converting from python to ue4 types: 

https://github.com/20tab/UnrealEnginePython/blob/master/Source/UnrealEnginePython/Private/UEPyEdGraph.cpp#L390

https://github.com/20tab/UnrealEnginePython/blob/master/Source/UnrealEnginePython/Private/UEPyEdGraph.cpp#L333

Not all the code has been ported to them so you may not note it

**Comment by Jay2645** [comment]
Implemented in pull request #166.
