### ISSUE TITLE
about support alembic

### ISSUE THREAD

**Issue by heylenz** [20tab/UnrealEnginePython#167]
`import unreal_engine as ue
from unreal_engine.classes import AlembicImportFactory

abc_factory = AlembicImportFactory()
abc_factory.ImportSettings.ImportType = 0
abc_factory.OverwriteYesOrNoToAllState= 1
abc_factory.bEditorImport=False
abc_factory.enable_input = True

print abc_factory.as_dict()

assets01 = ue.import_asset("d:/abc.abc", "/Game/xxx", abc_factory)`

I'm a new guy,to use UnrealEnginePython,I found I can not import alembic file through alembicImportFactory ,when i run code, a ui edit will display! I do not want this ui editor! any help?

**Comment by rdeioris** [comment]
Hi, thanks for reporting, never worked with Alembic files but i suppose we can do the same workaround we used for FBX if they automatically opens an import wizard. Can you give me a link where to download a pretty complex alembic file i can base my tests on ?

**Comment by heylenz** [comment]
thanks！ I export a alembic file from maya2014,

[https://www.dropbox.com/s/rhsvde4ppygrtf1/alembic_test.abc?dl=0](url)

**Comment by rdeioris** [comment]
Ok, i'll check it right now

**Comment by rdeioris** [comment]
So, unfortunately UE explicitely calls ShowImportOptionsWindow() in AlembicImportFactory.cpp and there is no way to turn it off.

I will try exposing a PyAlembicImportFactory overriding FactoryCreateFile(). I will back to you in few hours

**Comment by heylenz** [comment]
thanks very much!

**Comment by rdeioris** [comment]
So, unfortunately it is not somethign that can be solved in UnrealEnginePython, so i am building a pull request for Epic to include the possibility to avoid opening the wizard.

**Comment by heylenz** [comment]
Anyway，thank you for your time!

**Comment by rdeioris** [comment]
Reopening it while getting feedback from epic

**Comment by rdeioris** [comment]
Pull request has been made:

https://github.com/EpicGames/UnrealEngine/pull/3551

(obviously you need to register to the epic repository to see it)

**Comment by rdeioris** [comment]
4.17 includes the patch
