### ISSUE TITLE
compilation error on Ubuntu 16.04, UE-4.16 and clang-3.8

### ISSUE THREAD

**Issue by mmmaat** [20tab/UnrealEnginePython#170]
Hello and thank you for your plugin, it looks amazing ;)

But... I have a compilation issue on the latest **UE-4.16** compiled with **clang-3.8** on **Ubuntu 16.04**. I set pythonHome to "python35" in the Build.cs, else the compiler does not found Python.h.

In details I get two errors reported below (I replaced my personal dirs by [...]). Any idea or suggestion ?

Thank you!!

**Error 1**

> In file included from [...]/UnrealEnginePython/Module.UnrealEnginePython.cpp:16:
> [...]/Source/UnrealEnginePython/Private/Slate/UEPyFMenuBuilder.cpp:140:2: error:
>       delete called on non-final 'FMenuBuilder' that has virtual functions but non-virtual destructor [-Werror,-Wdelete-non-virtual-dtor]
>       delete(self->menu_builder);        
>       ^

**Error 2**

> In file included from [...]/UnrealEnginePython/Module.UnrealEnginePython.cpp:20:
> [...]/Source/UnrealEnginePython/Private/Slate/UEPyFToolBarBuilder.cpp:113:2: error:
>      delete called on non-final 'FToolBarBuilder' that has virtual functions but non-virtual destructor [-Werror,-Wdelete-non-virtual-dtor]
>        delete(self->tool_bar_builder);
>       ^

**Comment by rdeioris** [comment]
You can comment the two delete() directives in the code (if you do not plan to use the slate api).
I am checking for a workaround right now. Thanks for reporting

**Comment by mmmaat** [comment]
Thank you, this is working without the deletes for now!

**Comment by rdeioris** [comment]
It should work now, take into account that i have modified the build system on Linux. On Ubuntu systems it should find the python installation automatically.

**Comment by mmmaat** [comment]
Yes it works, many thanks!
