### ISSUE TITLE
UE 4.16 with python 3.52 -- can't get installation from sources to work

### ISSUE THREAD

**Issue by mwk888** [20tab/UnrealEnginePython#172]
My source install with Win UE 4.16 + python 3.5.2 doesn't work -- don't know if I made an error or if UE 4.16 is not yet supported? (I don't see a 4.16 + 3.5 binary release yet)

I followed steps for "Installation from sources on Windows (64 bit)" with no problem:
- git cloned repo then copied that to <project>/Plugins/UnrealEnginePython
- "generate visual studio project files" succeeded
- VS shows the plugin
- VS build had no obvious errors but did show 3 warnings like this: "_Module constructors should take a ReadOnlyTargetRules argument (rather than a TargetInfo argument) and pass it to the base class constructor from 4.15 onwards ... Plugins\UnrealEnginePython\Source\PythonConsole\PythonConsole.Build.cs_"

However when I run Unreal editor the plugin does not  work:
- "Window/Developer Tools" does not show "Python Console"
- create from blueprint does not find any py* classes 

I'm running 64 bit python 3.5.2, default install location and it's on %PATH%.

Any advice what to try next would be appreciated!

**Comment by rdeioris** [comment]
Hi, have you enabled the plugin in edit/plugins menu ?

**Comment by mwk888** [comment]
Doh! Thanks, yes that was the problem.

I'm getting other build problems now but maybe I can sort those out myself...

**Comment by mwk888** [comment]
I have plugin working, but I had to comment out this line in UnrealEnginePython.h to get it to build:

`#pragma clang diagnostic ignored "-Wdelete-non-virtual-dtor"`

Curious if anyone knows why that doesn't work?

**Comment by rdeioris** [comment]
That line is "surrounded" by #if defined(__clang__), is it possible you did not pulled latest changes ?

**Comment by mwk888** [comment]
You're right, I pulled just before that change -- works after update.
