### ISSUE TITLE
UnrealEnginePython_20170510_4_15_python35_win64 Fails to load 

### ISSUE THREAD

**Issue by HassamSheikh** [20tab/UnrealEnginePython#174]
Hi, 

I am using the above mentioned file but it gives me an error that UnRealEngine Plugin fails to load, However I tried with the embedded version, it works. I have Python in my environment variables. Can anyone tell me where I am doing wrong. Moreover, can someone tell me that can we add packages like numpy here?

**Comment by rdeioris** [comment]
Hi, generally if you have the directory containing python35.dll in your system PATH, it should work. Regarding external packages you can install them via pip (even using venv). Take into account that embedded versions do not have a python binary included so it could be a little annoying to build the distribution. I will try to add a commandlet to emulate pip
