### ISSUE TITLE
Import options ignored for FBX files

### ISSUE THREAD

**Issue by hdev-ndunsworth** [20tab/UnrealEnginePython#177]
```python
obj_path = '/some/path/object.fbx'

world = ue.get_editor_world()

factory = PyFbxFactory()

factory.ImportUI.bImportAsSkeletal = True
factory.ImportUI.bImportAnimations = True

factory.ImportUI.bImportMaterials = False
factory.ImportUI.bImportMesh = False
factory.ImportUI.bImportTextures = False

object = ue.import_asset(obj_path, '/Game/test', factory)
```

No matter what I do or if i use "set_property" everything from the FBX file is imported.

I've tried only setting a single property instead of all and no difference in results occurred.

**Comment by rdeioris** [comment]
can you try directly using the factory like described here ? https://github.com/20tab/UnrealEnginePython/blob/master/tutorials/YourFirstAutomatedPipeline.md#importing-the-mesh-fbx

in addituon to this ensure you have the latest code

**Comment by hdev-ndunsworth** [comment]
That works.

The documentation at, [link ](https://github.com/20tab/UnrealEnginePython/blob/master/docs/ManagingAssets.md), has an example that does not use this method. Should that be updated?

> If the factory supports options, you can instantiate a factory before use:
>
>```python
> from unreal_engine.classes import PyFbxFactory
>
>factory = PyFbxFactory()
>factory.ImportUI.bImportAsSkeletal = True
>
>asset002 = ue.import_asset('/Users/FooBar/Desktop/warrior001.fbx', '/Game/Meshes', factory)
>```

**Comment by rdeioris** [comment]
it is a bug of ue.import_asset i leave this issue opened until it will be fixed. Thanks for reporting

**Comment by rdeioris** [comment]
It looks like the internal UE api for that function reinstantiate a default factory everytime. I have changed the docs to only report factory.factory_import_object()

Thanks again for reporting
