### ISSUE TITLE
Level Sequence can't be reference in a Level Sequence Actor

### ISSUE THREAD

**Issue by grichardsonHalon** [20tab/UnrealEnginePython#178]
In order for a Level Sequence to be referenced in the Level Sequence Actor, it needs to be a FStringAssetReference value instead of the asset path or the UObject.

**Comment by rdeioris** [comment]
The FStringAssetReference wrapper has been added: 
https://github.com/20tab/UnrealEnginePython/commit/eacb9771b827bb4d9ee1f4104886484e65f999aa

**Comment by grichardsonHalon** [comment]
Still cannot import it with from unreal_engine import FStringAssetReference

**Comment by rdeioris** [comment]
have you rebuilt the plugin after having cloned the repository ?

**Comment by grichardsonHalon** [comment]
yes I rebuilt the plugin, but no luck on actually importing FStringAssetReference

**Comment by rdeioris** [comment]
check your sources if the Wrappers/UEPyFStringAssetReference.cpp is there

**Comment by grichardsonHalon** [comment]
I just downloaded and rebuilt and it seems to be importing properly.

**Comment by grichardsonHalon** [comment]
Although there is still an issue on referencing the Level Sequence asset to the Level Sequence Actor...

import unreal_engine as ue
from unreal_engine import FStringAssetReference
from unreal_engine.classes import LevelSequenceActor. LevelSequenceFactoryNew

world = ue.get_editor_world()

lsActor = world.actor_spawn(LevelSequenceActor)

factory = LevelSequenceFactoryNew()
seq = factory.factory_create_new("/Game/Test")

seqAsset = FStringAssetReference(seq)

lsActor.LevelSequence = seqAsset

ValueError: invalid value for UProperty

**Comment by rdeioris** [comment]
Hi, get the latest code, i have added actor_set_level_sequence(object):

```python
import unreal_engine as ue
from unreal_engine import FStringAssetReference
from unreal_engine.classes import LevelSequenceActor, LevelSequenceFactoryNew

world = ue.get_editor_world()

lsActor = world.actor_spawn(LevelSequenceActor)

factory = LevelSequenceFactoryNew()
seq = factory.factory_create_new("/Game/Test3")

lsActor.actor_set_level_sequence(seq)
```
