### ISSUE TITLE
Importing FBX Camerea into CineCameraActor in Sequencer

### ISSUE THREAD

**Issue by grichardsonHalon** [20tab/UnrealEnginePython#179]
I've been looking around and I couldn't find anyway where I can import an FBX file with camera animation onto a CineCameraActor in Sequencer. Is there a way to do that?

**Comment by rdeioris** [comment]
can you upload an example fbx with canera animation so i can check it ? Thanks

**Comment by grichardsonHalon** [comment]
Here's is an example fbx
[testCam.zip](https://github.com/20tab/UnrealEnginePython/files/1076225/testCam.zip)

**Comment by rdeioris** [comment]
Can i add this file to the test suite ? I am working on low-level fbx management and this file could be useful as a corner-case test. Regarding your problem, ue4 does not support importing raw curves, but the python plugin should be able to do it :)

**Comment by grichardsonHalon** [comment]
Yeah sure that sounds good. The camera animation itself isn't that great and is only 40 frames. Is there a specific example that you could provide from the python plugin?

**Comment by rdeioris** [comment]
https://github.com/20tab/UnrealEnginePython/blob/master/examples/fbx_curves_extractor.py

this class extracts all of the animation curves from an fbx file. Just put them in a sequencer or a curve asset

(note: ensure to pull latest code as it includes advanced fbx parsing features)

**Comment by grichardsonHalon** [comment]
How can I put the curves onto a CIneCameraActor?

**Comment by rdeioris** [comment]
Hi, you need to place each curve transform in the sequencer timeline:

https://github.com/20tab/UnrealEnginePython/blob/master/examples/sequencer_scripting.py

https://github.com/20tab/UnrealEnginePython/blob/master/docs/sequencer_API.md

**Comment by grichardsonHalon** [comment]
Okay, and is there a way to change the frame rate of the sequence?

**Comment by rdeioris** [comment]
sequence.MovieScene.FixedFrameInterval = 1.0/60

to set the fps at 60
