### ISSUE TITLE
Missing consts for Mac build

### ISSUE THREAD

**Issue by RonFischer** [20tab/UnrealEnginePython#18]
Don't seem worth a pull request:

../../Source/UnrealEnginePython/Private/UEPyFColor.cpp

-static void fcolor_add_color(char *color_name, FColor fcolor) {
+static void fcolor_add_color(const char *color_name, FColor fcolor) {

../../Source/UnrealEnginePython/Private/UEPyFLinearColor.cpp

-static void flinearcolor_add_color(char *color_name, FLinearColor lcolor) {
+static void flinearcolor_add_color(const char *color_name, FLinearColor lcolor)

**Comment by rdeioris** [comment]
done thanks :)
