### ISSUE TITLE
No module named 'funnygameclasses'

### ISSUE THREAD

**Issue by TylerReynolds** [20tab/UnrealEnginePython#180]
I was following the starting guide to ease the transition, so i tried applying the first funnygameclasses example.
I put the .py file in Content/Scripts as written in the tutorial.

But the python console keeps showing "no module named 'funnygameclasses'.
I also tried some custom .py scripts, none of them seems to be found.

How can i solve this problem?

I checked and the console is working, and it shows the correct python version (i'm using the one i already installed).

On a related note, it will be possible to use my own libraries, won't it?
Because in the python console i cannot use them, but core libraries work fine.

**Comment by rdeioris** [comment]
check sys.path content, you can eventually append more paths to it. You are free to use any module you want. Just ensure it is in a directory reported in sys.path.

**Comment by TylerReynolds** [comment]
Nevermind the main problem, i managed to fix it by creating a ue_site.py script in the Scripts folder.

I just finished trying the sys.path thing and i read your reply suggesting this xD

It doesn't seem to be working, in fact it should have been automatically working right from the start since those paths are already there in sys.path, as i already used python for some time.

What do you suggest i do?

**Comment by rdeioris** [comment]
this is super weird :( are you using a binary release or you compiled from sources ? could it be your system module are from a 32bit installation ? (just shooting in the dark, sorry)

**Comment by TylerReynolds** [comment]
My installation is a 3.5 64 bit one, in fact to install most modules i had to use the binary releases in a well known site providing those.

I installed a binary release, specifically UnrealEnginePython_20170611_4_15_python35_win64.zip

Sooooo, i have no idea... everything else works fine in PyCharm, and basically the only problem left with the plugin is using my own libs.


Could it some kind of conflict with other Python versions? There could be others in sys.path, maybe it's detecting another one?

By the way, i'm using Python 3.5.1, don't know if i'm supposed to have 3.5.x something since i never updated.

**Comment by rdeioris** [comment]
in Config/DefaultEngine.ini you can tune the python envuronment:

```ini
[Python]
Home = path_to_pyhome
ProgramName = path_to_python_exe
```

the full list of variable is in UnrealEnginePython.cpp

**Comment by TylerReynolds** [comment]
Is it really DefaultEngine?
The one in MyProj/Config/DefaultEngine?

I don't see anything related to Python.. :\

**Comment by rdeioris** [comment]
yep that one

you have to manually add the python stanza in the ini file

**Comment by TylerReynolds** [comment]
Oh, i see!
Thank you, will do it and let you know

**Comment by TylerReynolds** [comment]
I tried it, and now the project doesn't open because it keeps crashing, here is my .ini file:
```

[URL]
GameName=AdvancedLocomotionSystemV

[/Script/EngineSettings.GameMapsSettings]
EditorStartupMap=/Game/AdvancedLocomotionV1/DemoLevel.DemoLevel
GameDefaultMap=/Game/AdvancedLocomotionV1/DemoLevel.DemoLevel

[/Script/HardwareTargeting.HardwareTargetingSettings]
TargetedHardwareClass=Desktop
AppliedTargetedHardwareClass=Desktop
DefaultGraphicsPerformance=Maximum
AppliedDefaultGraphicsPerformance=Maximum

[/Script/Engine.RendererSettings]
r.DefaultFeature.MotionBlur=False
r.GenerateMeshDistanceFields=True

[/Script/Engine.PhysicsSettings]
DefaultGravityZ=-980.000000
DefaultTerminalVelocity=4000.000000
DefaultFluidFriction=0.300000
SimulateScratchMemorySize=262144
RagdollAggregateThreshold=4
TriangleMeshTriangleMinAreaThreshold=5.000000
bEnableAsyncScene=False
bEnableShapeSharing=False
bEnablePCM=False
bWarnMissingLocks=True
bEnable2DPhysics=False
LockedAxis=Invalid
DefaultDegreesOfFreedom=Full3D
BounceThresholdVelocity=200.000000
FrictionCombineMode=Average
RestitutionCombineMode=Average
MaxAngularVelocity=3600.000000
MaxDepenetrationVelocity=0.000000
ContactOffsetMultiplier=0.010000
MinContactOffset=0.000100
MaxContactOffset=1.000000
bSimulateSkeletalMeshOnDedicatedServer=True
DefaultShapeComplexity=CTF_UseSimpleAndComplex
bDefaultHasComplexCollision=True
bSuppressFaceRemapTable=False
bSupportUVFromHitResults=False
bDisableActiveActors=False
bDisableCCD=False
MaxPhysicsDeltaTime=0.033333
bSubstepping=False
bSubsteppingAsync=False
MaxSubstepDeltaTime=0.016667
MaxSubsteps=6
SyncSceneSmoothingFactor=0.000000
AsyncSceneSmoothingFactor=0.990000
InitialAverageFrameRate=0.016667

[/Script/Engine.RecastNavMesh]
RuntimeGeneration=Static

[Python]
Home="D:/Python/Python35"
ProgramName="D:/Python/Python35/python.exe"
```

I also tried not using any ", still crashes.
What am i doing wrong?

**Comment by rdeioris** [comment]
Try (without double quoting) specifying only the Home field.

**Comment by TylerReynolds** [comment]
Finally, after changing it to Program_Name it's working and it chose the right interpreter, now the modules are working!

Awesome, thank you very much, i also tried playing around with building from source and stuff and in the process learned about how plugins are packaged and how source is handled, i'm sure it'll come in handy in the future.

For some reason, though, despite indicating the proper python interpreter in the build .cs file it still chose the anaconda one, must be because of some system variables.

Oh, well, what matters is that it finally works xD

Thank you very much!
(Grazie, se sei italiano anche te xD)

**Comment by rdeioris** [comment]
(prego ;)

It is working because basically you removed ProgramName (Program_Name does not exist). So in your case you only need the Home variable

**Comment by naveenT1010** [comment]
Hi I am using Ubuntu 16.04 and I am having the same error.

**Comment by rdeioris** [comment]
patch merged. thanks

**Comment by naveenT1010** [comment]
Hi @rdeioris , actually I am able to compile the Plugin now, but my script is not running. When I check the python console, It shows No module named '<my script's name>'.

**Comment by rdeioris** [comment]
how you are running the script ? are you using ue.py_exec or you are importing it ? in the second case ensure the Scripts directory has been added to sys.path. Generally restarting the editor will fix it.

**Comment by naveenT1010** [comment]
I am just following the starting tutorial, I am writing a script in the Scripts folder and then putting its name in Python Module field of PyActor, and class name in the class field. When I press play, I can see that it is not able to find the module in python console.

I checked the sys.path, and it seems fine to me, I dont have access to machine right now, so I cant comment the output right now.

**Comment by rdeioris** [comment]
You may be facing this problem if it is the first time you run the editor with the python plugin: https://github.com/20tab/UnrealEnginePython/blob/master/tutorials/PlottingGraphsWithMatplotlibAndUnrealEnginePython.md#our-project-plotting-a-pie-chart-tracking-overlap-events

Basically if the python vm does not find the /Content/Scripts directory on startup it does not truly add it to the search path. Just create it (if the editor has not just created it for you) and restart.

**Comment by naveenT1010** [comment]
It was already created, but still it is not able to find the scripts. Here is my sys.path output:
```bash
['', '../../../../../Documents/Unreal Projects/PythonProject/Content/Scripts', '../../../../../Documents/Unreal Projects/PythonProject/Content/ue_python.zip', '', '/usr/local/lib/python2.7/dist-packages', '/home/warp-robotics/catkin_ws/devel/lib/python2.7/dist-packages', '/opt/ros/kinetic/lib/python2.7/dist-packages', '/usr/lib/python35.zip', '/usr/lib/python3.5', '/usr/lib/python3.5/plat-x86_64-linux-gnu', '/usr/lib/python3.5/lib-dynload', '/home/warp-robotics/.local/lib/python3.5/site-packages', '/usr/local/lib/python3.5/dist-packages', '/usr/lib/python3/dist-packages']
```
and when I try to execute any script from console within UE, it show:
```python
ue.py_exec('game.py')
Unable to open file ../../../../../Documents/Unreal Projects/PythonProject/Content/Scripts/game.py
```

**Comment by rdeioris** [comment]
that relative paths scare me a bit :) Try inserting the absolute path of the Scripts directory on top of sys.path

**Comment by naveenT1010** [comment]
It worked! 
Thanks alot for your help. Can you tell me how can I add the path permanently?

**Comment by rdeioris** [comment]
https://github.com/20tab/UnrealEnginePython#plugin-configuration

ScriptsPath will do the trick
