### ISSUE TITLE
A few things I think that  broke in the last few versions

### ISSUE THREAD

**Issue by sinokgr** [20tab/UnrealEnginePython#182]
Hi guys,

I think two things broke lately. Firstly, the menu on top, suddenly stopped appearing for me. For example:
```python
import unreal_engine as ue

def do_something():
	print "menu"
	
ue.add_menu_extension('Menu', do_something, 'Submenu')
```
doesn't show anything. If I revert back to older version of your plugin, it works fine.

Secondly, I'm getting an Error 5 every time I try to pack the project. File>Package Project>Windows>Windows (64-bit). As soon as I remove python, the project packs normally. (I've also switched the "Name": "UnrealEnginePython" to "Type": "Editor" and tried it on an free new project. As soon as I remove Python and restart UE, everything works again.

All testing was done with downloads from the release section in github with UE 4.15 and Python 2.7.

Any ideas?
Nick

**Comment by sinokgr** [comment]
oh, just saw that you released a new version 2 days ago. I just tried it and it seems that this have fixed the second problem I still don't get the menu.

**Comment by rdeioris** [comment]
Hi, the slate menu api has been refactored, you have two different functions:

```python
ue.add_menu_extension('name', action[, 'position'])
```

calling

```python
ue.add_menu_extension('fooBar', lambda: ue.log('Hello'))
```

will ad a 'fooBar' entry in the Window menu

while

```python
ue.add_menu_bar_extension('name', callback)
```

gives you full access to the FMenuBuilder system:

```python
def build_menu(menu):
    menu.begin_section('section001', 'section001')
    menu.add_menu_entry('one1', 'two1', lambda: ue.log('hello'))
    menu.add_menu_entry('one2', 'two2', lambda: ue.log('hello2'))
    menu.end_section()

ue.add_menu_bar_extension('Test001', build_menu)
```

**Comment by rdeioris** [comment]
I have added a more complex example:

https://github.com/20tab/UnrealEnginePython/blob/master/examples/extenders_example.py

**Comment by sinokgr** [comment]
awesome, it's so much better now! thanks :)
