### ISSUE TITLE
Multithreading-enabled binaries?

### ISSUE THREAD

**Issue by jbecke** [20tab/UnrealEnginePython#187]
Part of the reason I'm using ue4python is because I couldn't build the engine in VS 2017 and I just want a quick hack solution to audio input. So I'm using the binaries. Could someone please instruct how to or provide binaries with multithreading enabled? I'm using ue4 4.15 and python 3.5

**Comment by rdeioris** [comment]
We can release threaded binary versions from the next round. Thanks for reporting. Take into account that yesterday i implemented the IVoiceCapture interface (docs will be available during the weekend) so you should be able to capture data without relying on pyaudio or threads

**Comment by jbecke** [comment]
@rdeioris You're awesome thank you!
