### ISSUE TITLE
Documentation Error uobject.get_components

### ISSUE THREAD

**Issue by EmpereurOkais** [20tab/UnrealEnginePython#188]
Documentation concerning [UObject](https://github.com/20tab/UnrealEnginePython/blob/master/docs/uobject_API.md) seems to have an error:

What you wrote:

`components` = `uobject.actor_components()`

what python console thorw me:

`LogPython:Error:` 'unreal_engine.UObject' object has no attribute 'actor_components'
LogPython:Error: Traceback (most recent call last):
LogPython:Error:   File "G:/projet/Unreal/Sandbox/Content/Scripts\Master.py", line 17, in begin_play
    CompList = self.uobject.actor_components()
LogPython:Error: AttributeError: 'unreal_engine.UObject' object has no attribute `'actor_components'`

What works:

`components` = `uobject.get_components()`

Sorry if you find my answer blunt, english is not my first language.

**Comment by rdeioris** [comment]
Fixed with get_actor_components(). Thanks for reporting
