### ISSUE TITLE
Casting to Python primitives is very slow

### ISSUE THREAD

**Issue by mrpropellers** [20tab/UnrealEnginePython#190]
It seems like there is a lot of functional overhead when casting very simple UObjects to Python primitives.  For example, if I have an object defined like this in UE:
```cpp
// 8-bit grayscale image
TArray<uint8> GrayImage 
```
where each element is a 8 bit grayscale pixel value (and the image is 1600 x 1200).  Attempting to copy these values into an array that is useful in Python like this:
```python
img = [numpy.uint8(pixel) for pixel in GrayImage]
```

Took me 700-800ms on a 7th gen i7.  Is this due to all the memory safety checking happening when a uobject is accessed?  Is there more efficient way to access the data stored in TArray objects, or maybe plans to create custom method for copying Unreal primitives and simple containers like TArray<primitive>, FString, TChar?

**Comment by rdeioris** [comment]
Hi, it is really heavy to iterate each element of the array, insert it into another list containing numpy items. You should always reshape/remap arrays with numpy api.

numpy.frombuffer|fromstring|asarray|fromarray and so on are extremely fast and often zero-copy.

Can you paste a bit of the code you are using so i can suggest you a better solution ?

**Comment by dronesrcool** [comment]
Maybe some more context would be useful.  I have a ActorComponent class in UE that manages a number of camera objects and stores grayscale scene captures into `TArray<uint8> Image` which is of length `width * height`.  The objective of my Python component is to grab these images and cast them to a Python list which I can use for other operations such as serialization for network publishing.  Here is how the image is stored in UE:
```cpp
// Original grayscale image from scene capture component
TArray<FColor> img;
// Ready image container
Image.reset(img.Num())
for (auto &pixel : img) {
  // Assuming img is grayscale, each pixel has the same values for R, G, and B
  Image.Add(pixel.R);
}

// imageQueue is TQueue<TArray, EQueueMode::Spsc>
imageQueue.empty();
imageQueue.Enqueue(Image);
```

The Python component holds a reference to the camera manager actor component and calls a `getNewImage()` function which dequeues Image and returns it, if it exists.  Then, I attempt to copy this into an array like above and find it to be incredibly slow:
```python
Image = self.camera_interface.GetNewImage()
# ~750ms
img = [np.uint8(pixel) for pixel in Image]
# ~ 260ms
img = np.asarray(Image, dtype=np.uint8)
```
For reference, executing this code:
```python
import unreal_engine as ue
import random
fake_img = [random.randint(0, 255) for _ in xrange(1200 * 1600)]
fake_img_cont = np.ascontiguousarray(fake_img)
t = time.time()
img_copy = np.asarray(fake_img, dtype=np.uint8)
t1 = time.time()
ue.log("Time to copy: %f" % (t1 - t))
img_contig_copy = np.asarray(fake_img_cont, dtype=np.uint8)
ue.log("Time to copy: %f" % (time.time() - t1))
```
Returns ~65ms for copying the list and ~2ms for copying the contiguous array on the same computer.

**Comment by rdeioris** [comment]
Hi, yes returning a TArray<uint8> instead of a texture is pretty heavy as the reflection system will be triggered in:

https://github.com/20tab/UnrealEnginePython/blob/master/Source/UnrealEnginePython/Private/UEPyModule.cpp#L1705

As the returned value is already a valid python list is not easier to do something like this ?

```python
img = np.array(Image, dtype=np.uint8)
```

(instead of asarray that creates a new copy ?)

If it is not enough, we could add an ad-hoc optimization for the most common cases (like TArray<uint8>() returning directly a bytearray)

**Comment by dronesrcool** [comment]
I will give that I shot.  From digging deeper into the TArray API doc I see there is also a GetData() member for returning a pointer to the buffer.  Do you have any intuition as to whether that buffer could be used direction in python?  `Image.GetData()` doesn't seem to work as python thinks Image is a list and does not have the GetData method.  However, I could modify my component UObject's GetNewImage to return the GetData pointer instead of the TArray itself...  Then use `numpy.frombuffer()` ?

**Comment by dronesrcool** [comment]
`np.array(Image, dtype=np.uint8)` takes ~250ms.  I'm not convinced it is doing what we expect it to, though.  The average pixel value reported by the UObject:
```cpp
uint32 total = 0;
for (auto &pixel : image.image) {
	total += pixel;
}
double avg = (double)total / (1600.0 * 1200.0);
UE_LOG(LogTemp, Warning, TEXT("Image pixel average: %f"), avg);
```
reports ~66.9.  The numpy array created using `np.array(Image, dtype=np.uint8)` is an array comprised entirely of the value 221.  If I do not explicitly state a dtype, `np.array(Image)` returns an array comprised entirely of the value -35.  Seems something is going awry when the TArray is converted to a py_list.

**Comment by dronesrcool** [comment]
So - another update:
It appears I was hiding one of the issues in my example code.  My GetNewImage() method as I have it implemented does not actually return the TArray directly, but returns a UStruct called ImageMessage with an image member.  So it looks a bit more like this:
```cpp
USTRUCT()
struct FImageMessage
{
  //... 
  // image metadata
  // ...

  UPROPERTY()
  TArray<uint8> image;
}

When I return this UStruct from component.GetNewImage(), Image.image contains a bogus list of all -35 values.  However, if I return Image.image DIRECTLY from GetNewImage(), then it seems to be a proper python list.  HOWEVER, when returning the TArray<uint8> directly, I don't think it is correctly mapping.  I found about 4.5% of the list had values that were outside the range of a uint8.  Checking the type of Image elements, I find they have been cast to signed long ints.  When I cast them back to uint8 using `np.array(Image, dtype=np.uint8)` it looks like I am getting the correct values (mean pixel value goes back to what it was in the UObject), BUT I am betting it is creating a copy of the original list since it needs to recast all the values from long into to uint8.

SO!  In summary, there are two bugs here:
1) When a TArray is defined inside a UStruct, its values are not preserved when the encapsulating struct gets exposed in python.
2) TArrays of primitives are not properly preserving their values' type when returned as python lists.  Casting from unsigned to long also has the side effect of turning all >127 values into negative numbers.

**Comment by rdeioris** [comment]
I think the problem is here: https://github.com/20tab/UnrealEnginePython/blob/master/Source/UnrealEnginePython/Private/UEPyModule.cpp#L1596 the return value is built from a signed value. and it should be unisgned. Can you check if changing that part fixes both of your issues ?

In the mean time i am evaluating ad-hoc optimizations, like `TArray<uint8>` automatically mapped to bytearray

**Comment by rdeioris** [comment]
https://github.com/20tab/UnrealEnginePython/commit/b4eb1b5671e33836e62ab2e83a0db54fa93b8847

this patch will optimiza any TArray<uint8> occurrence by using a bytearray instead of a list of integer.

Let me know

**Comment by mrpropellers** [comment]
Thanks!  Will try this out in a bit, I've been on a fairly old commit so I will have to update and merge any modifications.

**Comment by mrpropellers** [comment]
After pull and rebuild, without even touching my python code the time to get and convert the array went from 300ms to 2ms!  Love it!
