### ISSUE TITLE
4.16 win64 threaded binaries broken

### ISSUE THREAD

**Issue by jbecke** [20tab/UnrealEnginePython#191]
Using 4.16.2 UE4 (binary version) I can follow funnygameclasses tutorial without issues on the unthreaded version, but the editor crashes when I click "compile" on the blueprint when using the threaded version with funnygameclasses.

**Comment by rdeioris** [comment]
Thanks for reporting

**Comment by rdeioris** [comment]
Hi, can you try with latest binaries ? Thanks
