### ISSUE TITLE
set_actor_rotation doesn't support FQuat

### ISSUE THREAD

**Issue by mrpropellers** [20tab/UnrealEnginePython#192]
set_actor_rotation only accepts FRotator objects, but the UE API allows for specifying rotations as a quaternion.  Could this be added to the native set_actor_rotation call?

**Comment by mrpropellers** [comment]
Some extra info:
`actor.SetActorRotation(FQuat(0, 0, 0, 1), 1)` gives `LogPython:Error: TypeError: unable to convert pyobject to property NewRotation (StructProperty)`
`actor.call_function('SetActorRotation', FQuat(0, 0, 0, 1), 1)` gave `LogPython:Error: Exception: unable to find function`

And tangentially related:
`from unreal_engine.enums import ETeleportType` was unable to find ETeleportType

https://docs.unrealengine.com/latest/INT/API/Runtime/Engine/GameFramework/AActor/SetActorRotation/2/index.html

**Comment by rdeioris** [comment]
Unfortuntaley FQuat is not exposed to the reflection system (this really surprised me !).

I am refactoring the whole transformations code (it does not support sweeping). In few minutes i should came back with a patch supporting quaternions too.

**Comment by rdeioris** [comment]
Note: Neither ETeleportType is exposed :( i am exporting it as a boolean flag for wrappers, but you can use 0 for None and 1 for PhysicsTeleport.

Regarding the 'SetActorRotation' reflection-based function, it requires the K2_ prefix (it is automatically managed when you use the shortcut actor.SetActorRotation)

**Comment by rdeioris** [comment]
the new set_actor_rotation has been pushed, as well as the first round of support for sweep tests

**Comment by mrpropellers** [comment]
Ok - I'll go ahead and close this issue although I have not tested the FQuat support myself.  I adjusted my script to convert my quaternions to RPY and that seems to be stable for my use case.
