### ISSUE TITLE
Requesting Threaded Binaries for winx64 python 35 engine 4.15 (Shader Error)

### ISSUE THREAD

**Issue by TylerReynolds** [20tab/UnrealEnginePython#194]
Well, the title says it all, requesting threaded binaries for winx64 python 35 engine version 4.15 (4.16 would be nice too, as i should be switching to that one soon)

I'm slowly continuing my tests, and i ran into a very big issue: every time shaders are compiled there is an assertion error and the editor crashes.
I never noticed this earlier because i didn't import any new asset for some time.

Could this be related to multi-threading?

I have no idea, but since i compiled from source it could also be that i got something wrong, dunno.
Everything else seems to be working quite fine though.

Anyway, getting the official binaries i'm requesting would let me check whether or not i did something wrong compiling the code, so i'm kindly asking for them if possible.

This is the error:
`Assertion failed: ShaderFormatsNum()
[File:D:\Build\++UE4+Release-4.15+Compile\Sync\Engine\Source\Runtime\Engine\Private\ShaderCompiler\ShaderCompiler.cpp][Line:321]`

I'm using of course engine version 4.15 and python 35 64 bit

**Comment by rdeioris** [comment]
Latest release includes 4_15_python35_threaded.

Regards
