### ISSUE TITLE
Access Asset Registry

### ISSUE THREAD

**Issue by ElviraHT** [20tab/UnrealEnginePython#195]
Hi, how would i access the asset registry if i need to get a list of assets filtered for example by static mesh? I don't need to load them in memory, and this is what the "managing assets" docs methods do.
I have a lot of assets, and using the get_assets_by_class() not only takes a looot of time, but it also overloads the ram because of the amount of assets i have.

How can i access the asset registry using python so i can get the lists of asset paths i need?
In an instant way like the Content Browser (asset registry should be what i need)
What i need to do is get a random asset for example static mesh or static meshes + blueprints among all the ones i have, if you have a better way please tell me
Then i will spawn it in the world using the asset path

**Comment by rdeioris** [comment]
Hi, use get_assets_by_filter:

```python
import unreal_engine as ue

from unreal_engine import FARFilter

new_filter = FARFilter()
new_filter.class_names = ['Skeleton', 'AnimSequence']

items = ue.get_assets_by_filter(new_filter, True)

for item in items:
    ue.log('{0} -> {1}'.format(item.asset_name, item.object_path))
```

**Comment by rdeioris** [comment]
Note: the second argument of get_assets_by_filter, specifies that you do not want the UObject but the FAssetData.

**Comment by ElviraHT** [comment]
Exactly what i was looking for, thank you

**Comment by ElviraHT** [comment]
Um very quick question, how can i make it add the mesh where the i click with the mouse in the viewport?
This is the idea: i press a shortcut, and it waits for me to place the mesh by clicking somewhere on the map
I know how to do this in game mode by adapting this i found in navigation_api:
`class Walker:
    def begin_play(self):
        self.uobject.show_mouse_cursor()
    def tick(self, delta_time):
        if not self.uobject.is_input_key_down('LeftMouseButton'):
            return
        hit = self.uobject.get_hit_result_under_cursor(ue.COLLISION_CHANNEL_VISIBILITY)
        if not hit:
            return
        # hit is a unreal_engine.FHitResult object
        self.uobject.simple_move_to_location(hit.impact_point)`

But how do i apply it when outside the game since the editor doesn't tick and how do i set if key pressed event outside of play mode as well?
Ty for the help

**Comment by rdeioris** [comment]
I would use ue.editor_get_selected_actors() that returns a list of currently selected actor

**Comment by ElviraHT** [comment]
Sorry if i didn't write clearly enough, but what i meant is:
1) how do i make a pyactor tick in editor (kind of like ShouldTickIfViewportsOnly in c++)
2) how do i bind events in editor so i can set shortcuts to start script while in editor for example

**Comment by rdeioris** [comment]
You do not need an actor for adding "ticker" to the editor:

```python
def foo_tick(delta_time):
    ...
   # returning True, will re-schedule the task
   return True

my_ticker = ue.add_ticker(foo_tick, frequency)

# to remove a ticker
ue.remove_ticker(my_ticker)
```

**Comment by rdeioris** [comment]
Regarding triggering actions, i would use menu or toolbars: https://github.com/20tab/UnrealEnginePython/blob/master/examples/extenders_example.py

for event managed by the editors i need to check if it is something possible

**Comment by ElviraHT** [comment]
the extender example crashes my editor (4.15 maybe it's for 4.16?), but what i'm really having problems with is spawning a mesh where the cursor is, is it possible to do it in editor?
do i have to use c++?

**Comment by rdeioris** [comment]
extenders must be registered in ue_site.py

regarding retrieving the mouse position in the editor i need to check if the function can be exposed

**Comment by ElviraHT** [comment]
yes i placed the code in ue_site as recommended, in fact it crashes before finishing opening the project.
thank you, if you find any solution i will use it right away because this is very important and blocking all the other stuff, i will also dig into the code and try to find out a way to do it

**Comment by ElviraHT** [comment]
So, my current workaround is to simply use a mesh to pilot around and getting the forward vector a new one is placed close to it, i can also use said mesh as a "cursor" to drag around, so this is working nicely enough
i noticed as well that the set_timer() method doesn't work when real-time is off in editor, you should add that to the timer docs because i spent about two hours trying to figure out why timer wasn't ticking and i sometimes turn realtime off so i didnt realize it right away, would be useful to specify it as im sure many people turn it off for performance reasons

another question: the same code to spawn static mesh actor and loading object static mesh as component works with collision if spawned in editor, but not in game.
how so, how can i keep collision when spawning my loaded static mesh?

**Comment by lsr1994** [comment]
@rdeioris   Hey guys, I got an error using FARFilter and asked for help. I used the native python 2.7, Unreal 4.19。
![image](https://user-images.githubusercontent.com/40679973/52764899-c6416180-3019-11e9-8328-889dc89e18cb.png)
