### ISSUE TITLE
about Setting anim_sequence.Animation

### ISSUE THREAD

**Issue by heylenz** [20tab/UnrealEnginePython#196]
I am using UnrealEnginePython for the TV series,I want to load animation ! but not work!
```python
import unreal_engine as ue
from unreal_engine.classes import AnimSequence, LevelSequenceFactoryNew, MovieSceneSkeletalAnimationTrack, Character,SkeletalMeshActor, SkeletalMesh, MovieScene3DTransformTrack, CineCameraActor


factory = LevelSequenceFactoryNew()
seq = self.factory.factory_create_new('/Game/SC002_' + str(int(time.time())))
world = ue.get_editor_world()        
character = self.world.actor_spawn(SkeletalMeshActor)
character.modify()
character.SkeletalMeshComponent.SkeletalMesh = ue.load_object(SkeletalMesh, '/Game/Model/Character/Gerui/Gerui.gerui')
character.post_edit_change()
guid = self.seq.sequencer_add_actor(character)        

for track in self.seq.sequencer_possessable_tracks(guid):
    if track.is_a(MovieSceneSkeletalAnimationTrack):
        anim_seq = track.sequencer_track_add_section()
        # I want to load animSequence from '/Game/Animation/episode01/character/gerui/sc002_fbx_GeRui_finaly', but not work!
        anim_seq.Animation = ue.load_object(AnimSequence, '/Game/Animation/episode01/character/gerui/sc002_fbx_GeRui_finaly')
```

**Comment by rdeioris** [comment]
Hi, do you get some specific errror ?

A trick i often use to check assets path is selecting it in the content browser and then movign to the python console and running:

```python
asset = ue.get_selected_assets()[0]
ue.log(asset.get_full_path())
```

**Comment by heylenz** [comment]
I did not get any mistakes my process, My version is 4.16.2.
1, create a LevelSequence,
2, add a character to the sequence, set the character's skeletalmesh (work)
3, I would like to import an already done animation clips. (No error, but look at the sequence panel, I found the character exists, but the animation clips was not imported)


I tried ,
```python
Asset = ue.get_selected_assets () [0]
# Ue.log (asset.get_full_path ()) # AttributeError: 'unreal_engine.UObject' object has no attribute 'get_full_path'
Ue.log (asset.get_path_name ()) #I dir (asset) does not have this property, I think it might be asset.get_path_name ()
```

**Comment by rdeioris** [comment]
Ok, now i have understood your problem.

The field to change is not Animation but the struct 'Params' that is done like this:

```python
['Animation', 'StartOffset', 'EndOffset', 'PlayRate', 'bReverse', 'SlotName', 'Weight']
```

It is a struct so everything is passed as value (read: it is copied every time)

```python
from unreal_engine.structs import MovieSceneSkeletalAnimationParams

...

anim_seq.Params = MovieSceneSkeletalAnimationParams(Animation=your_anim_asset, Weight=1.0)

```

**Comment by rdeioris** [comment]
Oh and the function name is get_full_name() not get_full_path() sorry :)

**Comment by heylenz** [comment]
It works! That's Cool! Thanks!
can i found struct doc? like MovieSceneSkeletalAnimationParams, so i can find parms ['Animation', 'StartOffset', 'EndOffset', 'PlayRate', 'bReverse', 'SlotName', 'Weight']!
I think many places may need to be set to get parameters!

**Comment by rdeioris** [comment]
Unfortunately there is no documentation on the internals (excluded the auto-generated one for c++ classes) so it is currently a trial-and-error approach.

The reflection subsystem should help you in understanding how things works. You generally do something in the editor and the you "inspect" the data using .properties() and .fields() python functions

**Comment by heylenz** [comment]
Thanks for these tips！

**Comment by lsr1994** [comment]
Hi, friend, I have the same problem as you. I still can't figure it out. Asking for help, I wrote:





The import unreal_engine as ue

The from unreal_engine. Classes import AnimSequence LevelSequenceFactoryNew, MovieSceneSkeletalAnimationTrack, Character, SkeletalMeshActor, SkeletalMesh, MovieScene3DTransformTrack, CineCameraActor

The from unreal_engine. User-defined structs import MovieSceneSkeletalAnimationParams





The factory = LevelSequenceFactoryNew ()

Seq = factory. Factory_create_new ('/Game/SC002_ ')

World = ue. Get_editor_world ()



Character = world. Actor_spawn (SkeletalMeshActor)



Character. The modify ()

Character. SkeletalMeshComponent. SkeletalMesh = ue. Load_object (SkeletalMesh, '/ Game/B2_Content/Models/character/uSsoldier01 / B2_skin_uSsoldier01 B2_skin_uSsoldier01')

Character. Post_edit_change ()



Guid = seq. Sequencer_add_actor (character)





For track in seq. Sequencer_possessable_tracks (guid) :

If track. Is_a (MovieSceneSkeletalAnimationTrack) :

Anim_seq = track. Sequencer_track_add_section ()

Anim_seq. Params = MovieSceneSkeletalAnimationParams (Animation = '/ Game/B2_JSL002_C001 / B2_JSL002_C001_B2_uSsoldier01_v001 B2_JSL002_C001_B2_uSsoldier01_v001', Weight = 1.0)
