### ISSUE TITLE
Access user c++ classes at load time

### ISSUE THREAD

**Issue by simtbi** [20tab/UnrealEnginePython#197]
First I want to say it is really amazing what you have achieved with the subclassing functionality, it opens up so many possibilities!

I find it's working great as long as I stick to subclassing built-in engine classes.  e.g. Create a subclass of Actor, called MyPythonActor.  It registered with UE when the editor loads, so any blueprints referencing the class are OK, any instances of the MyPythonActor in the world remain valid etc.

I can also create subclasses of my own c++ classes, but only register them by using unreal_engine.exec() once the UE editor is running.  The subclass is then registered with UE and I can place it in world etc

However, if I call unreal_engine.exec() in ue_site.py, then when the editor starts an error is thrown that the parent custom C++ class is not known.  This means any blueprints referring to the python subclass, or any instances of the python class in the world all break/disappear etc.  If I run the unreal_engine.exec() manually again, the class is re-registered and I can start again, but it all breaks next time I load the project. 

It seems like at the time all the python scripts are executed at project load, only the base engine classes are known to it?  Is there any way to have access to my own c++ classes at load time when ue_site.py is first run?

**Comment by rdeioris** [comment]
Hi, you can use the load_class(asset) function:

```python
EvilEnemy = ue.load_class('/Script/PyTest415.EvilEnemy')
```
class asset names should be in the form /Script/ProjectName.ClassName.

If you have doubts on the name you can use this trick:

```python
ue.log(ue.get_selected_assets()[0].get_path_name())
```

after having selected the c++ class in the content browser

**Comment by simtbi** [comment]
Thanks for the suggestion, I have given that a go but I'm getting a similar result, it works if I exec() the python file manually, but trying to do it at load time still gives an error about not being able to find my c++ class asset.

The UE project is "Messages", ActorTest is the c++ class extending AActor.  My python code is just:

```python
import unreal_engine as ue

ActorTest = ue.load_class('/Script/Messages.ActorTest')

class PythonTest(ActorTest):
    def __init__(self):
        pass
        
```

And when opening the project I find the error in the log:
```
Can't find file '/Script/Messages'
Failed to find object 'Class /Script/Messages.ActorTest'
unable to find class /Script/Messages.ActorTest
Traceback (most recent call last):
  File "C:/programming/Unreal Engine/Messages/Content/Scripts/test.py", line 3, in <module>
    ActorTest = ue.load_class('/Script/Messages.ActorTest')
Exception: unable to find class /Script/Messages.ActorTest
```

running `ue.exec('test.py')` in the console works properly though and registers the PythonTest class

**Comment by rdeioris** [comment]
Hi, i have changed the loading phases of the plugin so the python vm does not start too early:

https://github.com/20tab/UnrealEnginePython/commit/53fc807f9a69dde0629fa5d8d95092d34ef245bf

Let me know if it works for you

**Comment by simtbi** [comment]
Excellent, that got it working! Thanks very much
