### ISSUE TITLE
Embedded python install

### ISSUE THREAD

**Issue by nessusing** [20tab/UnrealEnginePython#198]
I am having difficulty embedding python install to the plugin. Is it just a matter of dumping the py install folder inside the binary folder? Every time I do that UEditor crashes. I am not seeing a guide on how to build the plugin with embedded python? Thanks!

**Comment by rdeioris** [comment]
Hi, ensure the python version of the embeddable distribution is the same for which you have built the plugin. Then yes, just copy it to the Binary folder.

I suggest you to download a binary embedded release of the plugin and just substitute its 3 plugin-related DLLs

**Comment by nessusing** [comment]
> I suggest you to download a binary embedded release of the plugin and just substitute its 3 plugin-related DLLs

This approach worked really well for me. Thank you!
