### ISSUE TITLE
Use for 4.13

### ISSUE THREAD

**Issue by LarsGroh** [20tab/UnrealEnginePython#20]
Hi guys,

any issues to be expected building the plugin with 4.13?

**Comment by rdeioris** [comment]
This is the version we are currently using for development (albeit we continue to support 4.12). So you should not have problems

**Comment by LarsGroh** [comment]
Thanks!

**Comment by LarsGroh** [comment]
Hi, 
I'm getting this error message in the output log when opening the editor after having set up and compiled everything:

```
LogPython: Python VM initialized: 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)]
LogPython: Python Scripts search path: ../../../../../../workspace/UE4/staud/GT_VIS/Content/Scripts
LogPython:Error: No module named 'ue_site'
```

**Comment by RonFischer** [comment]
Me too

**Comment by rdeioris** [comment]
the error is harmless, on startup the plugin tries to import the ue_site.py file where you could place initialization code. If you want to silence it, just create an empty ue_site.py into /Content/Scripts. Soon we will change it to a warning or a simple info message

**Comment by LarsGroh** [comment]
Thanks - good to know where to put init-stuff!
