### ISSUE TITLE
as_dict() not working on USTRUCT()

### ISSUE THREAD

**Issue by mrpropellers** [20tab/UnrealEnginePython#200]
I have a USTRUCT defined in my code that holds metadata that I would like to pass to a Python function as keyword arguments

The struct looks kind of like this:
```cpp
USTRUCT()
struct FMetadata {
  GENERATED_BODY()

  UPROPERTY()
  uint32 x;

  UPROPERTY()
  uint32 y;

  UPROPERTY()
  uint32 z;

  UPROPERTY()
  FString name;

  UPROPERTY()
  uint8 num;
}
```
... and is created as a member variable in a Component class:
```cpp
public: 
  UPROPERTY()
  FMetadata Args;
```
I have a reference to the component class in Python, let's call it `my_component`:
```python
args = my_component.Args.as_dict()
# I'd like to do this...
foo(**args)
```
calling `my_component.Args.as_dict()` returns this error, though: `'unreal_engine.UScriptStruct' object has no attribute 'as_dict'`

Where'd I go wrong?  Is calling it with a struct not supported?

**Comment by rdeioris** [comment]
as_dict() to user structs has been added: https://github.com/20tab/UnrealEnginePython/commit/0955dd0c7db292f25ad8a1056d976c5122d99ad3

thanks for reporting
