### ISSUE TITLE
PythonComponent missing

### ISSUE THREAD

**Issue by Archina** [20tab/UnrealEnginePython#202]
I tried to create a new Blueprint and discovered that the PythonComponent class seems to be either missing or not being extensible.

![image](https://user-images.githubusercontent.com/7892595/28756683-cd7a931a-7538-11e7-9e94-cb7e57a00514.png)

I also feel like it should be named PyComponent after the naming convention encouraged by PyActor, PyPawn and PyCharacter.

**Comment by rdeioris** [comment]
Hi, i jave just exposed the UPythonComponent as "blueprintable".

Thanks for reporting.

Regarding the name, you are right, it is only for showing it as 'Python' instead of 'Py' when added to an actor

**Comment by Archina** [comment]
Wow that was fast! Thank you very much
