### ISSUE TITLE
How to rename tracks in Sequencer?

### ISSUE THREAD

**Issue by nessusing** [20tab/UnrealEnginePython#203]
`factory = LevelSequenceFactoryNew()`
`seq = factory.factory_create_new('/Game/foobar')`
`camera_cut_track = seq.sequencer_add_camera_cut_track()`
`camera_cut_track.set_name('TestRename')`

I am using part of your sequencer example and trying to rename a cut track. But it does not seem to do anything?

Also I tried calling the actual API `camera_cut_track.call('SetDisplayName TestRename')`, that raises a generic error: `Exception: error while calling "SetDisplayName TestRename"`.

What am I missing? Thanks.

**Comment by heylenz** [comment]
maybe you can try!
```python
camera_cut_track.set_actor_label("TestRename")
```

**Comment by rdeioris** [comment]
Display names in sequencer are properties:

```python
camera_cut_track.DisplayName = 'TestRename'
```

**Comment by nessusing** [comment]
Thanks rdeioris. It works. I am still very new to UE API. How do you tell apart a function and a property in UE? The UE document puts SetDisplayName() in the function category.

**Comment by nessusing** [comment]
While I am at it, I also wanted to explore how calling functions work. I tried the following:
`camera_cut_track.call('IsAMasterTrack')`
`camera_cut_track.call_function('IsAMasterTrack')`
Both failed. I then tried:
`camera_cut_track.functions()`
it only returned:
`['ExecuteUbergraph']`

How do I access the functions that are available for UMovieSceneAudioTrack?
Thank you.

**Comment by rdeioris** [comment]
Regarding UE docs only the functions with the 'u' logo in the left are exposed to the reflection system. For the others we need ad-hoc wrappers. By the way generally properties() exposes lot of features (most undocumented) so working on them is the best start.

Here are the optimized wrappers related to the sequencer:

https://github.com/20tab/UnrealEnginePython/blob/master/Source/UnrealEnginePython/Private/UEPyModule.cpp#L697

to check if you are working with a master track you can simply compare the item with the list returned by sequencer_master_tracks()

```python
if camera_cut_track in seq.sequencer_master_tracks():
    ...
````

or eventually make a pull request for exposing something like sequencer_is_master_track(track)
