### ISSUE TITLE
how delete sequence Track? 

### ISSUE THREAD

**Issue by heylenz** [20tab/UnrealEnginePython#204]
I try to find a function to delete sequence track ,but not found ! can python do it? and 
I can not find the delete command，like right menu delete command！ i just found delete_asset!

**Comment by rdeioris** [comment]
Hi, pull latest code. It includes item removals wrappers:

https://github.com/20tab/UnrealEnginePython/blob/master/Source/UnrealEnginePython/Private/UEPyModule.cpp#L714

**Comment by heylenz** [comment]
get it !thanks!
