### ISSUE TITLE
multiprocessing's Process.start() seems to create a new UE session instead of launching a thread

### ISSUE THREAD

**Issue by mrpropellers** [20tab/UnrealEnginePython#205]
From the Python class created by a Python component:
```python
import multiprocessing

class Foo:
def bar(self):
  # Do stuff

def bar_with_timeout(self, timeout):
  p = multiprocessing.Process(target=self.bar)
  p.start()
  p.join(timeout)
```
When p.start() gets called from a PIE session, a new Unreal Engine instance gets started with my current project loaded.  Since I was calling bar_with_timeout from tick, this happens indefinitely until I use Task manager to kill all instances of UE.  I know I was trying to cheat by importing a threading module without rebuilding with the threading support, so maybe this is a known issue...  Still it's pretty funny!  Maybe there is a way to block import of modules that will clearly screw up the plugin?

**Comment by rdeioris** [comment]
Yep, it is expected as the multiprocessing module builds a unix fork()-like environment.

If you want parallelism you need threading (that should be pretty solid now) or external processes speaking via some form of IPC (sockets)

**Comment by mrpropellers** [comment]
I was able to get the behavior I needed with a threading.Thread object.  Interesting how the behavior differs, but probably no outstanding issue here if it's known and understood, thanks!
