### ISSUE TITLE
Earliest supported version?

### ISSUE THREAD

**Issue by theodox** [20tab/UnrealEnginePython#206]
I've been trying to build against our 4.13 based Unreal Engine but I've had little luck.  It looks like there are differences for the following classes 

* `FAssetStringReference`
* `FReferenceSkeleton`
* `UAnimSequence`
* `UAnimMontage`
* `FClassIconFinder`

 I see an `#if ENGINE_MINOR_VERSION == 13` block but it seems to be surrounding a reference to something my 4.13 doesn't have (or maybe has in a different header).   Is there by any chance way I can spot other stuff which is built against later engine versions?Are there tags or labels in the project which might help me figure out what won't roll back to 4.13?

**Comment by rdeioris** [comment]
Hi, the oldest is the 4.12 (in the sense that we offer commercial support for it), but the master has various issue with versions < 4.14. I have just pushed a pre4.15 branch, you can try it. Let me know if it works for you
