### ISSUE TITLE
 'Sequencer_section_add_key' parameter added FRotator found error

### ISSUE THREAD

**Issue by heylenz** [20tab/UnrealEnginePython#207]
when i try to Importing FBX Camerea into CineCameraActor in Sequencer, I place each curve transform in the sequencer timeline,
when Sequencer_section_add_key parameter add FRotator all key will be 0,
```python
transform.sequencer_section_add_key(key, FTransform(FVector(v[0],v[1],v[2]), FRotator(v[3],v[4],v[5])))
```
when remove FRotator transform will be ok
```python
transform.sequencer_section_add_key(key, FTransform(FVector(v[0],v[1],v[2]))))
```
Is i doing it wrong? or bug？

**Comment by rdeioris** [comment]
What is the output of the following commands ? 

```python
transform = FTransform(FVector(1, 2, 3), FRotator(90, -90, 10))
ue.log(transform)
```

**Comment by heylenz** [comment]
output
```
<unreal_engine.FTransform {'translation': (1.0, 2.0, 3.0), 'rotation': (85.96376037597656, -90.0, 14.036263465881348), 'scale': (1.0, 1.0, 1.0)}>
```

**Comment by heylenz** [comment]
sorry!  Maybe I made mistakes
When I add camara to sequence It will aotu create transform track,and then I created new transform track for this camera, so when i delete empty transform track, key looks ok!

**Comment by heylenz** [comment]
I found new question,
No matter how large I set, or how small the value, can not let the rotation value becomes larger
in sqeuence ecitor i found camera track's transform value is ok as i see! but rotation value was not ok!

```
transform = FTransform(FVector(1, 2, 3), FRotator(90, -90, 10))
# rx = -0.511675
# ry = 0.454519
# rz = 0.541675
```
when  import camera fbx the translation value can be larger!
