### ISSUE TITLE
Unable to call functions on actors

### ISSUE THREAD

**Issue by Devination** [20tab/UnrealEnginePython#208]
Hello, I just started using this plugin a couple of days ago. Very cool project, thanks for putting it up here!

While following the samples listed under [Native methods VS reflection](https://github.com/20tab/UnrealEnginePython#native-methods-vs-reflection) I discovered that I could access properties of actors as shown in the samples, but when I tried to call functions I get the following errors:
`AttributeError: 'unreal_engine.UObject' object has no attribute 'CanModify'` or `Exception: unable to find function`

Here is the code I'm using:
```python
import unreal_engine as ue

#Get the selected StaticMeshActor
world = ue.get_editor_world()
actor = ue.editor_get_selected_actors()[0]

#I can access variables just fine
print(actor) #<unreal_engine.UObject 'SomeCube' (0x00000164545BF200) UClass 'StaticMeshActor'>
print(actor.bHidden) #False
print(actor.StaticMeshComponent) #<unreal_engine.UObject 'StaticMeshComponent0' (0x00000163CB65A080) UClass 'StaticMeshComponent'>

#Errors when trying to call functions
print(actor.CanModify()) #AttributeError: 'unreal_engine.UObject' object has no attribute 'CanModify'
print(actor.call_function("CanModify")) #Exception: unable to find function
```

I've tried plenty of functions from these pages:
https://docs.unrealengine.com/latest/INT/API/Runtime/Engine/Engine/AStaticMeshActor/index.html
https://docs.unrealengine.com/latest/INT/API/Runtime/Engine/GameFramework/AActor/index.html
https://docs.unrealengine.com/latest/INT/API/Runtime/CoreUObject/UObject/UObject/index.html

All of the functions give the same error. However, I can access all of the variables listed on those pages just fine. Any idea what's going on?

Two interesting things to note: I'm using Unreal 4.16 and Python 2.7

**Comment by rdeioris** [comment]
Hi, only the functions marked in the ue4 docs with the 'u' on the left are available to the reflection system. You can get them with the functions() method (very few are exposed generally).  Handy functions are wrapped by the plugin (can_modify is not but it is very easy to add new wrappers).

**Comment by rdeioris** [comment]
here you can get the list of wrappers

https://github.com/20tab/UnrealEnginePython/blob/master/Source/UnrealEnginePython/Private/UEPyModule.cpp#L326

**Comment by Devination** [comment]
Ah ok I didn't realize, thanks. Is there a small example I could look at for how to add new wrappers?

**Comment by rdeioris** [comment]
This commit should help you: https://github.com/20tab/UnrealEnginePython/commit/6f2033392e8a854325b31efe91ad366c368c1dca
