### ISSUE TITLE
FBX Import bImportAsSkeletal = False not working

### ISSUE THREAD

**Issue by grichardsonHalon** [20tab/UnrealEnginePython#209]
Hi,

I just pulled the latest update and the PyFbxFactory ImportUI property, bImportAsSkeletal I do not think it communicating properly. It still imports a skeletal mesh with my fbx.

**Comment by unbit** [comment]
Please paste the code

**Comment by rdeioris** [comment]
This is the code for importing a skeletal mesh as a static one:

```python
from unreal_engine.classes import PyFbxFactory
from unreal_engine.enums import EFBXImportType

factory = PyFbxFactory()
factory.ImportUI.MeshTypeToImport = EFBXImportType.FBXIT_StaticMesh

mesh = factory.factory_import_object('D:/Users/rober/Downloads/run.fbx', '/Game/Assets001/Vampire')
```

**Comment by grichardsonHalon** [comment]
`from unreal_engine.classes import PyFbxFactory

importFile = "C:/Users/grichardson/Desktop/PRP_TobaccoPipe_UEAnim_v0001.fbx"

skeleton = "PRP_TobaccoPipe"

factory = PyFbxFactory()

factory.ImportUI.bImportAsSkeletal = False
factory.ImportUI.bImportMesh = False
factory.ImportUI.bImportAnimations = True
factory.ImportUI.bImportTextures = False
factory.ImportUI.bCreatePhysicsAsset = False
factory.ImportUI.bImportMaterials = False
factory.ImportUI.Skeleton = skeleton

factory.factory_import_object(importFile, '/Game/test')`

**Comment by rdeioris** [comment]
This is not the correct way, you need a reference to the skeleton asset:

```python
# something like this
factory.ImportUI.Skeleton = ue.load_object(Skeleton, '/Game/YourSkeletonPath')
```
(check here for more infos https://github.com/20tab/UnrealEnginePython/blob/master/tutorials/YourFirstAutomatedPipeline.md#importing-animations-and-creating-a-new-monodimensional-blendspace-for-locomotion)

**Comment by grichardsonHalon** [comment]
Oh sorry, I wrote that code already, I forgot that I already referenced the skeleton asset. But that still does not answer my issue

**Comment by rdeioris** [comment]
You need to set the MeshTypeToImport like shown before but setting it to animation instead of staticmesh

**Comment by grichardsonHalon** [comment]
Ahh okay, that ended up working out. Thank you very much!
