### ISSUE TITLE
import classes from other python scripts

### ISSUE THREAD

**Issue by MatzeOGH** [20tab/UnrealEnginePython#212]
Is it possible to import classes from other files in your scripts folder.
I tried to import a texture import class but I had no luck with the constructor or calling functions of that class.

from MyCustomClass import MyTextureImporter

my_texture_importer = MyTextureImporter(path)

this fails all the time
Copying the class into the same file solves the problem

**Comment by rdeioris** [comment]
If it is a brand new installation, the Scripts directory could not be successfully added to the python path. Restart the project or run

```python
import site
import imp

imp.reload(site)
```

**Comment by MatzeOGH** [comment]
So doing that allows me to split my script into multiple files?

**Comment by rdeioris** [comment]
Yep, otherwise it would not be very 'handy' to write bigger tools. Obviously you can add more 'search paths' for modules, by modifying sys.path list.

Remember that once you import a python module it will remain resident in memory. If you need to reload it, just do imp.reload(module_name)

**Comment by MatzeOGH** [comment]
Thanks, I'll try that later today.
