### ISSUE TITLE
Calling UnrealEnginePython from another software ?

### ISSUE THREAD

**Issue by Papoun** [20tab/UnrealEnginePython#215]
Hey there ! :-) 
Just found out this project while searching for UE4 Python support, and wanted to know how does the plugin handle command calls from external programs ?

I'll soon start investigating it (probably around this weekend), but any tips/tricks on the general workflow would be greatly appreciated ! 👍 

Thanks !

PS : Sorry if this is in the wrong section, this is the first time i post on Github ^^'

**Comment by rdeioris** [comment]
Hi, what you mean exactly for external command calls ? you have full support for asyncio in the engine (writing an article about it right now) so you can basically open all of the communication channels you need and we are working in FMessageBus support too.

**Comment by Papoun** [comment]
Hi, thanks for the quick answer ! :) i'd basically like to use sockets to communicate between two applications (say Maya and UE4).

Haven't tested UnrealEnginePython yet so i dunno if it's possible with it ? 

Thanks !

**Comment by rdeioris** [comment]
Yep absolutely, you can use basically any python library. For best/safest networking communication check this work in progress tutorial (should be complete soon):

https://github.com/20tab/UnrealEnginePython/blob/master/tutorials/AsyncIOAndUnrealEngine.md
