### ISSUE TITLE
Exposing Slate Notifications

### ISSUE THREAD

**Issue by MatzeOGH** [20tab/UnrealEnginePython#216]
Is it possible to use the slate notification manager to show an in progress notification already?
It would help a lot to display some kind of visual when the editor is busy(ie. importing a lot of textures) with a task

**Comment by rdeioris** [comment]
Pull latest code (it includes the ue.slate_tick() function):

```python
from unreal_engine import SWindow, SProgressBar
import unreal_engine as ue

# sizing_rule =1 means autosizing
window = SWindow(title='slow task', sizing_rule=1)
progress_bar = SProgressBar()
# add the progress bar to the window window.set_content(progress_bar) is the same
window(progress_bar)


import time

for i in range(0, 100):
    time.sleep(0.1)
    progress_bar.set_percent(1/100 * i)
    ue.log('slow task iteration: {0}'.format(i))
    ue.slate_tick()
```

**Comment by rdeioris** [comment]
More complex example here: https://github.com/20tab/UnrealEnginePython/blob/master/examples/slow_task_with_progress_bar.py

**Comment by MatzeOGH** [comment]
Thanks, that might work
