### ISSUE TITLE
Mobile Devices

### ISSUE THREAD

**Issue by LarsGroh** [20tab/UnrealEnginePython#22]
We intend to use the plugin within a project, where we need to deliver the application for several plattforms - including Desktop, VR and Mobile (iOS and Android).

How would the plugin work on a mobile device? I am not familiar with running python on mobile devices, which might already answer the question.

**Comment by rdeioris** [comment]
Hi, currently the kivy project is the best bet to add libpython to the final build. Unfortunately we still have not focused on the mobile platforn, but it should be doable

**Comment by rdeioris** [comment]
Android support has been added: https://github.com/20tab/UnrealEnginePython/blob/master/docs/Android.md

**Comment by rdeioris** [comment]
iOS support proposed: https://github.com/20tab/UnrealEnginePython/pull/601
