### ISSUE TITLE
Autocomplete in other IDE?

### ISSUE THREAD

**Issue by taba9** [20tab/UnrealEnginePython#221]
Any options on getting autocomplete for this plugin in other IDE's ?
I try getting this to work in vs code or pycharm but no success atm.

Can you provide some informations how i can get this to work ?

**Comment by rdeioris** [comment]
Hi, i have only implemented a generator for sublime text:

https://github.com/20tab/UnrealEnginePython/blob/master/tools/generate_sublime_text_autocomplete.py

I think you can follow the same approach for visual studio code:

https://code.visualstudio.com/docs/editor/userdefinedsnippets

**Comment by johnfredcee** [comment]
This approach probably won't work for Visual Studio Code, as it doesn't use pre-generated json files to drive autocompletion but instead uses JEDI https://github.com/davidhalter/jedi 

The way forward would seem to be to embed JEDI in UEPython.
