### ISSUE TITLE
FRotator<->FQuat functions don't seem to be exposed

### ISSUE THREAD

**Issue by mrpropellers** [20tab/UnrealEnginePython#222]
It seems like none of the functions for converting between FRotator and FQuat are exposed.

Constructors like FRotator(FQuat) or FQuat(FRotator) and the conversion functions FRotator.Quaternion() and FQuat.Rotator() seem to all be missing.  Shouldn't the "CORE_API" ufunctions map to uobjects "auto-magically?"

**Comment by rdeioris** [comment]
Hi, if you pull recent code you should find an improved implementation of both FQuat and FRotator (we are working on scriptable animation retargeting so they needed to be improved).

Particularly, FRotator constructor can take an FQuat as argument and an FRotator object exposes the .quaternion() method

**Comment by mrpropellers** [comment]
Thanks.  Updated from mainline (90+ commits!)  and got the functionality I needed.
