### ISSUE TITLE
Compilation error for Linux/UE-4.17/clang-3.8

### ISSUE THREAD

**Issue by mmmaat** [20tab/UnrealEnginePython#223]
Hello,

I'm trying to setup UnrealEnginePython on UE-4.17 within Ubuntu 16.04. I get one warning and one error...

* Warning

Once I created a new empty project and cloned the Python plugin in .../Plugins/UnrealEnginePython, the UE4Editor complains with the following message: *This project requires the 'UnerealEnginePython' plugin, which is not compatible with the current engine version. Would you like to disable it? You will no longer be able to open assets created using it.* Just answering *No* seems ok, but I guess there is a little issue in the plugin integration with UE-4.17.

* Error [1/4] Compile Module.UnrealEnginePython.2_of_3.cpp

In file included from .../Plugins/UnrealEnginePython/Source/UnrealEnginePython/Private/UEPyEditor.cpp:231:16: error: default initialization of an object of const type 'const FString' without a user-provided default constructor
        const FString mobile_device;

The piece of code is here, just adding the initialization in bold fix the error...

#if ENGINE_MINOR_VERSION >= 17
	const FString mobile_device **= FString("")**;
	GEditor->RequestPlaySession(&v, &r, false, false, mobile_device);
#else
	GEditor->RequestPlaySession(&v, &r, false, false);
#endif

Thank you,
Mathieu

**Comment by rdeioris** [comment]
Hi, Mathieu, thanks for reporting, would you like to make a pull request for the FString initialization ?

**Comment by mmmaat** [comment]
Done ;)
