### ISSUE TITLE
extenders_example.py stopped working

### ISSUE THREAD

**Issue by sinokgr** [20tab/UnrealEnginePython#227]
In the past few builds, this seems to have have stopped working. It makes UE to instantly crash.
(of course I've added it to the scripts folder renamed as ue_site.py)

**Comment by rdeioris** [comment]
Hi, do you have a backtrace from UE4 ?

**Comment by sinokgr** [comment]
Don't know what's that. Something like an error log? Where can I find it?

**Comment by rdeioris** [comment]
When UE4 crashes it generally generates a windows with the backtrace of the error

**Comment by sinokgr** [comment]
OK, I have to leave now. I'll do it tomorrow.

**Comment by sinokgr** [comment]
Don't know if that helps, but below is the screenshot of the window I'm getting.
That's UE 4.16, with the latest release from the plugin for Python27 on Windows.
The only think I've done is created a ue_site.py file in the scripts folder and copy/pasted the code from the extenders_example.py. Hope that helps.

I've uploaded the project [here](https://drive.google.com/file/d/0B6VzQgjFuZ7-TWZuUVRzMGlFQkU/view?usp=sharing) if that's any help

![image](https://user-images.githubusercontent.com/22396951/30856468-5f90a4ca-a2b0-11e7-8dfd-d6dda9b6a553.png)

**Comment by rdeioris** [comment]
Hi, can you try with latest code from master ? I have refactored both menu and toolbar builders to avoid pointers

**Comment by sinokgr** [comment]
Hi @rdeioris, seems to be working fine now! Thanks 👍
