### ISSUE TITLE
mixamo.py issues

### ISSUE THREAD

**Issue by moadib** [20tab/UnrealEnginePython#228]
I just tried it with YBot character from Mixamo site on ue 4.17 and _rooted version have visible artifacts. Some spherical joints are missed and some vertices messed up.

Also, i think that "required_bones" should contain all bones from old skeleton, not only from bone_map.

**Comment by rdeioris** [comment]
Hi can you post the animation file and a screenshot ?

**Comment by moadib** [comment]
Skin+Animation(no issues there)
[mixamo.zip](https://github.com/20tab/UnrealEnginePython/files/1333378/mixamo.zip)

**Comment by rdeioris** [comment]
Thanks for reporting, the problem was caused by ybot having multiple sections. I have updated the script and updated the tutorial with a special note with your credits:

https://github.com/20tab/UnrealEnginePython/blob/master/tutorials/FixingMixamoRootMotionWithPython.md#update-20170927-by-issue-228

**Comment by moadib** [comment]
Thanks! Mesh geometry converted without issues now. But there is some difference in bones hierarchy.

Original model: ![mixamo_original](https://user-images.githubusercontent.com/190252/30902699-45458400-a37d-11e7-9c44-87327c5b9f9c.jpg)

Fixed by script: ![mixamo_fixed](https://user-images.githubusercontent.com/190252/30902703-47a7c62c-a37d-11e7-96f8-83f352d4c08b.jpg)

If my assumptions are correct - "required bones" in converted model must contains all "required bones" from old. Not only from new_bone_map.

**Comment by rdeioris** [comment]
I have updated the script a bit.

Basically active_bones are the ones mapped to one or more vertices (in the old script it was the required_bones list). So i have changed the code to dynamically build the active_list, and to mark as required_bones all of the single bone of the Skeleton.
