### ISSUE TITLE
Install as Engine Plugin

### ISSUE THREAD

**Issue by LarsGroh** [20tab/UnrealEnginePython#229]
Is it possible to install the plugin es an engine plugin instead of a project plugin?

**Comment by rdeioris** [comment]
Hi @LarsGroh just copy the plugin directory into Engine/Plugins in your specific veditor version directory (the one you choose when installing new editors from the launcher)

**Comment by sabhiram** [comment]
Word to the wise, depending on your platform, you might have to build the plugin in another project and then you should be able to move it to the engine's `Plugins` directory.

**Comment by LarsGroh** [comment]
Hi,
thanks for the reply. I actually tried this, but I will give it another go.
Regards,
Lars

**Comment by LarsGroh** [comment]
Hi,
built it in a 4.17 project and copied it to the engine plugin folder - works perfectly!
Thanks!
