### ISSUE TITLE
Cant' set list property - Materials

### ISSUE THREAD

**Issue by LarsGroh** [20tab/UnrealEnginePython#23]
Hi,

I am tryint to change the materials on an imported asset in the content browser, which is a Static Mesh by the uniqe name "test":

I get a reference to the static mesh and also the material, that I want to assign.
Both "find_object" operations work fine and I am able to retrieve the current materials by calling
get_property("Materials"). But setting the property with a new list won't work - example code:

```
import unreal_engine as ue
my_asset = ue.find_object("test")
new_material = ue.find_object("test_material")
my_asset.set_property("Materials", [new_material])

Exception: unable to set property Materials
```

Is there any special kind of List/Array-instance I need to create and pass?

**Comment by rdeioris** [comment]
Hi, the patch to 'write' arrays in in my queue. I will push it tomorrow with the new features

**Comment by rdeioris** [comment]
@LarsGroh arrays writing is now avaialble. Remember you can do

```py
my_asset.Materials = [new_material]
```

instead of directly calling set_property()

**Comment by LarsGroh** [comment]
Hi,
Thanks a lot. I've tried it out.. this works:

```
import unreal_engine as ue
ue.get_selected_assets()[0]""
# selecting the skeletal mesh manually in the content browser
a = ue.get_selected_assets()[0]
# selecting the material manually in the content browser
m = ue.get_selected_assets()[0]
materials = a.Materials
materials[0] = m
a.Materials = materials
```
But this approach causes the editor to crash:
```
def find_object(path):
    object_ = None
    try:
        object_ = ue.find_object(path)
        return object_
    except:
        pass
    finally:
        return object_

def relink_materials(asset, materials_folders):

    new_mats = []
    for material in asset.Materials:
        mat_name = material.get_name()

        supposed_path = "%s/%s" % (materials_folders, mat_name)
        ue.log("Looking for this material: %s" % supposed_path)
        supposed_material = find_object(supposed_path)

        if supposed_material:
            ue.log("Found supposed material and assigning it: %s" % supposed_path)
            new_mats.append(supposed_material)
        else:
            new_mats.append(material)

    if new_mats:
        asset.Materials = new_mats

    return new_mats


relink_materials(a, "/Games/Content/Materials")
```
The respecitve materials in the Materials folder are being found and assigned to the list.
But when I navigate into the content folder browser Unreal crashes when it tries to reload the Material thumbnails.

Any suggestions?

**Comment by rdeioris** [comment]
can you pull latest code ? I have tried to reproduce your problem but your script works flawlessly. Are you using python 2 or 3 ?

**Comment by LarsGroh** [comment]
Hi,
I pulled the latest code. I am using python 3.
The error still occurs. But I figured out why:

"ue.find_object" returns an instance of type "Pakage" and not of type "Material".
This causes Unreal to crash - how do I retreive an insance of the acutal type?

Another strange thing was, that "find_object" only returns an instance, when another instance of the object/asset has already been initialized before - e.g. by calling ue.get_selected_assets() on it.
Is there some initializiation that needs to be executed for all content browser assets to be "available"?

**Here is my output:**

```
>>> m = ue.find_object("Game/Materials/my_test_material")
unable to find object Game/Materials/my_test_material
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Exception: unable to find object Game/Materials/my_test_material

# with my_test_material selected:
>>> m = ue.get_selected_assets()[0]
>>> ue.log(m)
<unreal_engine.UObject 'my_test_material' (0x00000000488150C0) UClass 'Material'>
>>> m = ue.find_object("Game/Materials/my_test_material")
>>> ue.log(m)
<unreal_engine.UObject 'Game/Materials/my_test_material' (0x0000000035C94B80) UClass 'Package'>
```

**Comment by LarsGroh** [comment]
Ok..I dug around a bit and seems I have missed the difference between loaded and unloaded objects.
"ue.load_object(Material, "MY_PATH") does what I need. 

But what's the actuall use-case for "find_object" then?

**Comment by rdeioris** [comment]
Hi, as you have already spotted, find_object is only meaningful when an object is already loaded in memory. It is basically an optimization. More infos here:

https://docs.unrealengine.com/latest/INT/Programming/Assets/ReferencingAssets/

(Find/Load Object section)

What i need to understand is why the editor crashes. The property system should warn you when you try to inject the wrong type. I will investigate on it. Thanks

**Comment by rdeioris** [comment]
@LarsGroh ok i have managed to reproduce the crash. Basically when creating array the type-safety is not correctly checked. Expect a patch soon. I will close the ticket once the error is fixed.

**Comment by rdeioris** [comment]
The crash problem should be fixed now. Regarding your specific problem  with find_object:

```py
 m = ue.find_object("/Game/Materials/my_test_material")
```

refers to a UPackage.

while

```py
 m = ue.find_object("my_test_material")
```

refers to the Material.

You can Eventually be more strict and use:

```py
 m = ue.load_object(Material, "/Game/Materials/my_test_material")
```

(the first parameters ensures the to load the object of the specified type)

**Comment by LarsGroh** [comment]
Hey,
thank you some much for your effort and support!!!
This Plugin is going to improve our efficiency by far!

**Concerning ue.find_object:**

Shouldn't the return value be the same regardless the path specification?
In my case, I don't acutally know what a UPackage is  - but that's my problem and I need to look it up.
But isn't it confusing to get different types with essentially the same method - especially when supplying the more specific full path? 
In my case using the short name is not suitable as I have several Materials with the same name in different folders.

But based on this fact - is there a way to get the Material reference through UPackage - is this again something I would find in the UE4 docs?

**Comment by rdeioris** [comment]
Unfortunately this is how the unreal api works :( (they are two different objects for unreal) But i totally agree, consistence is really important. I will check how to improve it

**Comment by rdeioris** [comment]
Btw, have you tried if 

```py
mat = ue.load_object(Material, '/Game/Materials/my_test_material')
```

works for you ?

**Comment by LarsGroh** [comment]
Alright, then I guess I just need to get more into the unreal api itself.
Yes, ue.load_object works for me just fine!

Thanks!!
