### ISSUE TITLE
Save asset thumbnails

### ISSUE THREAD

**Issue by sinokgr** [20tab/UnrealEnginePython#230]
Is there any way to save the asset thumbnails to images?
I'm trying to create an external tool that will show the assets so I was wondering if there is any way, where I can "cache" the thumbnails to a folder. I don't mind if it's a script that I will run from inside unreal in order to save the images out.

**Comment by rdeioris** [comment]
@sinokgr Just added the thumbnail api:

https://github.com/20tab/UnrealEnginePython/blob/master/docs/Thumbnail_API.md

Check this example too:

https://github.com/20tab/UnrealEnginePython/blob/master/examples/thumbnail_viewer.py

Let me know if it works for you (hey remember to pull latest code ;)

**Comment by sinokgr** [comment]
@rdeioris , you are a legend🥇.
Copy pasted the python and i'm getting an error.
unable to retrieve thumbnail
Traceback (most recent call last):
  File "<string>", line 12, in <module>
Exception: unable to retrieve thumbnail
I'll try to re-download everything from scratch because I have a feeling I messed it up.

**Comment by sinokgr** [comment]
Hm.. so.. I think the problem is with the Python code, not the C++.
I tried a simpler version of:
```Python
import unreal_engine as ue
import os
import io
from PIL import Image
from array import array

meshes = ue.get_assets_by_class('StaticMesh')
thumbnail = meshes[0].get_thumbnail()

bytes = thumbnail.get_uncompressed_image_data()

image = Image.open(io.BytesIO(bytes))
image.save(r"c:\users\sinokgr\Desktop\testtt.jpg")
```
but it crashes when I try to convert the bytes to data.
cannot identify image file <_io.BytesIO object at 0x00000291CE2C0938>
Traceback (most recent call last):
  File "<string>", line 13, in <module>
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2319, in open
    % (filename if filename else fp))
IOError: cannot identify image file <_io.BytesIO object at 0x00000291CE2C0938>

Any idea why?

**Comment by rdeioris** [comment]
Image.open expects an image file or stream, for passing a byte array you need Image.frombytes

**Comment by sinokgr** [comment]
Awesome! this seems to have done the trick. Thanks 👍 
```Python
import unreal_engine as ue
import os
from PIL import Image
from array import array

meshes = ue.get_assets_by_class('StaticMesh')
thumbnail = meshes[0].get_thumbnail()

width = thumbnail.get_image_width()
height = thumbnail.get_image_height()
data = thumbnail.get_uncompressed_image_data()

image = Image.frombytes('RGBA', (width, height), buffer(data))
image.save(r"c:\users\n.moutafis\Desktop\testtt.jpg")
```
