### ISSUE TITLE
In Use By Level

### ISSUE THREAD

**Issue by sinokgr** [20tab/UnrealEnginePython#231]
Hi there,
In unreal there is a filter called "In Use By Level". Can you please add it as property in the assets?
I want to search all assets and delete any assets not used by any level. I tried doing it with Python and recursively looking through using **ue.get_asset_referencers()** and **ue.get_asset_dependencies()** by either going up the levels for each asset until I find a level, or by collecting all the levels and going down until I collect all the assets. It works great for small projects, but in our actual production projects, Python hits it's recursion limit. I've tried increasing the recursion limit but still I get recursion limit crashes.
Cheers,
Nick

**Comment by rdeioris** [comment]
Hi, first of all get latest code as it add support for the class_generated_by() method. Then play with this script:

https://github.com/20tab/UnrealEnginePython/blob/master/examples/get_uobjects_in_loaded_levels.py

it is the python implementation of unreal makes in c++ into ObjectTools.cpp

**Comment by sinokgr** [comment]
Hi @rdeioris ,
I tried to download and build the latest version, but I got a few errors.

UEPyEditor.cpp
![image](https://user-images.githubusercontent.com/22396951/31072927-d2f43bb0-a761-11e7-9654-d2821d571580.png)
![image](https://user-images.githubusercontent.com/22396951/31072947-e12e72e0-a761-11e7-91fd-cffe895c864d.png)

SceneManagement.h
![image](https://user-images.githubusercontent.com/22396951/31072960-ec72dc22-a761-11e7-8ea6-d59608e2c98b.png)

Thanks,
Nick

**Comment by rdeioris** [comment]
Hi, the build on < 4.17 should be fixed
