### ISSUE TITLE
Issue with python components in subdirectory

### ISSUE THREAD

**Issue by sabhiram** [20tab/UnrealEnginePython#232]
Heyo! Awesome plugin - this has made our development process much simpler (so far). One small gripe I have had has to do with the following scenario:

1. Make an actor in the `Content/Scripts` directory - lets call him `foo_actor.py`
2. Have another directory in scripts called lets say `Content/Scripts/components`
3. Make a component class (pure python or extending an actor etc), lets call that `bar.py` which implements a class Bar
4. Create a __init__.py in components so we can include things from here
5. Have `foo_actor.py` include this line: `from compoenents.bar import Bar`

You will notice that the editor correctly reloads changes in `foo_actor.py` but not in `bar.py`. 

Any ideas where to look? I run a slightly modified version of your plugin at the moment anyway and don't mind getting my hands dirty w/ plugin C code.

**Comment by rdeioris** [comment]
Hi, everything you import in your script via the 'import' directory became resident. If this is not what you want, you need to use the imp module:

```python
import foobar
import imp
imp.reload(foobar)
```

It is important to maintain the original python behaviour by default and allow the user to modify it on-demand
