### ISSUE TITLE
Question about access to C++ class

### ISSUE THREAD

**Issue by sabhiram** [20tab/UnrealEnginePython#233]
How would one go about getting access to creating the following class:
https://docs.unrealengine.com/latest/INT/API/Runtime/Core/Math/FVector2D/index.html

**Comment by rdeioris** [comment]
Hi, structs registered with the reflection system (like FVector2D) can be accessed like this:

```python
from unreal_engine.structs import Vector2D

v = Vector2D(X=17,Y=22)
```

take into account that the python slate api (as an optimization) uses a tuple of two floats whenever an FVector2D is expected

**Comment by sabhiram** [comment]
Bah, makes sense. Thank you for the quick replies!
