### ISSUE TITLE
Can't compile python plug-in

### ISSUE THREAD

**Issue by StrahmS** [20tab/UnrealEnginePython#236]
Following the instruction for installing the plugin on mac from source does not work on my machine. When I restart my unreal-project, Xcode try to build relevant dependencies but always fails to complete. Error-Message: "... try to build from source". 
Am I missing something?

**Comment by rdeioris** [comment]
Does the binary releases work for you ? Can you paste the logs of the build procedure ?

**Comment by StrahmS** [comment]
I also tried with the binary releases and restarted unreal. Same problem: can't reopen my project

**Comment by rdeioris** [comment]
Can you paste a screenshot of the error ?

**Comment by StrahmS** [comment]
![bildschirmfoto 2017-10-05 um 16 23 09](https://user-images.githubusercontent.com/20658847/31232306-ca590bd6-a9e9-11e7-88fc-2cefb02ddf0a.png)

**Comment by StrahmS** [comment]
![bildschirmfoto 2017-10-05 um 16 25 01](https://user-images.githubusercontent.com/20658847/31232310-cf027b04-a9e9-11e7-8425-c70cc39bf585.png)

**Comment by StrahmS** [comment]
So I chose to build them, and the log reports 2 or more errors, but the breaks down and it shows me this error-mesage.

**Comment by rdeioris** [comment]
Oh ok, well you should open the project from xcode and run the build from there, so you can report which error the compiler is reporting

**Comment by StrahmS** [comment]
I'm not sure, if this is what you searched for, but: 
![bildschirmfoto 2017-10-05 um 16 40 47](https://user-images.githubusercontent.com/20658847/31233135-2f003378-a9ec-11e7-8754-e02db260cd59.png)

**Comment by rdeioris** [comment]
Yep i will fix it, but in the mean time you can get this sources from the release page:

https://github.com/20tab/UnrealEnginePython/archive/20170911.tar.gz

**Comment by StrahmS** [comment]
Ok, thanks for your quick response and your help. I'll try to install it again with this sources and give you a feedback. Thx

**Comment by StrahmS** [comment]
Perfect! Everything is working now. Many thanks!

**Comment by rdeioris** [comment]
Current code should now build flawlessly on mac/linux
