### ISSUE TITLE
PyQt5 no events delivered on Mac OS?

### ISSUE THREAD

**Issue by RonFischer** [20tab/UnrealEnginePython#24]
Example from readme is OK on Windows, but on Mac spinning wheel and no mouse over events.

How are events getting delivered in the Windows release and how does Mac differ?

Easy for me to work around by moving to Windows for now. Thank you.

**Comment by RonFischer** [comment]
I installed PyQt5 using pip3 and can run PyQt5 outside UE fine.

I tried the dynamic load path trick. Unclear where it should be pointed on Mac OS.

If anyone has experience with this thanks in advance.

**Comment by rdeioris** [comment]
Hi Ron, are you using the experimental thread build or the standard one ?

**Comment by RonFischer** [comment]
Standard.

**Comment by rdeioris** [comment]
Ok, i'll check it tomorrow as i will include the tick patch too

**Comment by osstony** [comment]
This could be due to processEvents never being called. The QApplication is never started and so it is required to manually pump the event loop. This is partly what my pull request for FTicker is meant to go towards solving.

**Comment by RonFischer** [comment]
Curious: Why does it work on Windows?

**Comment by osstony** [comment]
I'm not sure. The issues you're currently seeing may not be due to the event loop never starting. Are you using any Qt Signals?

**Comment by RonFischer** [comment]
Just running the example from the readme page.

I'm not completely sure events aren't being delivered, but the Mac cursor
charges to spinning wheel and Unreal hangs.

Since PyQt runs fine outside of Unreal I don't suspect the install of pyqt5
is bad (done with pip).

Anyone else running this on Mac OS?

**Comment by osstony** [comment]
You are definitely going to hit unexpected issues with Qt when an event loop isn't running or being pumped by using a callback on any OS. Your results are most likely different due to the OS specific implementations within Qt. Once the FTicker patch has been integrated we can get a Qt event loop callback setup at initialization using a python startup file. I personally have not used the OSX version so this is just a guess as to your current issue.

**Comment by rdeioris** [comment]
I think the best thing to do is adding in the README how to use the ticker for Qt, I'll do it soon

**Comment by rdeioris** [comment]
Integration with Qt is now solid thanks to threading enabled by default and dedicated loop:

https://github.com/20tab/UnrealEnginePython#integration-with-qt4qt5pyside2
