### ISSUE TITLE
SetOuterConeAngle doesn't work?

### ISSUE THREAD

**Issue by sinokgr** [20tab/UnrealEnginePython#242]
Any idea why this doesn't work (tested on a spot light)

```Python
import unreal_engine as ue

# Get the root component
rc = ue.editor_get_selected_actors()[0].rootComponent
rc.SetOuterConeAngle(40)
rc.post_edit_change()
```

**Comment by Schizo** [comment]
Hi sinokgr, 

Looking at the methods of the Component, you can use the `set_property` method to set the Cone Angle. I am not so familiar with the internals whether or not your could "supposed to work" but one way is to set a property.

import unreal_engine as ue

```
# Get the root component
rc = ue.editor_get_selected_actors()[0].rootComponent
#rc.SetOuterConeAngle(40)
rc.set_property("OuterConeAngle", 1003.0)
rc.post_edit_change()
```

the attribute names are capital camelcase.

**Comment by sinokgr** [comment]
Hi @Schizo, many thanks for the reply. It doesn't really matter if you use the set_property or use the property name. It's explained [here](https://github.com/20tab/UnrealEnginePython#native-methods-vs-reflection) how the system works. Unfortunately there is no property called "OuterConeAngle" but there is a function called SetOuterConeAngle() which unfortunately doesn't seem to work.

to print all your rootComponent properties, you can use this:
```Python
import unreal_engine as ue

# Print properties
for prop in ue.editor_get_selected_actors()[0].rootComponent.properties():
	print (prop)
```

and for functions you can use this:
```Python
import unreal_engine as ue

# Print functions
for fn in ue.editor_get_selected_actors()[0].rootComponent.functions():
	print (fn)
```
Hope that helps,
Nick

**Comment by Schizo** [comment]
I see, that makes sense! The properties function is handy too, I did just guesswork what the property would be named,  and thought that a `properties()` function would be nice to have, here you go! 

Anyhow, do I hear correct, that you couldn't set the property with the following snippet: 
```python
rc.set_property("OuterConeAngle", 1003.0)
```
Because that works for me, and I can see in the Details window that the values are reflected.

**Comment by sinokgr** [comment]
hm.. that's weird, I just copy-pasted again today your code, and it looks like it works with no issues. I might have missed-typed something last time. Thanks @Schizo 👍
