### ISSUE TITLE
Perspective View Transforms

### ISSUE THREAD

**Issue by sinokgr** [20tab/UnrealEnginePython#243]
Hi there,

Is there any way to get the current active perspective view transform? I want to "sync" (not live) the 3ds Max viewport with Unreal's.

Thanks,
Nick

**Comment by rdeioris** [comment]
Hi, you can check this tiny example:

https://github.com/20tab/UnrealEnginePython/blob/master/examples/viewport_manager.py

ensure to take into account only the viewports with a non zero size

**Comment by sinokgr** [comment]
Just had some time to download and test the new code. Works great! thanks 💯 @rdeioris 
btw, in my case I check if it's a perspective viewport and visible.

```Python
import unreal_engine as ue

for viewport_client in ue.all_viewport_clients():
	if not viewport_client.is_ortho() and viewport_client.is_visible():
		print(viewport_client.get_look_at_location())
		print(viewport_client.get_view_location())
```
