### ISSUE TITLE
Any Snippets about placing items like instancing?

### ISSUE THREAD

**Issue by Schizo** [20tab/UnrealEnginePython#244]
Hi, 

are there any minimal snippets that can place an element and eventually duplicate it's material and do modifications?

Thanks

**Comment by Schizo** [comment]
Found a good reference actually from the examples:

https://github.com/20tab/UnrealEnginePython/blob/master/examples/editor_scripting001.py

**Comment by rdeioris** [comment]
If you have time, would you like to add a snippet about instancing in the repository ? Thanks
