### ISSUE TITLE
Question about struct access / editing

### ISSUE THREAD

**Issue by sabhiram** [20tab/UnrealEnginePython#247]
In a static mesh, we have the `SourceModels` property which is a list of `unreal_engine.UScriptStruct` objects.  Lets say the first one is a `StaticMeshSourceModel` which contains `BuildSettings` as one of the fields.

I would like to modify the `BuildScale3D` which belongs to the `BuildSettings` which is a `MeshBuildSettings` struct. I am able to call `set_field` on the MeshBuildSettings and have it change the field I wish to modify, however when issuing a `.save_package()` to the modified param - the plugin crashes UE4 :)

Any ideas on how this access / modification should be carried out?

**Comment by sabhiram** [comment]
When I directly modify it this way, the exception is seen when calling save_package:
```
sm = ue.load_object(StaticMesh, "/Game/Import/...")
sm.SourceModels[0].BuildSettings.BuildScale = 2.0
sm.save_package()
```

Stack trace:
```
 SEGV_MAPERR at 0x3

FGenericPlatformMisc::RaiseException(unsigned int) Address = 0x108d9e25b (filename not found) [in UE4Editor-Core.dylib]
FOutputDeviceMacError::Serialize(wchar_t const*, ELogVerbosity::Type, FName const&) Address = 0x108fb594f (filename not found) [in UE4Editor-Core.dylib]
FOutputDevice::Logf(ELogVerbosity::Type, wchar_t const*, ...) Address = 0x1090868d5 (filename not found) [in UE4Editor-Core.dylib]
UPackage::Save(UPackage*, UObject*, EObjectFlags, wchar_t const*, FOutputDevice*, FLinkerLoad*, bool, bool, unsigned int, ITargetPlatform const*, FDateTime const&, bool) Address = 0x10a9920d2 (filename not found) [in UE4Editor-CoreUObject.dylib]
UPackage::SavePackage(UPackage*, UObject*, EObjectFlags, wchar_t const*, FOutputDevice*, FLinkerLoad*, bool, bool, unsigned int, ITargetPlatform const*, FDateTime const&, bool) Address = 0x10a9a430c (filename not found) [in UE4Editor-CoreUObject.dylib]
py_ue_save_package(ue_PyUObject*, _object*) Address = 0x189ce76dc [.../Environments/Unreal/BaseEnvironment/Plugins/UnrealEnginePython/Source/UnrealEnginePython/Private/UObject/UEPyObject.cpp, line 1432] [in UE4Editor-UnrealEnginePython.dylib]
PyEval_EvalFrameEx Address = 0x18a00ba0b (filename not found) [in Python]
PyEval_EvalCodeEx Address = 0x18a0083c1 (filename not found) [in Python]
```

**Comment by rdeioris** [comment]
Hi, a fundamental trait of structs is that they are always passed by value (and this is pretty weird for the classic python way):

```python
sm.SourceModels[0].BuildSettings.BuildScale = 2.0
```

this code, albeit valid, is wrong from a logical point of view as the BuildSettings struct has been assigned to a copy. 

Check this example for correct usage:

https://github.com/20tab/UnrealEnginePython/blob/master/tutorials/SnippetsForStaticAndSkeletalMeshes.md#staticmesh-adding-lods

Honestly i really would like to improve this part of the plugin to be more python friendly :(

**Comment by sabhiram** [comment]
Yea I figured I would need to re-instantiate the whole thing. Thanks for pointing out the link above and the handy `save_to_static_mesh_source_model` function.  I still have a doubt about what I am trying to implement: I would like to take a given set of meshes and rescale them via their `BuildSettings.BuildScale3D` without creating a new mesh and deleting the old one. Is that feasible in the current implementation?
