### ISSUE TITLE
Build error on OSX / Linux w/ UE4.18

### ISSUE THREAD

**Issue by sabhiram** [20tab/UnrealEnginePython#249]
In the UEPyLandscape.cpp file, we have this code:
```
	if (heightmap_buffer.len < (Py_ssize_t)(size_x * size_y * sizeof(uint16)))
		return PyErr_Format(PyExc_Exception, "not enough heightmap data, expecting %d bytes", size_x * size_y * sizeof(uint16));
```

However, `size_x * size_y * sizeof(blah)` returns potentially something larger than the max size of an int - and this throws a warning as an error.  We can get around this easily, but just figured I would post here for completeness.

**Comment by rdeioris** [comment]
Thanks for reporting, would you like to make a pull request or you prefer we directly fix it ?

**Comment by sabhiram** [comment]
I can send you something soon :)
