### ISSUE TITLE
Any chance for Linux support for Python with Unreal?

### ISSUE THREAD

**Issue by daeilkim** [20tab/UnrealEnginePython#25]
If not, wondering if there would be a way to help with that. Thanks very much.

**Comment by rdeioris** [comment]
Just add a new "if block" here for linux:

https://github.com/20tab/UnrealEnginePython/blob/master/Source/UnrealEnginePython/UnrealEnginePython.Build.cs#L79

the procedure should be the same of osx

**Comment by rdeioris** [comment]
Oh and if you manage to run it, make a pull request ;)

**Comment by daeilkim** [comment]
Thanks so much for that suggestion. I've tried putting what I thought was the equivalent here, but it seemed to still crash, saying that there is an invalid plugin. 

```
else if (Target.Platform == UnrealTargetPlatform.Linux)
	{
            if (pythonHome == "python35")
            {
                string linux_python = "/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu/";
                PublicIncludePaths.Add("/usr/include/python3.5/");
                PublicAdditionalLibraries.Add(Path.Combine(mac_python, "libpython3.5m.so"));
                Definitions.Add(string.Format("UNREAL_ENGINE_PYTHON_ON_LINUX=3"));
            }
            else if (pythonHome == "python27") {
                string l_python = "/usr/lib/python2.7/config-x86_64-linux-gnu/";
                PublicIncludePaths.Add("/usr/include/python2.7/");
                PublicAdditionalLibraries.Add(Path.Combine(mac_python, "libpython2.7.so"));
                Definitions.Add(string.Format("UNREAL_ENGINE_PYTHON_ON_LINUX=2"));
            }
	}
```
Apologies in advance if this seems obvious. I've tried to include in a similar fashion the python development headers and linux equivalent of the dylib file in mac.

**Comment by daeilkim** [comment]
![screenshot from 2016-09-22 00-39-28](https://cloud.githubusercontent.com/assets/3966792/18737244/11d0711e-805d-11e6-813c-6de1f9752e59.png)

**Comment by daeilkim** [comment]
![screenshot from 2016-09-22 00-41-29](https://cloud.githubusercontent.com/assets/3966792/18737275/5530000a-805d-11e6-9a6a-7e05784d6711.png)

**Comment by rdeioris** [comment]
Can't you enable logging of the build phase ?

By the way, check the UnrealEnginePythonPCH.h file as you need to se the right includes

**Comment by daeilkim** [comment]
Thanks, here's what I find in my logfile that I think is relevant:

[2016.09.22-13.43.37:737][  0]LogModuleManager:Warning: No filename provided for module UnrealEnginePython
[2016.09.22-13.43.37:737][  0]LogModuleManager:Warning: ModuleManager: Unable to load module 'UnrealEnginePython' because the file '/home/daeil/Programs/UnrealEngine/Engine/Binaries/Linux/' was not found.

By UnrealEnginePythonPCH.h, i couldn't find that, but found UnrealEnginePythonPrivatePCH.h which I think you were referring to. Modified it to include this:

```
#elif UNREAL_ENGINE_PYTHON_ON_LINUX == 2
#include <python2.7/Python.h>
```

**Comment by rdeioris** [comment]
Linux is now officially supported:

https://github.com/20tab/UnrealEnginePython#installation-on-linux-64-bit
