### ISSUE TITLE
Adding a toolbar button ?

### ISSUE THREAD

**Issue by Papoun** [20tab/UnrealEnginePython#258]
Hi there ! I was messing around the plugin with building some simple UIs :

```python
SWindow(title='Simple Window', client_size=(256, 45), modal= False)(
        SHorizontalBox()
        (
            SButton(text='Import Mesh', on_clicked=FBX_Importer, h_align=EHorizontalAlignment.HAlign_Center)
        )
    )
```

I'm wondering what is the best workflow for having a button like that in the editor's toolbar ?

![ooe](https://user-images.githubusercontent.com/31083009/33000746-37acf330-cdaa-11e7-9281-a592c7f42a9a.PNG)

I know how to put it in the menus with the help of ue_site.py, but haven't had any success in doing the same with the editor's toolbar.

Sorry if this has already been asked, and thanks in advance for any help !

**Comment by rdeioris** [comment]
Hi, you can check this example: https://github.com/20tab/UnrealEnginePython/blob/master/examples/extenders_example.py

**Comment by Papoun** [comment]
Hey, thanks for the reply ! :)

I've tried using the extenders example (just changed the image path) to test it but the editor instantly crashes on startup, similar to what was [described here](https://github.com/20tab/UnrealEnginePython/issues/227).

I'm using UE 4.16.3 and the [4_16_python36_threaded_embedded_win64](https://github.com/20tab/UnrealEnginePython/releases/download/20170911/UnrealEnginePython_20170911_4_16_python36_threaded_embedded_win64.zip) build for these tests, if that can help.

There's nothing outputted in the crash reporter, too :

![wut_](https://user-images.githubusercontent.com/31083009/33049133-f1126512-ce5e-11e7-9143-002ec5d7d9f0.PNG)


Thanks !

**Comment by rdeioris** [comment]
Can you try with a non-threaded build ?

**Comment by Papoun** [comment]
Hmm looks like the error is still persisting with the non-threaded build, too :/

I tried on another version of UE4 and got the same abrupt crash. Testing it in the python editor also resulted in a crash.

**Comment by rdeioris** [comment]
Can you try with latest binary ? https://github.com/20tab/UnrealEnginePython/releases/tag/20171121

**Comment by Papoun** [comment]
Worked like a charm with the latest binaries ! Thanks a lot !

One last question before closing this, can PyFbxFactory be called in the ue_site.py file on startup ? it always returns a `ImportError: cannot import name 'PyFbxFactory'`, and the icon in the toolbar doesn't show.

Not that it's very important, just curious to know if some imports can/cannot be called on execution of the engine :)
