### ISSUE TITLE
How to get DataTable content?

### ISSUE THREAD

**Issue by 4tmn** [20tab/UnrealEnginePython#260]
Hi guys!
Is there any approach to retrieve data from DataTable?

Thanks!

**Comment by rdeioris** [comment]
I have checked the UDataTable api and i think i would be a good idea to expose its api.

I will work on it soon.

**Comment by rdeioris** [comment]
Hi, the DataTable api has been added: https://github.com/20tab/UnrealEnginePython/blob/master/docs/DataTable_API.md

**Comment by 4tmn** [comment]
Thank you! Great news!
