### ISSUE TITLE
UGameplayStatics class found

### ISSUE THREAD

**Issue by matheus2740** [20tab/UnrealEnginePython#263]
Hello,

While testing out UEPython, I noticed I cant load the `UGameplayStatics` class.

When I do:

```python
gs = ue.load_class('UGameplayStatics')
```

I get an exception saying it couldn't find the class (the class exists, tho).

```
Exception: unable to find class UGameplayStatics
```

**Comment by rdeioris** [comment]
Hi, you have to use the Blueprint naming scheme, so just remove the 'U' prefix:

ue.load_class('GameplayStatics')

or better

from unreal_engine.classes import GameplayStatics

**Comment by matheus2740** [comment]
Neither seems to work...

```
Exception: unable to find class GameplayStatistics
```

**Comment by matheus2740** [comment]
Actually, strangely enough, importind directly worked on my mac (I remember it not working on windows, tho I might be wrong here), but the find_class still does not work.
