### ISSUE TITLE
Failed to import PyFbxFactory when starting UE4

### ISSUE THREAD

**Issue by taotang1984** [20tab/UnrealEnginePython#268]
I am making a plugin to import asset to UE using python. Right now I tried to import PyFbxFactory in ue_site.py. It has following error:

LogPython: Python VM initialized: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
LogPython: Python Scripts search path: E:/UnrealProjects/MyProject/Content/Scripts
LogPython: Error: cannot import name PyFbxFactory
LogPython: Error: Traceback (most recent call last):
LogPython: Error:   File "E:/UnrealProjects/MyProject/Content/Scripts\ue_site.py", line 26, in <module>
    from unreal_engine.classes import PyFbxFactory
LogPython: Error: ImportError: cannot import name PyFbxFactory
LogEngine: Initializing Engine...

Thanks in advance.

**Comment by rdeioris** [comment]
Hi, by default the PythonConsole plugin (the one exposing  PyFbxFactory) is loaded in the 'PostDefault' Phase.: https://github.com/20tab/UnrealEnginePython/blob/master/UnrealEnginePython.uplugin

Just change the phase of the three plugins  to Default or PreDefault.

**Comment by taotang1984** [comment]
That works! Thank you!
