### ISSUE TITLE
Is there a function to select an asset in content browse?

### ISSUE THREAD

**Issue by taotang1984** [20tab/UnrealEnginePython#269]
Hi, I'd like to select an asset in content browse by giving asset name(or uobject), something like select_asset('/Game/test.test'), but I couldn't find it. The only function I found was 'get_selected_assets'. Does anyone have any clue? Thank you!

**Comment by 4tmn** [comment]
[ UnrealEnginePython/docs/ManagingAssets.md ]( UnrealEnginePython/docs/ManagingAssets.md )

**Comment by rdeioris** [comment]
Hi, if you mean "highlighting" an asset in the content browser you can use the brand new 

```python
sync_browser_to_assets(assets, focus)
```

that selects a list of assets (can be UObjects or FAssetData) and (if focus is True), shows the Content Browser

**Comment by 4tmn** [comment]
@rdeioris 
Useful function, thanks.

**Comment by taotang1984** [comment]
Thanks so much! That is what I wanted:)
