### ISSUE TITLE
PySideQt Test Widget

### ISSUE THREAD

**Issue by sinokgr** [20tab/UnrealEnginePython#27]
Hi Guys,
After a little help from 20tab, I successfully compiled the plugin and ran the first example with the Py Anchor and everything worked great. The next step for me, is to have a PySide QtWidget running in Unreal. I uncommented [this line](https://github.com/20tab/UnrealEnginePython/blob/master/Source/UnrealEnginePython/Private/UnrealEnginePythonPrivatePCH.h#L4), re-build and tried to run the following small script.

    import sys
    from PySide import QtGui, QtCore
    
    
    class ModalWidget(QtGui.QWidget):
        def __init__(self, parent=None):
            super(ModalWidget, self).__init__()
            self.resize(200, 200)
            self.setWindowModality(QtCore.Qt.ApplicationModal)
            # Label Widget
            self.test_lbl = QtGui.QLineEdit(self)
            self.show()
    
    
    class MainWidget(QtGui.QWidget):
        def __init__(self, parent=None):
            super(MainWidget, self).__init__()
            self.resize(400, 200)
            self.window = None
            # Button Widget
            self.my_btn = QtGui.QPushButton(self)
            self.my_btn.clicked.connect(self.open_second_window)
            self.my_btn.setText("Open Modal Window")
            self.show()
    
        # Def to open the Modal window
        def open_second_window(self):
            self.window = ModalWidget()

When I **import PySideTestWidget**, it loads the module fine. When I try to execute **PySideTestWidget.MainWidget()** Unreal instantly freezes. Any idea why and how to fix?

Thanks,
Nick

_***Note I'm relatively new to Python and completely new to Unreal._

**Comment by rdeioris** [comment]
If it freezes without crashing it is probably because of self.show() that takes control of the thread.

Does the qt windows works while unreal is freezed ?

**Comment by osstony** [comment]
If you are calling QApplication.exec_() Unreal will freeze. Doing so will start Qt's event loop which will take control and block. Instead a QApplication instance needs to be created and the event loop needs to be manually pumped by using a callback. Putting something like the following in your startup script should work:
    
    app = QtGui.QApplication()
    def _qt_event_loop():
        QtGui.QApplication.processEvents()
        QtGui.QApplicaiton.sendPostedEvents(None, 0)

    unreal.add_ticker(_qt_event_loop, 10)

I'm not sure yet which frequency is appropriate. That will need to be further tested.

**Comment by sinokgr** [comment]
@rdeioris It was freezing but no windows were opening
@osstony Thanks for that. Now, a black window flashes but doesn't stay open. Should I add somewhere the sys.exit(app.exec_())? I tried to add it in the end but it freezes on import.

Updated code:

    import sys
    import unreal_engine as unreal
    from PySide import QtGui, QtCore
    
    
    class ModalWidget(QtGui.QWidget):
        def __init__(self, parent=None):
            super(ModalWidget, self).__init__()
            self.resize(200, 200)
            self.setWindowModality(QtCore.Qt.ApplicationModal)
            # Label Widget
            self.test_lbl = QtGui.QLineEdit(self)
            self.show()
    
    
    class MainWidget(QtGui.QWidget):
        def __init__(self, parent=None):
            super(MainWidget, self).__init__()
            self.resize(400, 200)
            self.window = None
            # Button Widget
            self.my_btn = QtGui.QPushButton(self)
            self.my_btn.clicked.connect(self.open_second_window)
            self.my_btn.setText("Open Modal Window")
            self.show()
    
        # Def to open the Modal window
        def open_second_window(self):
            self.window = ModalWidget()
    
    app = QtGui.QApplication([])
    def _qt_event_loop():
        QtGui.QApplication.processEvents()
        QtGui.QApplication.sendPostedEvents(None, 0)
    
    unreal.add_ticker(_qt_event_loop, 10)
    # If you uncomment the next line, it freezes on import.
    # sys.exit(app.exec_())

**Comment by osstony** [comment]
Where are you instantiating your window? Make sure to keep a reference to it otherwise it will get garbage collected and close. You don't need the sys.exit(app.exec_()) call in your code. You'd use that if you are running a Qt app as a standalone python script.

**Comment by sinokgr** [comment]
Ok! That fixed it! Last question, is there any way to parent the QWidget to Unreal cause now it opens as a separate window?

**Comment by osstony** [comment]
It's definitely doable but first we need to either expose getting a handle to the Unreal window or using win32 python methods to do it. It's on my list of things to do next.

**Comment by rdeioris** [comment]
@osstony if you only need to get the HWND handle to accomplish it, the SWindow class has the GetNativeWindow() method that gives you a FGenericWIndow class on which you can call GetOSWindowHandle()

**Comment by osstony** [comment]
@rdeioris is that already being exposed to python? I was planning on exposing it if it isn't already.

**Comment by rdeioris** [comment]
@osstony nope i ha studied the slate api but currently i am focusing on other areas, so feel free to work on it :)

**Comment by sinokgr** [comment]
Hi guys, just wanted to let you know, that I've tried it with the actual tool, not just sample code, and it worked fine - expect from the known parent-issue! Thanks! 😄

**Comment by rdeioris** [comment]
Ok, closing it

**Comment by sinokgr** [comment]
Thanks @rdeioris. Do you want me to create a new issue for the parenting?

**Comment by rdeioris** [comment]
@sinokgr  yes, thanks
