### ISSUE TITLE
Obj Support?

### ISSUE THREAD

**Issue by Schizo** [20tab/UnrealEnginePython#271]
I didn't read it in the readme's, nor the search for `obj` was helpful. May I ask what the status is on importing `OBJ's` ?

**Comment by rdeioris** [comment]
The FBX pipeline supports OBJ's too. Eventually (if you want to go more low-level) you can use a pure python parser (obj are simple text files) and build stuff with the FRawMesh api.

**Comment by Schizo** [comment]
Oh that's very good to know! Many houdini user's who only have the indy licenses have to rely on the `obj` export, as `FBX` is only available in the full license!
