### ISSUE TITLE
C++: Creating UPythonComponent compilation error related to "RAWMESH_API"

### ISSUE THREAD

**Issue by BenAsaf** [20tab/UnrealEnginePython#273]
Hello, I am running:
UE4 (Version 4.18.2) Python 3.6.3 on Ubuntu 64bit and using CLion as my IDE.
Worth noting: I also have `CLionSourceAccess` - https://github.com/dotBunny/CLionSourceCodeAccess
Although I don't think it is what causing the issue.

I tried the includes like in the following closed issue as well: https://github.com/20tab/UnrealEnginePython/issues/51
However I am still missing something.

**Recreating the issue:**
1. Created a new blank C++ project named: `SimpleProj` without StarterContent
2. Compiled both plugins. (UnrealEnginePython, CLionSourceAccess)
3. Edited `SimpleProj.Buid.cs` and appended `UnrealEnginePython` as a Public Dependecy to `PublicDependencyModuleNames`
4. Created new C++ Pawn class named: `MyPawn` with `Pawn` as base class. (Didn't change any of the efault settings; None selected out of Public\Private and Runtime remains project name)
5. Went ahead to the constructor of `MyPawn` and added the following line:
    `UPythonComponent *pyComp = CreateDefaultSubobject<UPythonComponent>(TEXT("pyComp"));`
6. Added in `PyPawn.h` the following include:
    `#include "UnrealEnginePython/Private/UnrealEnginePythonPrivatePCH.h"`
    `#include "UnrealEnginePython/Public/PythonComponent.h`
7. Trying to compile... receiving:
[ERROR.txt](https://github.com/20tab/UnrealEnginePython/files/1567341/ERROR.txt)

I am attaching my `MyPawn` class as well:
[SimpleProj.zip](https://github.com/20tab/UnrealEnginePython/files/1567346/SimpleProj.zip)

**Things I've tried:**
1. Including only `#include "UnrealEnginePython/Public/PythonComponent.h` instead of both generates a compilation error that _pyobject_ is unknown.
2. Including _UnrealEnginePython/Public/PythonComponent.h_ in the header file and _UnrealEnginePython/Private/UnrealEnginePythonPrivatePCH.h_ in the cpp file.
3. Adding to `SimpleProj.Build.cs` private dependencies `UnrealEnginePython` as well.
4. Instead of using `#include "CoreMinimal.h"` I tried: `#include "Engine.h"` and both _Engine.h_ and _Core.h_ 
5. In the `CLionSourceAccess` configuration I've tried to include "Plugins" so it'll compile it as well.
![clionsourceaccess](https://user-images.githubusercontent.com/5612635/34099854-5cd9b7ba-e3e9-11e7-8657-d3b839df23a0.png)

**Obvious soultion but unwanted:**
Is to not create a _UPythonComponent_ in C++, but rather in Blueprint that inherits from it.  But still, this should be supported isn't it?

**Possble root of the problem?**
Maybe it has to do something with the way both plugins communicate. Is there a conditional compilation header that doesn't include "RAWMESH_API" in _UnrealEnginePython_ if it sees different Target Configuration/Target Projects than what it expects? (See img above) Tomorrow I'll be able to dig in the Source code and try to see if this is the case..

I've been working on this for 2-3 days. There were more attempts to try and solve this, can't remember it all, and I've tried any combination of them to try and find a solution, yet I am having the same issue.

**UPDATE:**
Manually defining `RAWMESH_API` by: `#define RAWMESH_API ` in `MyPawn.h` like it is shown in an external Definitions file: `SimpleProj/Intermediate/ProjectFiles/Definitions.cmake` causes a new compilation error:
[ERROR2.txt](https://github.com/20tab/UnrealEnginePython/files/1567552/ERROR2.txt)
Note that this definition is included in the generated `CMakeLists.txt`. Perhaps it is really an issue of a Target Configuration/Target Projects?

Thanks,
Ben.

**Comment by rdeioris** [comment]
Hi, can you try by completely removing the FRawMesh api from the sources ?
