### ISSUE TITLE
Creating a foliage mesh ?

### ISSUE THREAD

**Issue by Papoun** [20tab/UnrealEnginePython#278]
Hey there :)

I've been checking the examples provided by the plugin but wasn't able to find any mention of 3d foliage, and how to create them from a given static mesh.

Are they supported in the plugin yet ?

Thanks !

**Comment by Schizo** [comment]
I would be actually interested as well, i just had the feeling that Unreal didn't ever expose any functionalities. (I might be wrong). Anyhow, it would be very useful if we generate foliage in a 3rd Party Tool and import it.

**Comment by rdeioris** [comment]
Hi, i have implemented a preliminary api: https://github.com/20tab/UnrealEnginePython/blob/master/docs/Foliage_API.md

**Comment by Schizo** [comment]
Very nice! Thanks a lot! Do you know, when the next binaries will include those changes?

**Comment by Papoun** [comment]
Thank you so much for the quick reply ! Really can't wait to test this one !

**Comment by rdeioris** [comment]
Binary releases are available: https://github.com/20tab/UnrealEnginePython/releases/tag/20171229
