### ISSUE TITLE
Sequencer API

### ISSUE THREAD

**Issue by rdeioris** [20tab/UnrealEnginePython#28]
Extend the editor api to allow scripting of the sequencer

**Comment by RonFischer** [comment]
Would you like a snippet which traverses the structure?

On Sep 26, 2016 3:09 PM, "rdeioris" <notifications@github.com> wrote:

Extend the editor api to allow scripting of the sequencer

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/20tab/UnrealEnginePython/issues/28>, or mute the thread

**Comment by rdeioris** [comment]
Yes, absolutely

**Comment by RonFischer** [comment]
Just a sketch. Please pardon the unusual formatting. It gets down to the
animation underlying a section.


    UMovieScene* scene = levelSeq->GetMovieScene();

    if (!scene) {

        UE_LOG(LogTemp, Error, TEXT("Level sequence %s had no movie scene"),
name)

        return "failed";

    }



    UE_LOG(LogTemp, Display, TEXT("Parsing sequence %s"), name);



    const TArray< FMovieSceneBinding >allBindings = scene->GetBindings();

    for (int bindingIndex=0; bindingIndex < allBindings.Num();
++bindingIndex) {

        FMovieSceneBinding binding = allBindings[bindingIndex];

        FString bindingName = binding.GetName();

        //FGuid bindingGuid = binding.GetObjectGuid();

        TArray< UMovieSceneTrack * > tracks = binding.GetTracks();

        int numTracks = tracks.Num();

        UE_LOG(LogTemp, Display, TEXT("Binding %s has %d tracks"),
*bindingName,
numTracks);



        for (int trackIndex = 0; trackIndex < numTracks; ++trackIndex) {

            UMovieSceneTrack* track = tracks[trackIndex];

            if (!track) {

                UE_LOG(LogTemp, Error, TEXT("\tNull track %s (ignored)"), *
(track->GetName()));

                continue;

            }

            UE_LOG(LogTemp, Display, TEXT("\tTrack %s"), *
(track->GetName()));

            const TArray<UMovieSceneSection*> sections =
track->GetAllSections();

            int numSections = sections.Num();

            for (int j = 0; j < numSections; ++j) {

                UMovieSceneSection* section = sections[j];

                if (!section) {

                    UE_LOG(LogTemp, Error, TEXT("\t\tNull section (ignored)"
));

                    continue;

                }

float trackStart = section->GetStartTime();

float trackEnd = section->GetEndTime();

UClass* sectionClass = section->GetClass();

FString sectionClassName = sectionClass->GetName();

UE_LOG(LogTemp, Display, TEXT("\t\t%f - %f %s"), trackStart, trackEnd, *
sectionClassName);


UMovieSceneSkeletalAnimationSection* skelAnimSection =

Cast<UMovieSceneSkeletalAnimationSection>(section);

if (!skelAnimSection) {

                    UE_LOG(LogTemp, Error, TEXT("\t\t\tNon skeletal
animation section (ignored)"));

                    continue;

                }

float clipStart = skelAnimSection->GetStartOffset();

                float clipEnd = skelAnimSection->GetEndOffset();

                UAnimSequenceBase* animSeq =
skelAnimSection->GetAnimSequence();

                const TArray<class UAnimMetaData*>clipMeta =
animSeq->GetMetaData();

                UE_LOG(LogTemp, Display, TEXT("\t\t\t%f - %f"),

                       clipStart, clipEnd

                       );

                for (int clipMetaIndex = 0; clipMetaIndex < clipMeta.Num();
++clipMetaIndex) {

                    UAnimMetaData* animMeta = clipMeta[clipMetaIndex];

                    FString animName = animMeta->GetName();

UE_LOG(LogTemp, Display, TEXT("\t\t\t\tmeta %s"), *name);

                }

            }

        }

**Comment by RonFischer** [comment]
Also, this was in 4.13. The driving animation API changed a bit between the
two I think.

**Comment by rdeioris** [comment]
Ok, thanks to your pdf and the pasted code i have a clear view of the sequencer.

I will start adding access to the bindings. Next step will be mapping guid to something useful.

Do you know if there is any specific behaviour for camera track ?

**Comment by RonFischer** [comment]
I need to look at camera tracks. Have not tried to walk any examples yet.

I am deep into C++ code for parsing skeletal mesh tracks down to their
animation curves.

The spawn and possess object guids are tricky. E.g. possess bindings are
resolved by either the level sequence or a movie scene instance. Spawn is
just a template.

I am also still trying to fully understand the bone to skeleton index
through track index map to curve API chain.

**Comment by rdeioris** [comment]
Here i am traccking api progresses:

https://github.com/20tab/UnrealEnginePython/blob/master/sequencer_API.md

feel free to improve it with pull requests

**Comment by rdeioris** [comment]
@RonFischer Just grasped camera track system. Tomorrow i will add more functions to the api

**Comment by RonFischer** [comment]
@rdeioris thank you! I look forward to review, comment and build the new
code.

**Comment by rdeioris** [comment]
The sequencer api suppot has been improved heavily thanks to Matthew Whelan (http://www.mattwhelan.com/) sponsorship:

https://github.com/20tab/UnrealEnginePython/blob/master/examples/sequencer_scripting.py

This is a first round of patches, more to come soon
