### ISSUE TITLE
set class of ObjectProperty

### ISSUE THREAD

**Issue by MatzeOGH** [20tab/UnrealEnginePython#283]
Does anybody know how to set the class of an UObjectProperty in python.
I'm trying to create a texture2d field in an object very much like in the custom settings example

**Comment by rdeioris** [comment]
If i understand correctly you mean something like this:

```python
import unreal_engine as ue
from unreal_engine.classes import Character, Texture2D, FloatProperty


class TestEnemy(Character):

    DumbTexture = Texture2D
    Energy = FloatProperty

    def FooBar(self):
        print('FooBar')
```

**Comment by MatzeOGH** [comment]
Thanks. I was definitely thinking too complicated
