### ISSUE TITLE
Coding unreal games completely?

### ISSUE THREAD

**Issue by mingguichen** [20tab/UnrealEnginePython#286]
Hi, Thanks so much for the wonderful effort! I am wondering if it's possible to code the game completely now using python, without using the unreal GUI. This is possible with the official C++ API. I am very curious about the status of the python bindings now.

**Comment by rdeioris** [comment]
Hi, currently the whole Blueprint api (based on the UE reflection) is working. If you mean to not even open the unreal editor and simply code in python and then run the engine, it is theoretically already possible as at bootup the engine tries to load ue_site.py

**Comment by mingguichen** [comment]
Sounds great! I can imagine there are lots of work! Do you plan to expose
the entire C++ API some time in the near future? Thanks!

**Comment by rdeioris** [comment]
We are adding new classes and wrappers based on the users request, there are already hundreds of "pythonized" wrapper for the C++ api (like the staticmesh api). Just ask for them eventually proposing a "pythonic" api

**Comment by mingguichen** [comment]
Cool. Thanks for all the hard work!
