### ISSUE TITLE
Option to add Editor Buttons/Menus

### ISSUE THREAD

**Issue by sinokgr** [20tab/UnrealEnginePython#29]
Hi again,

I know that this is already in the list, I just wanted to create this "issue" in order to track the process.
The idea is that I would love if I could have the ability to create menus/buttons in the editor instead of having to execute python commands to start a tool.

Thanks,
Nick

**Comment by rdeioris** [comment]
add_menu_extension() has been added:

```py
import unreal_engine as ue

def menu_callback_for_script():
    ue.exec('yourscript.py')

ue.add_menu_extension('Run My Funny Script', menu_callback_for_script)
```

add_menu_extension is useful only on ue_site.py.  (you can call it multiple time to register multiple menu entries)

**Comment by sinokgr** [comment]
I've created a new project, ran the installion process of the new repository and the project built successfully. When I'm tried to open the project though, it crashed after the splash screen. Here is the report:

>Access violation - code c0000005 (first/second chance not available)
>
>UE4Editor_UnrealEnginePython!FPythonSlateCommands::RegisterCommands() [c:\users\sinokgr\documents\unreal projects\python_4_12_5\plugins\unrealenginepython\source\unrealenginepython\private\uepyslate.cpp:15]
>UE4Editor_UnrealEnginePython!TCommands<FPythonSlateCommands>::Register() [c:\program files (x86)\epic games\4.12\engine\source\runtime\slate\public\framework\commands\commands.h:53]
>UE4Editor_UnrealEnginePython!FUnrealEnginePythonModule::StartupModule() [c:\users\sinokgr\documents\unreal projects\python_4_12_5\plugins\unrealenginepython\source\unrealenginepython\private\unrealenginepython.cpp:86]
>UE4Editor_Core
>UE4Editor_Core
>UE4Editor_UnrealEnginePython!FModuleManager::LoadModuleChecked<FUnrealEnginePythonModule>() [c:\program files (x86)\epic games\4.12\engine\source\runtime\core\public\modules\modulemanager.h:281]
>UE4Editor_UnrealEnginePython!APyActor::APyActor() [c:\users\sinokgr\documents\unreal projects\python_4_12_5\plugins\unrealenginepython\source\unrealenginepython\public\pyactor.cpp:13]
>UE4Editor_CoreUObject
>UE4Editor_CoreUObject
>UE4Editor_CoreUObject
>UE4Editor_CoreUObject
>UE4Editor_Core
>UE4Editor_Core
>UE4Editor_Projects
>UE4Editor_Projects
>UE4Editor
>UE4Editor
>UE4Editor
>UE4Editor
>UE4Editor
>UE4Editor
>kernel32
>ntdll

**Comment by rdeioris** [comment]
sorry, missed a check, i will push the fix in few minutes

**Comment by rdeioris** [comment]
should be fixed now, pull and rebuild :)

**Comment by sinokgr** [comment]
Thanks @rdeioris, it opens fine now. Sorry if this is stupid question, but what do you mean by "add_menu_extension is useful only on ue_site.py". I was searching a file named ue_site.py to add my menus, couldn't find any so I then tried to create a new ue_site.py and add it to Scripts folders and import it. That didn't work either so I assume I'm doing something wrong.

**Comment by rdeioris** [comment]
ue_site.py in Scripts is automatically imported on startup. You have to call ue.add_menu_extension() there

**Comment by sinokgr** [comment]
In the folder Scripts, I created a file named "ue_site.py", copy-pasted your code in there and started the project but I can't find the menu 'Run My Funny Script' anywhere. Where is it supposed to appear? Top menu? RC menu?

**Comment by rdeioris** [comment]
Window -> at the end they are appended. Check python logs for eventual errors

**Comment by sinokgr** [comment]
You're correct, I found an error and it was in this line

    ue.exec('yourscript.py')

I changed it to

    ue.exec_('yourscript.py')

and now the project is crashing before even start. In order to simplify stuff, I changed it to

    ue.log('Begin Play on Hero class')

but it still crashes.
![image](https://cloud.githubusercontent.com/assets/22396951/18951777/d1c10f2e-863e-11e6-8bf8-3ef3ba8a0c3c.png)
![image](https://cloud.githubusercontent.com/assets/22396951/18951787/db6f2830-863e-11e6-89c8-87ab6413cc73.png)
I went to debug mode, and it opened the file PyCharacter.cpp in line 13
![image](https://cloud.githubusercontent.com/assets/22396951/18951909/6bc8d3a4-863f-11e6-9922-2d5874a8b193.png)

Last thing. Except from just appending sub-menus to the Window menu, will there be an option to create new menus in top bar with submenus??

**Comment by rdeioris** [comment]
Can you paste/upload the whol ue_sitepy ? Is it python2 or 3 ? Is it possible you have built the plugin with threading support ?

**Comment by sinokgr** [comment]
that's the current script

```python
import unreal_engine as ue


def menu_callback_for_script():
    ue.log('Log test')

ue.add_menu_extension('Run My Funny Script', menu_callback_for_script)
```
I use python 2.7 and I've build the plugin with threading support because I need to use PySide and in your email you told me that this is how you add support (at least one of the two ways to be accurate)

**Comment by rdeioris** [comment]
For now try removing threading support. If i remember correctly you are using the custom loop for qt, and this does not  require threading

**Comment by sinokgr** [comment]
ok, I'll try that and I'll let you know.
Thanks!

**Comment by sinokgr** [comment]
Yei! It works! Many thanks @rdeioris! :D
You haven't answered me about the Menus-Submenus though. Can you add this option like [Unity](https://unity3d.com/learn/tutorials/topics/interface-essentials/unity-editor-extensions-menu-items) for example?

**Comment by rdeioris** [comment]
Yes it is almost ready, just a couple of tests

**Comment by rdeioris** [comment]
@sinokgr You can now pass a third argument to add_menu_extension, with the name of the new menu bar:

```py
ue.add_menu_extension('Foobar', callable, 'NewMenu')
```

**Comment by sinokgr** [comment]
Awesome! Worked like charm! Many thanks for that @rdeioris. :)
Now the only thing remaining from my point of view is [issue30](https://github.com/20tab/UnrealEnginePython/issues/29).

**Comment by sinokgr** [comment]
Hi there,
 I tried to create a menu today, with no main menu and nothing happens.
Console reports **Registered python extender command "Test"**, but nothing appears.
```python
ue.add_menu_extension('Test', test)
```
if I change that to the following it works as expected
```python
ue.add_menu_extension('Test', test, 'Top')
```

Any ideas why?
Thanks

**Comment by rdeioris** [comment]
Hi, if i remember correctly main menus can only be created in ue_site.py

**Comment by sinokgr** [comment]
yep, this is where this code exists. The second snippet works fine. The only issue is that currently I can only create submenus, so I can have something like "menu bar item>tool". Initially you could do just "tool". Third variable is optional but without it, it doesn't add the menu.

**Comment by thomas-dumonet** [comment]
Hi,

The third argument doesn't seem to be working anymore. If it is used, no menu item is created at all.

**Comment by LarsGroh** [comment]
This one does not work on my side:
ue.add_menu_extension('Test', test, 'Top')

I placed it within ue_site.py No other main menu is being created.

This one worked:
ue.add_menu_extension('Test', test)

An item is being created under "Window"
Bu I noticed that if erase the command from ue_site the menu item is still being created.
This is something I would not expect for a clean startup process.

**Comment by rdeioris** [comment]
Hi, the extender api has been changed some month ago:

https://github.com/20tab/UnrealEnginePython/blob/master/examples/extenders_example.py

**Comment by yuchen-sketch** [comment]
Hi, @rdeioris 
I am also trying to add buttons to unreal.

Any way that the buttons can be loaded automatically when create a new project rather than closing the project and pasting the scripts folder and reopening it?

**Comment by rdeioris** [comment]
@yuchen-sketch please open new issues for new requests :) btw you can put the Scripts/ directory in the Plugin Content directory (instead of the project dir). it will be added to the pythonpath automatically. So when the user enables the python plugin the ue_site.py script can be execute automatically

**Comment by yuchen-sketch** [comment]
@rdeioris 
Got it. Thanks!
