### ISSUE TITLE
Error when installing Tracery package

### ISSUE THREAD

**Issue by Henelik** [20tab/UnrealEnginePython#290]
Hi, I'm having an issue when installing the Tracery package in the Python 3.6.2 version of this plugin.

I'm installing packages using the method outlined at https://github.com/20tab/UnrealEnginePython/blob/master/tutorials/PlottingGraphsWithMatplotlibAndUnrealEnginePython.md

I've already successfully installed Numba, Numpy, and Scipy using the method from the article, but whenever I try to install Tracery, I get the error: "Command "python setup.py egg_info" failed with error code 1 in C:\Users\kelyn\AppData\Local\Temp\pip-build-5ourb6xw\tracery\".

I've also tried manually installing Tracery in the embedded Python with no success.

I already successfully installed Tracery in a clean Python 3.6.2 main install.  I don't understand why only the Tracery package is having a problem, and only with the python version embedded with this plugin.  Any ideas for a workaround?  Is this an issue with the plugin?  Any help would be greatly appreciated.

**Comment by rdeioris** [comment]
Hi, can you report the whole traceback of the tracery installation ?
