### ISSUE TITLE
Getting Unreal project path

### ISSUE THREAD

**Issue by thomas-dumonet** [20tab/UnrealEnginePython#291]
Hi,

Is there a way to get the absolute path to the current Unreal Engine project ?
I tried `unreal_engine.convert_relative_path_to_full('')` and `os.getcwd()` but they both point to the Unreal Engine executable folder.

**Comment by rdeioris** [comment]
Hi you can use unreal_engine.get_content_dir()

**Comment by thomas-dumonet** [comment]
Thanks you very much, I tried searching the API but i didn't have the right keywords I guess.
