### ISSUE TITLE
 error: binding dereferenced null pointer to reference has undefined behavior

### ISSUE THREAD

**Issue by ankitmishra262** [20tab/UnrealEnginePython#293]
Hi,

On linux, using Unreal Engine 4.18, I am getting the following error after the pop up informs to load the plug-ins. Am I missing something? Please help!

```
In file included from ThirdParty/FBX/2018.1.1/include/fbxsdk/core/fbxobject.h:21:

ThirdParty/FBX/2018.1.1/include/fbxsdk/core/fbxproperty.h:1188:70: error: binding dereferenced null pointer to reference has undefined behavior [-Werror,-Wnull-dereference]

                return StaticInit(pObject, pName, FbxGetDataTypeFromEnum(FbxTypeOf(*((FbxReference*)0))), pValue, pForceSet, pFlags);

```

**Comment by rdeioris** [comment]
Hi, unfortunately it is a third party lib error (fbxsdk). Which clang version are you using ? Is it a supported-by-epic one ?

**Comment by ankitmishra262** [comment]
I checked the clang version, it was 3.9. I tried update-alternative-ing it to 3.8, the error remains the same. (read it [here](http://kuantinglai.blogspot.co.uk/2017/09/setup-unreal-as-deep-reinforcement.html)). I am going to try to build again and check. Anything else I should check?

**Comment by ankitmishra262** [comment]
I could remove the error. I realized I was using the wrong clang version, so I `update-alternative`d it to clang-3.5, rebuilt UnrealEngine Editor and the UnrealEnginePython plugin with the project using python3.5 and everything works fine now.

Thanks a lot for the quick support! Appreciate your work!
