### ISSUE TITLE
Multiline mode : Start following lines with "..." rather than ">>>"

### ISSUE THREAD

**Issue by HughMacdonald** [20tab/UnrealEnginePython#294]
It's a small niggle, but when in multiline mode, like the internals of a `for` block, standard Python would look like this:

    >>> for i in range(10):
    ...     print(i)

However, the console looks like this:

    >>> for i in range(10):
    >>>     print(i)

I think that keeping this the same helps with readability.

**Comment by rdeioris** [comment]
done ;)
