### ISSUE TITLE
Could not import setuptools which is required to install from a source distribution.

### ISSUE THREAD

**Issue by mfruhner** [20tab/UnrealEnginePython#295]
Hi,
I am trying to install a python package via pip by following the instructions about matplotlib (which installed nicely):
`./python.exe -m pip install paho-mqtt`

I get the following error:
`Could not import setuptools which is required to install from a source distribution.
Please install setuptools.`

running `./python.exe -m pip install setuptools` does not help.
Do you have any idea why? 
Thank you in advance!

Maik

**Comment by rdeioris** [comment]
Hi @mfruhner check this guide for a correct setup: https://packaging.python.org/tutorials/installing-packages/#ensure-you-can-run-pip-from-the-command-line

**Comment by mfruhner** [comment]
hi,
i followed the instructions, but it did no difference.
I could successfully install it in my system python installation, but in the embedded python the setup would still fail.
I tried to use the plugin version using the system python, but then the project fails to load. Python is available on the path though..

Greetings.

**Comment by mfruhner** [comment]
I think I managed to make it work. I installed it in my system python and copied it to the embedded env. Not a solution, but a workaround. If you want to investigate further, I will be glad to help.
Ty!

**Comment by rdeioris** [comment]
@mfruhner maybe it is useful to add a doc file in the /docs directory with the steps you followed ?
