### ISSUE TITLE
AsyncIO Client/Server Example

### ISSUE THREAD

**Issue by Schizo** [20tab/UnrealEnginePython#296]
Is there an example **client** code within the `asyncio` document in the section  `A simple tcp server spawning Character's in the editor`? I only found the server code.

**Comment by rdeioris** [comment]
Hi, you mean a tcp client ?

**Comment by Schizo** [comment]
Yes, exactly. I tried using the client described in the asyncio docs: http://asyncio.readthedocs.io/en/latest/tcp_echo.html but it wouldn't connect, however the server/client on asyncio doc worked.

**Comment by Schizo** [comment]
Just updated to Unreal 4.18.3, same  behavior.
