### ISSUE TITLE
transactions with attribute changes position/rotation

### ISSUE THREAD

**Issue by Schizo** [20tab/UnrealEnginePython#298]
I'm streaming the position/rotation of Elements from Maya to Unreal. I've realized that we can use `transactions` to put actions to the undo  stack, which works fine for creating elements as in the [example](https://github.com/20tab/UnrealEnginePython/blob/master/docs/Transactions_API.md): 

Does this currently support only object creation but not modification? In the following example I'm modifying the rotation of a selected element and trying to undo. It is:

- Setting the rotation
- Undoing the operation (The popup appears with the transaction name)

**But  the rotation isn't actually set back.** 

```
import unreal_engine as ue

# get the editor world
world = ue.get_editor_world()

#Selected Element
new_actor =  unreal_engine.editor_get_selected_actors()[0]

#new transaction
ue.begin_transaction("rotate selected object")
rotation = new_actor.get_actor_rotation()
rotation += 45
new_actor.set_actor_rotation(rotation)
ue.end_transaction()

#undo
ue.editor_undo()


```

**Comment by rdeioris** [comment]
Hi, add modify() before setting properties:


```python
#new transaction
ue.begin_transaction("rotate selected object")
rotation = new_actor.get_actor_rotation()
rotation += 45
new_actor.modify()
new_actor.set_actor_rotation(rotation)
ue.end_transaction()
```

Feel free to make a pull request for the docs :)
