### ISSUE TITLE
Set Unreal as QtWidget.Parent()

### ISSUE THREAD

**Issue by sinokgr** [20tab/UnrealEnginePython#30]
Hi guys,

Can you please expose UnrealEditors's Window handle so we can set it as parent to the QtWidgets?
Similar to 3dsMax's MaxPlus.GetQMaxWindow().

Thanks,
Nick

**Comment by sinokgr** [comment]
Any news on this one? :thinking:

**Comment by rdeioris** [comment]
What kind of argument type Qt expects for the window handle ?

**Comment by osstony** [comment]
We will want the integer for the Unreal HWND. 

After that, in python, we will need to create an invisible Qt proxy parent widget which is parented to the Unreal window using win32gui methods. The invisible Qt proxy parent widget will then act as the main window parent for future widgets.

**Comment by sinokgr** [comment]
have a look at this example, it might be helpful
https://github.com/alfalfasprossen/qtinwin/blob/master/maxparenting.py

**Comment by rdeioris** [comment]
@sinokgr i have added this:

```py
import unreal_engine as ue

root_window = ue.get_editor_window()
ue.log(root_window.get_window_handle())
```

i think it should be enough for you

**Comment by sinokgr** [comment]
worked fine! Thanks! 😀

**Comment by sinokgr** [comment]
Hi @rdeioris, I just downloaded and re-compiled the latest version with levels support and it looks like this stopped working. Have you accidentally deleted [this](https://github.com/20tab/UnrealEnginePython/commit/160cc5a1e93c0aed899e32d78e96dde4441f22a2#diff-633c64bb8571d9b90a038d15e2b48d0d) line of code or is intentional?

**Comment by rdeioris** [comment]
sorry, fixed

**Comment by Papoun** [comment]
Bumping this one ^^' Not sure if i need to create a new thead ? sorry if that's the case !
How are you setting the UE window as a parent of a QtWidget, @sinokgr ?

I haven't been able to get the unreal window from it's hwnd (using `
 ue.get_editor_window().get_handle()` for the hwnd) with Ctypes (_PyCObject_AsVoidPtr_ is deprecated in 3.6 when trying a similar approach to the 3DS Max parenting one) or the win32gui one.

Thanks !

**Comment by Papoun** [comment]
An update on this. You can get the handle of the ue4 editor window with ctypes like so :
`handle = ctypes.windll.user32.GetForegroundWindow()`

And use the windll's SetParent to set the Qt widget (self) as a child of the unreal editor window : 
`ctypes.windll.user32.SetParent(self.winId(), handle)`

A few issues arise from this though. You cant for instance move the Qt widget outside of ue4 like a regular unreal window/tab. This can be pretty annoying if the user tries to move the Qt window on another screen or outside of the unreal window geometry.

I ended up resorting to a simpler method where im using a thread to monitor the current foreground application, but would really like to see if the problems above still persist with different methods !

**Comment by rdeioris** [comment]
@Papoun reopening the issue, as it looks like a new revamp of QT for python is coming and i will like to support it in the best possible way

**Comment by rdeioris** [comment]
Closing it as now we have the set_as_owner() api function:

https://github.com/20tab/UnrealEnginePython/blob/master/README.md#integration-with-qt4qt5pyside2
