### ISSUE TITLE
Fbx import with FbxImportUI doesn't look like it can work

### ISSUE THREAD

**Issue by plipson** [20tab/UnrealEnginePython#301]
I was following the example in the PythonConsole.md about importing using already-loaded skeletons but the underlying code looks like it can't work as intended.
   The key lines in the python script:

`fbx_import_ui.set_property('Skeleton', skeleton)`
`ue.set_fbx_import_option(fbx_import_ui)       ## Sets the skeleton into the FFbxImporter instance`
`ue.import_asset(filename, asset_name, factory)  ## will overwrite the options in the FFbxImporter instance`

The 'import_asset' will cause a new PyFbxFactory to be instantiated; it will have its own FbxImportUI object freshly created and it will overwrite the data set in the previous line.  Am I missing something, and has anyone made this work??

this is the implementation:
`UPyFbxFactory::FactoryCreateBinary(...)`
`{`
 `     ....`
 `     FbxMeshUtils::SetImportOption(ImportUI);  // This is the line that wipes it out.`
`}`

**Comment by taotang1984** [comment]
Using the following code should work:
```
            from unreal_engine.classes import PyFbxFactory, Skeleton
            from unreal_engine.enums import EFBXImportType

            fbx_factory = PyFbxFactory()
            fbx_factory.ImportUI.MeshTypeToImport = EFBXImportType.FBXIT_Animation
            fbx_factory.ImportUI.Skeleton = skeletonUobject

            uobject_import = fbx_factory.factory_import_object(fbx_path, import_path)
```

**Comment by taotang1984** [comment]
@rdeioris I just made a pull request. 
It is my first time to do it, hope I didn't do anything too wrong:)
