### ISSUE TITLE
Creating materials from macro code ?

### ISSUE THREAD

**Issue by Papoun** [20tab/UnrealEnginePython#302]
Hi,

There's this cool feature in UE4 that allows you do to simply copy and paste a complex material's setup code ([like this one](https://pastebin.com/vdxBbUUs)) into a material and have everything up and running.

Is there a way for me to have import a text file and create the material, all from the python editor ?

A bit more info on the subject if needed : [UE4 Pasting txt into material](https://answers.unrealengine.com/questions/215042/how-do-i-use-this-for-a-material.html)

Thanks !

**Comment by rdeioris** [comment]
I think the best approach is using the new FSlateApplication class. It allows you to 'inject' input. So you will basically end with automatically opening the material editor, filling the clipboard with a custom string and sending 'ctrl-v'. All of the pieces are in place, i need only to complete the 'ctrl' key management. I will ping you back as soon as it is ready for a test

**Comment by Papoun** [comment]
Bumping this one to see if there's any update ^^'

**Comment by unbit** [comment]
Working on it right now :)

**Comment by Papoun** [comment]
Hey there ! I noticed that you've added a few features related to this functionality were added in the source code, does this mean this feature has already been implemented, or is it still work in progress/too early to test on my end ?

Sorry for the double-bump, we've been heavily using your Python plugin at Quixel/Megascans and this feature is the holly grail we're all waiting for ^^'

Have a nice weekend !

**Comment by rdeioris** [comment]
Hi, i only need to write example docs, btw, are you sure the approach described here: https://github.com/20tab/UnrealEnginePython/blob/master/tutorials/YourFirstAutomatedPipeline.md#creating-the-materials is not a better way for your use case ?

**Comment by Papoun** [comment]
I've actually used that approach at first, but then we switched to more complex materials with dozens of nodes and i thought it would be a lot more efficient in the long-run if we used a faster method, and maybe even allow the user to set their own custom materials with this technique :) 

Great to hear that it's already been implemented ! <3

**Comment by Papoun** [comment]
Hi, thanks a lot for the sample code !

Tried it with the latest binaries (4.16, embedded) and it gives me the following error :

cannot import name 'MaterialEditingLibrary'
Traceback (most recent call last):
  File "<string>", line 4, in <module>
ImportError: cannot import name 'MaterialEditingLibrary'

Tried with a custom build that i compiled from the source yesterday also, same error.

**Comment by rdeioris** [comment]
Hi, i think you can avoid importing MaterialEditingLibrary as i do not use it in the script (was only in a previous version)

**Comment by Papoun** [comment]
Ah yes it's working fine now ! Noticed that it creates all the different materials that are in the text file but doesn't connect them to the main material's node, is that the expected behavior ?

![mat_](https://user-images.githubusercontent.com/31083009/36775808-cf6a2316-1c63-11e8-82c4-c85cecbf81f5.JPG)

Either way this makes everything so much easier <3

**Comment by rdeioris** [comment]
Yep it is the expected behaviour, as there is no way for the system to know which expression to connect to which pin (well, you could use the 'Desc' field to automate things... IE. you could write to it a special string to instruct the script).
Effectively at the end of the script i print the '.Expressions' field to get the list of the expressions (from which you can choose what to attach)

**Comment by Papoun** [comment]
Perfect ! yeah it shouldn't be hard to connect them with the classic method :) 

Thanks again for all the efforts !

**Comment by rdeioris** [comment]
You are welcome, maybe you could write a blog post on how you are using the plugin ;)

**Comment by Papoun** [comment]
Hi,

Out of curiosity, is there any StaticSwitch input method for linking a StaticSwitchParameter node to our main material ?

```python
m_.BaseColor = StaticSwitchInput(Expression=mynode)
```
Given a material m_ and a StaticSwitchParameter node, how would you go about connecting these ?

I ended up just using a scalar and a lerp, but would be curious to know if such this is already possible to do.

Thanks !

PS : a blog post/breakdown is definitely in the todo list ! :)

**Comment by rdeioris** [comment]
Hi, something like this ?

https://github.com/20tab/UnrealEnginePython/blob/master/examples/MaterialExpressionStaticSwitch.md

**Comment by Papoun** [comment]
That's even more than what i was looking for, thank you so much !!!
