### ISSUE TITLE
List / Delete / Move / Rename assets in Content Browser

### ISSUE THREAD

**Issue by LarsGroh** [20tab/UnrealEnginePython#31]
Hey guys, 

how could I delete, move or rename an exisiting asset in the content browser?
Also, is there a way to check the existence of a folder (apart from checking on file system) and then list all assets within that folder?

I tried to figure this out by digging around in the existing funcionality but had no luck.

**Comment by rdeioris** [comment]
A part from this https://github.com/20tab/UnrealEnginePython/blob/master/PythonConsole.md#assets-listing and the set_name() method you can call on objects,  the delete/move of assets is related to the filesystem. There are facilities exposed by the unreal api that should be exposed, but in the mean time using native python filesystem libraries is the best bet

**Comment by rdeioris** [comment]
We have now a pretty complete assets api: https://github.com/20tab/UnrealEnginePython/blob/master/docs/ManagingAssets.md
