### ISSUE TITLE
When trying to compile C++ code I get error

### ISSUE THREAD

**Issue by RepublicofTexas** [20tab/UnrealEnginePython#313]
`
CompilerResultsLog: ERROR: Could not find definition for module 'UnrealEnginePython' (referenced via default plugins -> UnrealEnginePython.uplugin)` Any fix?

**Comment by rdeioris** [comment]
It looks like you are trying to build from a binary distribution of the plugin. You need its sources

**Comment by RepublicofTexas** [comment]
Oh I thought hitting compile would've compiled my C++ component for my blueprint, not the plugin, sorry.

**Comment by RepublicofTexas** [comment]
`Running C:/Epic Games/UE_4.18/Engine/Binaries/DotNET/UnrealBuildTool.exe  -projectfiles -project="C:/Users/myuser/Documents/Unreal Projects/MyProject8/MyProject8.uproject" -game -rocket -progress
Discovering modules, targets and source code for project...
ERROR: Could not find definition for module 'UnrealEnginePython' (referenced via default plugins -> UnrealEnginePython.uplugin)` This happens while trying to refresh Visual Studio project too

**Comment by rdeioris** [comment]
That error means you are trying to package the project but you do not have copied the UnrealEnginePython sources into the the Plugins directory. If you do not want to use the Python plugin for the runtime, just edit its UnrealEnginePython.uplugin file and change the type of the module 'UnrealEnginePython' from 'Runtime' to 'Editor'

**Comment by RepublicofTexas** [comment]
Oh I was just downloading the release, sor

**Comment by RepublicofTexas** [comment]
`
ERROR: Unable to instantiate module 'UnrealEnginePython': System.Exception: Unable to find Python installation`
I get this now?

**Comment by rdeioris** [comment]
read here about sources installation https://github.com/20tab/UnrealEnginePython/blob/master/README.md#installation-from-sources-on-windows-64-bit

**Comment by RepublicofTexas** [comment]
It wasn't able to find python, sent python to C:\ and renamed to Python26 and it works now. Adding some more paths to line 22 of `UnrealEnginePython.Build.cs` would fix it (e.g C:\Users\userhere\AppData\Local\Programs\Python\Python36 ) to it
