### ISSUE TITLE
Can't import PyFactory subclasses from ue_site.py

### ISSUE THREAD

**Issue by rokel** [20tab/UnrealEnginePython#315]
```
    from unreal_engine.classes import PyFactory, Texture, Object, Class
LogPython: Error: ImportError: cannot import name 'PyFactory'
```

It would be good if this could be done on editor startup.

**Comment by rdeioris** [comment]
Just change "LoadingPhase": "PostDefault" of PythonConsole in UnrealEnginePython.plugin to "Default".

"PostDefault" will load it after ue_site.py has been called

**Comment by rokel** [comment]
Thanks, but I still get the same error. I've tried a few other loading phases but they don't seem to help.

**Comment by Papoun** [comment]
IIRC setting the PythonConsole state to "PreDefault" should load it on editor startup.
Also keep in mind that if the plugin is installed elsewhere (maybe you put it in the engine instead of the project, and vice-versa) you might want to change the loading phase in there also.

**Comment by rokel** [comment]
Thanks, setting the PythonConsole state to "PreDefault" worked.
