### ISSUE TITLE
Blueprint to call Python function?

### ISSUE THREAD

**Issue by sinokgr** [20tab/UnrealEnginePython#324]
Hi there,

A colleague is working on a blueprint and he want to access some things he can, but your python plugin does (btw, that's all for editor scripting not runtime).
I can't figure out if it's possible, or what's the best way around, to have a blueprint, call a python action. I know that there are the PyActor, PythonComponent etc. Any ideas?

Target is to:
Click BP button -> BP do a few things -> have something like a Python BP action with X inputs and a return value for outputs. -> continue BP execution. Even without inputs/outputs, it would do for now.

Hope that makes sense

**Comment by rdeioris** [comment]
Hi, you always have access to the PythonBlueprintFunctionLibrary that exposes the 'execute python script' and 'execute python string' functions

**Comment by sinokgr** [comment]
I was totally looking in the wrong place. Thanks, that worked great. 👍
