### ISSUE TITLE
Compilation error PythonHouseKeeper.h

### ISSUE THREAD

**Issue by rockawho** [20tab/UnrealEnginePython#327]
Hello,

I am using Engine version 4.16.3 and am trying to compile the plugin.
I keep getting this error:
PythonHouseKeeper.h(69): error C2039: 'GetPostGarbageCollect': is not a member of 'FCoreUObjectDelegates'
Any help would be appreciated

**Comment by rdeioris** [comment]
@rockawho the current code requires 4.18, i am about to push the latest stuff for older version. It is a matter of few minutes

**Comment by rockawho** [comment]
Cool. Thanks

**Comment by rdeioris** [comment]
4.16 support has been fixed

**Comment by rockawho** [comment]
Thanks. It complies successfully now :)
