### ISSUE TITLE
How to read UScriptStruct properties

### ISSUE THREAD

**Issue by keithcheuk** [20tab/UnrealEnginePython#334]
Hi, please pardon me as I am pretty new to scripting and especially python in unreal.

What I am trying to find out is what are the accessible properties in something like this:
AlembicImportFactory().ImportSettings.SamplingSettings and I get information like this <unreal_engine.UScriptStruct {'struct': 'AbcSamplingSettings', 'size': 24, 'ptr': 0x000002F104AA7298}>.

So how am I able to find out what properties I can access? By some guess work I can figure out that I can access AlembicImportFactory().ImportSettings.SamplingSettings.StartFrame and AlembicImportFactory().ImportSettings.SamplingSettings.EndFrame. But it is impossible for me to guess what other options I can access.

Similarly, I need to access information in SkeletalMaterial for assigning specific material to a specific material slot. By reading the SkeletalMaterial, I get a UScriptStruct Object [<unreal_engine.UScriptStruct object at 0x000002F0884F6D50>, <unreal_engine.UScriptStruct object at 0x000002F0884F6D20>]. How do I read this information to access the material slot name I have in that UScriptStruct Object?

Is there a way to find out all the python functions we have in unreal? Appreciates if someone can point me in the right direction. Thanks!

**Comment by rdeioris** [comment]
The .properties() method returns the list of UObject properties, while fields() returns the list of UStructs fields name.

Check this paragraph for more infos:

https://github.com/20tab/UnrealEnginePython#the-automagic-uclass-ustruct-and-uenums-mappers

**Comment by keithcheuk** [comment]
Thanks for pointing me at the right place. Cheers
