### ISSUE TITLE
Assigning Material with Skeletal Material: invalid value for UProperty

### ISSUE THREAD

**Issue by keithcheuk** [20tab/UnrealEnginePython#337]
I am following the tutorial here https://github.com/20tab/UnrealEnginePython/blob/master/tutorials/YourFirstAutomatedPipeline.md
but I am unable to get materials assigned to my own fbx.
Example: https://www.dropbox.com/s/cai12zpvwfrokry/jersey.fbx?dl=0

I am getting error on this line of code: 

asset.Materials = [SkeletalMaterial(MaterialInterface=materialFront, MaterialSlotName='MTL_front', UVChannelData=MeshUVChannelInfo(bInitialized=True)),SkeletalMaterial(MaterialInterface=materialSide, MaterialSlotName='MTL_side', UVChannelData=MeshUVChannelInfo(bInitialized=True))]

Error:
invalid value for UProperty
Traceback (most recent call last):
  File "<string>", line 40, in <module>
ValueError: invalid value for UProperty

Do I have to prepare my fbx export in a certain way for this to work? This line of code worked for the slicer fbx provided and I have trouble finding out the difference between this mesh with mine.

Thanks in advance,
Keith

**Comment by keithcheuk** [comment]
I exported the slicer to an alembic file and now it have the same issue.
Example: https://www.dropbox.com/s/i1qxmkglqz97qz6/slicer.abc?dl=0

Is static mesh created differently from alembic imports?

**Comment by rdeioris** [comment]
If you are using a StaticMesh you cannot use the SkeletalMaterial stuff.

Check here: https://github.com/20tab/UnrealEnginePython/blob/master/tutorials/SnippetsForStaticAndSkeletalMeshes.md#staticmesh-merging

**Comment by keithcheuk** [comment]
Ah alright, thanks for pointing me at the right direction!
