### ISSUE TITLE
how to add actors to the world that not opened ？

### ISSUE THREAD

**Issue by shenroom** [20tab/UnrealEnginePython#338]
I have two world: testWorld , mainWorld. and the mainWorld is current level .

there are few questions 
1. i only want to add actors to the testWorld but when i add a actor to the testWorld and the actor added to the current world (mainWorld) too. 

2. how to save changes when i add actors to the world?

**Comment by rdeioris** [comment]
Hi, did you solved it ?

Basically you can call actor_span on any UWorld object (included level assets)
