### ISSUE TITLE
Declaring Matrix Structs

### ISSUE THREAD

**Issue by keithcheuk** [20tab/UnrealEnginePython#343]
Hi, I am following a thread regards to instance mesh components in blue print: https://github.com/20tab/UnrealEnginePython/issues/333

Unfortunately I am having trouble using the matrix function, this line InstancedStaticMeshInstanceData(Transform=FTransform(FVector(0, 0, 200), FRotator(90, 90, 0)).get_matrix())

Will return an error: 'unreal_engine.FTransform' object has no attribute 'get_matrix'

I thought I can create the Matrix by this instead.
from unreal_engine.structs import InstancedStaticMeshInstanceData, Matrix

InstancedStaticMeshInstanceData(Transform=Matrix(FTransform(FVector(0, 0, 200), FRotator(90, 90, 0))))

Now that there is no error, but when I query the value in the Matrix, it returns 0 for all. May I know if I am using the Matrix function correctly here?

Thanks in advance!
Keith

**Comment by rdeioris** [comment]
Hi, get_matrix() is only available in the latest releases (20180305)

**Comment by keithcheuk** [comment]
Got it! Thanks again!
