### ISSUE TITLE
How to add a component to an actor?

### ISSUE THREAD

**Issue by Schizo** [20tab/UnrealEnginePython#344]
I was trying to add an `instancedStaticMeshComponent` to an existing actor, but I didn't get any results and no errors. Here is the code:

```
import unreal_engine as ue
from unreal_engine.classes import InstancedStaticMeshComponent

#Selected the Floor actor from the Worldoutliner
actor = ue.editor_get_selected_actors()[0]
actor.add_actor_component(InstancedStaticMeshComponent, 'foo')
```

I don't think that is necessary, but that didn't help either

```
# updated actor
actor.post_edit_change()
```

**Comment by rdeioris** [comment]
Hi, the syntax is right, maybe you are expecting the world outliner to be updated on the fly ? (just deselect and re-select the actor to get the component).

Take into account that if the Actor has still not root component you need to attach the component with add_actor_root_component(componentClass, name)

**Comment by Schizo** [comment]
Hey Roberto. I wasn't expecting to be updated on the fly, I've deselected and re-selected the actor, but the component still didn't appear. I've tried other component's as well it didn't work. I'm running `Unreal 4.18.3` and `Python 3.6`

Can you provide a snippet that creates an actor, add's a component that is reproducible at your end?

**Comment by rdeioris** [comment]
```python
import unreal_engine as ue
from unreal_engine.classes import Actor, InstancedStaticMeshComponent

world = ue.get_editor_world()

new_actor = world.actor_spawn(Actor)
new_actor.set_actor_label('Test Actor')
new_actor.add_actor_root_component(InstancedStaticMeshComponent, 'Root')
```

**Comment by rdeioris** [comment]
If you prefer your component to not be a 'native' one (you cannot edit native/inherited component from the details tab) you can do:

```python
import unreal_engine as ue
from unreal_engine.classes import Actor, InstancedStaticMeshComponent

world = ue.get_editor_world()

new_actor = world.actor_spawn(Actor)
new_actor.set_actor_label('Test Actor')
new_component = new_actor.add_actor_root_component(InstancedStaticMeshComponent, 'Root')
new_actor.add_instance_component(new_component)
```

**Comment by Schizo** [comment]
Ok, I must be doing something dumb. Let me post a screenshot of what code I'm running  and how my outliner looks like. 

![image](https://user-images.githubusercontent.com/38006/37239772-089ad2a4-23f6-11e8-80be-67c31947242b.png)

**Comment by Schizo** [comment]
Actually, my mistake, I didn't see that it was collapsed in the Details Component Hierarchy, all seem to be good now! Thanks for looking!
