### ISSUE TITLE
Spawning C++ Class

### ISSUE THREAD

**Issue by natanielruiz** [20tab/UnrealEnginePython#345]
I can't seem to figure this out. How do I spawn a C++ Class without creating a Blueprint from that C++ Class (unfortunately not possible in my use-case).

**Comment by rdeioris** [comment]
Hi, if the class is already loaded you can reference to it like the others:

```python
from unreal_engine.classes import NameOfYourClass
```

so if you have create the UFooBar class you will do:

```python
from unreal_engine.classes import FooBar
```

(note the missing U prefix)

If instead, for some reason, the class is still not loaded, you need to call ue.load_class(path).

C++ classes are mapped to '/Script/ProjectName.ClassName, so if you project is named 'Test001' you will need to do:

```python
your_class = ue.load_class('/Script/Test001.FooBar')
```

**Comment by natanielruiz** [comment]
And then should I do:
actor = world.actor_spawn(NameOfMyClass, FVector(0,0,0), FRotator(0,0,0))?

**Comment by natanielruiz** [comment]
Okay so I investigated further and it looks like my actor is being spawned AFTER play is ended and that is why it shows up in the editor after I end play but not during play where it should show up. Anyone have any problem similar to this one?

**Comment by natanielruiz** [comment]
The same is happening with a very simple blueprint class with a cube mesh. It is generated after simulation is stopped and not during play.

**Comment by natanielruiz** [comment]
So what I noticed is that anything I want to spawn is being spawned after the simulation is stopped. Even empty actors and pawns.

**Comment by rdeioris** [comment]
Hi, from what you describe it looks like you are spawning your actor in the editor world instead of the game world. When you hit play/simulate a new world is created and you need to spawn actors in that world. You can access the current game viewportclient with:


```python
ue.get_game_viewport_client()
```

**Comment by natanielruiz** [comment]
Thanks so much @rdeioris, I'll try this out!

**Comment by natanielruiz** [comment]
It works! Thank you again! Closing the issue.

**Comment by Balasass** [comment]
hi I have the same problem and I tried your solution but now I have an error

> LogPython: Error: module 'unreal_engine' has no attribute 'get_world'
LogPython: Error: Traceback (most recent call last):
LogPython: Error:   File "<string>", line 9, in <module>
LogPython: Error: AttributeError: module 'unreal_engine' has no attribute 'get_world'

**Comment by UtkarshMoholkar** [comment]
> hi I have the same problem and I tried your solution but now I have an error
> 
> > LogPython: Error: module 'unreal_engine' has no attribute 'get_world'
> > LogPython: Error: Traceback (most recent call last):
> > LogPython: Error:   File "", line 9, in 
> > LogPython: Error: AttributeError: module 'unreal_engine' has no attribute 'get_world'

Here is the Sample example to Spawn Blueprint Actor
    def spawn_actor(self):
        self.blueprint = ue.load_object(Blueprint, '/Game/Blueprints/YourActorName')
        self.world = self.uobject.get_world()
        self.actor_object = self.world.actor_spawn(self.blueprint.GeneratedClass, FVector(-300, 0, 500), FRotator(0, 0, 0))
