### ISSUE TITLE
Assets converted using the Root Motion Fix for Mixamo script are not moving

### ISSUE THREAD

**Issue by Pomettini** [20tab/UnrealEnginePython#348]
When I try to convert a model and its animations that I imported from Mixamo using the Root Motion Fix script, the Root Motion is not physically moving the character. The only workaround I found is to export the faulty animation and reimport it using Reimport From Source from the asset menu.

**Comment by rdeioris** [comment]
Fixed: https://github.com/20tab/UnrealEnginePython/commit/ef01c4e566f56f093ad4d7d07fddaddd82b44bb8#diff-2a09d16411bd595ae0ce31e9a2db0b6d
