### ISSUE TITLE
Actor Properties Don't Refresh

### ISSUE THREAD

**Issue by natanielruiz** [20tab/UnrealEnginePython#349]
Hi,
I am trying to:
-spawn an actor
-refresh the properties of an actor while the game is running

After spawning the actor I modify a property as follows:
spawned_actor.PropertyToModify = 'new_property'

I can see that the property changes when I simulate the game but the actor stays the same and does not refresh to the new property. For example if this property would be changing mesh then the mesh stays the same as the initial mesh, but the UProperty changes.

Thanks for the help!

**Comment by natanielruiz** [comment]
Also using
spawned_actor.modify()

Either before or after modifying the property doesn't help.

**Comment by rdeioris** [comment]
Hi, a bunch of actor properties (for performance reasons, mainly) do not apply modifications to the actor itself until you manually call .post_edit_change() (PostEditChange() in c++). In this way you can enqueue a bunch of changes and then apply all of them in one shot:

```python
actor.Prop1 = 'value1'
actor.Prop2 = 'value2'
actor.post_edit_change()
```

In addition to this, there are cases (like for animations) where you even need to 'prepare' the actor for a series of updates, in such a case you need to do:

```python
actor.pre_edit_change()
actor.Prop1 = 'value1'
actor.Prop2 = 'value2'
actor.post_edit_change()
```

**Comment by natanielruiz** [comment]
Hi. Thanks a lot for the tip. Unfortunately it doesn't seem to work. I have a parameter which decides what type of road intersection to spawn and updating it this way doesn't change the type of intersection.

**Comment by natanielruiz** [comment]
I actually got it to work by using actor.post_edit_property_changed('MyProperty', 0)

Any idea why it doesn't work with post_edit_change()?

Also, is there any way to use python to define the properties of an actor before spawning so it spawns with the desired properties? Thanks so much!

**Comment by rdeioris** [comment]
Hi, it depends on the kind of property and how it works related to the actor.

Regarding 'properties before spawning' i suppose you mean 'expose on spawn' vars. In such a case you can use:

```python
actor = world.actor_spawn(class, location rotation, prop1=value1, prop2=value2,...)
```

**Comment by natanielruiz** [comment]
Awesome. Thanks so much @rdeioris, love your work. Closing this issue.
