### ISSUE TITLE
API docs and auto complete

### ISSUE THREAD

**Issue by jiamingfeng** [20tab/UnrealEnginePython#35]
I love the have auto completion working in Visual Studio Code with UnrealEnginePython. 
Is there anyway to do that?

If not, is there a way to have some APIs doc to reference to?

**Comment by sinokgr** [comment]
Hey @jiamingfeng, I don't know about auto-completion, but in terms of docs, I believe you can find most of the things you want in the following files:
[README](https://github.com/20tab/UnrealEnginePython/blob/master/README.md)
[PythonConsole](https://github.com/20tab/UnrealEnginePython/blob/master/PythonConsole.md)
[sequencer_API](https://github.com/20tab/UnrealEnginePython/blob/master/sequencer_API.md)
[uObject_API](https://github.com/20tab/UnrealEnginePython/blob/master/uobject_API.md)
Hope that helps 😄

**Comment by rdeioris** [comment]
Even this file would be helpful https://github.com/20tab/UnrealEnginePython/blob/master/Source/UnrealEnginePython/Private/UEPyModule.cpp#L87

Take in account that those are the python-specific functions. The reflection-based functions are the same of the Blueprint api.

**Comment by jiamingfeng** [comment]
Thanks for the reply @sinokgr  @rdeioris .
I guess the python console is still a bit hard to use and I was getting a bit frustrated. 
Is the ue.exec("file.py") the best way to test my own script?

**Comment by sinokgr** [comment]
@jiamingfeng, personally, if I want to test something, what I do is I import in console the module  like "import file" and then run my defs from "file.my_def()". If I change anything I do "reload(file)" and run the def again.

**Comment by rdeioris** [comment]
@jiamingfeng you can map python script to menus (https://github.com/20tab/UnrealEnginePython/issues/29#issuecomment-250678767) but yes, the console currently sucks. Next step will be adding history support and the printing of the last evaluated statement (like the standard python interactive console)
