### ISSUE TITLE
Executing functions from external python scripts

### ISSUE THREAD

**Issue by natanielruiz** [20tab/UnrealEnginePython#353]
I want another external python script to call functions on a class object that is running inside UE4. Is there any way to do this? For example I would like an external script to execute a function which changes the mesh of an actor inside of a running game.

Cheers!

**Comment by sabhiram** [comment]
You could setup a embedded python server w/in your actor and implement a socket listener and a Queue to keep the treads happy. Anything is possible :)

**Comment by Schizo** [comment]
I've used UnrealEnginePython to stream data to elements to update their positions and if you follow this [tutorial](https://github.com/20tab/UnrealEnginePython/blob/master/tutorials/AsyncIOAndUnrealEngine.md), that one is well described. Just Note that the examples are using `asyncio`. If you don't want to use 3.6 you have to use your own sockets.

**Comment by natanielruiz** [comment]
@sabhiram and @Schizo thank you very much for your suggestions! Will try to implement them and keep this issue updated.

**Comment by natanielruiz** [comment]
Works beautifully. Thank you very much!
