### ISSUE TITLE
Animation curves.

### ISSUE THREAD

**Issue by GOS-Onfinger** [20tab/UnrealEnginePython#361]
Hi, first of all, great job you guys are doing!
Not sure where to post it, please forgive me.
Regarding to the fbx curve extractor, it worked as expected, my doubt is, how can i store those values as a curve inside ue4, is it possible? Thanks in advance!

**Comment by Schizo** [comment]
Can you explain in a little more detail what exactly you want to do and show a little example you tried? You might probably get more responses by doing that.

Cheers

**Comment by GOS-Onfinger** [comment]
Hi, Let try to explain better, I'm looking to find a way to visually see those numbers from FbxExtractor and create(programatically, or some kind of import data curve from .cvs) into ue4 (curve vector I gguess?), so I could do some adjustments bones xyz or some small glitchs.
Hopefully, it make sense.

Thanks for the response!

**Comment by rdeioris** [comment]
@GOS-Onfinger Hi, check this new example: https://github.com/20tab/UnrealEnginePython/blob/master/examples/curve_generator.py

Note: you need latest version of the plugin

**Comment by GOS-Onfinger** [comment]
Hi Roberto, It worked Perfectly, It's amazing! 
I`m starting to learn python more from now on.
Hope in future i could contribute in some way.

Thanks!
