### ISSUE TITLE
get error when package my game

### ISSUE THREAD

**Issue by xermao** [20tab/UnrealEnginePython#362]
log
1>------ Build started: Project: UE4, Configuration: BuiltWithUnrealBuildTool Win32 ------
2>------ Build started: Project: Studio, Configuration: BuiltWithUnrealBuildTool Win32 ------
3>------ Build started: Project: Game_2018, Configuration: Development_Game x64 ------
3>  Using 'git status' to determine working set for adaptive non-unity build.
3>  Distributing 8 actions to XGE
3>  --------------------Build System Warning---------------------------------------
3>  Failed to connect to Coordinator:
3>      All builds will run in standalone mode.
3>
3>  -------------------------------------------------------------------------------
3>  --------------------Project: Default-------------------------------------------
3>  PCH.UnrealEnginePython.cpp (0:25.73 at +0:00)
3>f:\xermao\documents\unreal projects\game_2018 4.19\plugins\unrealenginepython\source\unrealenginepython\private\Wrappers/UEPyFSoftSkinVertex.h(15): error C3646: “ss_vertex”: 未知重写说明符
3>f:\xermao\documents\unreal projects\game_2018 4.19\plugins\unrealenginepython\source\unrealenginepython\private\Wrappers/UEPyFSoftSkinVertex.h(15): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
3>f:\xermao\documents\unreal projects\game_2018 4.19\plugins\unrealenginepython\source\unrealenginepython\private\Wrappers/UEPyFSoftSkinVertex.h(22): error C2065: “FSoftSkinVertex”: 未声明的标识符
3>
3>  Error executing C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe (tool returned code: 2)
3>  ---------------------- Done ----------------------
3>
3>      Rebuild All: 0 succeeded, 1 failed, 0 skipped
3>
3>  1 build system warning(s):
3>     - Failed to connect to Coordinator
3>
3>
3>
3>UnrealBuildTool : error : UBT ERROR: Failed to produce item: F:\xermao\Documents\Unreal Projects\Game_2018 4.19\Plugins\UnrealEnginePython\Binaries\Win64\UE4-UnrealEnginePython.lib
3>  Total build time: 27.30 seconds (XGE executor: 0.00 seconds)

**Comment by rdeioris** [comment]
Fixed in latest code. Thanks for reporting

**Comment by slartibaartfast** [comment]
I'm also getting this unreal build tool error when building on ubuntu 17.10

Steps to reproduce:
1) install unreal engine 4.19 from the release branch
2) make a new c++ project (named fouronenine in this case)
3) install unrealenginepython plugin from master branch
4) run the build tool

I ran the build tool with this command:

> /home/.../UnrealEngine/Engine/Build/BatchFiles/RunUAT.sh BuildCookRun -project="/home/.../UnrealProjects/fouronenine/fouronenine.uproject" -nop4 -build -cook -stage -compressed -platform=Linux -clientconfig=Development -pak -archive archivedirectory="" -utf8output

The error message I received is:

>   ERROR: UBT ERROR: Failed to produce item: /home/.../UnrealProjects/fouronenine/Plugins/UnrealEnginePython/Binaries/Linux/libfouronenine-UnrealEnginePython.a
  Total build time: 637.49 seconds (Local executor: 0.00 seconds)
Took 637.793242s to run mono, ExitCode=5
ERROR: Command failed (Result:5): /home/.../UnrealEngine/Engine/Binaries/DotNET/UnrealBuildTool.exe fouronenine Linux Development -Project=/home/.../UnrealProjects/fouronenine/fouronenine.uproject  /home/.../UnrealProjects/fouronenine/fouronenine.uproject -NoUBTMakefiles  -remoteini="/home/.../UnrealProjects/fouronenine" -noxge -NoHotReload -ignorejunk. See logfile for details: 'UnrealBuildTool-2018.04.02-09.33.55.txt' 
       (see /home/.../Library/Logs/Unreal Engine/LocalBuildLogs/UAT_Log.txt for full exception trace)
AutomationTool exiting with ExitCode=5 (5)
RunUAT ERROR: AutomationTool was unable to run successfully.


The error that is thrown is:

>   In file included from /home/.../UnrealProjects/fouronenine/Plugins/UnrealEnginePython/Intermediate/Build/Linux/B4D820EA/fouronenine/Development/UnrealEnginePython/PCH.UnrealEnginePython.h:115:
  In file included from /home/.../UnrealProjects/fouronenine/Plugins/UnrealEnginePython/Source/UnrealEnginePython/Private/UnrealEnginePythonPrivatePCH.h:50:
  /home/.../UnrealProjects/fouronenine/Plugins/UnrealEnginePython/Source/UnrealEnginePython/Private/Wrappers/UEPyFSoftSkinVertex.h:15:2: error: unknown type name 'FSoftSkinVertex'
          FSoftSkinVertex ss_vertex;
          ^
  /home/.../UnrealProjects/fouronenine/Plugins/UnrealEnginePython/Source/UnrealEnginePython/Private/Wrappers/UEPyFSoftSkinVertex.h:22:39: error: unknown type name 'FSoftSkinVertex'; did you mean 'FFinalSkinVertex'?
  PyObject *py_ue_new_fsoft_skin_vertex(FSoftSkinVertex);
                                        ^~~~~~~~~~~~~~~
                                        FFinalSkinVertex
  Runtime/Engine/Classes/Components/SkinnedMeshComponent.h:273:43: note: 'FFinalSkinVertex' declared here
          void GetCPUSkinnedVertices(TArray<struct FFinalSkinVertex>& OutVertices, int32 InLODIndex);


Not sure if this is relevant...
[https://forums.unrealengine.com/development-discussion/c-gameplay-programming/1446998-what-happened-to-uskeletalmesh-in-ue-4-19](url)

**Comment by slartibaartfast** [comment]
I'll try pulling new code again.
