### ISSUE TITLE
Question: How would I go about invoking `AddOrUpdateBlendable()`

### ISSUE THREAD

**Issue by sabhiram** [20tab/UnrealEnginePython#366]
I have a `SceneCaptureComponent` in python which exposes a visible method `AddOrUpdateBlendable()`. However when I call this with a `Material` which I load using `ue.load_object(Material, "/Game...")` - I get this error:

```
unable to convert pyobject to property InBlendableObject (InterfaceProperty)
```

Any clues? I don't mind adding more wrappers if you can steer me in the right direction :)

**Comment by rdeioris** [comment]
Hi, check latest code, it implements interfaces supports
