### ISSUE TITLE
Access to Built Actions

### ISSUE THREAD

**Issue by Schizo** [20tab/UnrealEnginePython#368]
I did a quick search but didn't see any actions related `building`. I would love to run some wedges with different light bake settings to easily compare them. That would definitely increase the process of finding the right values for visualization.

**Comment by rdeioris** [comment]
Hi, you can use the unreal_engine.editor_command_* functions (like unreal_engine.editor_command_build).

If you want to extend that part of the api with new commands the implementation is pretty easy:

https://github.com/20tab/UnrealEnginePython/blob/master/Source/UnrealEnginePython/Private/UEPyEditor.cpp#L177

here are the available static functions (from c++):

http://api.unrealengine.com/INT/API/Editor/LevelEditor/FLevelEditorActionCallbacks/

**Comment by Schizo** [comment]
@rdeioris  Thanks for your reply, that looks promising. I'll dig into that.

**Comment by Schizo** [comment]
Just wanted to add this for completeness, to trigger light build, you would use the following snippet.

    import unreal_engine as ue
    ue.editor_command_build_lighting()
