### ISSUE TITLE
Build failed for 4.19 can't find GenericApplication.h

### ISSUE THREAD

**Issue by Aszutai** [20tab/UnrealEnginePython#369]
Hi, here's the error that I'm getting:
Error	C1083	Cannot open include file: 'Runtime/Core/Public/GenericPlatform/GenericApplication.h': No such file or directory
d:\ue4\*Project_directory*\plugins\unrealenginepython\source\unrealenginepython\private\slate\UEPyFModifierKeysState.h

I opened and checked in the engine source folder and I didn't find the GenericApplication.h file in there. Anyone else getting this error? Is it just my build, as in I'm getting the wrong version or something else?

Thanks in advance!

**Comment by Aszutai** [comment]
I took a look at the github history looks like the include was newly added for 4.15 compatibility. By checking the engine minor version I was able to compile successfully. Of course I don't know if 4.15 uses the same version check as 4.19 so it could very fail for 4.15 users.

code:
#if ENGINE_MINOR_VERSION <= 15
#include "Runtime/Core/Public/GenericPlatform/GenericApplication.h"
#endif

If I used the wrong solution please let me know, thanks!

**Comment by rdeioris** [comment]
Yes, your fix was right, i have fixed the master branch too. Thanks for reporting
