### ISSUE TITLE
Access Functions

### ISSUE THREAD

**Issue by sinokgr** [20tab/UnrealEnginePython#37]
While I'm trying to get familiar with developing in Python for Unreal, I realised that I didn't know how to access funtions. Currently we have access to properties (.get_property, .set_property, .properties) and they work fine but how about functions? I saw that in the [UEPyModule.cpp](https://github.com/20tab/UnrealEnginePython/blob/master/Source/UnrealEnginePython/Private/UEPyModule.cpp#L87) there are a few related functions (.find_function and .call_function") but I can't make them work. I assume that I'm doint something wrong.

That's a simple example of how I was trying access Actor's [GetLevel()](https://docs.unrealengine.com/latest/INT/API/Runtime/Engine/GameFramework/AActor/index.html) function:
![image](https://cloud.githubusercontent.com/assets/22396951/19082306/7cd110e8-8a55-11e6-8094-84e8e96fe633.png)

Scripts\test.py
```Python
def fun():
    selected_actors = ue.editor_get_selected_actors()
    for actor in selected_actors:
        fn = actor.find_function("GetLevel")
        ue.log(str(fn))
```

This prints "None". What am I doing wrong?

**Comment by rdeioris** [comment]
Only the function marked (in the docs) as UFunction (the ones with the 'u' logo) can be called via reflection:

```py
life = actor.GetLifeSpan()
```

"private" functions must be exposed natively. 

By the way the rule is that if a function is availabel to blueprint, you can call it in python via reflection

**Comment by rdeioris** [comment]
Can we close it ? Or do you prefer do add support for GetLevel() natively ?

**Comment by sinokgr** [comment]
Hi @rdeioris, sorry for the late reply. I'm assigned to another project the past couple of weeks but I expect to get back on Unreal later down the line. I think you should close it, yeah. Thanks.
