### ISSUE TITLE
Populating a SPythonComboBox with items

### ISSUE THREAD

**Issue by Papoun** [20tab/UnrealEnginePython#371]
Hi,

I'm looking into making a combobox in Slate but can't seem to get the right argument for options_source. Coming from a PyQT background a tried with a basic array of strings but with no luck, most other attempts also didn't result in anything that's working, even after setting on_generate_widget.

```python
window = SWindow(title='My Popup Window', min_width = 450, min_height = 360,
 create_title_bar = True, drag_anywhere = True, sane_window_placement=True, foreground_color=SlateColor(SpecifiedColor=FLinearColor(0.141, 0.6, 0.965)))

main_layout = SVerticalBox(auto_height=True, padding = 2)

materials_cmbx = SPythonComboBox(options_source = ['something', 'object'], on_generate_widget=lambda: ue.log('...'))

combobox_layout = SHorizontalBox()

combobox_layout.add_slot(materials_cmbx)

main_layout.add_slot(combobox_layout, v_align=2, h_align=2)

window.set_content(main_layout)
```

Thanks !

**Comment by rdeioris** [comment]
Hi, the on_generate_widget callback expects you to return an SWidget:

```python
on_generate_widget=lambda x: STextBlock(text=x)
```

**Comment by Papoun** [comment]
Hey, sorry for the late answer ! Ended up moving altogether to PySide2 instead of relying on Slate for future UI work in Unreal ^^' works like a charm ! although i'm having a bit of a hard time parenting it to the editor window to make it always ontop of it (couldn't make it to work with the `ue.get_editor_window().get_handle()` method), but that's for another issue ! :-)

The STextBlock seems to have been the missing link in here, thanks a lot for that info !
