### ISSUE TITLE
Can i set my slate window always top?

### ISSUE THREAD

**Issue by fuliangjun1002** [20tab/UnrealEnginePython#373]
As the title says, Can i placed my slate window always at the top ?

**Comment by rdeioris** [comment]
Hi, here you find an example of a modal window:

https://github.com/20tab/UnrealEnginePython/blob/master/tutorials/WritingAColladaFactoryWithPython.md#adding-a-gui-to-the-importer-the-slate-api

**Comment by fuliangjun1002** [comment]
Good idea 👍
