### ISSUE TITLE
Error while packaging app with the Python Plugin

### ISSUE THREAD

**Issue by Aszutai** [20tab/UnrealEnginePython#374]
Hi, I ran into an odd issue while attempting to package our unreal application with the plugin. I got a bunch of compile errors while trying to package saying they can't find included header files. It's weird because the project compiles fine in visual studio 2017 and runs completely fine in the editor, only when I attempt to package it does it start to give me errors.

I have attached the output, thank you.
[UE4_Packaging_Error_Log.txt](https://github.com/20tab/UnrealEnginePython/files/1913812/UE4_Packaging_Error_Log.txt)

Edit:
Currently I suspect that this is due to the header reorganizations, seems like there are files that still need to have their headers adjusted? Anyways, I'll attempt to do that tomorrow. If it works then I'll submit a pull request. Of course if I'm off the mark on this issue please let me know, thank you.

**Comment by rdeioris** [comment]
@Aszutai yep, it is caused by headers reorganization. Just add #if WITH_EDITOR where you get errors. I will fix it next week (unless you manage to make a pull request). Thanks

**Comment by Aszutai** [comment]
@rdeioris Hi robb, I actually did fix a few shortly after I posted the issue, but a bunch of other similar errors popped up afterwards. Been busy with other task in the past 2 days so I haven't worked further on it yet. But yea, I'll make a pull if I managed to get enough time to finish it before you get to it :)

**Comment by Aszutai** [comment]
Went through the source files and fixed all of the header issues that popped up for me. Although without spending more time on it I can't say for sure that what I did was correct for the Python Plugin as a whole, but I was able to successfully package the app and everything functioned like it should for me. 

Please check the pull request and let me know. Thank you :D
