### ISSUE TITLE
Using MaterialFunctions with UEP

### ISSUE THREAD

**Issue by HughMacdonald** [20tab/UnrealEnginePython#378]
Hi,

I'm struggling to figure out how to connect inputs to MaterialFunctions using UEP.

    material.modify()

    myTexture = MaterialExpressionTextureSample( "", material )
    myTexture.Texture = texture

    myFunction = MaterialExpressionMaterialFunctionCall( "", material )
    myFunction.MaterialFunction = ue.get_asset( "/Game/Materials/MaterialFunctions/MyMaterialFunction.MyMaterialFunction" )

And then I've tried each of the following lines to try to connect its input to the Texture:

    myFunction.FunctionInputs[0].Input = ExpressionInput( Expression=myTexture )
    myFunction.FunctionInputs[0] = FunctionExpressionInput( Input=ExpressionInput( Expression=myTexture ) )
    myFunction.FunctionInputs = [ FunctionExpressionInput( Input=ExpressionInput( Expression=myTexture ) ) ]

Followed by

    material.EmissiveColor = ColorMaterialInput( Expression=myFunction )
    material.Opacity = ScalarMaterialInput( Expression=myFunction, OutputIndex=1 )

    material.Expressions = [ myTexture, myFunction ]

    material.post_edit_change()

In all of these cases, it doesn't connect the input, and I'm at a loss as to how to connect it in.

Any guidance would be much appreciated. I'm going to keep on trying, so I may hit on the solution (if I do, I'll make sure I mention it here).

Thanks

**Comment by HughMacdonald** [comment]
I figured out what I was doing wrong here. I'm not sure if this is something that could be changed in UEP to make it easier to do...

This is what I ended up having to do. I believe that this is something that would be required any time someone wants to modify an array property.

     functionInputs = myFunction.get_property( "FunctionInputs" )
     functionInputs[0].set_field( "Input", ExpressionInput( Expression=myTexture) )
     myFunction.set_property( "FunctionInputs", functionInputs )

**Comment by rdeioris** [comment]
Hi, structures are always passed by value for security reasons (it is very easy to end with dangling pointers all over the place). Unfortunately this choice forces the user to a non-pythonic coding style. If you know what you are doing, you can use the ref() method:

```python
myFunction.FunctionInputs[0].ref().Input = ExpressionInput( Expression=myTexture)
```

**Comment by HughMacdonald** [comment]
Ah - fantastic! Thanks for the pointer (pun not intended). I think I'll go that route as it feels cleaner, and I won't get stuck on it next time!
