### ISSUE TITLE
Building blueprint construction graph 

### ISSUE THREAD

**Issue by keithcheuk** [20tab/UnrealEnginePython#380]
Hi,

I am trying to build a procedural blueprint, but I am stuck on 2 issues. First, being able to set a variable editable and second to link the variable to a component in the blueprint. Can you point me at the right direction?

My code:
import unreal_engine as ue
from unreal_engine.classes import BlueprintFactory, DirectionalLightComponent

bpFactory = BlueprintFactory()
bp = bpFactory.factory_create_new('/Game/test')

intensity = ue.blueprint_add_member_variable(bp, 'intensity', 'float')
directLightComponent = ue.add_component_to_blueprint(bp,DirectionalLightComponent, "Directional_light")

ue.compile_blueprint(bp)
ue.get_editor_world().actor_spawn(bp.GeneratedClass)

How do I connect the intensity variable to the directional light's intensity and make that variable visible?

Thanks in advance!

**Comment by rdeioris** [comment]
Hi, this is the script you need:

https://github.com/20tab/UnrealEnginePython/blob/master/examples/blueprint_example_generator.py

always use this tutorial as reference:

https://github.com/20tab/UnrealEnginePython/blob/master/tutorials/YourFirstAutomatedPipeline.md
