### ISSUE TITLE
Support for adding widgets to WidgetBlueprints

### ISSUE THREAD

**Issue by HughMacdonald** [20tab/UnrealEnginePython#381]
Hi,

First off, I'm not sure if this is possible already. I tried to do it with the following Python, but this left me with errors when I opened the WidgetBlueprint inside the editor and tried to recompile it.

    import unreal_engine as ue

    from unreal_engine.classes import Image, \
                                      CanvasPanelSlot, \
                                      WidgetBlueprintFactory

    widget = WidgetBlueprintFactory().factory_create_new( "/Game/W_MyWidgetBlueprint" )

    widget.modify()

    widgetTree = widget.WidgetTree

    image = Image()
    slot = CanvasPanelSlot()

    slot.Content = image
    widgetTree.RootWidget.Slots = [ slot ]
    widgetTree.AllWidgets = [ widgetTree.RootWidget, image ]

    slot.LayoutData.Offsets.Left, slot.LayoutData.Offsets.Top = ( 0, 0 )
    slot.LayoutData.Offsets.Right, slot.LayoutData.Offsets.Bottom = ( 200, 200 )

    widget.post_edit_change()

I feel like what is needed is a module-level function similar to add_component_to_blueprint.

Is this something that would be required? Or am I missing a way of doing this using the existing UEP?

Thanks

**Comment by rdeioris** [comment]
Hi, i have added an example:

https://github.com/20tab/UnrealEnginePython/blob/master/examples/widget_blueprint_generator.py

basically you need to ensure the outer of each widget is the WidgetTree

**Comment by HughMacdonald** [comment]
Ahh - amazing - thank you for this. I didn't realise I needed that.


Much appreciated!
