### ISSUE TITLE
Adding variable to blueprints - additional types

### ISSUE THREAD

**Issue by HughMacdonald** [20tab/UnrealEnginePython#386]
Hi,

In adding variables to blueprints, how do I add specific struct or object types?

In my case, I want to add a Material Interface object reference, but I'd also like to know how to format the string being passed into `ue.blueprint_add_member_variable` to get any object reference or struct. For example, a more commonly used variable type that might be wanted would be Vector or Rotator.

Thanks

**Comment by rdeioris** [comment]
Hi, you need to use latest code that support the EdGraphPinType struct:

https://github.com/20tab/UnrealEnginePython/blob/master/examples/blueprint_variables.py

**Comment by HughMacdonald** [comment]
Amazing - thanks for that.

I had noticed the EdGraphTerminalType, but hadn't clicked what it was for.

I have one last question (for now, anyway). How can I set the default value on a variable? Because I'm making a WidgetBlueprint at the moment, I'm not dropping it into the level where I can set variables on it.


Thanks for all your help!

**Comment by rdeioris** [comment]
Hi, you need to re-pull latest sources and check the updated example. Take into account that the default values syntax is pretty weird...

**Comment by HughMacdonald** [comment]
Thanks - appreciate all of the help! I've got another one coming, but it's a separate thing, so I'll close this issue and create a new one.
