### ISSUE TITLE
Blueprints - having a strange issue creating a return node in a function

### ISSUE THREAD

**Issue by HughMacdonald** [20tab/UnrealEnginePython#387]
I've got an odd one here. Once again, I'm not sure if I'm doing something silly myself, or it's some other reason...

Here's my code:

    import unreal_engine as ue
    from unreal_engine.classes import BlueprintFactory, K2Node_FunctionResult
    from unreal_engine.structs import EdGraphPinType
    from unreal_engine.enums import EEdGraphPinDirection
    import time

    # create new blueprint from factory
    bpFactory = BlueprintFactory()
    bp = bpFactory.factory_create_new('/Game/test' + str(int(time.time())))

    func = ue.blueprint_add_function( bp, "MyFunction" )

    funcEntryNode = func.Nodes[0]
    funcEntryNode.node_create_pin( EEdGraphPinDirection.EGPD_Output, EdGraphPinType( PinCategory="float" ), "value" )

    funcResultNode = func.graph_add_node( K2Node_FunctionResult )
    funcResultNode.node_create_pin( EEdGraphPinDirection.EGPD_Input, EdGraphPinType( PinCategory="int" ), "result" )

    # compile the blueprint
    ue.compile_blueprint(bp)

    # open related editor
    ue.open_editor_for_asset(bp)

When I call `func.graph_add_node( K2Node_FunctionResult )`, it's creating a Return node with duplicated input pins. The pin that I then add onto it is not duplicated.

![bp_function_bad](https://user-images.githubusercontent.com/625512/39196568-573bccee-47da-11e8-913d-752dd3d9264b.PNG)

As soon as I change something on the output variables in the Blueprint Editor, it removes the duplicates. So here I created a new output boolean value:

![bp_function_good](https://user-images.githubusercontent.com/625512/39196683-a79119f6-47da-11e8-9cf3-022f3195cc49.PNG)

If I then go and call `func.graph_add_node( K2Node_FunctionResult )` in Python, it creates a new return node, but with all of the outputs duplicated.

![bp_function_bad2](https://user-images.githubusercontent.com/625512/39196734-bf49c0ac-47da-11e8-81c8-793b587cb902.PNG)

If I don't create the pins at either end, I still get the same thing, just with only the doubled-up exec pins.

Any thoughts on what might be causing this?

Thanks

**Comment by rdeioris** [comment]
Hi, i have fixed the duplicated exec pin, but take into account that K2Node_FunctionResult is a speciale one, as when you instantiate it, it will 'remember' the pins of the previously created return node.

So in your case it will be something like

```python
funcResultNode = func.graph_add_node( K2Node_FunctionResult )
funcResultNode.node_create_pin( EEdGraphPinDirection.EGPD_Input, EdGraphPinType( PinCategory="int" ), "result" )

funcResultNode2 = func.graph_add_node( K2Node_FunctionResult )

funcResultNode3 = func.graph_add_node( K2Node_FunctionResult )

```

so you need to create the pins only for the first one

**Comment by HughMacdonald** [comment]
Awesome - thanks for that.

Regarding the special case of not needing to add the pins every time, I was aware of that uniqueness, but thanks for reminding me.
