### ISSUE TITLE
Override material instance parameters

### ISSUE THREAD

**Issue by jiamingfeng** [20tab/UnrealEnginePython#39]
Is there anyway to do with the current python binding?

I would like to do something like this:

`myMaterialInstance.OverrideScalarParameterDefault("UseThisColor", 1.0, True)`

Cheers,
Eric

**Comment by jiamingfeng** [comment]
As UMaterialInstanceConstant doesn't change parameters at Runtime, I have to wrap the following functions in my own UEPyMaterialInstance.h/.cpp

```
SetScalarParameterValueEditorOnly();
SetVectorParameterValueEditorOnly();
SetTextureParameterValueEditorOnly();
SetParentEditorOnly();
PostEditChange();
```

@rdeioris, what is the contribution policy here? Possible to push my changes to a dev branch?

**Comment by rdeioris** [comment]
Yes, the material interface is not exposed to the reflection system (except for very few cases).

I think a UEPyMaterial.c/.cpp api would be a better naming choise, so we can expose all of the material related features (starting from here: https://docs.unrealengine.com/latest/INT/API/Runtime/Engine/Materials/UMaterialInterface/index.html)

Regarding contribution, simply make a pull request for the master branch (add your credits into the CONTRIBUTORS file)

Regarding 

```
SetParentEditorOnly();
PostEditChange();
```

combine them in a single function as PostEditChange() is mandatory.

**Comment by jiamingfeng** [comment]
Ok, I can call PostEditChange() right after SetParentEditorOnly(). The following functions require to call PostEditChange to populate the changes down the chain as well.

```
SetScalarParameterValueEditorOnly();
SetVectorParameterValueEditorOnly();
SetTextureParameterValueEditorOnly();
```

As you may want to set multiple parameters without triggering post edit change event for performance reason,  PostEditChange() could be exposed separately.

**Comment by rdeioris** [comment]
Ok, at this point i think it is better to expose PostEditChange as a generic UObject method and follow the C++ pattern by calling it manually.

**Comment by jiamingfeng** [comment]
I didn't realized that PostEditChange is UObject method. Good call.

**Comment by rdeioris** [comment]
Remember to make a pull request when your code is usable :) Thanks
