### ISSUE TITLE
Adding a call to a blueprint-defined function from within a blueprint.

### ISSUE THREAD

**Issue by HughMacdonald** [20tab/UnrealEnginePython#390]
Hi again,

Apologies if my questions are getting a little incessant... I'm doing what I can to figure it out before asking, but keep hitting a roadblock..

This time it's to do with adding a blueprint-defined function into elsewhere in that blueprint (in my case, the event graph).

Here's some code that is what I was hoping I'd be able to do. This replicates what I can see when I look at a CallFunction node that has been dropped into the EventGraph by hand, but when I do this I end up with a node with no pins.

    import unreal_engine as ue
    from unreal_engine.classes import BlueprintFactory, K2Node_CallFunction
    from unreal_engine.structs import MemberReference
    import time

    bpFactory = BlueprintFactory()
    bp = bpFactory.factory_create_new('/Game/test' + str(int(time.time())))

    func = ue.blueprint_add_function( bp, "MyFunction" )

    callFuncNode = bp.UberGraphPages[0].graph_add_node( K2Node_CallFunction )
    callFuncNode.FunctionReference = MemberReference( MemberName="MyFunction", bSelfContext=True )

    ue.compile_blueprint(bp)

If you've got any direction for me, I'd appreciate it.

Thanks

**Comment by rdeioris** [comment]
Hi, do not worry, all of your issues are becoming a doc reference :)

Your specific problem is that the node cannot allocate the pins until it knows the signature of the function, so soon after the the FunctionReference assignment just call:

```python
callFuncNode.node_allocate_default_pins()
```

**Comment by HughMacdonald** [comment]
Great - glad to be helping with the docs then ;-)

Thanks - glad to see that I was on the right track then.
