### ISSUE TITLE
Can't override Yes/No to all state when importing fonts

### ISSUE THREAD

**Issue by HughMacdonald** [20tab/UnrealEnginePython#391]
This may be a UE4 issue rather than something in UEP

I'm automating the importing of a number of fonts. I don't want it to create a new Font asset, so want it to reply NoAll to the question it asks.

I did this based on what you're doing in `YourFirstAutomatedPipeline`, but whatever I set `OverwriteYesOrNoToAllState`, it still pops up the dialogue.

    from unreal_engine.classes import FontFileImportFactory

    fontFile = "C:/Windows/Fonts/arial.ttf"

    fontFileFactory = FontFileImportFactory()
    fontFileFactory.OverwriteYesOrNoToAllState = 3 # EAppReturnType::NoAll
    fontFileFactory.factory_import_object(fontFile, "/Game/Fonts" )

Thanks

**Comment by rdeioris** [comment]
Hi, looking at the sources i found that this factory disables the wizard when the AutomatedImportData property is defined:

```python
fontFileFactory.AutomatedImportData = AutomatedAssetImportData()
```

should do the trick

**Comment by HughMacdonald** [comment]
Perfect. Thanks!
