### ISSUE TITLE
Creating a DynamicCast node : missing output pin, or duplicated pins.

### ISSUE THREAD

**Issue by HughMacdonald** [20tab/UnrealEnginePython#395]
This one is potentially a similar one to #387 

Here's the code I'm running:

    import unreal_engine as ue
    from unreal_engine.classes import BlueprintFactory, K2Node_DynamicCast, Actor
    import time

    bpFactory = BlueprintFactory()
    bp = bpFactory.factory_create_new('/Game/test' + str(int(time.time())))

    graph = bp.UberGraphPages[0]

    castNode = graph.graph_add_node( K2Node_DynamicCast, 400, 0 )
    castNode.TargetType = Actor
    # castNode.node_allocate_default_pins()

    ue.compile_blueprint(bp)

    ue.open_editor_for_asset(bp)

If I run it like this, I get no `As Actor` output pin on the node, and the `Object` pin stays as a wildcard.

![castnode_01](https://user-images.githubusercontent.com/625512/39371887-d7b55ab8-4a3a-11e8-86fc-0bde046e3efa.PNG)

If I uncomment the `castNode.node_allocate_default_pins()` line, I get duplicate pins. Also, the `Object` pin remains a wildcard.

![castnode_02](https://user-images.githubusercontent.com/625512/39371899-dd598444-4a3a-11e8-9aac-dee6d74736bc.PNG)

The `Object` pin being a wildcard isn't really an issue as I can use `connect()` to connect a pin in, and it will be assigned a type, but either the lack of an output Actor pin, or the duplicated pins across the whole node is.

I'm going to have a look at the changes you made to the plugin to fix #387, and see if there's something I can do there, and also wanted to flag it here.

**Comment by HughMacdonald** [comment]
I've created a new function called graph_add_node_dynamic_cast in PullRequest #396

**Comment by dengzibiao** [comment]
Creating a DynamicCast node, the targetType is a BluePrint

```
import unreal_engine as ue
from unreal_engine.classes import Object, Blueprint
from unreal_engine.classes import BlueprintFunctionLibraryFactory
from unreal_engine.classes import KismetSystemLibrary, KismetMathLibrary, K2Node_FunctionResult, K2Node_DynamicCast
from unreal_engine.classes import K2Node_Event, K2Node_CallFunction, Actor, AnimInstance
from unreal_engine.classes import TableManager
from unreal_engine.structs import EdGraphPinType
from unreal_engine.enums import EPinContainerType
from unreal_engine.enums import EEdGraphPinDirection

bpTableManager = ue.find_asset('/Game/Blueprint/TableManager_BP.TableManager_BP')
if bpTableManager:
    ue.delete_asset(bpTableManager.get_path_name())

bpTableManager = ue.create_blueprint(TableManager, '/Game/Blueprint/TableManager_BP')

bpfuncgraph = ue.blueprint_add_function(bpTableManager, "GetPayTableItem")

bpFuncEntry = bpfuncgraph.Nodes[0]

bppin = EdGraphPinType(PinCategory = 'int')
bpFuncEntry.node_create_pin(EEdGraphPinDirection.EGPD_Input , bppin, "RowIndex", 1)

GetTableItemNode = bpfuncgraph.graph_add_node_call_function(TableManager.GetTableItem, 200, 0)

# GetTableItemNode.node_find_pin('TableName').default_value = 'pay'

bpFuncEntry.node_find_pin('then').make_link_to(GetTableItemNode.node_find_pin('execute'))

bpFuncEntry.node_find_pin('RowIndex').make_link_to(GetTableItemNode.node_find_pin('RowIndex'))

castNode = K2Node_DynamicCast()
pay_bp = ue.load_object(Blueprint, '/Game/TableMetas/pay_bp.pay_bp')
if pay_bp:
	pay_bp = pay_bp.GeneratedClass
castNode.TargetType = pay_bp
CastTopay_bpNode = bpfuncgraph.graph_add_node(castNode, 600, 0)

GetTableItemNode.node_find_pin('then').make_link_to(CastTopay_bpNode.node_find_pin('execute'))

GetTableItemNode.node_find_pin('ReturnValue').make_link_to(CastTopay_bpNode.node_find_pin('Object'))

# pay_bp_tableNode = bpfuncgraph.graph_add_node(pay_bp.get_cdo().GetTable, 700, 200)

# funcResultNode = bpfuncgraph.graph_add_node(K2Node_FunctionResult, 800, 0)
# pin = EdGraphPinType(PinCategory = 'struct', PinSubCategoryObject = pay)
# funcResultNode.node_create_pin(EEdGraphPinDirection.EGPD_Output, pin, "TableItem", 1)

# CastTopay_bpNode.node_find_pin('then').make_link_to(funcResultNode.node_find_pin('excute'))

# CastTopay_bpNode.node_find_pin('AsPayBp').make_link_to(pay_bp_tableNode.node_find_pin('Target'))

# pay_bp_tableNode.node_find_pin('Table').make_link_to(funcResultNode.node_find_pin('TableItem'))

ue.compile_blueprint(bpTableManager)
bpTableManager.save_package()

```
