### ISSUE TITLE
Add a Function to the graph?

### ISSUE THREAD

**Issue by realtyme** [20tab/UnrealEnginePython#397]
Hello! I have run out of ideas on how to add a function I made to the graph. 

from unreal_engine.classes import K2Node_CallFunction

graph = blueprint.UberGraphPages               # blueprint is the variable to the Blueprint. LOL
node = K2Node_CallFunction("TestFunction") #The Function I made to test! 

graph.graph_add_node(node)

I also tried the "graph_add_node_call_function"
So how do I get the UFunction it needs?
Thanks.

**Comment by HughMacdonald** [comment]
Hi,

Is this a function within the same blueprint as you're trying to call it from?

If so, here's how you do it, where `functionName` is the name of the function you want to call:

    callFunctionNode = graph.graph_add_node( K2Node_CallFunction )
    callFunctionNode.FunctionReference = MemberReference( MemberName=functionName, bSelfContext=True )
    callFunctionNode.node_allocate_default_pins()

Alternatively, you could pre-allocate the node:

    node = K2Node_CallFunction()
    node.FunctionReference = MemberReference( MemberName=functionName, bSelfContext=True )
    callFunctionNode = graph.graph_add_node( node )

**Comment by realtyme** [comment]
Thank you so so so much @HughMacdonald for the info. I did try it out and works. You forgot to menntion the need for : 

from unreal_engine.structs import MemberReference

I had some issues, but I am so loving this, 3 days in and my pipeline is going to be waaaaay waaaay faster now and loving. Thanks @rdeioris 
Double pins if I add the "allocate_pins()" on one sceneario and a crash on the other.
All in all Thanks. 
One more question though, I can read the C++ API, but how would I know it needs a "MemberReference" for the function call. plus I can't get the help to work despite adding some code provided on a previous post to the ue_site.py file

![code_post](https://user-images.githubusercontent.com/38818454/39405405-6480d41c-4b59-11e8-81a3-36cebdcf6db5.JPG)
![proof](https://user-images.githubusercontent.com/38818454/39405406-64bb917e-4b59-11e8-9243-361fc79ae8f9.JPG)

**Comment by HughMacdonald** [comment]
Cool - no worries - happy to help. @rdeioris has been incredibly helpful to me, so I thought I'd pass it on.

It's an awesome tool to have, and I've had a lot of questions for him over the last couple of weeks.

Enjoy!
