### ISSUE TITLE
Suggestion : Alternate search paths in FUnrealEnginePythonModule::RunFile()

### ISSUE THREAD

**Issue by HughMacdonald** [20tab/UnrealEnginePython#398]
Hi,

I've been doing a lot of work with UEP with a script inside my `Content/Scripts` folder. This means that I can easy run `ue.py_exec("myScript.py")`

However, I'm now looking to move the scripts, along with some supporting content, into a content plugin, which is currently in the project, but I'd move to the engine at some point.

As such, I was thinking that it would be good to have the ability to have a number of search paths for scripts if they aren't specified as full paths.

Right now, you're using the config value `Python.RelativeScriptsPath`, `Python.ScriptsPath` or `Project/Content/Scripts`, whichever is the first to exist.

I'm going to suggest changing `ScriptsPath` to an array, which would contain, in order (first one a script is found in is used:

`Project/Content/Scripts`
`Project/` (or `Project/Plugins/`)
`Python.RelativeScriptsPath`
`Python.ScriptsPath`
`Engine/` (or `Engine/Plugins/`)

You'll notice that I'm suggesting pushing `Project/Content/Scripts` higher than `Python.RelativeScriptsPath`. Personally, I think that a project-specific script should override a centrally installed one.

The straight `Project/` and `Engine/` paths would allow for something like:

    ue.py_exec( "Plugins/MyPlugin/Content/Scripts/myPluginScript.py" )

Alternatively, adding `Plugins/` to the end of each of these paths would allow for this to be removed from the start of the file to execute, and would mean that the entire engine or project folder wouldn't be accessible.

What do you reckon on this? I'm happy to look into implementing it myself.

Thanks

**Comment by rdeioris** [comment]
Hi, well i agree, but i suggest:

* .ini overrides
* Project/Content/Scripts
* all_enabled_plugins/Content/Scripts (check https://github.com/20tab/UnrealEnginePython/blob/master/Source/UnrealEnginePython/Private/UEPyEditor.cpp#L875 for getting the list of enabled plugins and https://github.com/20tab/UnrealEnginePython/blob/master/Source/UnrealEnginePython/Private/UEPyIPlugin.cpp#L18 for their content dir)

I would hold the PythonScriptsPath override to allow the user to change the first default search path

**Comment by HughMacdonald** [comment]
Implemented in #404

**Comment by Envenger** [comment]
https://github.com/20tab/UnrealEnginePython/issues/697
Any idea why this is not working?
