### ISSUE TITLE
How would this differ for python 2.7? 

### ISSUE THREAD

**Issue by mrG7** [20tab/UnrealEnginePython#4]

**Comment by rdeioris** [comment]
Not too much, but the ubiquitous usage of unicode in ue4 makes python3 a better choice. I will try to put down something after the gamescom to check for the effort of supporting python 2.7

**Comment by tonybarbieri** [comment]
I have gotten python 2.7 working with some changes (it wasn't bad). The biggest difference is I had a hard time getting the distributed zip file working correctly. I will hopefully be able to push up my changes soon for discussion.

**Comment by rdeioris** [comment]
great, i will wait for it

**Comment by LarsGroh** [comment]
Hi, 
as I don't understand the details of the implementation notes for the 2.7 support - is it save to use 2.7 instead of 3.5 with latest commit?

**Comment by rdeioris** [comment]
still not, we will do the first official merge during the week-end. Currently only python3 is officially supported

**Comment by LarsGroh** [comment]
Thanks for the reply - we will start with 3.5 and eventually switch to 2.7 as soon as the support is up and running as this would give us more compatibility with existing code bases!

**Comment by osstony** [comment]
@LarsGroh please note that you will need to use a python2.7 that has been compiled using Visual Studio 2015. You can find already built binaries here: http://p-nand-q.com/python/building-python-27-with-visual_studio.html

**Comment by rdeioris** [comment]
Python 2 support is now official
