### ISSUE TITLE
Create custom blueprint nodes with python

### ISSUE THREAD

**Issue by HeadClot** [20tab/UnrealEnginePython#402]
Hey Sorry for the newbie question - 

Is it possible to make custom blueprint nodes with UnrealEnginePython?
I know that it is possible to make custom components.

Thank you for your time

**Comment by rdeioris** [comment]
Hi, once you add the python component to a blueprint you will get access to the 'call python method' nodes from which you can call python methods

**Comment by HeadClot** [comment]
Ok thanks :)
