### ISSUE TITLE
Python editor features

### ISSUE THREAD

**Issue by HughMacdonald** [20tab/UnrealEnginePython#403]
Hey,

first off, how much of the functionality of the Python editor is built into UE and how much can be tweaked by UEP?

There are a couple of things that I've found have bugged me when using it. I have no idea if they could be modified in UEP, but I wanted to flag them.

- When on the very last line, pressing DOWN should take you to the end of the line. This means that doing SHIFT+DOWN when at the start of the bottom line would select the whole line, even if there isn't another line below it.
- Periods should not be considered part of a word. Currently double-clicking on a word will expand over all words connected with periods. The same goes for using CTRL+BACKSPACE to delete whole words. I regularly find myself over-deleting!

Now both of these may be built into UE, and you may not have the option to change them (or you may not want to), but I wanted to flag them. They certainly keep causing me the odd small issue.

Thanks

**Comment by rdeioris** [comment]
Unfortunately the Slate api is too limited to build something more advanced (even the latest addition of the zooming is a workaround for slate limits). The best bet is strong integration with vscode, visualstudio, atom, pycharm and friends... #384 could be a huge boost in this direction

**Comment by HughMacdonald** [comment]
Yeah - I thought that might be the case.

I do most of my work in Sublime, but when I'm doing introspection into existing objects, that's when I have to do it in the Python Editor.

Thanks. I'll close this for now then.
