### ISSUE TITLE
Struct not getting assigned

### ISSUE THREAD

**Issue by sinokgr** [20tab/UnrealEnginePython#409]
Hi there,

I have an issue and I'm not sure if I'm doing something wrong. I used to do something similar in the past with structs and it is working fine.
I want to change the Material, in the MaterialSlot value, of an Asset.

As a side note, I use an older version of the plugin, but I don't think it's related to the version.

```py
import unreal_engine as ue
import os

# Looping through all the selected assets
for asset in ue.get_selected_assets():
	# Looping through all the Static Materials
	for i in range(0, len(asset.get_property("StaticMaterials"))):
		StaticMaterialStruct = asset.get_property("StaticMaterials")[i]

		# Get Material
		mat = StaticMaterialStruct.get_field("MaterialInterface")
		# Get Material instance (based on a specific name convention
		path_parts = os.path.splitext(mat.get_path_name())
		mi = ue.get_asset(path_parts[0] + "_Inst" + path_parts[1] + "_Inst")
		
		# And if the Material instance exists,
		if mi is not None:
			# Clone the struct and assign the new material in the MaterialInterface 
			StaticMaterialClone = StaticMaterialStruct.clone()
			StaticMaterialClone.set_field("MaterialInterface", mi)
			
			# Finally, assign the new cloned struct
			asset.get_property("StaticMaterials")[i] = StaticMaterialClone
```

**Comment by sinokgr** [comment]
Many thanks for the reply @HughMacdonald.
I'm afraid the set_property function only gets two arguments.
I tried the second option which it was a great idea and it looks like it worked great!
Cheers,
Nick

**Comment by HughMacdonald** [comment]
Ahh - that would explain it then!

I hit an issue with fixed array properties myself a few days ago, and @rdeioris pointed me at setting them using the index. If you're using an old version, that would explain why you can't.
