### ISSUE TITLE
Add FARFilter Support

### ISSUE THREAD

**Issue by osstony** [20tab/UnrealEnginePython#41]
@rdeioris I am currently adding support for getting assets by using a FARFilter. I am creating a new PyFARFilter object to use and was wondering if you have any recommendations on how to handle the TArray, TSet and TMultiMap properties. Is there anything already setup in the existing code base for wrapping an object like this?

More information about FARFilter here:

https://docs.unrealengine.com/latest/INT/API/Runtime/AssetRegistry/FARFilter/index.html

**Comment by osstony** [comment]
My initial instinct is to use python types for the containers and push their contents to the filter properties when necessary.

**Comment by rdeioris** [comment]
I think you can check UEPyVector on how to add new types with properties and methods. For TArray use lists, TSet and TMultiMap should map easily to dictionaries

**Comment by osstony** [comment]
That's the approach I took and it seems to be working well. We may want to use a defaultdict(set) for the TMultiMap to better mimic the functionality of the Unreal type.

**Comment by osstony** [comment]
I did end up going with a defaultdict(set) to better emulate TMultiMap.

**Comment by rdeioris** [comment]
Added a couple of comments. I Think it is better to move the assets management sections from here https://github.com/20tab/UnrealEnginePython/blob/master/docs/PythonConsole.md to a dedicated doc files including the farfilter api.

**Comment by rdeioris** [comment]
...and add your credits to the CONTRIBUTORS file :)

**Comment by osstony** [comment]
This has been merged, closing for now
