### ISSUE TITLE
Build Errors using master branch with UE 4.19.2 on Ubuntu

### ISSUE THREAD

**Issue by slartibaartfast** [20tab/UnrealEnginePython#412]
On an Ubuntu 17.10 machine with clang 4.0.1, libc++ standard libary I'm seeing a few errors when compiling using either the editor or the unreal build tool.  All of the errors are error: ISO C++11 does not allow conversion from string literal to 'char *' [-Werror,-Wwritable-strings]

>   /.../UnrealProjects/PyMuws/Plugins/UnrealEnginePython/Source/UnrealEnginePython/Private/UEPyModule.cpp:1555:30: error: ISO C++11 does not allow conversion from string literal to 'char *' [-Werror,-Wwritable-strings]
          ue_py_register_magic_module("unreal_engine.classes", py_ue_new_uclassesimporter);
                                      ^
  /.../UnrealProjects/PyMuws/Plugins/UnrealEnginePython/Source/UnrealEnginePython/Private/UEPyModule.cpp:1556:30: error: ISO C++11 does not allow conversion from string literal to 'char *' [-Werror,-Wwritable-strings]
          ue_py_register_magic_module("unreal_engine.enums", py_ue_new_enumsimporter);
                                      ^
  /.../UnrealProjects/PyMuws/Plugins/UnrealEnginePython/Source/UnrealEnginePython/Private/UEPyModule.cpp:1557:30: error: ISO C++11 does not allow conversion from string literal to 'char *' [-Werror,-Wwritable-strings]
          ue_py_register_magic_module("unreal_engine.structs", py_ue_new_ustructsimporter);
                                      ^

Another block...

>   /.../UnrealProjects/PyMuws/Plugins/UnrealEnginePython/Source/UnrealEnginePython/Private/Wrappers/UEPyFSlowTask.cpp:77:15: error: ISO C++11 does not allow conversion from string literal to 'char *' [-Werror,-Wwritable-strings]
          char *text = "";
                       ^
  /.../UnrealProjects/PyMuws/Plugins/UnrealEnginePython/Source/UnrealEnginePython/Private/Wrappers/UEPyFSlowTask.cpp:156:26: error: ISO C++11 does not allow conversion from string literal to 'char *' [-Werror,-Wwritable-strings]
          char *default_message = "";

And also this...

>   In file included from /.../UnrealProjects/PyMuws/Plugins/UnrealEnginePython/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/PythonAutomation/Module.PythonAutomation.cpp:2:
  /.../UnrealProjects/PyMuws/Plugins/UnrealEnginePython/Source/PythonAutomation/Private/PythonAutomationModule.cpp:12:57: error: ISO C++11 does not allow conversion from string literal to 'char *' [-Werror,-Wwritable-strings]
          PyObject *py_automation_module = ue_py_register_module("unreal_engine.automation");

**Comment by rdeioris** [comment]
Hi, just add 

```c
(char *)
```

in front of any static string:

```c
ue_py_register_magic_module((char *)"unreal_engine.enums", py_ue_new_enumsimporter);
```

Feel free to make a pull request ;)

**Comment by slartibaartfast** [comment]
Thanks for the example.  Even I should be able to handle that :)

I'll submit a pull request when I'm back on it tomorrow.

**Comment by slartibaartfast** [comment]
Closing as pull request #413 has been merged
