### ISSUE TITLE
Error while get TransformTrack keys in sequencer

### ISSUE THREAD

**Issue by 5775486f** [20tab/UnrealEnginePython#415]
I want get all transform keys from all actors in level sequencer
But the Translation,Rotation,Scale keys seems wrong
the value that i get only include x axis,missing y and z 
```
import unreal_engine as ue
from unreal_engine.classes import MovieScene3DTransformTrack

selSeq = ue.get_selected_assets()[0]
rootFolder = selSeq.MovieScene.RootFolders
binding = selSeq.MovieScene.ObjectBindings

for thisBind in binding:
    tracks = thisBind.Tracks
    for track in tracks:
        if track.get_class() == MovieScene3DTransformTrack:
            transSec = track.Sections
            for thisSec in transSec:
                pos = thisSec.Translation
                rot = thisSec.Rotation
                scal = thisSec.Scale
                keys = pos.Keys
                for key in keys:
                    print key.as_dict()
```

**Comment by rdeioris** [comment]
Hi, Rich Curves are aligned as c arrays, so you need to get the Translation field by index:

```python
xCurves = thisSec.get_property('Translation', 0);
yCurves = thisSec.get_property('Translation', 1);
zCurves = thisSec.get_property('Translation', 2);
```

More infos here:

https://github.com/20tab/UnrealEnginePython/blob/master/examples/curve_generator.py

**Comment by 5775486f** [comment]
Hi，I have test in this way ，but I got different returns in different projects:

one of them got follow:

get_property() takes exactly 1 argument (2 given)
Traceback (most recent call last):
  File "<string>", line 18, in <module>
TypeError: get_property() takes exactly 1 argument (2 given)

they other runs ok

I just test put an empty actor in a level sequencer add a transform track got different returns

**Comment by 5775486f** [comment]
ok,that is a version probblem thx!
