### ISSUE TITLE
Incorporating UEP with AirSim

### ISSUE THREAD

**Issue by luis-bernard** [20tab/UnrealEnginePython#421]
Hey!

I'm trying to create a project with both UEP and Airsim plugins running. 
(I am running UE4 - 4.18.3 on Windows 10, with python 3.6)

I've managed to create a project and install only UEP or Airsim but when I try to put both plugins I get compiling errors:

- If I install the python plugin first, when I reach the following step of the AirSim installation - _"4.From the File menu select New C++ class, leave default None on the type of class, click Next, leave default name MyClass, and click Create Class. We need to do this because Unreal requires at least one source file in project. It should trigger compile and open up Visual Studio solution LandscapeMountains.sln.)"_ - I get the following error:

![1](https://user-images.githubusercontent.com/36504173/40577521-f461980e-60fe-11e8-9e3f-fe1862514b19.png)

- If I install the AirSim first, when I try to compile the project file in Visual Studio I get the following error:

"1>EXEC : error : Could not find definition for module 'UnrealEnginePython' (referenced via default plugins -> UnrealEnginePython.uplugin)"

Any ideas? I'll be very thankful :)

**Comment by luis-bernard** [comment]
@rdeioris I used the binary release. I also tried using the source one but I couldn't make it work (when I tried compiling it in Visual Studio I got build errors). 

(I intend to run the code in a conda environment. I have my python installation there but I also have it installed through visual studio if I'm not mistaken. Can the problem be something around this?)

**Comment by luis-bernard** [comment]
I tried everything again and I always get some sort of error. Focusing on installing through source, these were my steps:

1 - Created a C++ project. After it was created I closed everything
2 - Created the Plugins directory in the project directory
3 - I cloned the repository in: https://github.com/20tab/UnrealEnginePython, directly to the Plugins' folder
4 - Right clicked on the project main file and chose 'generate visual studio project files'
5 - Opened visual studio, (I can see the Plugins/UnrealEnginePython folder in the solution explorer)
6 - I run the compilation from visual studio by clicking on "build solution"

I get this errors:

1>------ Build started: Project: UE4, Configuration: BuiltWithUnrealBuildTool Win32 ------
2>------ Build started: Project: CPPSource, Configuration: Development_Editor x64 ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.props(31,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Makefile.props" cannot be imported again. It was already imported at "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.cpp.props (31,3)". This is most likely a build authoring error. This subsequent import will be ignored. [E:\Documents\Unreal Projects\CPPSource\Intermediate\ProjectFiles\UE4.vcxproj]
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.props(31,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Makefile.props" cannot be imported again. It was already imported at "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.cpp.props (31,3)". This is most likely a build authoring error. This subsequent import will be ignored. [E:\Documents\Unreal Projects\CPPSource\Intermediate\ProjectFiles\CPPSource.vcxproj]
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.props(31,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Makefile.props" cannot be imported again. It was already imported at "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.cpp.props (31,3)". This is most likely a build authoring error. This subsequent import will be ignored. [E:\Documents\Unreal Projects\CPPSource\Intermediate\ProjectFiles\UE4.vcxproj]
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.props(31,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Makefile.props" cannot be imported again. It was already imported at "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.cpp.props (31,3)". This is most likely a build authoring error. This subsequent import will be ignored. [E:\Documents\Unreal Projects\CPPSource\Intermediate\ProjectFiles\CPPSource.vcxproj]
2>Creating makefile for CPPSourceEditor (no existing makefile)
2>Using Python at: C:/Program Files/Python36
2>Parsing headers for CPPSourceEditor
2>  Running UnrealHeaderTool "E:\Documents\Unreal Projects\CPPSource\CPPSource.uproject" "E:\Documents\Unreal Projects\CPPSource\Intermediate\Build\Win64\CPPSourceEditor\Development\CPPSourceEditor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -installed
2>Reflection code generated for CPPSourceEditor in 7,1627577 seconds
2>Performing 7 actions (4 in parallel)
2>UEPyEditor.cpp
2>UnrealEnginePython.cpp
2>C:\Program Files\UE_4.18\Engine\Source\Runtime\Core\Public\Logging/LogMacros.h(34): error C2440: 'initializing': cannot convert from 'void *' to 'char *'
2>C:\Program Files\UE_4.18\Engine\Source\Runtime\Core\Public\Logging/LogMacros.h(34): note: Conversion from 'void*' to pointer to non-'void' requires an explicit cast
2>E:\Documents\Unreal Projects\CPPSource\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UnrealEnginePython.cpp(594): note: see reference to function template instantiation 'void FMsg::Logf_Internal<char*>(const ANSICHAR *,int32,const FName &,ELogVerbosity::Type,const TCHAR *,T1)' being compiled
2>        with
2>        [
2>            T1=char *
2>        ]
2>E:\Documents\Unreal Projects\CPPSource\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyEditor.cpp(637): error C2171: '!': illegal on operands of type 'void'
2>E:\Documents\Unreal Projects\CPPSource\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyEditor.cpp(637): error C2451: conditional expression of type 'void' is illegal
2>E:\Documents\Unreal Projects\CPPSource\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyEditor.cpp(637): note: Expressions of type void cannot be converted to other types
2>ERROR : UBT error : Failed to produce item: E:\Documents\Unreal Projects\CPPSource\Plugins\UnrealEnginePython\Intermediate\Build\Win64\UE4Editor\Development\UE4Editor-UnrealEnginePython.lib
2>Total build time: 29,52 seconds (Local executor: 0,00 seconds)
2>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.MakeFile.Targets(41,5): error MSB3075: The command ""C:\Program Files\UE_4.18\Engine\Build\BatchFiles\Build.bat" CPPSourceEditor Win64 Development "E:\Documents\Unreal Projects\CPPSource\CPPSource.uproject" -waitmutex" exited with code 5. Please verify that you have sufficient rights to run this command.
2>Done building project "CPPSource.vcxproj" -- FAILED.
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========


![imagem1](https://user-images.githubusercontent.com/36504173/40673886-139e10c6-636b-11e8-988a-ba76f7db52dd.png)

**Comment by rdsgautier** [comment]
Hello,
if (!AssetToolsModule.Get().RenameAssets(AssetsAndNames)) is a line i introduced lately in UnrealPythonPlugin, but i used Unreal 4.19 and not 4.18. The boolean return value for RenameAssets function has been introduced only in 4.19 version.
The condition should not be tested in version prior than 4.19.
