### ISSUE TITLE
material instance issue in ue4.19

### ISSUE THREAD

**Issue by samsky2017** [20tab/UnrealEnginePython#428]
hi!

when i using unrealPythonAPI create a **material instance** in **ue4.19**, after the material instance created,
when the material instance is opened and modified again(change value by manual, not API ), and then saved, the material uasset will be lost and become a 1kb invalidation file. At the same time, the shader(material instance) in the UE Editor( Content Browser ) will disappear (although the asset using the material will look fine at the time, reopening the project file will turn the asset gray -->  uasset of material-instance "lost"). 

tested both in py27 and py36 version. found same issue.

There is no such phenomenon in **UE418**.

**Comment by samsky2017** [comment]
here is the code

import unreal_engine as ue
from unreal_engine.classes import Material,MaterialInstanceConstant

parent_material = ue.load_object(Material,'/Game/Materials/M_base')
mat_inst_object = MaterialInstanceConstant()
mat_ball_name = 'M_test2'
mat_inst_object.set_name(mat_ball_name)
mat_inst_object.set_material_parent(parent_material)
save_path = '/Game/Materials2/MI_test2'
mat_inst_object.save_package(save_path)

run the codes, we got a material-instance at content browser.
![mi_issue_01](https://user-images.githubusercontent.com/29967173/40828640-c0f821ae-65b3-11e8-9cc8-49738fdabdfe.jpg)

change the value
![mi_issue_02](https://user-images.githubusercontent.com/29967173/40828809-36a4b17e-65b4-11e8-85df-0d5882d91d1b.jpg)

save it
![mi_issue_03](https://user-images.githubusercontent.com/29967173/40828983-bcbd21f6-65b4-11e8-9c8d-4d44b58d572d.jpg)

now the material-instance disappeared...
![mi_issue_04](https://user-images.githubusercontent.com/29967173/40829245-746bb380-65b5-11e8-8ffd-f9e6ab1dcff2.jpg)

**Comment by samsky2017** [comment]
PS:
in Content Browser, When you change to another folder (eg Geometry) and then switch back to the Materials2 folder, you will find that the material is still there (again). It seems no problem at present. But when you close the current project and reopen it, the texture ball really disappears.

**Comment by samsky2017** [comment]
PS:
in Content Browser, When you change to another folder (eg Geometry) and then switch back to the Materials2 folder, you will find that the material is still there (again). It seems OK at present. But when you close the current project and reopen it, the material-instance asset really disappears.

**Comment by rdeioris** [comment]
Hi, i strongly suggest you to use factories for creating assets:

```python
import unreal_engine as ue
from unreal_engine.classes import Material, MaterialInstanceConstantFactoryNew

parent_material = ue.load_object(Material,'/Game/Materials/M_base')
factory = MaterialInstanceConstantFactoryNew()
factory.InitialParent = parent_material


mat_inst_object = factory.factory_create_new('/Game/Materials2/MI_test3')
mat_inst_object.save_package()
```

**Comment by samsky2017** [comment]
that's works(use MaterialInstanceConstantFactoryNew). thank you very much ;-)
