### ISSUE TITLE
SetMaterialByName not available

### ISSUE THREAD

**Issue by knekke** [20tab/UnrealEnginePython#429]
Hi,

I'm just starting using UnrealEnginePython by scripting a custom asset importer. I think I would really need [SetMaterialByName](https://api.unrealengine.com/INT/API/Runtime/Engine/Components/UMeshComponent/SetMaterialByName/index.html) for this to work. Or is there a way to read the slotname somehow?

**Comment by rdeioris** [comment]
Hi, you can access the material slots like shown here:

https://github.com/20tab/UnrealEnginePython/blob/master/tutorials/SnippetsForStaticAndSkeletalMeshes.md#skeletalmesh-sections

or (for static meshes):

```python
static_mesh.StaticMaterials = [StaticMaterial(MaterialInterface=your_material, MaterialSlotName='Main')]
```

So you can simply iterate both arrays and search for a specific SlotName.

Btw set_material_by_name() seems a handy  shortcut, i will add it tomorrow to the api.

Thanks

**Comment by rdeioris** [comment]
HI, set_material_by_name(slot_name, material) has been added to the api.

**Comment by knekke** [comment]
Hi, big thanks for adding it to the api. You don't have nightly builds somewhere by any chance?
As for iterating, in all the examples the slot index is used or you are stiing a name, but I  can't figure out how to read a slot name. E.g:  How would I get the slot name for index 2? 
Thx!

**Comment by knekke** [comment]
Nevermind...installing from source works totally fine. THX!
