### ISSUE TITLE
IHttpRequest Not work 

### ISSUE THREAD

**Issue by Eric900614** [20tab/UnrealEnginePython#430]
I use IHttpRequest Module(from unreal_engine import IHttpReqest) in my project. However, i cannot receive the response now. 

Following is my test code.

`import unreal_engine as ue 
import json
from unreal_engine import IHttpRequest

class testHttp:
    def initialize_component(self):
        ue.log("----init")
        pass
    
    def test(self):
        url="http://10.1.99.152:8001/api/UEConfig/GetAllUEConfig"
        runCode(url,self.response_received)

    def response_received(self,request,response,success):
        ue.log("ssssssssss")

def request_progress():
    ue.log("ccccccccccccccccccccccccccccccc")

def runCode(url,callback):
    ue.log('sssend')
    request = IHttpRequest('GET',url)

    request.bind_on_request_progress(request_progress)
    request.bind_on_process_request_complete(callback)
    request.process_request()
    `

**Comment by bianchengxiaosheng** [comment]
flow 1 floor +1,hope  give the answer quickly

**Comment by rdeioris** [comment]
the bug has already been fixed in master. new binary releases are coming

**Comment by rdeioris** [comment]
Hi, can we close the issue ?
