### ISSUE TITLE
No Scripts Folder in 4.19 Package

### ISSUE THREAD

**Issue by Henelik** [20tab/UnrealEnginePython#433]
I'm using UE 4.19 with the source version of UnrealEnginePython and Python 3.6 (64 bit).  I also have a blank ue_site.py in my Content/Scripts/ folder.

Python scripts run perfectly within the editor.  However, when I package the project, there is no Scripts folder in the built version, and all of the game logic that was in Python doesn't execute.

Did I miss a step?  Do I have to copy the Scripts folder manually?  Any help would be appreciated, I'm totally lost at this point.

**Comment by rdeioris** [comment]
Hi, yes you need to manually copy the Scripts directory in Content/. Technically you can place scripts in any sys.path directory but ue_site.py is searched there
