### ISSUE TITLE
Msgpackrpc error while using Airsim with the UEP plugin

### ISSUE THREAD

**Issue by luis-bernard** [20tab/UnrealEnginePython#434]
Hey there!

I'm using UE 4.18 on Windows 10, and I'm trying to implement the AirSim plugin and running it in a Python Component.

I'm getting the following error:
WARNING:tornado.general:Connect error on fd 6248: WSAECONNREFUSED
WARNING:tornado.general:Connect error on fd 6248: WSAECONNREFUSED
WARNING:tornado.general:Connect error on fd 6248: WSAECONNREFUSED
WARNING:tornado.general:Connect error on fd 6248: WSAECONNREFUSED
WARNING:tornado.general:Connect error on fd 6248: WSAECONNREFUSED
Retry connection over the limit
Traceback (most recent call last):
  File "E:\Documents\Unreal Projects\PythonTrain\Content\Scripts\comm2.py", line 189, in begin_play
    self.client.confirmConnection()
  File "E:\Documents\Unreal Projects\PythonTrain\Content\Scripts\AirSimClient.py", line 445, in confirmConnection
    home = self.getHomeGeoPoint()
  File "E:\Documents\Unreal Projects\PythonTrain\Content\Scripts\AirSimClient.py", line 454, in getHomeGeoPoint
    return GeoPoint.from_msgpack(self.client.call('getHomeGeoPoint'))
  File "E:\Documents\Unreal Projects\PythonTrain\Plugins\UnrealEnginePython\Binaries\Win64\Lib\site-packages\msgpackrpc\session.py", line 41, in call
    return self.send_request(method, args).get()
  File "E:\Documents\Unreal Projects\PythonTrain\Plugins\UnrealEnginePython\Binaries\Win64\Lib\site-packages\msgpackrpc\future.py", line 43, in get
    raise self._error
msgpackrpc.error.TransportError: Retry connection over the limit 

When I run the same functions "outside" the UEP plugin it runs without a problem.

**Comment by rdeioris** [comment]
Hi, can you post example code ? btw the error reports "connection refused", could it be some firewall blocking ?

In addition to this is trongly suggest you to rely on python3 asyncio:

https://github.com/20tab/UnrealEnginePython/blob/master/tutorials/AsyncIOAndUnrealEngine.md

https://github.com/chuchiy/aiorpc

**Comment by luis-bernard** [comment]
I tried turning off the firewall but didn't achieve any better results. I added the asyncio but I am not sure where you wanted me to use it @rdeioris.

Example code:

    import unreal_engine as ue
    from AirSimClient import *

    ue.log('Testing Arisim')

    class myServer:
    def begin_play(self):
        # get a reference to the owing pawn (a character)
        self.pawn = self.uobject.get_owner()

        client = MultirotorClient()
        client.confirmConnection() #This here

The MultirotorClient and confirmConnection functions are on the next link, lines 445 and 454:
https://github.com/Microsoft/AirSim/blob/master/PythonClient/AirSimClient.py

**Comment by rdeioris** [comment]
Hi, mi doubt is that msgpack-rpc-python uses tornado, so without a tornado loop you will not be able to work with sockets/fd.

http://www.tornadoweb.org/en/stable/ioloop.html

In python3 the tornado ioloop maps to asyncio, so probably it will be enough to initialize it like described here:

https://github.com/20tab/UnrealEnginePython/blob/master/tutorials/AsyncIOAndUnrealEngine.md#adding-an-asyncio-loop-engine-in-the-ue4-core

**Comment by luis-bernard** [comment]
Hey. Sorry for taking so much to answer/close the issue. I kinda solved the problem!

If I launch AirSim in the tick function, I don't get the error. 
Code:

```
import unreal_engine as ue
from AirSimClient import *

ue.log('Testing Airsim')

class myServer:
    def begin_play(self):
        self.pawn = self.uobject.get_owner()
    def tick(self,delta_time):
        client = MultirotorClient()
        client.confirmConnection() #This here
```

I guess the world was not fully initialized or something?

Thank you for the attention :) and sorry for wasting your time!
