### ISSUE TITLE
Adding a Toolbar Extension

### ISSUE THREAD

**Issue by HughMacdonald** [20tab/UnrealEnginePython#435]
Hi,

I had a bit of a look into this a while ago, but was hoping you might have more thoughts on this.

Do you know what the best way to (if it is even possible) add a toolbar extension using UEP? Ideally, I'd like to be able to define the extension using Python (maybe in `ue_site.py`) and then have it call a Python function when I click it.

I started looking at what C++ code would be needed to do this, but it got to the point where other projects were taking over more of my time, and I was also feeling like there might be a bit too much in the way of compiled C++ code to be able to do this dynamically.

Thanks

**Comment by rdeioris** [comment]
Hi, you can get an example of extenders (included toolbar) here:

https://github.com/20tab/UnrealEnginePython/blob/master/examples/extenders_example.py

**Comment by HughMacdonald** [comment]
Thanks. I have no idea how I missed that a while back!
