### ISSUE TITLE
Spawn a Blueprint Script

### ISSUE THREAD

**Issue by Schizo** [20tab/UnrealEnginePython#437]
I have a `Blueprint` Type that I would like to spawn, how do I do that? That's how Actors are spawned

    import unreal_engine as ue
    from unreal_engine.classes import StaticMesh, StaticMeshActor
    cone2 = world.actor_spawn(StaticMeshActor)

How would I spawn a Blueprint that is in `Game/Assets/MyBlueprint` ?

**Comment by rdeioris** [comment]
Hi, you can load a Blueprint as a normal uobject:

```python
bp = ue.load_object(Blueprint, '/Game/Assets/MyBlueprint')
```

**Comment by Schizo** [comment]
That will just reference the object, but how do I add it to the scene? I've tried 

import unreal_engine as ue
	from unreal_engine.classes import Blueprint
	world = ue.get_editor_world()
	pickable = ue.load_object(Blueprint, '/Game/VirtualRealityBP/Blueprints/BP_PickupCube.BP_PickupCube')
	world.actor_spawn(pickable)

But that errors with:

```
LogPython: Error: argument is not a UClass
LogPython: Error: Traceback (most recent call last):
LogPython: Error:   File "<string>", line 1, in <module>
LogPython: Error:   File "<string>", line 5, in <module>
LogPython: Error: Exception: argument is not a UClass
```

**Comment by rdeioris** [comment]
pickable.GeneratedClass contains the related Class

**Comment by Schizo** [comment]
Perfect that worked!
