### ISSUE TITLE
please provide binary release of UE 4.16, python 3.6 for MAC

### ISSUE THREAD

**Issue by TCforgood** [20tab/UnrealEnginePython#438]
For some reason I have to use UE 4.16. I tried the 4.18 version binary but unfortunately it doesn't work (as expected).

**Comment by rdeioris** [comment]
Hi, have you tried building it from sources ? (btw updated releases should be available in the next few days)

**Comment by TCforgood** [comment]
Thanks @rafleze . I built from source and it's working now.
