### ISSUE TITLE
Creating Collision Setup in Bulk

### ISSUE THREAD

**Issue by Schizo** [20tab/UnrealEnginePython#439]
I'm trying to automate  the process  of generating collision setups. Basically I'm talking about selecting a `static Mesh` and accessing the function `Collision >  Add Box Simplified Collision`. 

Unfortunately  #91 didn't help in my case, even though I'm still not sure what **"Collision Complexity"** exactly does behind the scenes in Unreal.

**Comment by rdeioris** [comment]
Hi, collisions are part of the BodySetup property. In this UObject you can work on the AggGeom structure (https://api.unrealengine.com/INT/API/Runtime/Engine/PhysicsEngine/FKAggregateGeom/index.html) where each element is an array of collisions of the specified type.

**Comment by Schizo** [comment]
Hi @rdeioris  are you saying that I can walk my way through the python `UObject`, or would this need to be exposed from `cpp` to `python` ?

**Comment by Schizo** [comment]
I'm not sure if I got it right, but we are trying to set these `fields` :

![collisiongeo2](https://user-images.githubusercontent.com/38006/41642865-7032e406-741e-11e8-858b-3746b84a8f85.PNG)




**Code:**
```python
import unreal_engine as ue
from unreal_engine.classes import StaticMesh, StaticMeshComponent

actors = ue.editor_get_selected_actors()
staticMesh = actors[0].get_component_by_type(StaticMeshComponent)
aggregateGeom = staticMesh.StaticMesh.BodySetup.AggGeom
struct = aggregateGeom.get_struct()
print(aggregateGeom.as_dict())
#LogPython: {'SphereElems': [], 'BoxElems': [], 'SphylElems': [], 'ConvexElems': []}
print(aggregateGeom.set_field("ConvexElems"))
#LogPython:[]
```

So even though I set those from The UI on my `mesh`, those fields return empty and I'm not sure how i would set either a `BoxElems` or `ConvexElems` variable.

**Comment by rdeioris** [comment]
Hi, i have executed your same script and i had a consistent setup. 

Can you double check you are checking the right static mesh ?

Try selecting a static mesh in the content browser and running this:

```python
import unreal_engine as ue

asset = ue.get_selected_assets()[0]
geom = asset.BodySetup.AggGeom

print(geom.as_dict())
```

**Comment by Schizo** [comment]
@rdeioris for some reason it works now o_O. So, would it be possible to call 'Add 26DOP Simplified Collision'. I didn't see any callable methods. 

![door26dop](https://user-images.githubusercontent.com/38006/41733771-c9aa5cd2-7539-11e8-91e0-a7cda7326c21.png)

Basically I would wan't to run the 26 DOP setup.

**Comment by rdeioris** [comment]
Hi, pull the latest code, kdop related functions have been added:

https://github.com/20tab/UnrealEnginePython/blob/master/examples/kdop.py
