### ISSUE TITLE
PyUnicode_Check Does Not Cover Python2.7

### ISSUE THREAD

**Issue by osstony** [20tab/UnrealEnginePython#44]
PyUnicode_Check will not catch cases where strings are used in python 2.7. An example of the issue can be seen here: 

https://github.com/20tab/UnrealEnginePython/blob/master/Source/UnrealEnginePython/Private/UEPyModule.cpp#L449

PyUnicode_Check will always be false due to python 2.7 passing in strings. PyString_Check which is only available in Python < 3 will also need to be used in these cases.

**Comment by osstony** [comment]
Should we create a function which does a Unicode and in the case of python 2.7 check as well as a function to convert from either a unicode or again int he case of python 2.7 a string? There are many places where PyUnicode_Check and PyUnicode_AsUTF8 are being invoked. Adding in PyString checks with #if statements could get messy.

**Comment by rdeioris** [comment]
I Think you can improve this:

https://github.com/20tab/UnrealEnginePython/blob/master/Source/UnrealEnginePython/Private/UnrealEnginePython.cpp#L12


to support strings with PyString_Check()

**Comment by osstony** [comment]
Should we add a generic check function along side this? This function will perform the convert but we are doing many checks for Unicode as well.

**Comment by rdeioris** [comment]
Can we close it ?

**Comment by osstony** [comment]
All seems well with the patch, thanks!
