### ISSUE TITLE
Importing FBX via PyCommandline not generating skeletons

### ISSUE THREAD

**Issue by cgBartosz** [20tab/UnrealEnginePython#440]
I am importing skeletal assets via pyCommandline and Editor is not generating Skeletons the same way it does when right click in Content Browser -> New Asset -> Import To.

Is there any setting I can switch to have this behavior enabled or is it something I have to implement myself ? 

Thank you.

**Comment by rdeioris** [comment]
Hi, do you have example code to reproduce the issue ? To which skeleton the imported mesh is assigned ?

**Comment by cgBartosz** [comment]
I expected fbx importer to import skeleton and attach it to the mesh automatically, same way it does it when triggered from the UI.

**Comment by cgBartosz** [comment]
Worth mentioning, the code is trying to load multiple assets one by one...

**Comment by cgBartosz** [comment]
Also, in this ticket: https://github.com/20tab/UnrealEnginePython/issues/441 I am describing another scenario of running exactly the same code and having editor die every single time but not from exemplary QT dialog (which is very simplistic). Looks like some kind of data race to me although I am not sure.

**Comment by cgBartosz** [comment]
Can you reproduce this behavior on your end ?

**Comment by rdeioris** [comment]
Hi, could it be you are not saving the package in your commandlet ?

```python
import os.path
from unreal_engine.classes import PyFbxFactory
import unreal_engine as ue

ue.log('IMPORTING...')

# instantiate a new factory
fbx_factory = PyFbxFactory()

# build the path for the fbx file
kaiju_assets_dir = os.path.join(os.path.expanduser('~/Desktop'), 'Kaiju_Assets/Slicer')

slicer_fbx = os.path.join(kaiju_assets_dir, 'slicer.fbx')

# configure the factory
fbx_factory.ImportUI.bCreatePhysicsAsset = False
fbx_factory.ImportUI.bImportMaterials = False
fbx_factory.ImportUI.bImportTextures = False
fbx_factory.ImportUI.bImportAnimations = False
fbx_factory.ImportUI.bConvertScene = True
# scale the mesh (the Kaiju is 30 meters high !)
fbx_factory.ImportUI.SkeletalMeshImportData.ImportUniformScale = 0.1;

# import the mesh
slicer_mesh = fbx_factory.factory_import_object(slicer_fbx, '/Game/DumbKaiju/Slicer')

# save the .uasset files
slicer_mesh.save_package()
slicer_mesh.Skeleton.save_package()

ue.log('IMPORTED')
```

**Comment by cgBartosz** [comment]
That is possible, let me check...

**Comment by cgBartosz** [comment]
Yes, explicit save on the skeleton does help. How do I know how many other packages factory imported given one return value ? Is this something to consider for other factories as well ? Are many factories import packages they do not directly return ?

**Comment by rdeioris** [comment]
Well, afaik there is no way to programmaticaly know what UObject's a factory generates (unless the main [returned] one). Maybe saving all the dirty assets is the best approach ?
