### ISSUE TITLE
Possible to chain commandlets?

### ISSUE THREAD

**Issue by Schizo** [20tab/UnrealEnginePython#444]
This is a more `Unreal` question but I thought, that we eventually could leverage other `commandlets` with `PyCommandlet`. Before going into details, I [couldn't find any information if Unreal supports multiple commandlets](https://answers.unrealengine.com/questions/672190/is-it-possible-to-run-multiple-commandlets-from-on.html). 

This is a simple example that was provided in one of the threads, that' I've modified. 

**runner:**
```python
import subprocess

ue_editor = "E:/Program Files/Epic Games/UE_4.19/Engine/Binaries/Win64/UE4Editor-Cmd.exe"
project = "D:/projects/testExample.uproject"
command = "D:/Projects/test/job.py"
process = subprocess.Popen('{0} {1} -run=PyCommandlet {2}'.format(ue_editor, project, command))
```

**job.py:**
```python
import unreal_engine as ue
open("E:/test7.txt", 'w').write(str(material))
```

I was excited as I thought, that we could add `ue.editor_command_build_lighting()` in `job.py` to actually force a render. However this seems to be skipped as not all modules are loaded. 

Just for completeness, I'm adding the actual **commandlet** that is used to do lightbuilds:

````python
    process = subprocess.Popen('{0} {1}  -run=resavepackages -buildlighting -allowcommandletrendering'.format(ue_editor, project, command))
````

**Comment by rdeioris** [comment]
Hi, you need to add -allowcommandletrendering to the pycommandlet command line too (this will setup RHI). Regarding multiple commandlets, i think there is no need for it. Just create an additional py script that calls the commandlets in chain
