### ISSUE TITLE
Automatically sourcing files on startup

### ISSUE THREAD

**Issue by HughMacdonald** [20tab/UnrealEnginePython#450]
Hi,

I'm not sure if I'm doing something wrong here, or if something has changed recently that makes this not work.

I have a Python class which extends Actor which I want to use purely as a function library.

It looks something like this:

    import unreal_engine as ue
    from unreal_engine.classes import Actor
    
    class MyFunctionsClass(Actor):
    
        def MyStaticFunction(arg: int):
            ue.print_string('arg {}'.format(arg))
    
        MyStaticFunction.static = True`

Now, if I have this file (called `functions.py`) in my `/Game/Scripts` folder, and from inside UE4, I run `import functions`, then all is fine.

However, if I have a `ue_site.py` which is also in `/Game/Scripts` containing `import functions`, then I get a crash on launch.

The crash report is as follows:

    LoginId:c171dd5f44df65bcdd756d9797e69d31
    EpicAccountId:da0a8e0752334a16a2539e65dffe0883

    Access violation - code c0000005 (first/second chance not available)

    UE4Editor_BlueprintGraph
    UE4Editor_BlueprintGraph
    UE4Editor_BlueprintGraph
    UE4Editor_BlueprintGraph
    UE4Editor_UnrealEnginePython!unreal_engine_new_uclass() [c:\users\hughmacdonald\documents\unreal projects\plugindev\plugins\unrealenginepython\source\unrealenginepython\private\uepymodule.cpp:1448]
    UE4Editor_UnrealEnginePython!unreal_engine_py_init() [c:\users\hughmacdonald\documents\unreal projects\plugindev\plugins\unrealenginepython\source\unrealenginepython\private\uepysubclassing.cpp:36]
    python36
    python36
    python36
    python36
    python36
    python36
    python36
    python36
    python36
    python36
    python36
    python36
    python36
    python36
    python36
    python36
    python36
    python36
    python36
    python36
    python36
    python36
    python36
    python36
    python36
    python36
    python36
    python36
    python36
    python36
    python36
    python36
    python36
    python36
    python36
    python36
    python36
    python36
    python36
    python36
    python36
    python36
    python36
    python36
    python36
    python36
    python36
    UE4Editor_UnrealEnginePython!FUnrealEnginePythonModule::StartupModule() [c:\users\hughmacdonald\documents\unreal projects\plugindev\plugins\unrealenginepython\source\unrealenginepython\private\unrealenginepython.cpp:385]
    UE4Editor_Core
    UE4Editor_Projects
    UE4Editor_Projects
    UE4Editor_Projects
    UE4Editor
    UE4Editor
    UE4Editor
    UE4Editor
    UE4Editor
    UE4Editor
    kernel32
    ntdll

From doing some googling ([this result](https://answers.unrealengine.com/questions/396760/dont-understand-access-violation-c0000005-firstsec.html), for example), it sounds like it might be a null pointer being dereferenced somewhere along the way.

**Comment by rdeioris** [comment]
Hi, i think the reflection system is still not fully initialized when ue_site.py is called. I will try to reproduce your problem and i will come back

**Comment by HughMacdonald** [comment]
Great - thanks for that.

Is there a recommended way of doing this? I have a function in my python class that I need to be able to call from one of my blueprints. When I import the python module after I've already opened up the project, I get the Python object in fine, but the Blueprint is referencing a non-existent method, so has to be re-linked.

For now, I'm using `ExecutePythonString` and ensuring that I can rebuild the UObjects inside the Python function based on the string arguments that are passed in.

**Comment by rdeioris** [comment]
Hi, it should be fixed if you pull latest code. Basically i was reloading the blueprint graph at each new uclass/ufunction without checking if the engine is initialized

**Comment by HughMacdonald** [comment]
Awesome - let me give that a go then. Thanks
