### ISSUE TITLE
How to render sequence?

### ISSUE THREAD

**Issue by StevieZak** [20tab/UnrealEnginePython#453]
Can someone point me towards documentation on how to make calls to render a particular sequence, take, shot?  Can't seem to find any examples/documentation.

**Comment by rdeioris** [comment]
Hi, you mean generating the final video/image sequence ?

**Comment by StevieZak** [comment]
Yes.  Would like to do same as if in sequencer, hitting the Render Movie Settings button, set those options, hit Capture Movie.  Or right clicking on a shot in sequencer/track and selecting Render Shot.  Just not sure what to call.  Sorry, just getting into using this plugin so a bit new here.

**Comment by rdeioris** [comment]
Hi, you can start from this:

```python
import unreal_engine as ue
from unreal_engine.classes import AutomatedLevelSequenceCapture, VideoCaptureSettings
from unreal_engine.structs import CaptureProtocolID, MovieSceneCaptureSettings, DirectoryPath

seq = ue.get_selected_assets()[0]

capture = AutomatedLevelSequenceCapture()
capture.CaptureType = CaptureProtocolID(Identifier='Video')
capture.ProtocolSettings = VideoCaptureSettings()
capture.Settings = MovieSceneCaptureSettings(OutputDirectory=DirectoryPath(Path='D:/'))
capture.set_level_sequence_asset(seq)

# you can pass multiple capture objects, they will be encoded one after the other
ue.in_editor_capture([capture])
```

**Comment by StevieZak** [comment]
Thanks! This sort of helps.  Is there an easy way for me to obtain a listing of valid values to set, or documentation on the above so I don't have to bug you?  I've tried utilizing properties() and fields() calls, but not entirely understanding how to set these.  Would like to be able to set a lot of the different Render Movie Settings for example this stuff isn't working down below:

import unreal_engine as ue
from unreal_engine.classes import AutomatedLevelSequenceCapture, VideoCaptureSettings
from unreal_engine.structs import CaptureProtocolID, MovieSceneCaptureSettings, DirectoryPath

seq = ue.get_selected_assets()[0]
print(seq.get_name())

capture = AutomatedLevelSequenceCapture()
capture.CaptureType = CaptureProtocolID(Identifier='Video')
capture.ProtocolSettings = VideoCaptureSettings()
capture.Settings = MovieSceneCaptureSettings(OutputDirectory=DirectoryPath(Path='B:/home/szaharakis/Unreal_Testing'))

print(capture.CaptureType.fields())
#['Identifier']

print(capture.ProtocolSettings.properties())
#['bUseCompression', 'CompressionQuality', 'VideoCodec']

print(capture.Settings.fields())
#['OutputDirectory', 'GameModeOverride', 'OutputFormat', 'bOverwriteExisting', 'bUseRelativeFrameNumbers', 'HandleFrames', 'ZeroPadFrameNumbers', 'FrameRate', 'Resolution', 'bEnableTextureStreaming', 'bCinematicEngineScalability', 'bCinematicMode', 'bAllowMovement', 'bAllowTurning', 'bShowPlayer', 'bShowHUD']

print(capture.properties())
#['bUseCustomStartFrame', 'StartFrame', 'bUseCustomEndFrame', 'EndFrame', 'WarmUpFrameCount', 'DelayBeforeWarmUp', 'BurnInOptions', 'bWriteEditDecisionList', 'LevelSequenceAsset', 'LevelSequenceActor', 'CaptureType', 'ProtocolSettings', 'Settings', 'bUseSeparateProcess', 'bCloseEditorWhenCaptureStarts', 'AdditionalCommandLineArguments', 'InheritedCommandLineArguments']

#This isn't working
capture.UseCustomStartFrame = True
capture.StartFrame = 0
capture.UseCustomEndFrame = True
capture.EndFrame = 1

#This isn't working
capture.Settings = MovieSceneCaptureSettings(OutputFormat="png")
capture.Settings = MovieSceneCaptureSettings(Resolution="320x240")
capture.Settings = MovieSceneCaptureSettings(FrameRate=48)

#This seems to set preview window successfully?  Need render resolution though
#capture.Settings.Resolution.ResX = 320
#capture.Settings.Resolution.ResY = 240

capture.set_level_sequence_asset(seq)

# you can pass multiple capture objects, they will be encoded one after the other
ue.in_editor_capture([capture])

**Comment by rdeioris** [comment]
Unfortunately there is no documentation (except from the class-autogenerated one) about the UE api. Personally i needed to check the engine source code to discover how to use the vast majority of the features.

By the way, in your specific case you are mixing objects, structs and doing lot of overwrites, for example:

```python
capture.Settings = MovieSceneCaptureSettings(OutputFormat="png")
capture.Settings = MovieSceneCaptureSettings(Resolution="320x240")
capture.Settings = MovieSceneCaptureSettings(FrameRate=48)
```
it cannot work as you are overwriting the Settings field everytime. Instead you should do:

```python
capture.Settings =  MovieSceneCaptureSettings(OutputFormat="png", FrameRate=48)
```

and Resolution is not a string but a FCaptureResolution struct

(http://api.unrealengine.com/INT/API/Runtime/MovieSceneCapture/FMovieSceneCaptureSettings/Resolution/index.html)

```python
capture.Settings =  MovieSceneCaptureSettings(OutputFormat="png", FrameRate=48, Resolution=CaptureResolution(ResX=320, ResY=240))
```

More details:

(http://api.unrealengine.com/INT/API/Runtime/MovieSceneCapture/FMovieSceneCaptureSettings/index.html)

Regarding capture.UseCustomStartFrame, the right name is capture.bUseCustomStartFrame (with the 'b' prefix like reported in the properties() array)

**Comment by StevieZak** [comment]
Thanks so much, this helps a lot.

**Comment by ndeebook** [comment]
I'm trying this in 4.23... but the imports don't work anymore :/
```
ImportError: cannot import name VideoCaptureSettings
ImportError: cannot import name CaptureProtocolID
```

**Comment by unrealfuzzy** [comment]
@ndeebook yeah same here.. digging into it now, I'll keep you posted if I find anything.
@rdeioris any help please?
