### ISSUE TITLE
Get reference to component in blueprint asset

### ISSUE THREAD

**Issue by tweaq** [20tab/UnrealEnginePython#457]
First off: is there a list of commands? I think I could figure some stuff out if I could just search through a list. 

Anyway, now I'm just trying to change the static mesh in a child blueprint. I have my script creating the child blueprint in the content browser and I can create a new staticmesh component inside of it (using [this link](https://github.com/20tab/UnrealEnginePython/issues/26)) But I would rather just set the mesh that is in there. I can't seem to get a reference to the component.  I mostly just can't figure out what commands to use.

**Comment by rdeioris** [comment]
Hi, if you mean the list of wrappers, you find it here: https://github.com/20tab/UnrealEnginePython/blob/master/Source/UnrealEnginePython/Private/UEPyModule.cpp#L198

but take into account that those are mostly optimizations, and instead, 99% of time you will use the reflection api. I suggest you to read this one:

https://github.com/20tab/UnrealEnginePython/blob/master/tutorials/YourFirstAutomatedPipeline.md

your specific case:

https://github.com/20tab/UnrealEnginePython/blob/master/tutorials/YourFirstAutomatedPipeline.md#put-it-all-in-a-new-blueprint

**Comment by tweaq** [comment]
Will do. Thank you very much. I'm an animator, fumbling through trying to code, so a lot of it is over my head (at least for now). But that looks promising.

**Comment by tweaq** [comment]
using : `bp.SimpleConstructionScript.DefaultSceneRootNode.ChildNodes[0].ComponentTemplate.StaticMesh = cube`

It seems I am unable to get a reference to (or to set) the Static Mesh in a child blueprint. It works fine on the parent blueprint though.

**Comment by rdeioris** [comment]
Hi, i think you want UserConstructionScript (the tab Construction Script in blueprint) that is available in 
bp.FunctionGraphs array and you can manipulate as a normal graph

**Comment by rdeioris** [comment]
Sorry again, i think you were not rferring to the constrction script but instead you want defaults for you blueprint. In such a case you need to edit the cdo (class default object):

bp.GeneratedClass.get_cdo().CapsuleComponent.CapsuleRadius = 300

**Comment by tweaq** [comment]
I tried using the cdo, but that didn't work either. Its an actor blueprint with a static mesh. i tried it with the static mesh as the root and under a default scene root.

**Comment by rdeioris** [comment]
I fear i am not understanding your issue. Can you post a couple of screenshots with the situation you have now and the one you want ? Thanks

**Comment by rdeioris** [comment]
Hi, yes it is better to directly set the skeletalmesh of the child (or parent) blueprint:

```python
bp.GeneratedClass.get_cdo().Mesh.SkeletalMesh = <skeletal_mesh_object>
```

**Comment by tweaq** [comment]
It's a static mesh, but no matter what I try it says "NoneType object has no attribute 'SkeletalMesh' , or I tried StaticMesh.

**Comment by rdeioris** [comment]
That's because you have to respect the name of the component, if it is not called 'Mesh', you need to adapt the code (I suppose it is called NewMesh)
