### ISSUE TITLE
change sequence fps and use frame to count time instead of sec?

### ISSUE THREAD

**Issue by taotang1984** [20tab/UnrealEnginePython#460]
Hi,
I am wondering if I can change sequence fps to 24 by using code. 
Also, is there a way to use frame to set sequence start and end time? Right now I can write code like this:
anim_sequence.EndTime=3, but it is based on sec, not frame.
Thank you so much~

**Comment by rdeioris** [comment]
Hi, the field is sequencer.MovieScene.FIxedFrameInterval (you can set it to 1/24). 

For ranges you can use this one (just use the phormula sequencer.MovieScene.FIxedFrameInterval * frame_number)

https://github.com/20tab/UnrealEnginePython/blob/master/examples/sequencer_scripting.py#L65

**Comment by taotang1984** [comment]
Thanks, this really helps a lot~, as always
