### ISSUE TITLE
Return static mesh name from instanced mesh

### ISSUE THREAD

**Issue by aracid** [20tab/UnrealEnginePython#462]
Hi there

I was wondering how I could get the actual static mesh name and not just a path to an instanced mesh

This only works when there some instanced foliage in the level.

---------------------------------------------------------------------------------
import unreal_engine as ue
import json

foliage_actor = ue.get_editor_world().get_instanced_foliage_actor_for_current_level()

foliage_list = []

for foliage_type in foliage_actor.get_foliage_types():
	print("Path Name : " + foliage_type.get_path_name())

---------------------------------------------------------------------------------

Running this returns
LogPython: Path Name : /Game/myMap.myMap:PersistentLevel.InstancedFoliageActor_0.FoliageType_InstancedStaticMesh_0

Thanks in advance
Brian

**Comment by rdeioris** [comment]
Hi, it is under the 'Mesh' property:

```python
foliage_type.Mesh
```

**Comment by aracid** [comment]
Hi Rdeioris

Thanks for that!
