### ISSUE TITLE
Shotgun integration

### ISSUE THREAD

**Issue by aracid** [20tab/UnrealEnginePython#464]
Hi everyone

This isn't really an issue but rather a query about how people have circumnavigated the integration with Shotgun as it relies on 2.7, if other software relies on python 3.6?

Any suggestions to query or publish assets into shotgun?

Thanks in advance
Brian

**Comment by rdeioris** [comment]
Hi, you can use this plugin with python 2.7 too, but maybe i did not understand your question :)

**Comment by aracid** [comment]
Just read the question and yes it didn't make sense, for example, unreal uses python 3.6, how could I connect to the shotgun python api (which currently is on python v2.7)?

**Comment by unbit** [comment]
I think the best thing you can do is using the python 2.7 version of UnrealEnginePython plugin. So you can directly use the shotgun module.

**Comment by slackermorris** [comment]
Thanks Unbit

**Comment by aracid** [comment]
This was a silly question in the end as the py27 was available to download. Thanks again for your assistance.
