### ISSUE TITLE
Spawning actors to the game world from a Python script that is not part of a PyActor class

### ISSUE THREAD

**Issue by jsabater333** [20tab/UnrealEnginePython#469]
Currently, I'm able to spawn actors in the editor world using a Python script using the following code:

import unreal_engine as ue
from unreal_engine.classes import Blueprint
from unreal_engine import FVector, FRotator

world = ue.get_editor_world()
blueprint = ue.load_object(Blueprint, '/Game/Robot/BP_MainChar.BP_MainChar')
actor000 = world.actor_spawn(blueprint.GeneratedClass, FVector(1000, 250, 138), FRotator(0, 0, 0))

I would like to do the same but in the game world at runtime. My question is, how can I get a reference to the game world (not the editor world) from a Python script that is not part of a PyActor class (and therefore I cannot do 'world = self.uobject.get_world()' )?

Thanks a lot!

**Comment by rdeioris** [comment]
Hi, you can get the whole list of worlds in the engine with:

```python
import unreal_engine as ue

worlds = ue.all_worlds()
```

then for each world you can call get_world_type() that returns a number representing the type of world:

https://api.unrealengine.com/INT/API/Runtime/Engine/Engine/EWorldType__Type/index.html

(PIE or Game are the interesting one for you)

**Comment by jsabater333** [comment]
Uau! Thanks for the quick answer! Exactly what I needed.
Grazie mille!!!
