### ISSUE TITLE
Add UAssetImportData Support

### ISSUE THREAD

**Issue by osstony** [20tab/UnrealEnginePython#47]
Currently we are able to get this UObject via reflection but are unable to access any of it's methods.

Should a new class be created that inherits from UObject and adds the missing functions for this class? Is there a mechanism for looking up and returning python wrappers for these classes when reflection is invoked?

**Comment by rdeioris** [comment]
Which are the UAssetImportData methods that you need most ? last time i checked the only useful one was the package path (that can be retrieved with a call to get_outer()) so i did not investigated more. Eventually, we could have a more low-level get_assets() functions returning a dictionary-like object with additional infos.

**Comment by osstony** [comment]
Ah ok, I do only need the path to the file on disk, I will look at using get_outer() instead. 

If I do find additional classes that need to be fleshed out, what would be the approach you'd like me to take for adding them in?

**Comment by osstony** [comment]
Which method were you using on get_outer() to find the file path? I am using that and getting back a UPackage object which doesn't have any exposed properties or functions other than ExecuteUbergraph. Is there an exposed function that has been added to the Python UObject I am missing?

**Comment by rdeioris** [comment]
This should be useful: https://github.com/20tab/UnrealEnginePython/issues/36

**Comment by osstony** [comment]
Ah, that is the game path, I need the file path of the original file the asset was imported from. For example I'll want these methods from UAssetImportData:

ResolveImportFilename
GetFirstFilename

**Comment by rdeioris** [comment]
i think it is easier to get the package filename from the UPackage class:

https://docs.unrealengine.com/latest/INT/API/Runtime/CoreUObject/UObject/UPackage/index.html

a "package_get_filename()" method could be useful

**Comment by osstony** [comment]
Ok I'll look at adding that to the UObject. Do we have anything yet for getting different paths offered by FPaths? Should we add that to the UObject as well?

**Comment by rdeioris** [comment]
Check "get_content_dir" (py_unreal_engine_get_content_dir)

**Comment by osstony** [comment]
UPackage.FileName still returns the game path and not the path to the fbx file on disk. I'm going to add a quick function to get a dictionary of AssetImportData info.

**Comment by osstony** [comment]
#49 has some of what was discussed here plus some additions.

**Comment by osstony** [comment]
I left an updated version of this in #56. It returns additional data like timestamp and file hash plus could support multiple files like the Unreal API does.

**Comment by osstony** [comment]
This should be all set, closing.
