### ISSUE TITLE
Problem using Python Components

### ISSUE THREAD

**Issue by jsabater333** [20tab/UnrealEnginePython#471]
Hi all,

I'm struggling with a problem that probably is quite trivial. But I really don't know what I'm doing wrong.

I define a Python component with some methods and I attach the component to a PyCharacter. At some momment I get the component calling "get_actor_component" in a python script:

webSocketComponent = my_actor.get_actor_component('WebSocketInterface')

Everything seems to work because if I print "webSocketComponent" I obtain:

<unreal_engine.UObject 'WebSocketInterface' (0x00000188257EDA80) UClass 'PythonComponent' (refcnt: 5)>

The problem is that when I try to call one of the methods of this component using:

webSocketComponent.my_dummy_method(ws)

where "my_dummy_method" is defined as a method of the class 'WebSocketInterface', I get the error

AttributeError: 'unreal_engine.UObject' object has no attribute 'my_dummy_method'

How can I call, from a python script, the methods of the python component once I have the reference to the UObject component (as I showed before)?

Thanks a lot!

**Comment by rdeioris** [comment]
If my_dummy_method is a python method and not a native one, you need to access the python class mapped to the component:

```python
webSocketComponent = my_actor.get_actor_component('WebSocketInterface')
webSocketComponent.get_py_proxy().my_dummy_method(ws)
```

more infos here:

https://github.com/20tab/UnrealEnginePython#accessing-python-proxy-from-uobject

**Comment by jsabater333** [comment]
Great! it works as expected :)

I had read that part of the documentation but clearly I did not properly understand it because I was not able to make the connection with Python Components. My fault, I'm still learning, sorry.

Thanks a lot.

By the way, the plugin is really awesome! 
Regards.
