### ISSUE TITLE
Build failed with 4.20

### ISSUE THREAD

**Issue by kaedehao** [20tab/UnrealEnginePython#473]
Howdy,

I got following errors when build with 4.20 release version:

Error	C3861	'PyUnicode_AsUTF8': identifier not found	evalUE420	
\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\Wrappers\UEPyFARFilter.cpp	336	

Error	C2228	left of '.Get' must have class/struct/union	evalUE420	
\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\Wrappers\UEPyFARFilter.cpp	336

**Comment by rdeioris** [comment]
Hi, re-pull the code it has been fixed some minute ago.

Note: 4.20 still has almost broken sequencer api. Should be fixed soon
