### ISSUE TITLE
How to import audio file?

### ISSUE THREAD

**Issue by 5775486f** [20tab/UnrealEnginePython#475]
How could I import audio file (such as .wav files) just like 'PyFbxFactory'?
Or there's anyother way?

**Comment by rdeioris** [comment]
Hi

```python
import unreal_engine as ue

from unreal_engine.classes import SoundFactory

factory = SoundFactory()

sound_asset = factory.factory_import_object('D:/foo.wav', '/Game/FooSound')
```

Here you find the list of all the factories:

https://api.unrealengine.com/INT/API/Editor/UnrealEd/Factories/UFactory/index.html

**Comment by 5775486f** [comment]
Thank you
But when I add a MovieSceneAudioSection to my sequencer,UE crashed

**Comment by rdeioris** [comment]
Do you have a traceback to post for the crash ?

**Comment by 5775486f** [comment]
You can select a sequencer run that script I post,Engine crash directly

**Comment by rdeioris** [comment]
Ok, basically in 4.20 the CreateNewSection for audio tracks crashes ue.

If you update to latest plugin code you can force the creation of a specific section (like you were doing with your code by passing the section type).

If you cannot upgrade you can use this workaround:

```python
import unreal_engine as ue
from unreal_engine.classes import MovieSceneAudioTrack , MovieSceneAudioSection

selSeqs = ue.get_selected_assets()

if selSeqs == []:
	ue.message_dialog_open(ue.APP_MSG_TYPE_OK, "Please Select One Sequencer At Least ！ ")
else:
    thisSeq = selSeqs[0]
    track = thisSeq.sequencer_add_master_track(MovieSceneAudioTrack)
    section = MovieSceneAudioSection('', track)
    track.AudioSections = [section]
    print(section)
```

**Comment by 5775486f** [comment]
Ok,Tnang you
