### ISSUE TITLE
can not Installation from sources on python 2.7.14 ue4.19 win7

### ISSUE THREAD

**Issue by dengzibiao** [20tab/UnrealEnginePython#476]
python 2.7.14，ue4.19
run the compilation from visual studio
“UE4Editor.exe”(Win32): 已加载“C:\Windows\System32\wdmaud.drv”。无法查找或打开 PDB 文件。
“UE4Editor.exe”(Win32): 已加载“C:\Windows\System32\msacm32.drv”。无法查找或打开 PDB 文件。
“UE4Editor.exe”(Win32): 已加载“C:\Windows\System32\msacm32.dll”。无法查找或打开 PDB 文件。
“UE4Editor.exe”(Win32): 已加载“C:\Windows\System32\midimap.dll”。无法查找或打开 PDB 文件。
“UE4Editor.exe”(Win32): 已加载“D:\Program files\Epic Games\UE_4.19\Engine\Plugins\Runtime\CableComponent\Binaries\Win64\UE4Editor-CableComponent.dll”。无法查找或打开 PDB 文件。
“UE4Editor.exe”(Win32): 已加载“D:\Program files\Epic Games\UE_4.19\Engine\Plugins\Runtime\CustomMeshComponent\Binaries\Win64\UE4Editor-CustomMeshComponent.dll”。无法查找或打开 PDB 文件。
“UE4Editor.exe”(Win32): 已加载“D:\Program files\Epic Games\UE_4.19\Engine\Plugins\Runtime\MobilePatchingUtils\Binaries\Win64\UE4Editor-MobilePatchingUtils.dll”。无法查找或打开 PDB 文件。
“UE4Editor.exe”(Win32): 已加载“D:\Program files\Epic Games\UE_4.19\Engine\Plugins\Runtime\Oculus\OculusVR\Binaries\Win64\UE4Editor-OculusInput.dll”。无法查找或打开 PDB 文件。
[2018.07.23-04.32.04:606][  0]LogOcInput: OculusInput pre-init called
“UE4Editor.exe”(Win32): 已加载“D:\Program files\Epic Games\UE_4.19\Engine\Plugins\Runtime\ProceduralMeshComponent\Binaries\Win64\UE4Editor-ProceduralMeshComponent.dll”。无法查找或打开 PDB 文件。
“UE4Editor.exe”(Win32): 已卸载“D:\Program files\Epic Games\UE_4.19\Engine\Plugins\Runtime\ProceduralMeshComponent\Binaries\Win64\UE4Editor-ProceduralMeshComponent.dll”
“UE4Editor.exe”(Win32): 已加载“D:\Program files\Epic Games\UE_4.19\Engine\Plugins\Runtime\ProceduralMeshComponent\Binaries\Win64\UE4Editor-ProceduralMeshComponentEditor.dll”。无法查找或打开 PDB 文件。
“UE4Editor.exe”(Win32): 已加载“D:\Program files\Epic Games\UE_4.19\Engine\Plugins\Runtime\Steam\SteamVR\Binaries\Win64\UE4Editor-SteamVRController.dll”。无法查找或打开 PDB 文件。
“UE4Editor.exe”(Win32): 已加载“E:\UE4\UE4Protobuf-fin\Plugins\AutoGenerateProtoStructAndBp\Binaries\Win64\UE4Editor-AutoGenerateProtoStructAndBp-Win64-DebugGame.dll”。已加载符号。
“UE4Editor.exe”(Win32): 已加载“E:\UE4\UE4Protobuf-fin\Plugins\UnrealEnginePython\Binaries\Win64\UE4Editor-UnrealEnginePython-Win64-DebugGame.dll”。已加载符号。
[2018.07.23-04.32.05:584][  0]LogPython: Python Scripts search path: E:/UE4/UE4Protobuf-fin/Content/Scripts
[2018.07.23-04.32.05:585][  0]LogPython: Python Scripts search path: E:/UE4/UE4Protobuf-fin/Plugins/UnrealEnginePython
[2018.07.23-04.32.05:585][  0]LogPython: Python VM initialized: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
[2018.07.23-04.32.05:586][  0]LogPython: ue_site Python module successfully imported
0x0000000044F54D77 (python27.dll)处(位于 UE4Editor.exe 中)引发的异常: 0xC0000005: 写入位置 0x0000000000000018 时发生访问冲突。

It Stop when initialization UE4 in progressBar 73%

**Comment by rdeioris** [comment]
Hi, are you sure you did not built a hot-reload plugin version ? You should try rebuilding it with the editor closed

**Comment by dengzibiao** [comment]
I am sure run the compilation from visual studio with ue4 editor closed
