### ISSUE TITLE
python call struct have bug after packaging

### ISSUE THREAD

**Issue by bianchengxiaosheng** [20tab/UnrealEnginePython#479]
Hi:
I find a bug for python call struct after packaging，
I define a Struct in project Content named Test ,and define a string variable named hh.
follow the code as:

**from unreal_engine.structs import Test,TestItem
import unreal_engine as ue
class StructTT:
    def ATest(self):
        ts = Test()
        print(ts.hh)
        print(dir(ts))
        ts.hh = 'jsdhfgdhfkg'        
        self.uobject.call_function('FunctionTest',ts)**

  It is ok when i run these python code in editor,but when i packaged the project and run the exe,the error will show ::
 [2018.07.24-07.41.58:981][  0]LogPython: Error: 'unreal_engine.UScriptStruct' object has no attribute 'hh'
[2018.07.24-07.41.58:994][  0]LogPython: Error: Traceback (most recent call last):

[2018.07.24-07.41.58:994][  0]LogPython: Error:   File "../../../PythonTest/Content/Scripts\StructTest.py", line 6, in ATest
    print(ts.hh)

[2018.07.24-07.41.58:994][  0]LogPython: Error: AttributeError: 'unreal_engine.UScriptStruct' object has no attribute 'hh'

i update the plugin for lastest,but the error still have,so hope you can solve this problem,Thanke you

**Comment by rdeioris** [comment]
Hi, user struct fields are internally managed with a different name (it generally has a suffix). While in the editor we can get the value from the DisplayName metadata but once built that value is no more available.

Use the .fields() method to get the true name of the field (it returns the 'suffixed' values)

**Comment by bianchengxiaosheng** [comment]
thanks

**Comment by rdeioris** [comment]
Note: with latest commit, UObject's created by python, remains alive until the python object is alive.
