### ISSUE TITLE
Get the current unreal window for parenting in QT

### ISSUE THREAD

**Issue by khalibloo** [20tab/UnrealEnginePython#482]
The QT example on the readme uses `ue.get_editor_window()` to obtain the unreal editor window. How would one obtain non-editor windows? For example, the game window in a packaged app. Or the game window when running as standalone from the editor.

**Comment by rdeioris** [comment]
Hi, get the latest code and check this example for accessing the various windows:

https://github.com/20tab/UnrealEnginePython/blob/master/examples/get_windows.py

**Comment by khalibloo** [comment]
You sir, are awesome! That was super fast. It took me a while to build from source, but it works beautifully now. Thank you.
