### ISSUE TITLE
How can I set the SkeletalMeshComponent OverrideMaterials of an actor?

### ISSUE THREAD

**Issue by yes7rose** [20tab/UnrealEnginePython#489]
I  SkeletalMeshComponent materials by assign a list to the 
SkeletalMeshComponent.OverrideMaterials, 

sk_comp.OverrideMaterials = override_mats

but have the error:
LogPython: Error: ValueError: invalid value for UProperty;

What can I do?
Thanks.

**Comment by rdeioris** [comment]
Hi, just pass a list of materials:

sk_comp.OverrideMaterials = [mat0, mat1]

**Comment by yes7rose** [comment]
Can I pass a list of materail instances?
