### ISSUE TITLE
UE4.20 PyFbxFactory ImportUI.bImportMesh = False not working

### ISSUE THREAD

**Issue by heylenz** [20tab/UnrealEnginePython#497]
`
fbx_path = "xx_animation.fbx"
factory = PyFbxFactory()
factory.ImportUI.MeshTypeToImport = EFBXImportType.FBXIT_Animation
factory.ImportUI.Skeleton = skeleton
factory.ImportUI.bImportMaterials = False
factory.ImportUI.bImportTextures = False
factory.ImportUI.bCreatePhysicsAsset = False
factory.ImportUI.bImportMesh = False

print(factory.ImportUI.as_dict())
factory.factory_import_object(fbx_path, anim_destination)
`

when i setting `factory.ImportUI.bImportMesh = False`  not working ,will always create SkeletalMesh,
I just want import AnimSequence

**Comment by heylenz** [comment]
The same code is tested in ue4.18. When I set BimportMesh=False, factory_import_object only imports animation segments, but in ue4.20, the result is different. I imported SkeletalMesh and animation segments. I saw you give My link, only one bImportAsSkeletal may be related, but setting bImportAsSkeletal=False also doesn't work.

**Comment by rdeioris** [comment]
I am pretty sure the right field to set is this one:

https://api.unrealengine.com/INT/API/Editor/UnrealEd/Factories/UFbxImportUI/MeshTypeToImport/index.html


(sorry no time to test now as i am out of office)

**Comment by rdeioris** [comment]
Please retry with latest code. I think i have fixed it.

**Comment by heylenz** [comment]
Thank you so much, perfect!
