### ISSUE TITLE
Getting SkeletalMeshComponent fails with invalid UClass Error

### ISSUE THREAD

**Issue by DNCrosby** [20tab/UnrealEnginePython#498]
`self.uobject.get_component_by_type('SkeletalMeshComponent')`

Seems to fail in the latest Revision ( Aug. 2018 )
While it seems to work. in a revision, I pulled down in Mar / April.

Error: 
```
___init___
Bringing up level for play took: 0.001820
argument is not a UClass
Traceback (most recent call last):
  File "../../../../MyProject/Content/Scripts\ue_SkelMeshTest.py", line 14, in begin_play
Exception: argument is not a UClass
```

Previous Version:
```
___init___
Bringing up level for play took: 0.001555
<unreal_engine.UObject 'rd0001_character_body_rt1' (0x0000018726A32080) UClass 'SkeletalMeshComponent' (refcnt: 3)>
Play in editor start time for /Temp/UEDPIE_0_Untitled_1 -0.317
```

**Comment by rdeioris** [comment]
Hi use 

from unreal_engine.classes import SkeletalMeshComponent

or ue.find_class('SkeletalMeshComponent')

The first is faster and less error prone

**Comment by DNCrosby** [comment]
It must have sourced that in another script, and I didn't catch it. Thanks ! 👍

**Comment by DNCrosby** [comment]
`import unreal_engine as ue
from unreal_engine.classes import Skeleton, SkeletalMesh, SkeletalMeshComponent, MorphTarget

class MyGame:
    def __init__(self):
        ue.log('___init___')
        
    def begin_play(self):
        ue.log("Test")
        #ue.log(self.uobject.get_component_by_type("SkeletalMesh"))        
        self.skeletal = self.uobject.get_component_by_type('SkeletalMeshComponent')        
        print (self.skeletal)


`

`___init___
Bringing up level for play took: 0.007181
Native class hierarchy updated for 'MovieSceneCapture' in 0.0005 seconds. Added 11 classes and 0 folders.
Test
argument is not a UClass
Traceback (most recent call last):
  File "../../../../MyGame/Content/Scripts\ue_SkelMeshTest.py", line 11, in begin_play
    self.skeletal = self.uobject.get_component_by_type('SkeletalMeshComponent')
Exception: argument is not a UClass
Play in editor start time for /Game/Levels/UEDPIE_0_Default 1.076`

**Comment by DNCrosby** [comment]
That did it, funny in a lot of the samples you find it uses a string, so this is new (ish)?
