### ISSUE TITLE
Python 3.5  32/64 bit

### ISSUE THREAD

**Issue by LarsGroh** [20tab/UnrealEnginePython#5]
Hi,
i am getting a build error concerning the python version.
Is it supposed to be 32 or 64 bit?

Regards, 
Lars

**Comment by rdeioris** [comment]
Hi, currently only 64bit is supported

**Comment by LarsGroh** [comment]
Hi, thanks for the quick reply!
Maybe this also explains the large number of linking errors that I get.

**Comment by rdeioris** [comment]
Are you on windows or mac ?

**Comment by LarsGroh** [comment]
On windows; changing to 64bit got rid of all the linking errors.

Though I got a warning when opening the editor:
"UE4Editor-UnrealEnginePython.dll" was either missing or compiled with a different version of the engine - not sure if it was the ".dll" as I can't reproduce the warning.

Anyway, the editor did some compiling/build on startup. and everything seemed to work.

The only issue now is that my python module can't be found.
Is there anything that needs to be done to add the "Content/Scripts"-folder as a "lookup" location - similar to the PYTHONPATH?!

**Comment by rdeioris** [comment]
I strongly suggest you to pull latest code and work with the python console too: https://github.com/20tab/UnrealEnginePython/blob/master/PythonConsole.md

**Comment by LarsGroh** [comment]
Thanks for the suggestion! I will definately do that!
Scripting the editor is actually something I was looking forward to!

As I stated in my edit above, the module detection now works!

Thanks for your support!
