### ISSUE TITLE
Collision Presets

### ISSUE THREAD

**Issue by hoATwhiskytree** [20tab/UnrealEnginePython#500]
I was looking through the "Snippets for Static and Skeletal Meshes" example file and was wondering if it is even possible to access and change the collision presets in the static mesh editor.

**Comment by rdeioris** [comment]
Yes, you can access both the KAggregateGeom as well as kdop stuff

https://github.com/20tab/UnrealEnginePython/blob/master/examples/kdop.py

**Comment by rdeioris** [comment]
Oh ok, sorry, those data are in the BodyInstance property (it is a struct, so you need to call .fields() on it to get its members)

**Comment by hoATwhiskytree** [comment]
Oh I didn't know about the "fields()" Thanks for the tip!
staticmesh.BodySetup.DefaultInstance.CollisionProfileName = "NoCollision"
