### ISSUE TITLE
Change every LOD's material slot ?

### ISSUE THREAD

**Issue by LegionFu** [20tab/UnrealEnginePython#501]
### **How to change the LOD's material slot with python?**
![image](https://user-images.githubusercontent.com/20501414/43950501-0253211c-9cc3-11e8-98d1-e93a3c5a8db8.png)

**Comment by rdeioris** [comment]
```python
import unreal_engine as ue


mesh = ue.get_selected_assets()[0]

# this is the new material index
new_index = 1

for section_key in mesh.SectionInfoMap.Map:
    info = mesh.SectionInfoMap.Map[section_key]
    info.MaterialIndex = new_index
```

**Comment by LegionFu** [comment]
Thanks for your reply, But why my code is doesn't work ?
here is my code and output:
![image](https://user-images.githubusercontent.com/20501414/43953407-725a5216-9ccb-11e8-8a1c-9d7a123c13c4.png)
![image](https://user-images.githubusercontent.com/20501414/43953437-9059b93c-9ccb-11e8-93c4-9eb4c140291b.png)

**Comment by LegionFu** [comment]
Thanks for your reply , But why my code is doesn't work?
here is my code and output :
![image](https://user-images.githubusercontent.com/20501414/43953740-885c717e-9ccc-11e8-9558-92a78a13ca21.png)

![image](https://user-images.githubusercontent.com/20501414/43953751-93b5dd8a-9ccc-11e8-8867-e179d61148da.png)


It look like all right, But my static mesh is have no change...
![image](https://user-images.githubusercontent.com/20501414/43953795-b6e1d7fa-9ccc-11e8-9230-224f02796c10.png)

**Comment by rdeioris** [comment]
Are you using a recent release of the plugin ? Which ue version are you using ?

**Comment by LegionFu** [comment]
ue version is 4.18 , and plugin maybe a old version . I will trying the new version.

**Comment by LegionFu** [comment]
It work ! Thank you so much ! 👍
