### ISSUE TITLE
4.20 compile error

### ISSUE THREAD

**Issue by xermao** [20tab/UnrealEnginePython#503]
if UnrealEnginePython type set to Runtime,and compile without editor.
I get these error below(4.19 is fine)
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPyMaterial.cpp(63): error C2039: 'SetMaterial': is not a member of 'UStaticMesh'
3>  D:\Program Files\Epic Games\UE_4.20\Engine\Source\Runtime\Engine\Classes\Engine/StaticMesh.h(500): note: see declaration of 'UStaticMesh'

3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(70): error C2061: syntax error: identifier 'FMovieSceneFloatChannel'
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(72): error C2065: 'TMovieSceneChannelData': undeclared identifier
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(72): error C2065: 'FMovieSceneFloatValue': undeclared identifier
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(72): error C2065: 'ChannelData': undeclared identifier
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(72): error C2065: 'Dest': undeclared identifier
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(72): error C2227: left of '->GetData' must point to class/struct/union/generic type
3>  F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(72): note: type is 'unknown-type'
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(73): error C2065: 'ChannelData': undeclared identifier
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(73): error C2228: left of '.Reset' must have class/struct/union
3>  F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(73): note: type is 'unknown-type'
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(74): error C2065: 'DestFrameRate': undeclared identifier
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(74): error C2228: left of '.AsDecimal' must have class/struct/union
3>  F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(74): note: type is 'unknown-type'
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(89): error C2065: 'bNegateTangents': undeclared identifier
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(95): error C2065: 'DestFrameRate': undeclared identifier
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(95): error C2228: left of '.RoundToFrame' must have class/struct/union
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(96): error C2653: 'FMatineeImportTools': is not a class or namespace name
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(96): error C2065: 'ChannelData': undeclared identifier
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(96): error C3861: 'SetOrAddKey': identifier not found
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(99): error C2065: 'Dest': undeclared identifier
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(99): error C2227: left of '->AutoSetTangents' must point to class/struct/union/generic type
3>  F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(99): note: type is 'unknown-type'
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(102): error C2061: syntax error: identifier 'UMovieScene3DTransformSection'
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(111): error C2065: 'CurveAPI': undeclared identifier
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(111): error C2228: left of '.GetConvertedTransformCurveData' must have class/struct/union
3>  F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(111): note: type is 'unknown-type'
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(113): error C2065: 'TransformSection': undeclared identifier
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(113): error C2227: left of '->Modify' must point to class/struct/union/generic type
3>  F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(113): note: type is 'unknown-type'
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(115): error C2065: 'TransformSection': undeclared identifier
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(115): error C2227: left of '->GetTypedOuter' must point to class/struct/union/generic type
3>  F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(115): note: type is 'unknown-type'
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(115): error C2059: syntax error: ')'
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(120): error C2065: 'FMovieSceneFloatChannel': undeclared identifier
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(120): error C2059: syntax error: '>'
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(120): error C2976: 'TArrayView': too few template arguments
3>  d:\program files\epic games\ue_4.20\engine\source\runtime\moviescene\public\MovieSceneSection.h(24): note: see declaration of 'TArrayView'
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(120): error C2065: 'TransformSection': undeclared identifier
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(120): error C2227: left of '->GetChannelProxy' must point to class/struct/union/generic type
3>  F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(120): note: type is 'unknown-type'
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(120): error C2228: left of '.GetChannels' must have class/struct/union
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(120): error C2059: syntax error: ')'
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(122): error C2678: binary '[': no operator found which takes a left-hand operand of type 'TArrayView' (or there is no acceptable conversion)
3>  d:\program files\epic games\ue_4.20\engine\source\runtime\core\public\Containers/ArrayView.h(250): note: could be 'InElementType &TArrayView<InElementType>::operator [](int32) const'
3>  F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(122): note: while trying to match the argument list '(TArrayView, int)'
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(122): error C2227: left of '->SetDefault' must point to class/struct/union/generic type
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(123): error C2678: binary '[': no operator found which takes a left-hand operand of type 'TArrayView' (or there is no acceptable conversion)
3>  d:\program files\epic games\ue_4.20\engine\source\runtime\core\public\Containers/ArrayView.h(250): note: could be 'InElementType &TArrayView<InElementType>::operator [](int32) const'
3>  F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(123): note: while trying to match the argument list '(TArrayView, int)'
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(123): error C2227: left of '->SetDefault' must point to class/struct/union/generic type
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(124): error C2678: binary '[': no operator found which takes a left-hand operand of type 'TArrayView' (or there is no acceptable conversion)
3>  d:\program files\epic games\ue_4.20\engine\source\runtime\core\public\Containers/ArrayView.h(250): note: could be 'InElementType &TArrayView<InElementType>::operator [](int32) const'
3>  F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(124): note: while trying to match the argument list '(TArrayView, int)'
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(124): error C2227: left of '->SetDefault' must point to class/struct/union/generic type
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(126): error C2678: binary '[': no operator found which takes a left-hand operand of type 'TArrayView' (or there is no acceptable conversion)
3>  d:\program files\epic games\ue_4.20\engine\source\runtime\core\public\Containers/ArrayView.h(250): note: could be 'InElementType &TArrayView<InElementType>::operator [](int32) const'
3>  F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(126): note: while trying to match the argument list '(TArrayView, int)'
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(126): error C2227: left of '->SetDefault' must point to class/struct/union/generic type
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(127): error C2678: binary '[': no operator found which takes a left-hand operand of type 'TArrayView' (or there is no acceptable conversion)
3>  d:\program files\epic games\ue_4.20\engine\source\runtime\core\public\Containers/ArrayView.h(250): note: could be 'InElementType &TArrayView<InElementType>::operator [](int32) const'
3>  F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(127): note: while trying to match the argument list '(TArrayView, int)'
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(127): error C2227: left of '->SetDefault' must point to class/struct/union/generic type
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(128): error C2678: binary '[': no operator found which takes a left-hand operand of type 'TArrayView' (or there is no acceptable conversion)
3>  d:\program files\epic games\ue_4.20\engine\source\runtime\core\public\Containers/ArrayView.h(250): note: could be 'InElementType &TArrayView<InElementType>::operator [](int32) const'
3>  F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(128): note: while trying to match the argument list '(TArrayView, int)'
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(128): error C2227: left of '->SetDefault' must point to class/struct/union/generic type
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(130): error C2678: binary '[': no operator found which takes a left-hand operand of type 'TArrayView' (or there is no acceptable conversion)
3>  d:\program files\epic games\ue_4.20\engine\source\runtime\core\public\Containers/ArrayView.h(250): note: could be 'InElementType &TArrayView<InElementType>::operator [](int32) const'
3>  F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(130): note: while trying to match the argument list '(TArrayView, int)'
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(130): error C2227: left of '->SetDefault' must point to class/struct/union/generic type
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(131): error C2678: binary '[': no operator found which takes a left-hand operand of type 'TArrayView' (or there is no acceptable conversion)
3>  d:\program files\epic games\ue_4.20\engine\source\runtime\core\public\Containers/ArrayView.h(250): note: could be 'InElementType &TArrayView<InElementType>::operator [](int32) const'
3>  F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(131): note: while trying to match the argument list '(TArrayView, int)'
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(131): error C2227: left of '->SetDefault' must point to class/struct/union/generic type
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(132): error C2678: binary '[': no operator found which takes a left-hand operand of type 'TArrayView' (or there is no acceptable conversion)
3>  d:\program files\epic games\ue_4.20\engine\source\runtime\core\public\Containers/ArrayView.h(250): note: could be 'InElementType &TArrayView<InElementType>::operator [](int32) const'
3>  F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(132): note: while trying to match the argument list '(TArrayView, int)'
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(132): error C2227: left of '->SetDefault' must point to class/struct/union/generic type
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(134): error C2678: binary '[': no operator found which takes a left-hand operand of type 'TArrayView' (or there is no acceptable conversion)
3>  d:\program files\epic games\ue_4.20\engine\source\runtime\core\public\Containers/ArrayView.h(250): note: could be 'InElementType &TArrayView<InElementType>::operator [](int32) const'
3>  F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(134): note: while trying to match the argument list '(TArrayView, int)'
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(134): error C2660: 'ImportTransformChannel': function does not take 3 arguments
3>  F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(70): note: see declaration of 'ImportTransformChannel'
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(135): error C2678: binary '[': no operator found which takes a left-hand operand of type 'TArrayView' (or there is no acceptable conversion)
3>  d:\program files\epic games\ue_4.20\engine\source\runtime\core\public\Containers/ArrayView.h(250): note: could be 'InElementType &TArrayView<InElementType>::operator [](int32) const'
3>  F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(135): note: while trying to match the argument list '(TArrayView, int)'
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(135): error C2660: 'ImportTransformChannel': function does not take 3 arguments
3>  F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(70): note: see declaration of 'ImportTransformChannel'
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(136): error C2678: binary '[': no operator found which takes a left-hand operand of type 'TArrayView' (or there is no acceptable conversion)
3>  d:\program files\epic games\ue_4.20\engine\source\runtime\core\public\Containers/ArrayView.h(250): note: could be 'InElementType &TArrayView<InElementType>::operator [](int32) const'
3>  F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(136): note: while trying to match the argument list '(TArrayView, int)'
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(136): error C2660: 'ImportTransformChannel': function does not take 3 arguments
3>  F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(70): note: see declaration of 'ImportTransformChannel'
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(138): error C2678: binary '[': no operator found which takes a left-hand operand of type 'TArrayView' (or there is no acceptable conversion)
3>  d:\program files\epic games\ue_4.20\engine\source\runtime\core\public\Containers/ArrayView.h(250): note: could be 'InElementType &TArrayView<InElementType>::operator [](int32) const'
3>  F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(138): note: while trying to match the argument list '(TArrayView, int)'
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(138): error C2660: 'ImportTransformChannel': function does not take 3 arguments
3>  F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(70): note: see declaration of 'ImportTransformChannel'
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(139): error C2678: binary '[': no operator found which takes a left-hand operand of type 'TArrayView' (or there is no acceptable conversion)
3>  d:\program files\epic games\ue_4.20\engine\source\runtime\core\public\Containers/ArrayView.h(250): note: could be 'InElementType &TArrayView<InElementType>::operator [](int32) const'
3>  F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(139): note: while trying to match the argument list '(TArrayView, int)'
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(139): error C2660: 'ImportTransformChannel': function does not take 3 arguments
3>  F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(70): note: see declaration of 'ImportTransformChannel'
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(140): error C2678: binary '[': no operator found which takes a left-hand operand of type 'TArrayView' (or there is no acceptable conversion)
3>  d:\program files\epic games\ue_4.20\engine\source\runtime\core\public\Containers/ArrayView.h(250): note: could be 'InElementType &TArrayView<InElementType>::operator [](int32) const'
3>  F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(140): note: while trying to match the argument list '(TArrayView, int)'
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(140): error C2660: 'ImportTransformChannel': function does not take 3 arguments
3>  F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(70): note: see declaration of 'ImportTransformChannel'
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(142): error C2678: binary '[': no operator found which takes a left-hand operand of type 'TArrayView' (or there is no acceptable conversion)
3>  d:\program files\epic games\ue_4.20\engine\source\runtime\core\public\Containers/ArrayView.h(250): note: could be 'InElementType &TArrayView<InElementType>::operator [](int32) const'
3>  F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(142): note: while trying to match the argument list '(TArrayView, int)'
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(142): error C2660: 'ImportTransformChannel': function does not take 3 arguments
3>  F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(70): note: see declaration of 'ImportTransformChannel'
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(143): error C2678: binary '[': no operator found which takes a left-hand operand of type 'TArrayView' (or there is no acceptable conversion)
3>  d:\program files\epic games\ue_4.20\engine\source\runtime\core\public\Containers/ArrayView.h(250): note: could be 'InElementType &TArrayView<InElementType>::operator [](int32) const'
3>  F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(143): note: while trying to match the argument list '(TArrayView, int)'
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(143): error C2660: 'ImportTransformChannel': function does not take 3 arguments
3>  F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(70): note: see declaration of 'ImportTransformChannel'
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(144): error C2678: binary '[': no operator found which takes a left-hand operand of type 'TArrayView' (or there is no acceptable conversion)
3>  d:\program files\epic games\ue_4.20\engine\source\runtime\core\public\Containers/ArrayView.h(250): note: could be 'InElementType &TArrayView<InElementType>::operator [](int32) const'
3>  F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(144): note: while trying to match the argument list '(TArrayView, int)'
3>F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(144): error C2660: 'ImportTransformChannel': function does not take 3 arguments
3>  F:\xermao\Documents\Unreal Projects\tp420\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPySequencer.cpp(70): note: see declaration of 'ImportTransformChannel'

**Comment by rdeioris** [comment]
should be fixed now

**Comment by xermao** [comment]
Yes,you fix so quickly!
