### ISSUE TITLE
How to add LODs to staticmesh with python?

### ISSUE THREAD

**Issue by LegionFu** [20tab/UnrealEnginePython#505]
### **Why my code is doesn't work?**

![image](https://user-images.githubusercontent.com/20501414/44018606-e55700b2-9f0e-11e8-83ae-7b80adeb622d.png)

### **And, The last line output just one key:**
![image](https://user-images.githubusercontent.com/20501414/44018800-7f8d9b46-9f0f-11e8-94da-02842c630ca5.png)

**Comment by rdeioris** [comment]
Hi, the SectionInfoMap is completely under your control.

You can even clear it: FinalMesh.SectionInfoMap.Map = {}

and you will end with all the fields set.

The only thing you need to remember is that the key is a 32bit number, with the first 16bit mapped to the LOD and the others to the section:

```python
index = (lod << 16) | section

FinalMesh.SectionInfoMap.Map = {index: MeshSectionInfo(MaterialIndex=x,bCastShadow=True)}
```

**Comment by LegionFu** [comment]
Thank you so mush~ 👍
