### ISSUE TITLE
Import failed with Python

### ISSUE THREAD

**Issue by xavier150** [20tab/UnrealEnginePython#506]
Hello,
When I try to Import FBX like here [YourFirstAutomatedPipeline.md](https://github.com/20tab/UnrealEnginePython/blob/master/tutorials/YourFirstAutomatedPipeline.md)  I have a error. The classic import with the same fbx works normally
`
FBXImport: Error: Import failed. 
LogPython: Error: unable to create new object from factory
LogPython: Error: Traceback (most recent call last):
LogPython: Error:   File "<string>", line 21, in <module>
LogPython: Error: Exception: unable to create new object from factory
`

I'm using [UnrealEnginePython_20180813_4_20_python36_embedded_win64.zip](https://github.com/20tab/UnrealEnginePython/releases/download/20180813/UnrealEnginePython_20180813_4_20_python36_embedded_win64.zip) with Unreal 4.20.1 on Windows 10. 

Thanks, xavier Loux

**Comment by rdeioris** [comment]
Hi, ensure the factory options/properties are consistent with fbx import (4.20 is a lot more rigid). Can you post the fbx file and the current script ?

**Comment by xavier150** [comment]
Hi rdeioris, I have used the fbx and the script that is used in the tuto. I did not change anything to avoid making mistakes
Fbx : [Kaiju_Assets.zip](https://github.com/20tab/UnrealEnginePython/blob/master/tutorials/YourFirstAutomatedPipeline_Assets/Kaiju_Assets.zip)
Script :
```import os.path
from unreal_engine.classes import PyFbxFactory

# instantiate a new factory
fbx_factory = PyFbxFactory()

# build the path for the fbx file
kaiju_assets_dir = os.path.join(os.path.expanduser('~/Desktop'), 'Kaiju_Assets/Slicer')

slicer_fbx = os.path.join(kaiju_assets_dir, 'slicer.fbx')

# configure the factory
fbx_factory.ImportUI.bCreatePhysicsAsset = False
fbx_factory.ImportUI.bImportMaterials = False
fbx_factory.ImportUI.bImportTextures = False
fbx_factory.ImportUI.bImportAnimations = False
# scale the mesh (the Kaiju is 30 meters high !)
fbx_factory.ImportUI.SkeletalMeshImportData.ImportUniformScale = 0.1;

# import the mesh
slicer_mesh = fbx_factory.factory_import_object(slicer_fbx, '/Game/Kaiju/Slicer')```

**Comment by rdeioris** [comment]
You are right, the 4.20 detection is broken. You can bypass it passing the type of asset to the factory:

```
from unreal_engine.enums import EFBXImportType

fbx_factory.ImportUI.MeshTypeToImport = EFBXImportType.FBXIT_SkeletalMesh
```

I am preparing a new release

**Comment by xavier150** [comment]
Ok, thanks ^^
