### ISSUE TITLE
Best way to call python methods on a PyComponent from a C++ Actor

### ISSUE THREAD

**Issue by pokot0** [20tab/UnrealEnginePython#51]
Hi,

I hope this is a good place to ask questions.

I am experimenting with your project (which is great btw) and I am trying a basic interaction between a C++ Actor and a PyComponent contained in the actor.

What I need is basically call a python function from C++ actor passing parameters from C++ and receving a result from python (all synchronous).

So, i have tried to create the PyComponent object in the C++ Actor and add it to the RootComponent but I am running in a number of issues with includes. The code looks like:

```
#include "UnrealEnginePython.h"
#include "PythonComponent.h"

[....]

myPyComponent = CreateDefaultSubobject<UPythonComponent>(TEXT("MyPyComponent"));
```

Now, when I include the "PythonComponent.h" file, I get errors, probably related to include of Python headers:
```
error C2143: syntax error: missing ';' before '*'
error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
error C2238: unexpected token(s) preceding ';'

```
on this line in PyComponent.h:
`	PyObject *py_component_instance;`

Am i missing something? Am I not supposed to include "PythonComponent.h" in my game? Maybe I am just going down a rabbit hole and there is just a different way to do what I need?

Thanks a lot!
Mike

**Comment by 20tab** [comment]
Using python component should be definitely possible, i will check it and i will add a section in the README about it

**Comment by 20tab** [comment]
Using python component should be definitely possible, i will check it and i will add a section in the README about it

**Comment by rdeioris** [comment]
It looks like adding the following includes is enough:

```c
#include "UnrealEnginePython/Private/UnrealEnginePythonPrivatePCH.h"
#include "UnrealEnginePython/Public/PythonComponent.h"
```

**Comment by pokot0** [comment]
Indeed! Thank you. Sounds strange to have to include something from Private but it does work.

Thanks again for looking into this!
