### ISSUE TITLE
Exception: range must use float or FrameNumber

### ISSUE THREAD

**Issue by heylenz** [20tab/UnrealEnginePython#511]
```import unreal_engine as ue
from unreal_engine.structs import FrameNumber
seq = ue.get_asset('/Game/NewLevelSequence.NewLevelSequence')
start = FrameNumber(value=100)
end = FrameNumber(value=200)
seq.sequencer_set_playback_range(start, end)
```

I can't set FrameNumber in UE4.20.1 !  console reports an error.Exception: range must use float or FrameNumber

**Comment by rdeioris** [comment]
Hi you need to use the native FrameNumber object:

from unreal_engine import FFrameNumber

**Comment by heylenz** [comment]
```
import unreal_engine as ue
from unreal_engine import FFrameNumber

seq = ue.get_selected_assets()[0]
start = FFrameNumber(100)
end = FFrameNumber(120)
seq.sequencer_set_playback_range(start,  end)
```

The program can run, but the result is wrong, the playback start and end at 0 frame！

**Comment by rdeioris** [comment]
FFrameNumber does not work like this. Its value is expressed in the 'TickResolution' (its a property of MovieScene). As an example my TickResolution is 24000/1 (numerator and denominator). It means the frame at second 1 is the FFrameNumber 24000, the frame at second 0.5 is 12000 and so on.

**Comment by heylenz** [comment]
thanks!
