### ISSUE TITLE
Several questions with the sequencer, no API ?

### ISSUE THREAD

**Issue by xavier150** [20tab/UnrealEnginePython#515]
Hello,
I have to create a camera directly in the sequencer like CineCameraActor33 and not in level like CineCameraActor32 http://xavierloux.com/sharex/UE4Editor_2018-08-26_21-31-16.png
I must also rename and include the camera in the folder "ImportedCamera" in sequencer and I need import a fbx animation in the camera
I do not see how to do this and I do not find APIs about sequencing. :/ 

Code: 
```
#This script will import in unreal all camera in target sequencer
#The script must be used in Unreal Engine with UnrealEnginePython.
#About UnrealEnginePython GitHub : https://github.com/20tab/UnrealEnginePython

#Creating a Sequencer Asset
import os.path
import unreal_engine as ue
from unreal_engine.classes import MovieSceneCameraCutTrack, MovieSceneAudioTrack, CineCameraActor

# get a reference to the editor world (to spawn actors)
world = ue.get_editor_world()
MySeq = ue.find_asset("/Game/Animation/ScriptTesting/CameraCutTestingSequence.CameraCutTestingSequence")
if MySeq:
	print("Sequencer valid")
	StartFrame = 1
	EndFrame = 300
	MySeq.sequencer_set_playback_range(StartFrame/24, EndFrame/24)
	camera_cut_track = MySeq.sequencer_add_camera_cut_track()
	cam_folder = MySeq.sequencer_create_folder('ImportedCamera')
else:
	print("Sequencer not valid !")


#Camera01
if MySeq:
	print("Start import camera01")
	FbxLoc = os.path.join('G:\Projet perso\Small Project\BlenderScriptWork\BlenderforUnrealEngineAddon\0.2.0\ExportedFbx\Sequencer\Cam_Camera01.fbx')

	StartFrame = 1
	EndFrame = 106
	camera = camera_cut_track.sequencer_track_add_section()
	cine_camera = world.actor_spawn(CineCameraActor) #I need rename "Camera01"
	camera_guid = MySeq.sequencer_add_actor(cine_camera)
	camera.CameraBindingID = MovieSceneObjectBindingID( Guid=ue.string_to_guid( camera_guid ), Space=EMovieSceneObjectBindingSpace.Local )
	camera.sequencer_set_section_range(StartFrame/24, EndFrame/24)
	#I need import camera animation (FbxLoc) in camera_guid here
	#I need move camera_guid in sequencer in cam_folder here


#End
if MySeq:
	MySeq.sequencer_changed(True)
	print("Import finished")

```
Thanks

**Comment by rdeioris** [comment]
Given your code i suppose you already seen this (and the releated example): https://github.com/20tab/UnrealEnginePython/blob/master/docs/sequencer_API.md

AFAIK you need to create a camera in the world before and then map it to the sequencer (eventually you can change it to a spawnable object). For importing camera curves there is the MovieScene3DTransformSection.sequencer_import_fbx_transform(filename, node) function that takes an fbx file as the source (and the related nodename) and will fill the section

**Comment by xavier150** [comment]
I can not find the information I need with the API

How I can remove a sequencer folder ?
How move a spawnable in a sequencer folder ?
How I can get tracks of a spawnable in sequencer with out create new tracks ?
How I can get tracks of a Component in a spawnable ?
How I can get section of a track without create new section ?
http://xavierloux.com/sharex/UE4Editor_2018-09-05_23-41-00.png

the_class.functions() and the_class.properties() does not indicate all usable function and I do not find that what I need here https://github.com/20tab/UnrealEnginePython/blob/master/Source/UnrealEnginePython/Private/UEPyModule.cpp#L226 I may be looking for not the right words

Thanks, Xavier Loux
