### ISSUE TITLE
Where is PyComponent in Blueprints?

### ISSUE THREAD

**Issue by praveensharma** [20tab/UnrealEnginePython#52]
Hi! Is it possible to create a PythonComponent using blueprints? I only see pyActor pyPawn and pyCharacter in the list of available blueprints.

**Comment by rdeioris** [comment]
If you mean adding it from the blueprint interface, it is called 'Python'

**Comment by praveensharma** [comment]
@rdeioris thanks for the response! Yes - I mean from the "Add New" blueprint interface. For some reason I don't see a blueprint called "Python" only the pyActor / pyPawn and pyCharacter blueprints.

Attached is an img of the search results. I must be missing something obvious here, apologies.

<img width="208" alt="screen shot 2016-10-19 at 10 35 20 am" src="https://cloud.githubusercontent.com/assets/97845/19530221/cf8586fa-95e7-11e6-84c5-3b54e92815c2.png">

**Comment by praveensharma** [comment]
Found it. Its a component within an existing blueprint. Still an Unreal noob here... Closing issue.
