### ISSUE TITLE
how to add a python script component to an actor or spawn

### ISSUE THREAD

**Issue by positiveczp** [20tab/UnrealEnginePython#524]
hello, i want to ask : how to add a python script component to an actor or spawn? thank you

**Comment by rdeioris** [comment]
i suppose you mean "on spawn". You have the "add PythonComponent" node in blueprint that takes the various options (they are all marked as 'expose on spawn')

**Comment by positiveczp** [comment]
thank you

**Comment by positiveczp** [comment]
another question is if i put my python script in directory Scripts/myscript , the plugin will fail to find the Python Module, can you fix this problem

**Comment by rdeioris** [comment]
You have to respect the way the python vm expects modules. If you create subdirectories you need to add the __init__.py and so on

**Comment by positiveczp** [comment]
i add the __init__.py file in the subdirectory , but i also get the error-- No module named test, can i add subdirectory in the scripts?

**Comment by rdeioris** [comment]
You need to specify the full module, so if you have foo/bar/test.py the PythonModule will be foo.bar.test
