### ISSUE TITLE
Rename IDName of an actor 

### ISSUE THREAD

**Issue by xavier150** [20tab/UnrealEnginePython#525]
Hello, When I try to rename an actor I get an fatal error :/ 
I would like to change the id name of my actor in the scene for sequencer

```
	cine_camera_actor = world.actor_spawn(CineCameraActor)
	cine_camera_actor.set_name("MyCamera01")
	print("name: "+cine_camera_actor.get_name())
```

Result:
Fatal error: [File:D:\Build\++UE4\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\Obj.cpp] [Line: 199] Renaming an object (CineCameraActor /Game/Animation/ScriptTesting/SequenceLevel.SequenceLevel:PersistentLevel.CineCameraActor_18) on top of an existing object (CineCameraActor /Game/Animation/ScriptTesting/SequenceLevel.SequenceLevel:PersistentLevel.MyCamera01) is not allowed

Thanks, Xavier Loux

**Comment by rdeioris** [comment]
I am pretty use you want to change the display name (the label) not the low-level name.

Use cine_camera_actor.set_actor_label('Name')
