### ISSUE TITLE
get sequencer spawnable camera track 

### ISSUE THREAD

**Issue by xavier150** [20tab/UnrealEnginePython#530]
Hello, 
After creating a spawnable camera in sequencer http://xavierloux.com/sharex/UE4Editor_2018-09-05_23-41-00.png I have to add keys to the float tracks on the camera component and import a fbx on the track transfom. But I do not know how to get the tracks from the Spawnable Guid. and the function sequencer_spawnable_tracks() does not exist :/

Sorry for my English
Thanks Xavier Loux

**Comment by rdeioris** [comment]
Hi, you can use reflections:

sequencer_asset.MovieScene.ObjectBindings

it is a list of MovieSceneBinding structs

```python
['ObjectGuid', 'BindingName', 'Tracks', 'SortingOrder']
```

check sequencer_asset.MovieScene.Spawnables too

**Comment by xavier150** [comment]
Thanks !
