### ISSUE TITLE
Python class function being passed the 'Outer' object

### ISSUE THREAD

**Issue by estump** [20tab/UnrealEnginePython#531]
I get some unexpected behavior while trying to spawn an instance of a Python class (that is using the Subclassing functionality) inside a blueprint and interact with it. Apparently, the 'Outer' object is being passed in as the 'self' argument rather than the object instance itself.

A simple test case is defined by the following script that builds a Python-defined UObject subclass, a blueprint that will create and use an instance of it, and spawns an instance of the blueprint (blueprint definition below):

```python
import unreal_engine as ue
from unreal_engine.classes import Object, Actor

# Create a class that will belong to an actor
class Foo(Object):
    def __init__(self):
        ue.log_warning(str(self))
        self.value = 1
    def Bar(self):
        ue.log_warning(str(self))
        ue.log('value = %d' % self.value)

# Create a new blueprint that will create and hold a Foo
bp = ue.create_blueprint(Actor, '/Game/FooHolder')
ue.compile_blueprint(bp)
ue.get_editor_world().actor_spawn(bp.GeneratedClass)
ue.open_editor_for_asset(bp)
```

When a ```Foo``` is constructed, it will print out its type, and then the ```Bar``` method will also print out its type and access an attribute.

My ```FooHolder``` blueprint is setup like this (I played around with trying to automate this blueprint build in the script but it got too complicated for me):

![image](https://user-images.githubusercontent.com/134702/45333737-ab882f80-b545-11e8-8fd2-63a82c48fec5.png)

When running it, the log shows:

```
LogPython: Warning: <unreal_engine.UObject 'Foo_0' (0x1b316e1c0) UClass 'Foo' (refcnt: 5)>
LogPython: Warning: <unreal_engine.UObject 'FooHolder_72' (0x19aa8e000) UClass 'FooHolder_C' (refcnt: 5)>
LogPython: Error: 'unreal_engine.UObject' object has no attribute 'value'
LogPython: Error: Traceback (most recent call last):
LogPython: Error:   File "../../../../../Documents/Unreal Projects/Python2/Content/Scripts/bug.py", line 11, in Bar
    ue.log('value = %d' % self.value)
LogPython: Error: AttributeError: 'unreal_engine.UObject' object has no attribute 'value'
```

And so it seems that ```self``` is now pointing to the ```Outer``` instead.

I know that it is actually the ```Outer``` because if I add a member variable to the blueprint and set the ```Foo``` instance to it, then when I call ```Bar```, I can access the original ```Foo``` instance as an attribute of the ```self``` that was passed in.

**Comment by rdeioris** [comment]
Hi, this is the related part of the code: https://github.com/20tab/UnrealEnginePython/blob/master/Source/UnrealEnginePython/Private/PythonFunction.cpp

Maybe Stack.Object always points to the blueprint ? What happens if you add a second Argument to Bar ?

**Comment by estump** [comment]
After some debugging, it became clear that ```Context``` is actually the expected class instance. Seems like it was an API change for 4.19.

I dug through the UE4 source a bit to understand it better. The stack trace looks something like:
```
    frame #2: 0x000000016022bc94 UE4Editor-UnrealEnginePython.dylib`UPythonFunction::CallPythonCallable([...]) at PythonFunction.cpp:22 [opt]
    frame #3: 0x00000001048255ac UE4Editor-CoreUObject.dylib`UFunction::Invoke(UObject*, FFrame&, void*) + 108
    frame #4: 0x0000000104a89b5a UE4Editor-CoreUObject.dylib`UObject::CallFunction(FFrame&, void*, UFunction*) + 7322
[...]
```
And if you look at line 4540 of Engine/Source/Runtime/CoreUObject/Private/UObject/Class.cpp (I'm looking at the 4.19.2 source) where ```Invoke``` is defined, it definitely passes the ```Outer``` of the function in as the ```Context```. If the function is static, then it passes in the class object.

I fixed it and both member and static functions seemed to work as normal. I'll submit a pull request.
