### ISSUE TITLE
Execute python in development console

### ISSUE THREAD

**Issue by crizCraig** [20tab/UnrealEnginePython#535]
Thanks for the amazing project! I'm wondering if I can run Python (like you can now in your the Unreal Editor's Python console) in Unreal's development console (as below) so that I can test commands out in a packaged game.

![unreal dev console](https://media.giphy.com/media/RJy4kBjPzZjm2Y23t1/giphy.gif)

**Comment by crizCraig** [comment]
Just packaged (after adding ue_site.py to the `Content/Scripts`) and this is indeed possible already!


Just tail the logs of the package game with
```
$ tail '<your-package-dir>/LinuxNoEditor/YourGame/Saved/Logs/YourGame.log'
```

Then open the dev console with <kbd>``</kbd> and enter
```
py.cmd print(dir(unreal_engine))
```

to print the following in the tailed log

> [2018.09.16-23.47.47:346][ 38]LogPython: ['ATTACHMENT_RULE_KEEP_RELATIVE', 'ATTACHMENT_RULE_KEEP_WORLD', 'ATTACHMENT_RULE_SNAP_TO_TARGET', 'CLASS_ABSTRACT', 'CLASS_CONFIG', 'CLASS_DEFAULT_CONFIG', 'CLASS_INTERFACE', 'COLLISION_CHANNEL_CAMERA', 'COLLISION_CHANNEL_DESTRUCTIBLE', 'COLLISION_CHANNEL_PAWN', 'COLLISION_CHANNEL_PHYSICS_BODY', 'COLLISION_CHANNEL_VEHICLE', 'COLLISION_CHANNEL_VISIBILITY', 'COLLISION_CHANNEL_WORLD_DYNAMIC', 'COLLISION_CHANNEL_WORLD_STATIC', 'CPF_CONFIG', 'CPF_EXPOSE_ON_SPAWN', 'CPF_GLOBAL_CONFIG', 'CPF_NET', 'CPF_REP_NOTIFY', 'Callable', 'ENGINE_MAJOR_VERSION', 'ENGINE_MINOR_VERSION', 'ENGINE_PATCH_VERSION', 'ESlateEnums', 'EnumsImporter', 'FCharacterEvent', 'FColor', 'FDelegateHandle', 'FGeometry', 'FHitResult', 'FInputEvent', 'FKeyEvent', 'FLinearColor', 'FMenuBuilder', 'FModifierKeysState', 'FMorphTargetDelta', 'FObjectThumbnail', 'FPaintContext', 'FPointerEvent', 'FPythonOutputDevice', 'FQuat', 'FRandomStream', 'FRawAnimSequenceTrack', 'FRotator', 'FSlateApplication', 'FSlateIcon', 'FSlateStyleSet', 'FSocket', 'FTabManager', 'FTabSpawnerEntry', 'FTimerHandle', 'FToolBarBuilder', 'FTransform', 'FVector', 'FViewportClient', 'FoliageInstance', 'IConsoleManager', 'IE_AXIS', 'IE_DOUBLE_CLICK', 'IE_PRESSED', 'IE_RELEASED', 'IE_REPEAT', 'IHttpBase', 'IHttpRequest', 'IHttpResponse', 'IVoiceCapture', 'RF_ARCHETYPEOBJECT', 'RF_ARCHETYPE_OBJECT', 'RF_BEGINDESTROYED', 'RF_BEINGREGENERATED', 'RF_CLASSDEFAULTOBJECT', 'RF_CLASS_DEFAULT_OBJECT', 'RF_DEFAULTSUBOBJECT', 'RF_DUPLICATETRANSIENT', 'RF_DYNAMIC', 'RF_FINISHDESTROYED', 'RF_INHERITABLECOMPONENTTEMPLATE', 'RF_KEEPFORCOOKER', 'RF_LOADCOMPLETED', 'RF_MARKASNATIVE', 'RF_MARKASROOTSET', 'RF_NEEDINITIALIZATION', 'RF_NEEDLOAD', 'RF_NEEDPOSTLOAD', 'RF_NEEDPOSTLOADSUBOBJECTS', 'RF_NEWERVERSIONEXISTS', 'RF_NOFLAGS', 'RF_NONPIEDUPLICATETRANSIENT', 'RF_PUBLIC', 'RF_STANDALONE', 'RF_STRONGREFONFRAME', 'RF_TAGGARBAGETEMP', 'RF_TEXTEXPORTTRANSIENT', 'RF_TRANSACTIONAL', 'RF_TRANSIENT', 'RF_WASLOADED', 'RF_WILLBELOADED', 'SBorder', 'SBox', 'SBoxPanel', 'SButton', 'SCanvas', 'SCheckBox', 'SColorBlock', 'SCompoundWidget', 'SDockTab', 'SEditableTextBox', 'SGridPanel', 'SHeaderRow', 'SHorizontalBox', 'SImage', 'SLeafWidget', 'SListView', 'SMultiLineEditableText', 'SNumericEntryBox', 'SOverlay', 'SPanel', 'SProgressBar', 'SPythonComboBox', 'SPythonListView', 'SPythonMultiColumnTableRow', 'SPythonTreeView', 'SPythonWidget', 'SRotatorInputBox', 'SScrollBox', 'SSlider', 'SSpacer', 'SSplitter', 'STableViewBase', 'STextBlock', 'STreeView', 'SVectorInputBox', 'SVerticalBox', 'SViewport', 'SWidget', 'SWindow', 'UClassesImporter', 'UObject', 'UScriptStruct', 'UStructsImporter', '__doc__', '__loader__', '__name__', '__package__', '__spec__', 'add_on_screen_debug_message', 'add_ticker', 'all_classes', 'all_worlds', 'clipboard_copy', 'clipboard_paste', 'compress_image_array', 'convert_relative_path_to_full', 'copy_properties_for_unrelated_objects', 'create_and_dispatch_when_ready', 'create_checkerboard_texture', 'create_package', 'create_transient_texture', 'create_transient_texture_render_target2d', 'create_world', 'create_wrapper_from_pyswidget', 'destroy_color_picker', 'engine_tick', 'event', 'exec', 'find_class', 'find_enum', 'find_icon_for_class', 'find_object', 'find_slate_style', 'find_struct', 'get_base_filename', 'get_content_dir', 'get_delta_time', 'get_engine_defined_action_mappings', 'get_forward_vector', 'get_game_saved_dir', 'get_game_user_developer_dir', 'get_game_viewport_client', 'get_game_viewport_size', 'get_mutable_default', 'get_or_create_package', 'get_path', 'get_resolution', 'get_right_vector', 'get_swidget_from_wrapper', 'get_transient_package', 'get_up_vector', 'get_viewport_screenshot', 'get_viewport_size', 'invoke_tab', 'load_class', 'load_enum', 'load_object', 'load_package', 'load_struct', 'log', 'log_error', 'log_warning', 'new_class', 'new_object', 'object_path_to_package_name', 'open_color_picker', 'open_directory_dialog', 'open_file_dialog', 'open_font_dialog', 'play_sound', 'print_string', 'py_exec', 'py_gc', 'register_nomad_tab_spawner', 'remove_ticker', 'save_file_dialog', 'set_brutal_finalize', 'set_random_seed', 'shutdown', 'slate_tick', 'tobject_iterator', 'unregister_nomad_tab_spawner']


:snake: :tada: :snake:

**Comment by BillUtada** [comment]
Thanks for sharing~
