### ISSUE TITLE
Is there a way to build from source with embedded python ?

### ISSUE THREAD

**Issue by syedalamabbas** [20tab/UnrealEnginePython#536]
First of all thanks for this plugin, it is great ! However I am facing some issues trying to run this, I have noted some comments below.

1. I tried using the binary installation path, it fails to recognize the module every time I try to compile. Binary path seems like the best option when you simply want to try out some python libraries. 
2. I checked that the version of the dll that I downloaded from your release although it says 4.20 it shows 4.20.2 and the dll that I compile shows file version 4.20.1, these types of problems will occur since you can only do so many binary releases. I cannot compile the binary release !

> Unable to instantiate module 'UnrealEnginePython': System.Exception: Unable to find Python installation	SomeProject  
>  F:\SomeProject\Intermediate\ProjectFiles\UnrealBuildTool	1	
> Error	MSB3075	The command "D:\GitHub\UnrealEngine\Engine\Build\BatchFiles\Build.bat SomeProject Win64 Development "F:\SomeProject\SomeProject.uproject" -WaitMutex -FromMsBuild" exited with code 5. Please verify that you have sufficient rights to run this command.	SomeProjectC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets	44	

3. This is great work, just a suggestion, could you refactor this to have a separate folder with python installation and its related files including scripts and then have C# build code copy the necessary dlls and .exe into Binary during code generation time, I have a couple of other plugins where I do so, namely OpenCV and FLANN.  See below what I use:
 
   

>  private void CopyToBinaries(string Filepath, ReadOnlyTargetRules Target)
>     {
>         string binariesDir = Path.Combine(ModuleDirectory, "..\\..\\Binaries", Target.Platform.ToString());
>         string filename = Path.GetFileName(Filepath);
>         if (!Directory.Exists(binariesDir))
>             Directory.CreateDirectory(binariesDir);
>         if (!File.Exists(Path.Combine(binariesDir, filename)))
>             File.Copy(Filepath, Path.Combine(binariesDir, filename), true);
>     }

**Comment by syedalamabbas** [comment]
Without installing where do I copy the headers from ?

**Comment by rdeioris** [comment]
any source tarball is ok (just check the version)

**Comment by syedalamabbas** [comment]
I tried to set the home as source which has both Lib and Include directories. 
    
>    // Special set up 
>         pythonHome = Path.Combine(ModuleDirectory, "EmbeddedPython/PythonSource");
> 
How do I add the lib path ?

> 2>[WARNING] Your Python installation is not in the system PATH environment variable.
> 2>[WARNING] Ensure your python paths are set in GlobalConfig (DefaultEngine.ini) so the path can be corrected at runtime.
> 2>UnrealBuildTool : error : Unable to instantiate module 'UnrealEnginePython': System.Exception: Invalid Python installation, missing .lib files
> 2>                           at UnrealEnginePython.GetWindowsPythonLibFile(String basePath) in c:\Users\Alam Syed\Documents\Unreal Projects\Project1\Plugins\UnrealEnginePython\Source\UnrealEnginePython\UnrealEnginePython.Build.cs:line 432
> 2>                           at UnrealEnginePython..ctor(ReadOnlyTargetRules Target) in c:\Users\Alam Syed\Documents\Unreal Projects\Project1\Plugins\UnrealEnginePython\Source\UnrealEnginePython\UnrealEnginePython.Build.cs:line 219
> 2>                        (referenced via default plugins -> UnrealEnginePython.uplugin)
> 2>                        (see ../Programs/UnrealBuildTool/Log.txt for full exception trace)

**Comment by syedalamabbas** [comment]
I fixed the lib path problem, but when including the source headers I get another error about the forward and backslash being used. 
SampleProject

> 2>Using Visual Studio 2017 14.15.26726 toolchain (C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726) and Windows 10.0.16299.0 SDK (C:\Program Files (x86)\Windows Kits\10).
> 2>Using Python at: C:\Users\Alam Syed\Documents\Unreal Projects\SampleProject\Plugins\UnrealEnginePython\Source\UnrealEnginePython\EmbeddedPython\PythonSource\Include
> 2>C:\Users\Alam Syed\Documents\Unreal Projects\SampleProject\Plugins\UnrealEnginePython\Source\UnrealEnginePython\UnrealEnginePython.Build.cs : warning : Referenced directory 'C:\Users\Alam Syed\Documents\GitHub\UnrealEngine\Engine\Source\UnrealEnginePython\Public' does not exist.
> 2>UnrealBuildTool : error : In C:\Users\Alam Syed\Documents\Unreal Projects\SampleProject\Plugins\UnrealEnginePython\Source\UnrealEnginePython\EmbeddedPython\PythonSource\PC\_findvs.cpp: #include "external\include\Setup.Configuration.h" contains backslashes ('\'), please use forward slashes ('/') instead.
> 2>                        (see ../Programs/UnrealBuildTool/Log.txt for full exception trace)

**Comment by syedalamabbas** [comment]
Do you need to build python from source for this to work ?

**Comment by rdeioris** [comment]
Nope, check the code i linked to you, your distribution must be into Binaries directory, in this way dll can be found. DO NOT place c/cpp files in the plugin directory, the ue4 build system will add them to the final build (infact you are getting an error)

**Comment by syedalamabbas** [comment]
So If I understand this correctly you are telling that just copy the entire source directory into the Binaries folder ? I have already copied the embedded x64 download like so:

> 
> private void CopyUnrealEnginePython_FilesInBinaries()
>     {
>         string Python_EmbeddablePath = Path.Combine(ModuleDirectory, "EmbeddedPython\\PythonEmbeddable");
>         CopyToBinaries(Path.Combine(Python_EmbeddablePath, "_asyncio.pyd"), Target);
>         CopyToBinaries(Path.Combine(Python_EmbeddablePath, "_bz2.pyd"), Target);
>         CopyToBinaries(Path.Combine(Python_EmbeddablePath, "_contextvars.pyd"), Target);
>         CopyToBinaries(Path.Combine(Python_EmbeddablePath, "_ctypes.pyd"), Target);
>         CopyToBinaries(Path.Combine(Python_EmbeddablePath, "_decimal.pyd"), Target);
>         CopyToBinaries(Path.Combine(Python_EmbeddablePath, "_distutils_findvs.pyd"), Target);
>         CopyToBinaries(Path.Combine(Python_EmbeddablePath, "_elementtree.pyd"), Target);
>         CopyToBinaries(Path.Combine(Python_EmbeddablePath, "_hashlib.pyd"), Target);
>         CopyToBinaries(Path.Combine(Python_EmbeddablePath, "_lzma.pyd"), Target);
>         CopyToBinaries(Path.Combine(Python_EmbeddablePath, "_msi.pyd"), Target);
>         CopyToBinaries(Path.Combine(Python_EmbeddablePath, "_multiprocessing.pyd"), Target);
>         CopyToBinaries(Path.Combine(Python_EmbeddablePath, "_overlapped.pyd"), Target);
>         CopyToBinaries(Path.Combine(Python_EmbeddablePath, "_queue.pyd"), Target);
>         CopyToBinaries(Path.Combine(Python_EmbeddablePath, "_socket.pyd"), Target);
>         CopyToBinaries(Path.Combine(Python_EmbeddablePath, "_sqlite3.pyd"), Target);
>         CopyToBinaries(Path.Combine(Python_EmbeddablePath, "_ssl.pyd"), Target);
>         CopyToBinaries(Path.Combine(Python_EmbeddablePath, "pyexpat.pyd"), Target);
>         CopyToBinaries(Path.Combine(Python_EmbeddablePath, "select.pyd"), Target);
>         CopyToBinaries(Path.Combine(Python_EmbeddablePath, "unicodedata.pyd"), Target);
>         CopyToBinaries(Path.Combine(Python_EmbeddablePath, "winsound.pyd"), Target);
> 
>         CopyToBinaries(Path.Combine(Python_EmbeddablePath, "python37.zip"), Target);
> 
>         CopyToBinaries(Path.Combine(Python_EmbeddablePath, "python37._pth"), Target);
>         CopyToBinaries(Path.Combine(Python_EmbeddablePath, "python.exe"), Target);
>         CopyToBinaries(Path.Combine(Python_EmbeddablePath, "pythonw.exe"), Target);
> 
>         CopyToBinaries(Path.Combine(Python_EmbeddablePath, "libcrypto-1_1-x64.dll"), Target);
>         CopyToBinaries(Path.Combine(Python_EmbeddablePath, "libssl-1_1-x64.dll"), Target);
>         CopyToBinaries(Path.Combine(Python_EmbeddablePath, "python3.dll"), Target);
>         CopyToBinaries(Path.Combine(Python_EmbeddablePath, "python37.dll"), Target);
>         CopyToBinaries(Path.Combine(Python_EmbeddablePath, "sqlite3.dll"), Target);
> 
>     }

**Comment by rdeioris** [comment]
The opposite:

take the python embedded distribution and copy into Binaries (so the python dll is in Binaries).

Then copy includes and libs from a source distribution (only includes and libs, nothing else) into Binaries.

**Comment by syedalamabbas** [comment]
Something is wrong about all this or I am not understanding what needs to be done. 
1. The python source Gzipped source tarball of Python 3.7.0 does not have any folder named "libs". See the [link](https://www.python.org/downloads/release/python-370/).
2. There is however a folder named "Lib" but it does not have have any C++ .lib files that you are searching in the unreal build code. It has lots of python scripts though. 
> string fileName = string.Format("python3{0}.lib", i);
> string fullPath = Path.Combine(basePath, "libs", fileName);
3. I don't understand why do you need to copy include in libs into Binaries folder, since that folder is generated folder that is cleaned all the compile times.
4. As I asked before does this requires to build the source only then I think .lib files for python are generated.

> UnrealBuildTool : error : Unable to instantiate module 'UnrealEnginePython': System.Exception: Invalid Python installation, missing .lib files
> 2>                           at UnrealEnginePython.GetWindowsPythonLibFile(String basePath) in c:\Users\Alam Syed\Documents\Unreal Projects\SomeProject\Plugins\UnrealEnginePython\Source\UnrealEnginePython\UnrealEnginePython.Build.cs:line 483
> 2>                           at UnrealEnginePython..ctor(ReadOnlyTargetRules Target) in c:\Users\Alam Syed\Documents\Unreal Projects\SomeProject\Plugins\UnrealEnginePython\Source\UnrealEnginePython\UnrealEnginePython.Build.cs:line 270
> 2>                        (referenced via default plugins -> UnrealEnginePython.uplugin)
> 2>                        (see ../Programs/UnrealBuildTool/Log.txt for full exception trace)

**Comment by syedalamabbas** [comment]
I finally was able to build this, but not without a python install or even building python would have worked. I am going to create a pull request naming TrueEmbedPython to show I was able to make the plugin self-contained.

**Comment by avivazran** [comment]
@syedalamabbas 
Hi, I've managed to build and use the plugin with unreal 4.25.3 but I'm having trouble embedding a contained python version in my packaged version.
I've looked at the PR but I can;t figure out how you succeded.
can you provide a *detailed explanation*? the explanation in the original README is very unclear.

many thanks
