### ISSUE TITLE
Plugin failed to load

### ISSUE THREAD

**Issue by Devostated** [20tab/UnrealEnginePython#537]
I'm trying to run the 3.7 plugin, but I'm getting this error:
`https://media.discordapp.net/attachments/412326269120806912/492090356507344901/unknown.png`

What I've tried:
UE4 4.20 and 4.19
Python 3.7 and 3.6 in 32 and 64bit (C:\Program Files\Python37 or 36)
Restarting PC after installing Python

The embedded Version works, but I need 3.7.

**Comment by Devostated** [comment]
Fixed it. Forgot to add python to enviorment path.

**Comment by vr-marco** [comment]
You have to make sure you have the path to python.exe (3.7) within your system PATH variable. With that the project will open correctly.
