### ISSUE TITLE
Bulk renaming script issue

### ISSUE THREAD

**Issue by iMitrandir** [20tab/UnrealEnginePython#538]
I wrote a script for adding suffix\prefix to selected in CB assets, but it works strange- some part of the assets were renamed correctly, and for the other the names stayed the same.
 I'm using source control ( Perforce), and before running the script i didn't CheckOut ( but this operation is automatic, when some changes are being made to asset). I've ran this script on ~10k texture assets, some were renamed correctly but some weren't, thought the uasset package name it seems was changed because i couldn't run this script again after reloading project - Error was somthing - asset with this name already exists. 
I'm using rename_asset() because it renames also the uasset package what is very handy.

So why does this happened, does it source control fault, or maybe some old redirectors? 
On another test project ( 200 materials without source control) rename asset() works as expected even without cleaning redirectors

```
import unreal_engine as ue

assets = ue.get_selected_assets()

suffics = '_T'
prefix = ''
loading_class = 'Texture2D'

for asset in assets:
		old_name = asset.get_name()

		full_name = asset.get_full_name()  #Type Path.Name of selected asset
		full_path = full_name.split(' ', 1)[1]  #clean full path with name
		asset_path = full_path.split('.', 1)[0]  #clean full path without name

		#loading asset into memory
		asset_class = ue.find_class(loading_class)
		load_selected_asset = ue.load_object(asset_class, asset_path)


		new_name = prefix + old_name + suffics

		#rename and save ( the package .uasset also will be renamed to amth the asset)
		ue.rename_asset(full_path, new_name)
		
		# asset.set_name(new_name)  #run if rename_ass bugsout

		asset.save_package()


```

**Comment by iMitrandir** [comment]
Yeah, already tried this. 
1. Creat new project ( no source control)
2. import this set of folders with textures (dnd the folder in to the CB window),
3. run script 
The result in my case: some files were renamed, some were not ....
here are this folders with files to reproduse 
https://drive.google.com/open?id=1oP5W-qmrr8biT0YidQo21Lr7ABZEszcm

**Comment by iMitrandir** [comment]
> Maybe some asset is incorrect and failing the whole process- becouse a this messege shows up - File name '_25' resolves to 'None' and cannot be used
Yeah, this was the issue. After this asset all files retained their original names

**Comment by rdeioris** [comment]
Did the script generated some kind of error ? it would be cool to signal this kind of issues

**Comment by iMitrandir** [comment]
Yeah there was an error, sorry missed it in the middle of the night ))
