### ISSUE TITLE
UE4 deferring in_editor_captures

### ISSUE THREAD

**Issue by PhilStewart** [20tab/UnrealEnginePython#542]
I have continued with my batch renderer (as mentioned https://github.com/20tab/UnrealEnginePython/issues/330#issuecomment-423119345 ) but have hit a roadblock:

I have a loop that runs through each pair of level/sequences (a shot) in my project in turn: loading them both, generating a AutomatedLevelSequenceCapture() for that shot, and then calling a ue.in_editor_capture([capture])") on that AutomatedLevelSequenceCapture.
The problem is that UE4 queues up all the in_editor_capture's until it has finished loading the full set of levels/sequences - meaning that when it renders them, they all capture the last level/sequence to be loaded, and I end up with set of videos of the same environment/animation, but slightly different lengths (the captures still respect the frame ranges etc. set in their AutomatedLevelSequenceCapture properties).

Is there a way I can force UE4 to run the captures at the time they are called, instead of deferring them until the loop has run through all the level pairs, or instead a way I can block the loop from continuing until it has completed the capture?

I have also tried passing the in_editor_capture() the full list of AutomatedLevelSequenceCapture's at once, but end up with essentially the same result - videos all captured from the final level/sequence to be loaded in the list.

**Comment by rdeioris** [comment]
Hi, can you post your script ? in_editor_capture() takes a list exactly for this kind of issue. I am not sure to fully understand your problem, but could it be that the sequencer should load the related sequence after each capture ?

**Comment by PhilStewart** [comment]
This is for a short-film which I am rendering in UE4. I have a workflow where each shot is on a different level and uses the sequencer to hold the animations/camera track etc. For each shot the batch renderer needs to load the level/sequencer pair into the UE4 editor, generate the AutomatedLevelSequenceCapture and then render that shot. Then it moves onto the next shot.

The problem is that the in_editor_capture does not begin the render immediately when called, and because I am loading other levels/sequencers, by the time I've run through all the shots and the in_editor_capture begins on the list of renders it has to do, the wrong level/sequencer is loaded in the UE4 editor, so I get a render of the wrong shot.

The problem is that the in_editor_capture does not reload the level/sequence pair that was present when it was called. Similarly, if I pass in_editor_capture a list, all the shots are rendered from the level/sequencer pair that are _currently_ loaded, it does not load the appropriate pair for each shot.

You're right that the sequencer should load the related sequence after each capture, and also load the related level - I was wondering if there was a way to ensure that this happens, or a way to force UE4 to perform the in_editor_capture renders at the time that they are called (when the right level is loaded), rather than in a bunch when I reach the end of the list.

**Comment by PhilStewart** [comment]
This would be a perfect solution, thanks Roberto

**Comment by rdeioris** [comment]
Hi, i have just added a callback that is called before running the PIE capturing session.

Here you can load a new level, setup your actors or whatever you want/need.

Check this example:

https://github.com/20tab/UnrealEnginePython/blob/master/examples/multi_in_editor_capture.py

**Comment by PhilStewart** [comment]
This is really great Roberto, thanks so much for patching it in
