### ISSUE TITLE
Foliage_API question

### ISSUE THREAD

**Issue by iMitrandir** [20tab/UnrealEnginePython#547]
Hello! Could you tell  how to update location\rotation\scale of foliage instance ( i have different SMs and i need to place each of them in the specific coordinates). I tried
foliage_instance.location = FVector(100, 100, 100)
but error says - attribute 'location' of 'unreal_engine.FFoliageInstance' objects is not writable
The foliage_instance has no .properties(), etc so i couldn't find anything. :(

**Comment by iMitrandir** [comment]
Great, all works fine. Thx! The scale is similar to location, correct?

**Comment by iMitrandir** [comment]
One more question :) We have means to create foliage\addSM to the foliage editor, but Is there a way to spawn new foliage instances in the level instead of manually draw them? I'm not so good in c++ yet, so if there is some method in your changelist for this, please point me to it.
The foliage_actor is a UObject so i thought thet there is may be  some UObject's method?
despite foliage_actor.get_foliage_instances(foliage_type) returns a list in instances, it seems you can't simply append new foliage_type to it...

**Comment by hzm** [comment]
compile error in 4.18：

static PyObject *py_ue_ffoliage_instance_get_base_component(ue_PyFFoliageInstance *self, void *closure)
 {
 	get_instance(self);
 	Py_RETURN_UOBJECT(instance->BaseComponent);
 }

BaseComponent is not a member of instance。

**Comment by rdeioris** [comment]
@iMitrandir the AInstancedFoliageActor contains a FoliageInstancedStaticMeshComponent (if it still does not contains one, just add it from python). This component is a subclass of InstancedStaticMeshComponent, from which you can call all of the exposed UFunction's (you can access them with .functions()). The one interesting for you is AddInstanceWorldSpace(transform)
