### ISSUE TITLE
New binary please

### ISSUE THREAD

**Issue by PhilStewart** [20tab/UnrealEnginePython#548]
Would it be possible to get a new binary compiled for 4.20, python 2.7 embedded, win64 please?

**Comment by PhilStewart** [comment]
I've just realised that doing a 2.7 embedded is a lot of extra work - so a 3.6 embedded would be fine, thankyou.

The main thing I need is the new updates from #542 (new in_editor_capture callback)

**Comment by rdeioris** [comment]
Hi, new binary releases should be out during the week end

**Comment by PhilStewart** [comment]
Great - thanks Roberto

**Comment by rdeioris** [comment]
New releases are available

**Comment by PhilStewart** [comment]
Thanks for the updates
