### ISSUE TITLE
Automatically Override Events in subclassing mode

### ISSUE THREAD

**Issue by 20tab** [20tab/UnrealEnginePython#55]
When subclassing, every python callable is mapped to a UE4 function (eventually overridden if it matches a base function). The system should take in account multicast delegates so we can fastly do:

``` py

class Hero(Character):

    def OnActorBeginOverlap(self, .....):
        ...
```

without registering the event in the __init__

**Comment by rdeioris** [comment]
Example here:

https://github.com/20tab/UnrealEnginePython/blob/master/examples/subclassing_simple_example.py
