### ISSUE TITLE
set sequence fps in UE 4.20

### ISSUE THREAD

**Issue by taotang1984** [20tab/UnrealEnginePython#551]
seems MovieScene.FixedFrameInterval doesn't work in UE 4.20.

`seq.MovieScene.FixedFrameInterval = 0.041666667`
This has no effect to the sequence although it has no error.

Also, I was using PlaybackRange to set playback time, it does't work in 4.20 too.
`seq.MovieScene.PlaybackRange = FloatRange(LowerBound=FloatRangeBound(Value=0), UpperBound=FloatRangeBound(Value=100))`

**Comment by PhilStewart** [comment]
Since 4.20 I've been using new commands:

to set fps:
animSequence.MovieScene.DisplayRate.Numerator = 25

to set playback range/time:
animSequence.sequencer_set_playback_range(startFrame, endFrame)

hope these can help you.

**Comment by taotang1984** [comment]
@PhilStewart 
It works! Thanks so much!

**Comment by nasheetzaman** [comment]
'animSequence.MovieScene.DisplayRate.Numerator = 25' works for 4.21, thanks! I have been looking all over for a way to do that :).

However animSequence.sequencer_set_playback_range(startFrame, endFrame) doesn't seem to work in 4.21. Has this changed?

I'm looking for a way to set the frame range everywhere it matters (both the playback range and working range, as well as any tracks if they need to be set individually). Is there a way to set a 'global' frame range for everything in a level sequence?

**Comment by nasheetzaman** [comment]
Figured it out, it's a refresh issue. sequencer_set_playback_range was working fine, but the Sequencer needed to be closed and reopened to see the change.  Also, the frames needed to be divided by the frame rate. Example below. 

```
import unreal_engine as ue

def set_frame_range(seq,frame_start=1001,frame_end=1100,fps=24):
    seq.sequencer_set_playback_range(float(frame_start) / float(fps), float(frame_end) / float(fps))
    seq.sequencer_set_view_range(float(frame_start) / float(fps), float(frame_end) / float(fps))
    seq.sequencer_set_working_range(float(frame_start) / float(fps), float(frame_end) / float(fps))

    ue.close_editor_for_asset(seq)
    ue.open_editor_for_asset(seq)
```

This was helpful:
#636
