### ISSUE TITLE
ViewRange and WorkingRange Question for Sequencer

### ISSUE THREAD

**Issue by pete3d** [20tab/UnrealEnginePython#553]
Hi, 

thanks so much first of all for all the great examples. I managed to use all of it so far to create custom GEO, TEXTURE and CAMERA importer. 
With the camera importer I am stuck at one little thing. 

I need to set the sequencer timeline viewRange and workingRange to reflect this camera properties:
frameStart = 1001
frameEnd = 1100

With print statement I get following properties:

`print seq.MovieScene.EditorData.properties()`
`[u'ExpansionStates', u'ViewStart', u'ViewEnd', u'WorkStart', u'WorkEnd', u'WorkingRange', u'ViewRange']`

`seq.MovieScene.EditorData.ViewStart = 1001`
`# ValueError: invalid value for UProperty`

`from unreal_engine.structs import FloatRange`
`seq.MovieScene.EditorData.WorkingRange = FloatRange(1001/24, 1100/24)`
`# no error get returned but timeline doesn't update`

Any ideas how I can get the working/view range to work?

cheers,
Peter

**Comment by taotang1984** [comment]
I just asked same question, try to use this:
#set fps
seq.MovieScene.DisplayRate.Numerator = 24
#set start and end frame
seq.sequencer_set_playback_range( frameStart *0.041666667, frameEnd *0.041666667)

**Comment by pete3d** [comment]
Thanks Tao. But your example is not what I am after. I already incorporatated the code u mentioned. 
I ll post soon here the camera code if you like. 

What I need is the WorkingRange/ ViewRange slider adjustment. It only can be set through the EditorData properties... which don’t work for me.

**Comment by rdeioris** [comment]
Hi, sequencer_set_view_range(start, end) and sequencer_set_working_range(start, end) have been added

**Comment by pete3d** [comment]
> 
> 
> Hi, sequencer_set_view_range(start, end) and sequencer_set_working_range(start, end) have been added

Fantastic! Thanks Master :)

**Comment by pete3d** [comment]
hi kaedehao, 

sorry for the late reply. Christmas Holidays. :) 

Click the link below. I responded to someone else with similar question.
https://github.com/20tab/UnrealEnginePython/issues/636

Lets improve my method to make it better. I am doing a hack to get the focal length and film back size correclty in. Check it out.
