### ISSUE TITLE
Duplicate Array node outputs

### ISSUE THREAD

**Issue by realtyme** [20tab/UnrealEnginePython#559]
I just updated the plugin and it seems quite a few things have changed.  Anyways,  am trying to add a "MakeArray" node,  but it returns duplicate outputs

graph = blueprint.UberGraphPages[0]
arrayNode = graph. graph_add_node(K2Node_MakeArray)
#set positions here
arrayNode. NumInputs = 5
arrayNode. node_allocate_default_pins()

It returns duplicate [0] elements as well as 2  outputs

**Comment by realtyme** [comment]
Just did a compile,  even though the nodes are blue (staticmeshcomponent),  blueprint error says the array is undetermined. So How do I set it to a specific type,  in this case a static mesh component

**Comment by realtyme** [comment]
Okay!  Am answering my own question. If I call graph_add_node_variable_get("objName") once,  I get no errors,  if I call it from a forloop it errors out. I ended up using this inside the loop to get the meshes. 

node = K2Node_VariableGet()
node. VariableReference = MemberReference(MemberName = "objName", bSelfContext = True) 

And it works. Am bummed, Variable_get? How to use it

**Comment by realtyme** [comment]
Okay!  Am answering my own question. If I call graph_add_node_variable_get("objName") once,  I get no errors,  if I call it from a forloop it errors out. I ended up using this inside the loop to get the meshes. 

node = K2Node_VariableGet()
node. VariableReference = MemberReference(MemberName = "objName", bSelfContext = True) 

And it works. Am bummed, Variable_get? How to use it

And how to set the name of a component and have it update on the blueprint. It updates, but "internally",

**Comment by realtyme** [comment]
Okay!  Am answering my own question. If I call graph_add_node_variable_get("objName") once,  I get no errors,  if I call it from a forloop it errors out. I ended up using this inside the loop to get the meshes. 

node = K2Node_VariableGet()
node. VariableReference = MemberReference(MemberName = "objName", bSelfContext = True) 

And it works. Am bummed, Variable_get? How to use it

And how to set the name of a component and have it update on the blueprint. It updates, but "internally",

**Comment by rdeioris** [comment]
Sorry, can you close this issue and open a new one with the specific question ? Sorry but i completely lost your objective :) Thanks a lot
