### ISSUE TITLE
Renaming shots and sections in the sequencer.

### ISSUE THREAD

**Issue by ekermer** [20tab/UnrealEnginePython#560]
Hey,
does anyone know, if it is possible to rename shots/sections in the sequencer with Python?
I tried something similar to this:
```
master = ue.get_asset("My/Path/To/LevelSequence")
masterTrack = master.sequencer_master_tracks()[0]
masterSections = masterTrack.sequencer_track_sections()
masterSections[0].sequencer_set_display_name("MyDisplayName")
```
but I got the error, that this is not exposed for this type of object.
`Exception: the uobject does not expose the SetDisplayName() method`
Is there a way to manually expose it?

Thank you in advance for your help and time!

**Comment by ekermer** [comment]
... after a few hours of searching and getting a better understanding for the code, here is the answer:
`masterSections[0].set_property("ShotDisplayName", "MyDisplayName")`

**Comment by rdeioris** [comment]
Can i suggest a more readable:

```python
masterSections[0].ShotDisplayName = "MyDisplayName"
```

Unfortunately the only way to understand the UE api is by trying with .properties() and .fields()

**Comment by ekermer** [comment]
Yes, that's much more readable! Thanks for mentioning.
