### ISSUE TITLE
How to get/ set metadata on meshes?

### ISSUE THREAD

**Issue by ekermer** [20tab/UnrealEnginePython#561]
Hey

is there a possible way to get and set metadata of a static and/or skeletal mesh?
I tried this, but it replies with `TypeError: the object does not support MetaData`.
What I tried so far:
```
for i in actors:
    if i.get_class() == StaticMeshActor or i.get_class() == SkeletalMeshActor:
        print i
        comps = i.get_components_by_class(StaticMeshComponent)
        for x in comps:
            mesh = x.StaticMesh
            componentId = mesh.get_metadata("MyMetadataTag")
```

Any ideas?

Thank you in advance for your help and time!

**Comment by rdeioris** [comment]
Afaik, metadata are only for UClasses and UFields.Maybe you are referring to something else ?

**Comment by ekermer** [comment]
This is the metadata I am trying to access.
rightclick imported mesh -> Asset Actions -> Show Metadata
![metadata](https://user-images.githubusercontent.com/41114149/47226224-7d510780-d3af-11e8-9d17-682c6ed27784.png)

**Comment by rdeioris** [comment]
Hi, check this example: https://github.com/20tab/UnrealEnginePython/blob/master/examples/asset_metadata_tag.py

Note that the native api requires the latest code of the plugin, while the reflection based one (heavier) requires loading the  Editor Scripting Utilities plugin (to have access to the EditorAssetLibrary class)

**Comment by ekermer** [comment]
Thank you, 
that's perfect!
