### ISSUE TITLE
Get direct path to referencers of an asset

### ISSUE THREAD

**Issue by ekermer** [20tab/UnrealEnginePython#563]
Hey:)

how can I get the path to references of an object?
I want to check classes of references of my asset (to make sure, I can delete it without trouble).
When I use ` ue.get_asset_referencers("PathToAsset.Package")` I get only paths to the packages of the referencers.
A hacky way would be this, but there has to be something cleaner (or not?).
```
referencers = ue.get_asset_referencers("PathToAsset.Package")
for i in referencers:
    asset = ue.get_asset(i + '.' + os.path.basename(i))
```

Any ideas?

Thank you in advance for your help and time!

**Comment by rdeioris** [comment]
Hi, by looking at unreal sources, you should use ue.get_long_package_asset_name(name) (just added to the code) to retrieve the asset name.
