### ISSUE TITLE
Could not build for Linux CentOS and Unreal 4.20.3

### ISSUE THREAD

**Issue by ekermer** [20tab/UnrealEnginePython#566]
Hey,
I tried the Plugin on Linux today and get a lot of errors if I want to build it.
"The following modules are missing or built with a different engine version:
UnrealEnginePython
PythonAutomation
PythonConsole
PythonEditor
would you like to rebuild them now?"
If I press yes, it prints the following errors:
```
While compiling /mnt/home/elias.kremer/Desktop/MyProject/Intermediate/Build/BuildRules/MyProjectModuleRules.dll:
Desktop/MyProject/Plugins/UnrealEnginePython/Source/UnrealEnginePython/UnrealEnginePython.Build.cs(271,44) : warning CS0618: `UnrealBuildTool.ModuleRules.ReceiptPropertyList.Add(UnrealBuildTool.ReceiptProperty)' is obsolete: `Constructing a ReceiptProperty object is deprecated. Call ReceiptProperties.Add() with the path to the file to stage.
Creating makefile for MyProjectEditor (.uproject file is newer) 
ERROR: Unable to instantiate module 'UnrealEnginePython': System.Exception: Unable to find Python includes, please add a search path to linuxKnownIncludesPaths 
at UnrealEnginePython..ctor (UnrealBuildTool.ReadOnlyTargetRules Target) [0x00000] in <filename unknown>:0 
at (wrapper managed-to-native) System.Reflection.MonoCMethod:InternalInvoke (System.Reflection.MonoCMethod,object,object[],System.Exception&) 
at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0 (referenced via MyProject.uproject -> UnrealEnginePython.uplugin) (see ../Programs/UnrealBuildTool/Log.txt for full exception trace)
```
I just followed the instructions from github. Furthermore, I tried to build it manually with KDevelop which succeeded, but after launching the editor with this project, it asks again for rebuilding it.
Even if I build it as an engine-plugin together with the engine, it does not start.

any suggestions?

Thank you in advance for your help and time!

**Comment by ekermer** [comment]
Hey,

I figured it out .. and some other errors as well. 

`Unable to find Python includes, please add a search path to linuxKnownIncludesPaths `
the solution for this error is very simple. Just look up where your Python is installed and copy the path into `UnrealEnginePython/Source/UnrealEnginePython/UnrealEnginePython.Build.cs` under KnownIncludesPaths. (do the same for the Python lib paths)

If you got errors about redefinition of _XOPEN_SOURCE or _XPOSIX_C_SOURCE, you have to undefine those in ` UnrealEnginePython/Source/UnrealEnginePython/Public/UnrealEnginePython.h`
so unreal can define it by itself.
```
 #elif YOUR_PLATFORM
//add those two lines before including Python.h
#undef _POSIX_C_SOURCE
#undef _XOPEN_SOURCE
#include <Python.h>
```

And if you got this error: `ISO C++11 does not allow conversion from string literal to 'char *'`
you are using a "wrong" c++ version and have to change this file: `UnrealEnginePython/Private/UObject/UEPyCapture.cpp:141:58`
Just go to line 141 and convert the "0" yourself with: `PyObject *py_ret = PyObject_CallFunction(py_callable, (char*)"O", py_capture);`

Hopefully you can rebuild your plugin now, without interruptions.

**Comment by tklinterg** [comment]
I've got the exact same problem and tried to edit the mentioned file but with little progress, the same error persists. I'm using conda, but this should not be making a difference.

Someone who has a clue ?
