### ISSUE TITLE
Cannot get a RootWindow on startup.

### ISSUE THREAD

**Issue by ekermer** [20tab/UnrealEnginePython#568]
Hey:)
when I use `ue.get_editor_window()` on startup in the ue_site.py script, I get this error: `Exception: no RootWindow found`
I think Python is faster then the editor, which may be loaded completely. 
The same thing happens to `ue.get_editor_world()`

Is there a way to wait for the editor?

Thank you in advance for your help and time!

**Comment by rdeioris** [comment]
Hi, use unreal_engine.on_main_frame_creation_finished(callable) to postpone the call of 'callable' after the editor has finished its initialization

**Comment by ekermer** [comment]
Thanks! Makes the code more readable. I don't need the arguments, but for my personal interest, what is the second argument that will be put into my function? (I assume the first is deltatime again, right?)
