### ISSUE TITLE
UnrealEnginePython_20181020_4_19_python27_win64   Can't use

### ISSUE THREAD

**Issue by lsr1994** [20tab/UnrealEnginePython#570]
Hello, I downloaded this version of the file, I installed python2.7 in Windows, and the environment variable path added python's path, but the project was opened incorrectly, please ask for help. Thank you very much!
![ddd](https://user-images.githubusercontent.com/40679973/47550221-16bb7480-d8ee-11e8-8ea3-05f1bfb06326.png)
![bbb](https://user-images.githubusercontent.com/40679973/47550231-1ae79200-d8ee-11e8-8d6e-7630aad7f758.png)
![qwee](https://user-images.githubusercontent.com/40679973/47550264-38b4f700-d8ee-11e8-8d59-fa2c46dee566.png)
![dqqq](https://user-images.githubusercontent.com/40679973/47550270-3fdc0500-d8ee-11e8-88ee-0f7ffd9e4cfb.png)
![qweee](https://user-images.githubusercontent.com/40679973/47550277-48ccd680-d8ee-11e8-9117-5bf84fe79ec4.png)
![qq 20181026150820](https://user-images.githubusercontent.com/40679973/47550280-4bc7c700-d8ee-11e8-8264-8fd61d30842a.png)

**Comment by rdeioris** [comment]
Its the PythonScriptPlugin (the Epic one) that is crashing. Disable it

**Comment by colinzcli** [comment]
Can I use both of epic PythonScriptPlugin and 20tab UnrealEnginePython? @rdeioris
