### ISSUE TITLE
The compilation error in the UEPyFFoliageInstance.cpp

### ISSUE THREAD

**Issue by cyberbibby** [20tab/UnrealEnginePython#575]
Hello author, your plugin is awesome. But when I built the project with the latest source code on UE 4.20, I encountered a compilation error. When I choose a solution configured for Development without the Editor, I get the following compilation error message:

>Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\Wrappers\UEPyFFoliageInstance.cpp(35): error C2039: 'Instances': is not a member of 'FFoliageMeshInfo'
Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\Wrappers\UEPyFFoliageInstance.cpp(37): error C2039: 'Instances': is not a member of 'FFoliageMeshInfo'
Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\Wrappers\UEPyFFoliageInstance.cpp(67): error C2039: 'PreMoveInstances': is not a member of 'FFoliageMeshInfo'
Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\Wrappers\UEPyFFoliageInstance.cpp(69): error C2039: 'PostMoveInstances': is not a member of 'FFoliageMeshInfo'
Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\Wrappers\UEPyFFoliageInstance.cpp(88): error C2039: 'PreMoveInstances': is not a member of 'FFoliageMeshInfo'
Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\Wrappers\UEPyFFoliageInstance.cpp(90): error C2039: 'PostMoveInstances': is not a member of 'FFoliageMeshInfo'

There is no problem with using the solution configure for Development Editor.

I tried using the WITH_EDITOR macro to avoid compiling the relevant code in the file, but it still doesn't work. Do you understand the reason for this issue? Thank you.

**Comment by soTaddel** [comment]
We got the same issue!
Is there any solution? We need to ship the project soon. :sweat: 

Thank you.

**Comment by cyberbibby** [comment]
> We got the same issue!
> Is there any solution? We need to ship the project soon. 
> 
> Thank you.
> 
> > Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\Wrappers\UEPyFFoliageInstance.cpp(33): error C2039: 'Instances': is not a member of 'FFoliageMeshInfo'
> > ParallelExecutor.ExecuteActions:   C:\Program Files\Epic Games\UE_4.20\Engine\Source\Runtime/Foliage/Public/InstancedFoliageActor.h(20): note: see declaration of 'FFoliageMeshInfo'
> > ParallelExecutor.ExecuteActions:   C:\workspace\apps\ProjectName\dev\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\Wrappers\UEPyFFoliageInstance.cpp(33): error C2228: left of '.Num' must have class/struct/union
> > ParallelExecutor.ExecuteActions:   C:\workspace\apps\ProjectName\dev\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\Wrappers\UEPyFFoliageInstance.cpp(35): error C2039: 'Instances': is not a member of 'FFoliageMeshInfo'
> > ParallelExecutor.ExecuteActions:   C:\Program Files\Epic Games\UE_4.20\Engine\Source\Runtime/Foliage/Public/InstancedFoliageActor.h(20): note: see declaration of 'FFoliageMeshInfo'
> 
> and so on..

The easiest but not elegant way is to comment out the relevant code, anyway, these APIs can only be used in the editor.

**Comment by soTaddel** [comment]
That helped!
:+1:

**Comment by michealzhoufeng** [comment]
I think that the guard with #ifdef WITH_EDITOR would be a perfect solution.
