### ISSUE TITLE
 ue_sit.py Where should I store them?

### ISSUE THREAD

**Issue by lsr1994** [20tab/UnrealEnginePython#579]
Where should the ue_sit.py file be stored correctly? I am in? :\Epic_Unreal\ e_4.19 \Engine doesn't find the corresponding folder. For help

**Comment by ekermer** [comment]
By default in your project folder: `YourProject/Content/Scripts/ue_site.py`

**Comment by lsr1994** [comment]
> By default in your project folder: `YourProject/Content/Scripts/ue_site.py`

Wow, thank you very much. I made it. But could it be anywhere else? I want multiple computers to read this one ue_sit.py.

**Comment by ekermer** [comment]
I think you can just point from this file to your main script (that can be stored on a server as a module).
I also transformed this plugin into an engine plugin, by moving it into the main engine folder and set installed in the uplugin file to true.
You could as well make it a content plugin and put your ue_site file into its content directory. In that case, you don't need to create this Scipts/ue_site.py file with every project again.
