### ISSUE TITLE
add_menu_entry How to add  Command？？？？

### ISSUE THREAD

**Issue by lsr1994** [20tab/UnrealEnginePython#581]
Hey, guys, I want to add a def to this menu. What should I do? My def is ‘New’. Ask for help! Thank you!
![qq 20181031103304](https://user-images.githubusercontent.com/40679973/47762593-3ae3d080-dcb5-11e8-887c-0a11fe1a19e2.png)

**Comment by ricardosferro** [comment]
menu.add_menu_entry('Open', 'Open', New)
