### ISSUE TITLE
Does the unrealPython API support UE4 HairWorks Version?

### ISSUE THREAD

**Issue by samsky2017** [20tab/UnrealEnginePython#586]
hi!

i'm using UE4.16.3 HairWorks version(download from https://github.com/NvPhysX/UnrealEngine/tree/HairWorks ), can't load unreal python API.

![image](https://user-images.githubusercontent.com/29967173/47896528-f02aaa00-dea8-11e8-9d97-ef44867313d9.png)
![image](https://user-images.githubusercontent.com/29967173/47896551-046ea700-dea9-11e8-9799-0e8623585ef5.png)
![image](https://user-images.githubusercontent.com/29967173/47896572-19e3d100-dea9-11e8-880c-7cec2ab7781c.png)
![image](https://user-images.githubusercontent.com/29967173/47896590-25cf9300-dea9-11e8-8507-2cc5c7213fe9.png)

is there any solution?

I have tried the following versions of api:
UnrealEnginePython_20180907_4_16_python27_win64
UnrealEnginePython_20181020_4_16_python27_win64
UnrealEnginePython_20181020_4_16_python36_embedded_win64
unrealenginepython_20170911_4_16_python27_win64

thanks!

**Comment by rdeioris** [comment]
Hi, you have to compile it from sources, then it should work

**Comment by samsky2017** [comment]
compile it from sources, means compile the "HairWorks UE4 source", OR compile the "unreal python API source"(https://github.com/20tab/UnrealEnginePython#installation-from-sources-on-windows-64-bit)?

**Comment by rdeioris** [comment]
yep, you just need to compile UnrealEnginePython

**Comment by samsky2017** [comment]
I will give it a try ;-) thanks!
