### ISSUE TITLE
How do I get all Material slot names in turn ？？？

### ISSUE THREAD

**Issue by lsr1994** [20tab/UnrealEnginePython#589]
Hi, guys, I want to get the Material slot name for the FBX model I imported. Add them to an array in order. What should I do? Ask for help
![aa](https://user-images.githubusercontent.com/40679973/47974386-537f2c80-e0a1-11e8-9f1a-de07911c1358.jpg)

**Comment by rdeioris** [comment]
Hi,

```python
import unreal_engine as ue

asset = ue.get_selected_assets()[0]

for material in asset.StaticMaterials:
    print(material.MaterialSlotName)
```

**Comment by lsr1994** [comment]
> Hi,
> 
> ```python
> import unreal_engine as ue
> 
> asset = ue.get_selected_assets()[0]
> 
> for material in asset.StaticMaterials:
>     print(material.MaterialSlotName)
> ```
It's great. Thank you very much.

**Comment by lsr1994** [comment]
@rdeioris   Hi, friend. What should I do if it is SkeletalMesh? I tried: asset.SkeletalMaterials. I got the wrong reply :object has no attribute 'SkeletalMaterials'. Please ask for help. Thank you!

**Comment by lsr1994** [comment]
@rdeioris      Asset.Materials will do. Thank you.
