### ISSUE TITLE
Ticker Functions Only Fired Once

### ISSUE THREAD

**Issue by osstony** [20tab/UnrealEnginePython#59]
Currently the way add_ticker is implemented causes all ticker events to be treated as one shots and not execute repeatedly. The function added to the delegate is expected to return either true or false. If false then the function will not be called again. Is it possible to address this issue with the way add_ticker is currently implemented?

**Comment by rdeioris** [comment]
I think it will be enough to manage the return value here: https://github.com/20tab/UnrealEnginePython/blob/master/Source/UnrealEnginePython/Public/PythonDelegate.cpp#L22

I will work on it tomorrow

**Comment by rdeioris** [comment]
Ok, i investigated it. Basically we need a way to instruct UPythonDelegate (before being mapped to a ticker) to respect a specific signature (and this is easy), but the UPythonDelegate::ProcessEvent function must be extended to support a return value

**Comment by rdeioris** [comment]
Now add_ticker() expects a callable taing a deltatime as argument and returning a boolean.

add_ticker() returns a FDelegateHandle python object that you can pass to the new ue.remove_ticker() to destroy ticker. Let me know how it works for you
