### ISSUE TITLE
How does the asyncio tutorial work?

### ISSUE THREAD

**Issue by javidcf** [20tab/UnrealEnginePython#590]
I apologize because I do not thing this is really an issue, or maybe a documentation issue at most, but it probably is just me not understanding something about one of the tutorials.

I am trying to use asyncio with UEPy. I did not follow any guide for this, I just set up a component and put an asyncio loop in another thread (I still take care that modifications to UObjects are done on the main thread only). This took a bit of trial and error but it's working fine now (you can see the basic no-op thing [here](https://gist.github.com/javidcf/2d57e8dd19f6cd3972097c6349930d41) if you want but I don't think it's relevant, and also is not too pretty).

The thing is, I have only now seen this tutorial [Using asyncio with Unreal Engine](https://github.com/20tab/UnrealEnginePython/blob/master/tutorials/AsyncIOAndUnrealEngine.md), and I do not understand how that can work. The idea is to add a ticker that calls `loop.stop()` and then `loop.run_forever()`, but shouldn't that block the game thread forever, then? Maybe I am not understanding how the game thread actually works. My view was that it is a single thread that goes through every ticking thing on each frame, so hanging on a `tick` would hang everything; in this case, I would have thought this would stop the world until the asyncio program decides to self-stop at some point.

If you could point out why I'm wrong I would really appreciate it. As I said my code does work but I would rather understand the recommended way.

**Comment by rdeioris** [comment]
Hi, mixing threads and asyncio seems a bit 'strange' from my point of view :) asyncio works because it is fully non-blocking, so the unreal engine ticker periodically wake up asyncio that will check if it has something to do, once asyncio has finished it gives back contro to unreal engine. Technically it is very similar to what happens with actor's tick.

**Comment by javidcf** [comment]
@rdeioris Thank you for your answer (sorry, I didn't get a notification for it yesterday for some reason). Yes, you're right, I realize using asyncio with multiple threads is not really how it is supposed to be used. However, if you for example start a TCP server then the task will never finish. And in any case, even when there are no tasks to process `run_forever()` keeps running, so how is it than `tick` gets called again at all? I mean, in order for `run_forever` to finish one would have to call `stop` (presumably from a task within the loop), but the `stop` is in the tick function, so how does the game thread enter `tick` again without finishing the previous `tick` before? Unless the loop somehow ran in a different thread, but I don't think that is the case in the tutorial.

Sorry for insisting, I think there is probably something I am fundamentally misunderstanding here that I just can't figure out.

**Comment by rdeioris** [comment]
It is not very different to how a classic game loops works: you have a series of different objects (actors, tickers, network servers) that do a bunch of tasks and then returns the control to the main loop.

asyncio is the same principle, the unreal loop controls the asyncio loop by waking it at every tick. And yes even if you do not have asyncio task running, asyncio will be activated at each tick by unreal.

You can see it as "cooperative multitasking". I suggest you to check the "reactor pattern"
