### ISSUE TITLE
import LOD for SM

### ISSUE THREAD

**Issue by iMitrandir** [20tab/UnrealEnginePython#591]
Hello! I've looked through snippets and issues but couldn't find appropriate example :( , so Is there a way to import mesh from fbx file to use as LOD on selected in CB static mesh ( Import LOD). And is there a way to assign another mesh from CB to selected as LOD? 
Btw, thanks for your great plugin and help! despite that Epic's have their own ver, their support is 0

**Comment by rdeioris** [comment]
Hi, get latest code, i have added mesh.static_mesh_import_lod(filename, lod_level)

**Comment by iMitrandir** [comment]
Great! thanks a lot!
