### ISSUE TITLE
Failing to Instance Factory

### ISSUE THREAD

**Issue by crispy4004** [20tab/UnrealEnginePython#6]
Following the "Asset Importing" example in the Python Console and encountering an error.

```
import unreal_engine as ue

factory = ue.find_class('TextureFactory')

factory_obj = ue.new_object(factory)
```

If run from an external script I get the following error:
 "argument is not a UObject"
Running directly in the console results in a crash.

Thanks again for adding the import function!  Just wanted to report the bug.

**Comment by 20tab** [comment]
Are you sure you pulled the latest code ?

**Comment by crispy4004** [comment]
Unfortunately yes, did a "git pull" again this morning.

**Comment by rdeioris** [comment]
It should be fixed now. Let me know

**Comment by crispy4004** [comment]
Yup that fixed it.  Thanks again!
