### ISSUE TITLE
Submenu with add_menu_entry?  Is it possible ?

### ISSUE THREAD

**Issue by ricardosferro** [20tab/UnrealEnginePython#603]
Hi Guys,

Is it possible, create a submenu with add_menu_entry?
For example, I put an image of unreal.  Similar to this one...

Thanks a lot.

![image](https://user-images.githubusercontent.com/11772229/48484565-564eef80-e80e-11e8-86ce-8793413850ea.png)

**Comment by ricardosferro** [comment]
Perfect... Thank you for the support...

So, I have been trying and doesn't work.  Do you think maybe the version of my python?
I have been trying to change my version python to 3.6, but I was not able.  

Thanks a lot
Ricardo


The log Error was:

LogPython: Error: 'unreal_engine.FMenuBuilder' object has no attribute 'add_sub_menu'
LogPython: Error: Traceback (most recent call last):
LogPython: Error:   File "//ROCK/rock/PROJECTS/_RnD_/_Unreal_RnD_/RnD/2018_11_001/main.py", line 24, in open_menu
    builder.add_sub_menu('i am a submenu', 'tooltip for the submenu', open_submenu001)
LogPython: Error: AttributeError: 'unreal_engine.FMenuBuilder' object has no attribute 'add_sub_menu'

--------------------------------------------------------

LogPython: import sys
LogPython: print (sys.version)
LogPython: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]

**Comment by unbit** [comment]
Have you updated to the latest code ?

**Comment by ricardosferro** [comment]
Perfect.... Now, it is working perfectly...   TOP
it was the version...

Thanks a lot...  

![image](https://user-images.githubusercontent.com/11772229/49166876-23d3e500-f32c-11e8-90bb-f9ba23dd57bb.png)
