### ISSUE TITLE
Get MovieSceneFrameRange value

### ISSUE THREAD

**Issue by 5775486f** [20tab/UnrealEnginePython#606]
Hi there
I use 

origStart = thisSequencer.MovieScene.PlaybackRange.LowerBound.Value
origEnd = thisSequencer.MovieScene.PlaybackRange.UpperBound.Value

to get start and end of a sequencer

But now when I try to get MovieScene.PlaybackRange got a empty value

how could I get movie scene play back range and Track section range now?

**Comment by AndyZhou1123** [comment]
I have same problem
in sequencer i try seq.MovieScene.PlaybackRange.MovieSceneFrameRange it shows a ustruct there but i try as_dict() and get_field() it all return none value. i can use sequencer.set_playback_range to set value but i can't find way to get value of it

**Comment by AndyZhou1123** [comment]
And same problem for offset too, i try print Parameters.StartFrameOffset in a sequencer object but it also shows value 0, and i am guess 4.20 also move this value to section range, i also notice now it doesn't work when i just change value of Section.StartTime and Section.EndTime. I need use .sequencer_set_section_range() to set value for section. Here is another problem for me, in 4.18 is 2400=1 frame and in 4.20 960=1frame, is there any way for me to distinguish sequencer create by 4.18 or 4.20

**Comment by 5775486f** [comment]
> And same problem for offset too, i try print Parameters.StartFrameOffset in a sequencer object but it also shows value 0, and i am guess 4.20 also move this value to section range, i also notice now it doesn't work when i just change value of Section.StartTime and Section.EndTime. I need use .sequencer_set_section_range() to set value for section. Here is another problem for me, in 4.18 is 2400=1 frame and in 4.20 960=1frame, is there any way for me to distinguish sequencer create by 4.18 or 4.20

**Comment by rdeioris** [comment]
Note that latest release includes get_sequencer_playback_range and get_sequencer_selection_range
