### ISSUE TITLE
Could you pls expose 'Distance Field Resolution Scale'?

### ISSUE THREAD

**Issue by yuchen-sketch** [20tab/UnrealEnginePython#607]
Hi,

I am trying to use some 'Distance Field' related feature in unreal, such as distance field shadowing from a movable light.

I just found it was a bit annoying to adjust the 'distance field resolution scale' for every single static mesh.
Any possibility that this attribute can be exposed?
Therefore I can set this parameter for selected assets or actors.

Thanks.

**Comment by rdeioris** [comment]
Hi, you can already do it:


```python
import unreal_engine as ue

model = ue.get_selected_assets()[0]
model.modify()

for lod in model.SourceModels:
    lod.BuildSettings.DistanceFieldResolutionScale = 2.2

model.post_edit_change()
```

**Comment by yuchen-sketch** [comment]
Thank you.
