### ISSUE TITLE
FSplinePoint?

### ISSUE THREAD

**Issue by AdamGlass** [20tab/UnrealEnginePython#641]
>>> from unreal_engine.classes import FSplinePoint
cannot import name 'FSplinePoint'
>>> from unreal_engine.structs import FSplinePoint
cannot import name 'FSplinePoint'

Do i have to add specific support for FSplinePoint?  I'm trying to work the path of creating a landscape, heightmap, and then a spline and applying the Spline to the Landscape.  That seems to require a SplineComponent and some methods on that use the FSplinePoint.

Unreal 4.20, current UnrealEnginePython bits, python 3.5

**Comment by dfb** [comment]
Generally you omit the first letter used in the UE4 C++ naming convention ('A', 'F', U', etc.) so it's just:

```py
from unreal_engine.structs import SplinePoint
```

**Comment by AdamGlass** [comment]
so these are exceptions? 

from unreal_engine import FVector, FRotator, FTransform, FHitResult

**Comment by AdamGlass** [comment]
Thanks -- that helps a lot.
