### ISSUE TITLE
BlueprintGeneratedClass.GetActorBounds Causes Fatal Error

### ISSUE THREAD

**Issue by osstony** [20tab/UnrealEnginePython#65]
Calling the UFunction GetActorBounds causes an uncoverable fatal error.

**Comment by rdeioris** [comment]
Hi, can you paste a code example. The GetActorBounds() UFunction should return a tuple of 2 FVector:

```py
actor = ue.get_selected_assets()[0]
ue.log(actor.GeneratedClass.GetActorBounds())

(<unreal_engine.FVector object at 0x169fd4790>, <unreal_engine.FVector object at 0x169fd4dd0>)
```

**Comment by osstony** [comment]
I think the issue was running this on a Blueprint instance and not a GeneratedClass instance. I didn't understand how to properly get a GeneratedClass from a name at first. Might be useful to simplify some of the interactions in the future once the bindings mature a bit more.

**Comment by rdeioris** [comment]
@osstony absolutely, feel free to propose shortcuts
