### ISSUE TITLE
Can I use __init__.py with dynamic reload?

### ISSUE THREAD

**Issue by HueyPark** [20tab/UnrealEnginePython#66]
If I use __init__.py UnrealEngine can't reload module dynamically

Can you handle this?

**Comment by Amorano** [comment]
If you have code you need to hot reload, you should put it inside another module, and reload that module when needed/code changes.

This is not an issue with the library, that is just fundamental python use.

**Comment by HueyPark** [comment]
@Amorano Thank you for your support.
