### ISSUE TITLE
how can I get the full path of the current project? 

### ISSUE THREAD

**Issue by lsr1994** [20tab/UnrealEnginePython#672]
Hey guys, how can I get the full path of the current project? I get a relative path using 'get_content_dir()'. Ask for help!
![image](https://user-images.githubusercontent.com/40679973/52763937-c3447200-3015-11e9-9858-1f51461eb479.png)

**Comment by slartibaartfast** [comment]
One way you could get the full path of your project is by using the [os.path](https://docs.python.org/3/library/os.path.html) module.

```
import os
import unreal_engine as ue

# get the content directory
content_dir = ue.get_content_dir()

# get the absolute path to the content directory
abspath = os.path.abspath(content_dir)

# split the project directory into the variable 'project_dir'
project_dir, tail = os.path.split(abspath)
```

**Comment by lsr1994** [comment]
@slartibaartfast Thank you very much, my friend. I just need this.
