### ISSUE TITLE
Deadlock with SetPythonAttr from C++ Callback

### ISSUE THREAD

**Issue by Pepin-** [20tab/UnrealEnginePython#68]
Hi,
I am experiencing a deadlock when I call SetPythonAttrObject from within a C++ function invoked from Python. Is this something that should work currently? I have threading enabled, but everything UE-related is on the main thread. Other thread is running an async event loop that wouldn't be blocking.

**Comment by unbit** [comment]
Disable threading support, it currently introduces lot of implications when the call stack is pretty complex

**Comment by Pepin-** [comment]
Hmm, I'll see if I can work around this somehow... Unfortunately I need threading support for a framework I'm running alongside UEPython.

**Comment by Pepin-** [comment]
For my purposes, this solution seems to work for now:
https://github.com/Pepin-/UnrealEnginePython/commit/c97d57b3ba8ecebf9f64ace76813ebc075bea0dd

**Comment by rdeioris** [comment]
i think it is the only viable appeoach. i will refactor it a bit and i will merge. thanks

**Comment by rdeioris** [comment]
Can you try if the latest code fixes the issue ?

**Comment by Pepin-** [comment]
Hi, I tried with your changes instead and they seem to crash the editor on my end...

**Comment by rdeioris** [comment]
Are you using python2 or 3 ?

**Comment by Pepin-** [comment]
python3

**Comment by rdeioris** [comment]
Please, try again with latest code, i have made the gil scope struct smarter

**Comment by Pepin-** [comment]
Sorry for the delay. This new changes seem to work!
