### ISSUE TITLE
Wiki and/or Pages

### ISSUE THREAD

**Issue by Kiruse** [20tab/UnrealEnginePython#682]
I've been fighting my way through the docs and the readme for the past couple of hours. So far I'm a fan of the project, but I find it extremely difficult to find the information I'm looking for, especially because information on one topic may be scattered throughout the entire documentation.

I thus think it would greatly benefit the project if there was a community maintainable wiki or GitHub Pages repo available. I'd be invested enough to contribute a few of my findings...

Cheers!

**Comment by yobiminds** [comment]
I think it depends on the future of this project. See Issue [678](https://github.com/20tab/UnrealEnginePython/issues/678).

**Comment by Kiruse** [comment]
It is indeed quite obvious that this project demands a lot of care and attention and I am grateful that it exists. In fact, I was quite surprised to see that it had recent commits. I hope it continues to exist, but I doubt it's feasible to bear its weight on the shoulders of a small "David" company as a side project in light of the Goliath that is UE4.

The only viable solution that I see is maintaining it through a thriving open source community, which would probably involve such a wiki. ;)

**Comment by varomix** [comment]
Hi guys, we are also looking for docs
is there anything similar to this https://docs.unrealengine.com/en-US/PythonAPI/index.html
or can it be generated some how?

thank you
