### ISSUE TITLE
Annotating Array, Set and Dictionaries (attributes & parameters) (native subclassing)

### ISSUE THREAD

**Issue by Kiruse** [20tab/UnrealEnginePython#683]
When using native subclassing API, the docs demonstrate how to create a float array property, but there is no talk of TDictionaries or TSets. Are those possible yet?

Furthermore I have not been able to create a function which takes an array either. I tried `list`, `list(str)` and `[str]`, but `list` isn't supported altogether (missing `__args__` attribute) and `[str]` cannot be parsed (leaving the parameter ignored). Is this not possible yet?

**Comment by dfb** [comment]
For the function param stuff, see PR #635 for an unofficial patch that adds support for it. Unsupported, but we've been using it in our project for awhile and it's worked well for us. With the patch you can have e.g.:

```py
def Foo(stuff : [str]) -> [bool]:
     ...
```

for a function that takes an array of strings and returns an array of bools.
