### ISSUE TITLE
Take my money, please?

### ISSUE THREAD

**Issue by svfgit** [20tab/UnrealEnginePython#7]
You guys are completely awesome. My dream since ue4 was released was to have Python in the mix.  Python is like, the perfect match for ue4 and the blueprint system. SO many possibilities here.  I tried, tried to drop in cpython, SWIG, and failed badly. Crashes and errors galore.

My plan was to use Kivy ports to get things to work on mobile as well. 

How can I help? What kind of hacking needed? Oh, feel free to close this issue once you guys all admit you're the coolest thing that's happened to ue4. This is testament to the best part of open source.

**Comment by unbit** [comment]
Hi, thanks a lot :)

Well, Kivy support would be really awesome, if you want to help in this area you will be really welcomed.

Thanks again for your support

**Comment by svfgit** [comment]
Great, I will grab the recent ue4 and investigate Kivy support. Thank you!!

**Comment by rdeioris** [comment]
Android support has been added: https://github.com/20tab/UnrealEnginePython/blob/master/docs/Android.md
