### ISSUE TITLE
Accessing Static Mesh BuildSettings causes crash

### ISSUE THREAD

**Issue by LarsGroh** [20tab/UnrealEnginePython#73]
Hi,

I tried this and it caused unreal to crash when I attempt to open the Static Mesh asset from the Content Browser
(It acutally already crashes when I open the Folder "ImportTest" in the Content Browser):
```
import unreal_engine as ue
from unreal_engine.classes import StaticMesh
sm = ue.load_object(StaticMesh, "/Game/ImportTest/my_static_mesh")
source_model = sm.SourceModels[0]
source_model.BuildSettings.bUseFullPrecisionUVs = True
```

I am aware that when you do this within the UI you need to press the "ApplyChanges" button.
Any way to get this working?

**Comment by rdeioris** [comment]
It looks like this part of the unreal api is more complex than the others. i will check if i can track it diwn. thanks for reporting

**Comment by LarsGroh** [comment]
Any news on this one?

**Comment by rdeioris** [comment]
Structs support has fixed it (note the clone() usage as structs are passed by value)

```python
source_model = mesh.SourceModels[0].clone()
build_settings = mesh.SourceModels[0].BuildSettings.clone()
build_settings.bUseFullPrecisionUVs=True
# reassign build settings
source_model.BuildSettings = build_settings

# apply back
mesh.SourceModels = [source_model]

```
