### ISSUE TITLE
Rotate Texture

### ISSUE THREAD

**Issue by sinokgr** [20tab/UnrealEnginePython#74]
Hi Guys,

The artists asked me today if I could develop a tool to rotate the selected texture in the content browser by 90 degrees. Unreal doesn't support it by default, so the idea was to export (convert the uasset to a readable file format) -> rotate -> re-import.

Thanks,
Nick

**Comment by rdeioris** [comment]
I have just added a preliminary texture api:

```py
tex = ue.load_object(Texture2D, '/Game/xxxxx')
data = tex.texture_get_data()
````

in 'data' you now have a bytearray with the raw texture data. You can modify it and reapply back to the texture with:

```py
tex.texture_set_data(data)
```

take in account both texture_get_data() and texture_set_data() takes an optional int argument for the mipmap. By default the map 0 is used. I think the best approach is setting the texture to 'NoMipMaps', modify the texture data and then set back to what you need.

**Comment by sinokgr** [comment]
Thanks for that too but how do you edit an image when it's a bytearray format in Python?
I tried to use PIL.Image because it has a [frombytes
](http://pillow.readthedocs.io/en/3.1.x/reference/Image.html#PIL.Image.frombytes) function but it errors.
```python
PIL.Image.frombytes(mode, size, data, decoder_name='raw', *args)
```

Here is what I've tried but it errors.
```python
import unreal_engine as ue
from PIL import Image

Texture2D = ue.find_class('Texture2D')
tex = ue.load_object(Texture2D, '/Game/Maps/European_Oak_WOODEN_DOORS_BUMP')
data = tex.texture_get_data()

img = Image.frombytes("RGB", (2523, 2523), data)
```
But to be honest, even if that worked, I'm not sure how I would get the _size_ and the _mode_ from the Binary data.


Another thing that seems to work in most cases is that, but because it's based on the absolute path, I would prefer if I could make your approach to work.

```python
import os
from PIL import Image
import unreal_engine as ue
from shutil import copy2


def deleteFile(filename):
	if os.path.exists(filename):
		try:
			os.remove(filename)
			return True
		except:
			return False
	else:
		return True

def moveFile(src, dst):
	if deleteFile(dst):
		os.rename(src, dst)
		return True
	else:
		return False
	
def rotateSelectedAssets(degrees):
	if len(ue.get_selected_assets()):
		for asset in ue.get_selected_assets():
			if asset.get_class().get_name() == 'Texture2D':
				import_data = asset.asset_import_data()[0]
				absolute_filepath = import_data['absolute_filepath']
				absolute_filepath_temp = absolute_filepath + ".tmp"
				
				if os.path.exists(absolute_filepath):
					# Delete the temp file if already exists
					if deleteFile(absolute_filepath_temp):
						# Backup file
						copy2(absolute_filepath, absolute_filepath_temp)
						
						# Rotate file and re-import
						im = Image.open(absolute_filepath)
						out = im.rotate(degrees, expand=1)
						out.save(absolute_filepath,quality=100)
						asset.asset_reimport()
						
						# Restore original file
						moveFile(absolute_filepath_temp, absolute_filepath)
					else:
						ue.log_warning("Asset " + asset.get_name() + " failed to rotate. Temp file couldn't be deleted.")
				else:
					ue.log_warning("Asset " + asset.get_name() + " absolute path is invalid. " + absolute_filepath)
			else:
				ue.log_warning("Asset " + asset.get_name() + " is not a Texture2D asset.")
		ue.message_dialog_open(ue.APP_MSG_TYPE_OK, "Finished.")
	else:
		ue.message_dialog_open(ue.APP_MSG_TYPE_OK, "Finished")
```

**Comment by rdeioris** [comment]
Hi, calling bytes(data) (where data is a bytearray) will return a bytes object.

The size of the image is exposed as Texture2D properties. The only part i am not actualy sure about,it is how many bytes per pixel are used by default. It should be 4, but it looks like (from simple math) that it is 5

**Comment by sinokgr** [comment]
Not sure I'm following about the per pixel data. Are you trying to figure out the BitDepth? if it's an RGB or RGBA?

I've tried casting the ByteArray and getting the the size from the Texture2D properties and I'm getting a new error saying "ValueError: not enough image data". This specific image is a PNG with no alpha. I've tried both "RGB" and "RGBA" though.

```py
def rotateSelectedAssets():
	Texture2D = ue.find_class('Texture2D')
	for asset in ue.get_selected_assets():
		if asset.get_class() == Texture2D:
			tex = ue.load_object(Texture2D, asset.get_path_name())
			data = bytes(tex.texture_get_data())
			size = (asset.Blueprint_GetSizeX(), asset.Blueprint_GetSizeY())
			
			img = Image.frombytes("RGB", size, data)
```

**Comment by rdeioris** [comment]
It should be RGBA, but check if data is not empty. If it is empty, force the texture to not generate mipmaps

**Comment by sinokgr** [comment]
I've tried both RGB and RGBA with a PNG and a JPEG, with PowerOfTwo and random size, with mipmaps from Texture Group or no mipmaps but it doesn't seem to work.
This _sys.getsizeof(data)_ also seems to report that the data is not empty

**Comment by rdeioris** [comment]
Ok, i'll try to work on it in the next few days using your script as a base

**Comment by sinokgr** [comment]
Many thanks for that! Since yesterday I tried a number of things.. this is a bit more complete code snippet

```Python
def rotateSelectedAssets():
	Texture2D = ue.find_class('Texture2D')
	for asset in ue.get_selected_assets():
		if asset.get_class() == Texture2D:
			tex = ue.load_object(Texture2D, asset.get_path_name())
			data = bytes(tex.texture_get_data())
			size = (asset.Blueprint_GetSizeX(), asset.Blueprint_GetSizeY())
			ue.log(sys.getsizeof(data)) # 6512673
			
			img = Image.frombytes("RGB", size, data)
			ue.log(img)
			out = img.rotate(90, expand=1)
			tex.texture_set_data(bytearray(data))
			ue.log("finished")
```

I was experimenting with a specific texture which returns a size of 814113 and then crash. There were a couple of times though, that I go a size of 6512673 and only those times it seemed to work fine (it wasn't rotating it though) but then it stopped again. I've tried to be very thorough on my testing but I can't reproduce how it worked these few times. Here is a [link](https://1drv.ms/i/s!AkpIm5Ify5v9no4RgWD2HGw0AIjliw) from this texture. I know it's not the best example, but it's the only one that worked even for a few attempts but I can't get it to work again.

**Comment by sinokgr** [comment]
I finally managed to reproduce the issue!

1. Drag the image in the Content Browser
2. Hit Ctrl+S to save.

If you run the tool now it will crash or even if you try to right-click>Reimport it will crash.

To make it work you have to:

1. Make sure the file is saved (Ctrl+S)
2. Double click the texture to open the Texture Editor (or right click>Edit..)
3. Use the Reimport icon from the top toolbar
4. Run the script. 

If you follow this steps, it should work. I fixed some bugs in my code and I've added the img.show().
This will pop-up an image with how the bytesArray is converted to bytes
```py
def rotate_selected_assets_data(degrees):
    for asset in ue.get_selected_assets():
        if asset.get_class() == Texture2D:
            tex = ue.load_object(Texture2D, asset.get_path_name())
            data = bytes(tex.texture_get_data())
            size = (asset.Blueprint_GetSizeX(), asset.Blueprint_GetSizeY())
            ue.log(sys.getsizeof(data))  # 6512673

            img = Image.frombytes("RGB", size, data)
            img.show()
            out = img.rotate(degrees, expand=1)
            tex.texture_set_data(bytearray(out.tobytes()))
        ue.log("finished")
```

Hope that helps

**Comment by rdeioris** [comment]
I Leave this open as a note to add this snippet to the docs
