### ISSUE TITLE
Deadlock In py_ue_save_package

### ISSUE THREAD

**Issue by osstony** [20tab/UnrealEnginePython#75]
I am currently hitting a deadlock when trying to execute line #762 
  
    if (!self->ue_object->Rename(*(self->ue_object->GetName()), package))

Is running Rename necessary? I haven't been able to track down why the deadlock is occurring.

**Comment by osstony** [comment]
I should note I am running this on an existing package.

**Comment by osstony** [comment]
Commenting this out allows me to run a reimport/package save successfully.

**Comment by rdeioris** [comment]
i'll check it. thanks for reporting

**Comment by rdeioris** [comment]
I have refactored save_package() to be more smart:

- calling it without argument on an object already mapped to a package, will result in saving it in the same path (update)
- calling it with argument, will result in a new object (the object is returned) that is a copy of the original one, but saved in a new package under the specified name
- calling it without argument on an object without package will result in error
- calling it with argument, will result in saving the object in a new package

**Comment by osstony** [comment]
Great, I will give it a shot. Thank you!

**Comment by osstony** [comment]
Found a small issue which is addressed by pull request #76.

**Comment by osstony** [comment]
Going to close this now, thank you for addressing it!
