### ISSUE TITLE
Changing material of specified material slot

### ISSUE THREAD

**Issue by AgenteDog** [20tab/UnrealEnginePython#776]
Hey, so I have been trying to search but haven't been able to find anything. Is there a way to change the materials in a static mesh by material slot name?

![image](https://user-images.githubusercontent.com/54131016/64216708-46e28500-ceba-11e9-8362-5276899bbbcb.png)
As you can see in this image I have 4 material slots, and, I know already the names of these slots. Is there any way that I can replace/assign a material to a specified slot? 

So if I want to change the material of the material slot number 3 (mtl_p6_tree_palm_date_cuts) I just specify stuff like the mesh, the material slot and the material that I want to assign.

If it is possible (I imagine that it is) how can I do it?

**Comment by AgenteDog** [comment]
For those curious, I ended up fixing it...

`
            asset = ue.load_object(StaticMesh, location)
            for index, material in enumerate(asset.StaticMaterials):
                if material.MaterialSlotName == name:
                    component = ue.load_object(StaticMesh,location)
                    material = ue.load_object(Material, location)
                    component.set_material(index, material);
`

**Comment by DemoImprove** [comment]
Hello brother, thank you very much for providing this discussion for my reference. I am using version UE4.18, but I encountered an error while using your above method:
uobject is not a UPrimitiveComponent
Traceback (most recent call last):
  File "<string>", line 13, in <module>
Exception: uobject is not a UPrimitiveComponent
<img width="1014" alt="111" src="https://github.com/20tab/UnrealEnginePython/assets/145335974/4878cdb3-9b48-4fc9-8697-24eb717ba81f">
