### ISSUE TITLE
Can I directly compile the source code to 4.23?

### ISSUE THREAD

**Issue by Sengunbanba** [20tab/UnrealEnginePython#777]

**Comment by rdeioris** [comment]
Yes, 4.23 is supported, just clone the master branch

**Comment by Sengunbanba** [comment]
> 是的，支持4.23，只需克隆主分支
I did the same thing as the previous version 4.22, but I didn't succeed. Here's the partial output.

‘’‘
1>------ Rebuild All started: Project: CPP423, Configuration: Development_Editor x64 ------
1>Cleaning CPP423Editor and UnrealHeaderTool binaries...
1>Creating makefile for CPP423Editor (no existing makefile)
1>Using Python at: C:/Users/Drock/AppData/Local/Programs/Python/Python36
1>Parsing headers for CPP423Editor
1>  Running UnrealHeaderTool "D:\UE4_test\UE4_test-423\CPP423\CPP423.uproject" "D:\UE4_test\UE4_test-423\CPP423\Intermediate\Build\Win64\CPP423Editor\Development\CPP423Editor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -installed
1>Reflection code generated for CPP423Editor in 5.7355076 seconds
1>Using Visual Studio 2017 14.16.27023 toolchain (C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023) and Windows 10.0.17763.0 SDK (C:\Program Files (x86)\Windows Kits\10).
1>Distributing 240 actions to XGE
1>--------------------Build System Warning---------------------------------------
1>License is invalid:
1>    License information is invalid. Please try reloading your license file using the Coordinator Monitor application on the Coordinator machine, or reinstall IncrediBuild.
1>    This build will run in standalone mode.
1>
1>-------------------------------------------------------------------------------
1>--------------------Project: Default-------------------------------------------
1>SharedPCH.UnrealEd.cpp (0:16.26 at +0:00)
1>SharedPCH.Engine.cpp (0:18.31 at +0:16)
1>UEPyICollectionManager.cpp (0:01.45 at +0:34)
1>UEPyIConsoleManager.cpp (0:01.53 at +0:36)
1>UEPyFbxImporter.cpp (0:05.04 at +0:37)
1>UEPyFbxIOSettings.cpp (0:05.00 at +0:42)
1>UEPyFbxManager.cpp (0:04.87 at +0:47)
1>UEPyFbxMesh.cpp (0:04.87 at +0:52)
1>UEPyFbxNode.cpp (0:04.81 at +0:57)
1>UEPyFoliage.cpp (0:01.36 at +1:02)
1>D:\UE4_test\UE4_test-423\CPP423\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPyFoliage.cpp(41): error C2039: 'FoliageMeshes': is not a member of 'AInstancedFoliageActor'
1>C:\Program Files\Epic Games\UE_4.23\Engine\Source\Runtime/Foliage/Public/InstancedFoliageActor.h(67): note: see declaration of 'AInstancedFoliageActor'
1>D:\UE4_test\UE4_test-423\CPP423\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPyFoliage.cpp(71): error C2039: 'FoliageMeshes': is not a member of 'AInstancedFoliageActor'
1>C:\Program Files\Epic Games\UE_4.23\Engine\Source\Runtime/Foliage/Public/InstancedFoliageActor.h(67): note: see declaration of 'AInstancedFoliageActor'
1>D:\UE4_test\UE4_test-423\CPP423\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPyFoliage.cpp(76): error C2065: 'FFoliageMeshInfo': undeclared identifier
1>D:\UE4_test\UE4_test-423\CPP423\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPyFoliage.cpp(76): error C2065: 'info': undeclared identifier
1>D:\UE4_test\UE4_test-423\CPP423\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPyFoliage.cpp(76): error C2039: 'FoliageMeshes': is not a member of 'AInstancedFoliageActor'
1>C:\Program Files\Epic Games\UE_4.23\Engine\Source\Runtime/Foliage/Public/InstancedFoliageActor.h(67): note: see declaration of 'AInstancedFoliageActor'
1>D:\UE4_test\UE4_test-423\CPP423\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPyFoliage.cpp(80): error C2065: 'info': undeclared identifier
1>D:\UE4_test\UE4_test-423\CPP423\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPyFoliage.cpp(114): error C2039: 'GetLocalFoliageTypeForMesh': is not a member of 'AInstancedFoliageActor'
1>C:\Program Files\Epic Games\UE_4.23\Engine\Source\Runtime/Foliage/Public/InstancedFoliageActor.h(67): note: see declaration of 'AInstancedFoliageActor'
1>
1>Error executing C:\Program Files\Epic Games\UE_4.23\Engine\Build\Windows\cl-filter\cl-filter.exe (tool returned code: 2)
’‘’

**Comment by Sengunbanba** [comment]
> Yes, 4.23 is supported, just clone the master branch

I did the same thing as the previous version 4.22, but I didn't succeed. Here's the partial output.

‘’‘
1>------ Rebuild All started: Project: CPP423, Configuration: Development_Editor x64 ------
1>Cleaning CPP423Editor and UnrealHeaderTool binaries...
1>Creating makefile for CPP423Editor (no existing makefile)
1>Using Python at: C:/Users/Drock/AppData/Local/Programs/Python/Python36
1>Parsing headers for CPP423Editor
1> Running UnrealHeaderTool "D:\UE4_test\UE4_test-423\CPP423\CPP423.uproject" "D:\UE4_test\UE4_test-423\CPP423\Intermediate\Build\Win64\CPP423Editor\Development\CPP423Editor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -installed
1>Reflection code generated for CPP423Editor in 5.7355076 seconds
1>Using Visual Studio 2017 14.16.27023 toolchain (C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023) and Windows 10.0.17763.0 SDK (C:\Program Files (x86)\Windows Kits\10).
1>Distributing 240 actions to XGE
1>--------------------Build System Warning---------------------------------------
1>License is invalid:
1> License information is invalid. Please try reloading your license file using the Coordinator Monitor application on the Coordinator machine, or reinstall IncrediBuild.
1> This build will run in standalone mode.
1>
1>-------------------------------------------------------------------------------
1>--------------------Project: Default-------------------------------------------
1>SharedPCH.UnrealEd.cpp (0:16.26 at +0:00)
1>SharedPCH.Engine.cpp (0:18.31 at +0:16)
1>UEPyICollectionManager.cpp (0:01.45 at +0:34)
1>UEPyIConsoleManager.cpp (0:01.53 at +0:36)
1>UEPyFbxImporter.cpp (0:05.04 at +0:37)
1>UEPyFbxIOSettings.cpp (0:05.00 at +0:42)
1>UEPyFbxManager.cpp (0:04.87 at +0:47)
1>UEPyFbxMesh.cpp (0:04.87 at +0:52)
1>UEPyFbxNode.cpp (0:04.81 at +0:57)
1>UEPyFoliage.cpp (0:01.36 at +1:02)
1>D:\UE4_test\UE4_test-423\CPP423\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPyFoliage.cpp(41): error C2039: 'FoliageMeshes': is not a member of 'AInstancedFoliageActor'
1>C:\Program Files\Epic Games\UE_4.23\Engine\Source\Runtime/Foliage/Public/InstancedFoliageActor.h(67): note: see declaration of 'AInstancedFoliageActor'
1>D:\UE4_test\UE4_test-423\CPP423\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPyFoliage.cpp(71): error C2039: 'FoliageMeshes': is not a member of 'AInstancedFoliageActor'
1>C:\Program Files\Epic Games\UE_4.23\Engine\Source\Runtime/Foliage/Public/InstancedFoliageActor.h(67): note: see declaration of 'AInstancedFoliageActor'
1>D:\UE4_test\UE4_test-423\CPP423\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPyFoliage.cpp(76): error C2065: 'FFoliageMeshInfo': undeclared identifier
1>D:\UE4_test\UE4_test-423\CPP423\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPyFoliage.cpp(76): error C2065: 'info': undeclared identifier
1>D:\UE4_test\UE4_test-423\CPP423\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPyFoliage.cpp(76): error C2039: 'FoliageMeshes': is not a member of 'AInstancedFoliageActor'
1>C:\Program Files\Epic Games\UE_4.23\Engine\Source\Runtime/Foliage/Public/InstancedFoliageActor.h(67): note: see declaration of 'AInstancedFoliageActor'
1>D:\UE4_test\UE4_test-423\CPP423\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPyFoliage.cpp(80): error C2065: 'info': undeclared identifier
1>D:\UE4_test\UE4_test-423\CPP423\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UObject\UEPyFoliage.cpp(114): error C2039: 'GetLocalFoliageTypeForMesh': is not a member of 'AInstancedFoliageActor'
1>C:\Program Files\Epic Games\UE_4.23\Engine\Source\Runtime/Foliage/Public/InstancedFoliageActor.h(67): note: see declaration of 'AInstancedFoliageActor'
1>
1>Error executing C:\Program Files\Epic Games\UE_4.23\Engine\Build\Windows\cl-filter\cl-filter.exe (tool returned code: 2)
’‘’

**Comment by CheapDevotion** [comment]
I'm having the same issue on a fresh clone of the 4.23 source and a new blank project.

**Comment by plecheg** [comment]
I'm having the same.

**Comment by rdeioris** [comment]
Porting should be complete
