### ISSUE TITLE
Force FBX/Asset Import

### ISSUE THREAD

**Issue by LarsGroh** [20tab/UnrealEnginePython#79]
Is there away to force the asset import even though the respective static mesh already existst?

I need to do this as the re-import process is inconsistent when there is a change in the material assignment in the original maya file. For a single import this would not be a problem - but I need to run several hundreds of imports. And having the user to accept each import is not really an option.

**Comment by rdeioris** [comment]
We have a custom factory for fbx here: https://github.com/20tab/UnrealEnginePython/blob/master/Source/PythonConsole/Public/PyFbxFactory.h

if you use it instead of the classic FBXFactory you will shut-down the dialog window

**Comment by LarsGroh** [comment]
Hi,
I am actually already using that factory:
```
factory = ue.find_class('PyFbxFactory')
asset = ue.import_asset(filename, asset_path, factory)
```
But the UI still pops up if there is an already imported asset under the "asset_path".
Note: Im not using asset.reimport() on purpose as that approach causses issues with changing material assignments - as noted above.

**Comment by sinokgr** [comment]
I assume you mean this window right?
![image](https://cloud.githubusercontent.com/assets/22396951/21311144/96dd8070-c5dd-11e6-94ca-7c37229ffdc2.png)
I was planning to use asset.reimport() myself but you've raised a very valid point.. hm

**Comment by LarsGroh** [comment]
Yes! I mean exaclty that window ;-)

**Comment by rdeioris** [comment]
Check here for an update example: https://github.com/20tab/UnrealEnginePython/blob/master/examples/kaiju_builder.py#L20
