### ISSUE TITLE
Python classes extending from Engine classes

### ISSUE THREAD

**Issue by cardonator** [20tab/UnrealEnginePython#8]
One of the major features of Unreal.js that is handy is the ability to create subclasses of Engine classes in js (they are converted to JavascriptDelegateClass and treated similar to Blueprints). The same functionality would be nice in UE4.py as well. 

Assumptions for below example:
- unreal_engine.classes reference to internal C++ classes available to Blueprint
- MyBasePlayer inherit all the "functionality" of the Character with only additions/overrides as specified
- BaseGameMode blueprint having Python component with module = my_base_gamemode, class = MyBaseGameMode

See code example.

**Content/Scripts/my_base_player.py**

``` py
from unreal_engine.classes import Character

class MyBasePlayer(Character):
    def __init__(self):
        super().__init__()
        self.CharacterMovement.MaxWalkSpeed = 1200

    def is_grounded(self):
        return self.CharacterMovement.IsMovingOnGround()
```

**Content/Scripts/my_base_gamemode.py**

``` py
import unreal_engine as ue
from my_base_player import MyBasePlayer

class MyBaseGameMode:
    def __init__(self):
        if self.uobject.get_world().IsServer():
            owner = self.uobject.get_owner()
            owner.DefaultPawnClass = MyBasePlayer()
```

[Here is a link to the Unreal.js method of subclassing](https://github.com/ncsoft/Unreal.js/wiki/Subclassing). Theirs even works with Blueprints, which would be a nice addition at some point as well.

**Comment by rdeioris** [comment]
I think that thanks to the importer pluggable system and metaclasses, 90% of the work can be done in python itself. I will investigate on it soon.

**Comment by rdeioris** [comment]
@cardonator the system is almost complete i have just started writing docs here:

https://github.com/20tab/UnrealEnginePython/blob/master/docs/Subclassing_API.md

**Comment by cardonator** [comment]
Wow, I am very impressed with the progress you've made here! Good job! Let me know when you think it is pretty solid for the case I listed in my original report and I would be happy to test it out in a scenario I have written in Unreal.js that would be extremely easy to port.

**Comment by rdeioris** [comment]
I think the latest subclassing code base is 'robust' enough to allow us to close this issue after 9 months :)

https://github.com/20tab/UnrealEnginePython/blob/master/tutorials/WritingAColladaFactoryWithPython.md

Thanks a lot for your suggestion
