### ISSUE TITLE
How to import python library?(eg.numpy)

### ISSUE THREAD

**Issue by BulletHermit** [20tab/UnrealEnginePython#800]
What do I need to do if I want to import a third-party library（eg. numy）?

**Comment by Schizo** [comment]
Depending on whether you are using embedded python or not, you can use pip to install any package.

**Comment by HanChangHun** [comment]
In my case I added a python path.
```python
import sys
sys.path.append("D:/USER/py36/Lib/site-packages")
sys.path.append("C:/Python27/Lib/site-packages")
```
and It worked.
