### ISSUE TITLE
Is it possible to get BP's variable's changed value from python?

### ISSUE THREAD

**Issue by arafat0007** [20tab/UnrealEnginePython#804]
In blueprint i have a variable of 'array of color array' type. In blueprint graph, i set new values in it and then call python script for further process.

When i access the variable from the python script, i get the initial value of the variable, not the set up ones. Is it possible to get the changed variable value from python.

to get value what i do, 
1. load asset object  `x = ue.load_object(parameter)`
2. then `Array = x.GeneratedClass.get_cdo().ArrayOfBP`

**Comment by jonlm** [comment]
In general you should be able to get blueprint variable value by simply accessing it as a python attribute on the blueprint instance. If I create a variable named "test_color" of type color array in a blueprint and add that blueprint to the scene, I can do this while the blueprint actor is selected:

>>> print(ue.editor_get_selected_actors()[0].test_color[0])
<unreal_engine.FColor {'r': 1, 'g': 1, 'b': 255, 'a': 255}>

In that case there was one item in the array with those values.

BTW, can a BP variable really be an "array of array"? I don't see how to do that.

**Comment by arafat0007** [comment]
hello @jonlm , thank you so much for the response. let me explain more.

![image](https://user-images.githubusercontent.com/10024546/68273402-a1aa7f80-00a9-11ea-95c4-9455e9dfa8e7.png)

i get the pixel values of texture and save it to ’Image Array’ (initially 'Image Array' is empty) just like above picture. But when i tried to get the 'Image Array' variable by 'GeneratedClass.get_cdo().ImageArray' after loading the object just like my texts at question, i get the initial empty array from initial value. I dont get the value stored in 'Image Array' from my C++ function. 

Then I tried with simple things and it seems that, say a variable by default has 10 as value. now, if i change the value from 10 to 20 by set variable node, from python i always get the variable's value as 10, not the set up value 20 which i did in BP graph. 

Image Array is like this,
![image](https://user-images.githubusercontent.com/10024546/68273813-c9e6ae00-00aa-11ea-9f50-cd430dc7f1da.png)

I am not aware of right words and i am beginner and learning. **So, while in runtime, python does not get the changed value, rather gets the default value of editor? is it?**

**Comment by jonlm** [comment]
Look closely at my example above. You need to get a handle to the blueprint instance in your scene. In my example I'm getting that with "ue.editor_get_selected_actors()". Once you are pointing at the instance, accessing the variable with standard python dot notation (i.e. "bp_object.image_array") should give you the instance-modified value.

GeneratedClass.get_cdo() is by definition giving you only the default object, not the instance.

**Comment by arafat0007** [comment]
Here is what i have done.

1.  add an actor in editor. Actor has a test bool variable. default value is true.
![test](https://user-images.githubusercontent.com/10024546/68362032-31fbc980-0169-11ea-8b25-7d90229a1a91.PNG)
2. there is a button onclick in widget. In widget graph i take the actor's test and change it to false. and call python script.
![widget](https://user-images.githubusercontent.com/10024546/68362213-c534ff00-0169-11ea-82ad-698fa73c6123.PNG)
3. In python script, i get actor bp obj and call test which is still true which i changed before. ue.editor_get_selected_actors() returns empty array. 
![python](https://user-images.githubusercontent.com/10024546/68362334-49878200-016a-11ea-9049-344bfaecd65f.PNG)
and result is,
![result](https://user-images.githubusercontent.com/10024546/68362348-560bda80-016a-11ea-8103-e8a9015fa40e.PNG)
Where i am doing mistakes?

**Comment by arafat0007** [comment]
[https://github.com/20tab/UnrealEnginePython/issues/516](url)

by traversing, it is easy to access blueprint and get what is needed
