### ISSUE TITLE
How to get sections in SkeletalMesh? 

### ISSUE THREAD

**Issue by r1ch88** [20tab/UnrealEnginePython#809]
Hi, I want to get the LOD section name in skeletalmesh, but I don't know how to get.
![微信截图_20191118174736](https://user-images.githubusercontent.com/25290176/69042065-88032380-0a2b-11ea-8603-eece8a105491.png)

**Comment by jonlm** [comment]
Example using the selected rig in the content browser:
```
import unreal_engine as ue
from unreal_engine.classes import SkeletalMesh

mesh = ue.get_selected_assets()[0]
if not mesh.is_a(SkeletalMesh):
    raise Exception('the script only works with Skeletal Meshes')

for m in mesh.Materials:
    print(m.MaterialSlotName)
```

**Comment by r1ch88** [comment]
@jonlm thanks
