### ISSUE TITLE
Create Empty Actors

### ISSUE THREAD

**Issue by sinokgr** [20tab/UnrealEnginePython#81]
Hi guys,

While I can find a lot of functions for manipulating existing Actors, adding components etc, I can't find anything about creating new ones. What I want to do, is to import an FBX using the functions you provide and then create and Actor from the Asset.

Thanks,
Nick

**Comment by rdeioris** [comment]
```py
import unreal_engine as ue
editor_world = ue.get_editor_world()
new_actor = ue.actor_spawn(ue.find_class('YourClass'))
```

**Comment by sinokgr** [comment]
Oh, I see! I didn't know that it's called spawn. I was looking for "create" similar to unreal_engine.create_blueprint().

Just fixed the code you provided a bit, for anyone else who might have the same question.
```py
import unreal_engine as ue
editor_world = ue.get_editor_world()
new_actor = editor_world.actor_spawn(ue.find_class('Actor'))
```

Thanks

**Comment by sinokgr** [comment]
@rdeioris, I wrote a piece of code and it behaves a bit and I was wondering if it's just me doing something wrong or if it's a bit buggy.

The following code, correctly imports the asset and correctly creates the actor.

- The first weird thing is that the object is not displayed until I change any property in the "Details" - it's like I need to do some sort of refresh/update.
- The second weird thing is that even though I change the Actor name, the editor displays the default name. When I print all the Actor names, it seems that it prints the correct name.
- Last thing, if I reload the module, Unreal instantly crashes. 

```py
import unreal_engine as ue
from unreal_engine.classes import StaticMeshActor, PyFbxFactory, FbxImportUI
import os

def fbx_import(filename, asset_path):
    if os.path.exists(filename):
        actor_name = os.path.splitext(os.path.basename(filename))[0]

        editor_world = ue.get_editor_world()
        fbx_import_ui = ue.new_object(FbxImportUI)

        ue.set_fbx_import_option(fbx_import_ui)
        asset = ue.import_asset(filename, asset_path, PyFbxFactory)

        new_actor = editor_world.actor_spawn(StaticMeshActor)
        new_actor.set_name(actor_name)

        static_mesh_component = new_actor.get_property('StaticMeshComponent')
        static_mesh_component.set_property('StaticMesh', asset)


def print_actor_names():
    editor_world = ue.get_editor_world()
    for actor in editor_world.all_actors():
        ue.log(actor.get_name())


fbx_import("C:/Users/n.moutafis/Desktop/Teapot.FBX", "/Game/MyTeapot")
print_actor_names()
```

**Comment by rdeioris** [comment]
You can call post_edit_change() on the actor or package_is_dirty(). The name of the actor in the editor is the 'label' not the name. And it is available only in the editor. You can set/read it with set_actor_label()/get_actor_label()

Instead of reloading the module can you try simply calling ue.exec('file') ?

**Comment by sinokgr** [comment]
Hi @rdeioris, sorry for the late reply, I just wanted to make sure that I would finish the part I was working and I wouldn't have any further questions on this point.
The bit that it was crashing Unreal was the actor.set_name("name"). When I switched to just changing the label, everything returned back to normal. Couldn't use the ue.exec('file') for some reason, but thankfully, I didn't have to. If you are interested to investigate the bug with set_name and want my help, please feel free to let me know and keep the ticket open. Otherwise, the set_actor_label worked fine for me.

**Comment by sinokgr** [comment]
When I create an empty actor, I'm getting the following message and I can't change the "movable" to "static" option. Any ideas how to fix that?

```py
parent_actor = editor_world.actor_spawn(Actor)
parent_actor.add_actor_component(SceneComponent, "DefaultSceneRoot")
```
![image](https://user-images.githubusercontent.com/22396951/28630811-30547f64-7223-11e7-8c37-caceab2e3d34.png)

**Comment by rdeioris** [comment]
Once you create a component from the low-level api (read: not from a blueprint) you can work on it only using the low level api:

```python
from unreal_engine.enums import EComponentMobility

# can Be Static, Stationary or Movable
scene_component.Mobility =  EComponentMobility.Static
```

**Comment by sinokgr** [comment]
I won't pretend I understood exactly what you just said, but it worked great! Thanks :)
