### ISSUE TITLE
CANNOT use PySide2!

### ISSUE THREAD

**Issue by AgenteDog** [20tab/UnrealEnginePython#825]
Hey so I have been trying to use Qt5/Pyside2 but I just dont get how to actually start using it. It says stuff like ue4lib, PySide2 and qtWidget are missing and do not exist. I tried installing PySide2 and qt5 in the Win64 folder but it seems like the ue4lib is missing.

Is there a way for me to download a version of the plugin that comes with this things integrated? Am I doing something Wrong? Pls help.

PD: I am using unreal engine 4.21 python version 3.6.2

**Comment by varomix** [comment]
PySide2 is not included  you need to install them locally and add the path so you can use it, then just use the example from the front page

**Comment by AgenteDog** [comment]
Hey, how about the ue4 widget? I tried what you just said and didnt work. Also, add the path where, to the plugin path or from the plugin to my pc.

**Comment by idanyekutiel** [comment]
"PySide2 is not included you need to install them locally and add the path so you can use it, then just use the example from the front page" after some time, this did work. I had the embedded version so that was the problem!
