### ISSUE TITLE
Packaging for mac - libpython3.5m.dylib was in manifest but was not produced

### ISSUE THREAD

**Issue by Pepin-** [20tab/UnrealEnginePython#84]
Hi,
When I attempt to package my UE4 project for mac, I get the following error

Helper: Packaging (Mac): Program.Main: ERROR: AutomationTool terminated with exception: AutomationTool.AutomationException: BUILD FAILED /[path to project]/Binaries/Mac/[ProjectName].app/Contents/MacOS/libpython3.5m.dylib was in manifest but was not produced.

Any ideas?

**Comment by rdeioris** [comment]
Thanks for reporting, i'll check it

**Comment by rdeioris** [comment]
Unfortunately it looks like a bug with ue4 plugin system on the mac. I am looking for a workaround

**Comment by rdeioris** [comment]
Ok, the problem has been fixed, we are now able to release binary packages too
