### ISSUE TITLE
Compile Source code with Embed python?

### ISSUE THREAD

**Issue by woshisck** [20tab/UnrealEnginePython#841]
hi I wonder if there is any way to change the UnrealEnginePython.Build.cs file to make it enable to compile access the embed python file since embedpython doesn't have a lib file, what should I change to do the compile ?

**Comment by hoATwhiskytree** [comment]
I've built mine with Python 3.6.5. Once you are done compiling, you can download the Python 3.6.5 embed package and copy it's content into your binary folder. I've been able to move this plugin into another machine, and it has been working fine....so far.

**Comment by woshisck** [comment]
oh

> I've built mine with Python 3.6.5. Once you are done compiling, you can download the Python 3.6.5 embed package and copy it's content into your binary folder. I've been able to move this plugin into another machine, and it has been working fine....so far.
oh thx, thought it needs to compile with the embeded version :D
