### ISSUE TITLE
Detecting master material.

### ISSUE THREAD

**Issue by idanyekutiel** [20tab/UnrealEnginePython#844]
Hi, is there a way to detect the master material of an instance and get the name or location of it? And once you have done that, is there a way to change the master material of an instance?

**Comment by hoATwhiskytree** [comment]
It's a bit confusing, but "parent" is what you are looking for. If I remember correctly you can get the current master mtl and set it as well.

**Comment by AgenteDog** [comment]
Searching through the docs I found options to set the parent, but, not to identify the parent name of an instance. 

Maybe I was looking for the wrong thing but that is what I found.

**Comment by idanyekutiel** [comment]
It seems like
 ```python
material_instance.Parent
``` 

works. Thank you!
