### ISSUE TITLE
Installation on windows without visual studio

### ISSUE THREAD

**Issue by datalin** [20tab/UnrealEnginePython#85]
Is it possible to use this UnrealEnginePython on windows without visual studio? I would like to avoid installing visual studio if possible.

**Comment by rdeioris** [comment]
I suppose we can distribute binaries, i only need to check with Epic if we violates something at the license level

**Comment by rdeioris** [comment]
Hi, i have started dropping binaries here: https://github.com/20tab/UnrealEnginePython/releases/
