### ISSUE TITLE
Actor parent

### ISSUE THREAD

**Issue by sinokgr** [20tab/UnrealEnginePython#86]
Hi there,
I'm trying to create some actor hierarchies.
Let's assume that we have two actors selected and you want to set the parent_actor as parent to the child_actor. I've tried the following but it gives me an error "uobject is not a UMaterialInstanceConstant"
```py
import unreal_engine
child_actor = unreal_engine.editor_get_selected_actors()[0]
parent_actor = unreal_engine.editor_get_selected_actors()[1]
child_actor.set_parent(parent_actor)
```

I then tried to manually link the two actors in the Editor and then tried to read the 'children' property but it returns an empty array. 
```py
ue.log(mesh.get_property('children'))
[]
```
Any ideas? thanks

**Comment by rdeioris** [comment]
Hi, set_parent() is for materials (unfortunate naming ;) you have to use

'''py
object1.attach_to_actor(object2)
'''

**Comment by sinokgr** [comment]
Oh, I usually do that by dragging, didn't know that it's called "attach" in Unreal! Cheers, worked fine! :) You can close the issue.

**Comment by sinokgr** [comment]
quick question: I can't get the Actor's parent. The [GetAttachParentActor](https://docs.unrealengine.com/latest/INT/API/Runtime/Engine/GameFramework/AActor/GetAttachParentActor/index.html) is missing and the only way I found to get the parent, is by going through the Root Component. This doesn't return an Actor though, it returns the parent's Root Component
```py
child_actor.RootComponent.GetAttachParent()
```
Am I missing something?
