### ISSUE TITLE
Levels and sub-levels

### ISSUE THREAD

**Issue by sinokgr** [20tab/UnrealEnginePython#87]
Hi there,

Can you please add support to create levels and sub-levels?
I want if possible to be able to create sub-levels to my current level and add actors there.

Cheers,
Nick

**Comment by rdeioris** [comment]
Wow it was hard, i finally grasped how the whole level structure works. The support is pretty raw but should be a good base:

```py
import unreal_engine as ue
from unreal_engine.classes import WorldFactory

factory =  WorldFactory()
new_Level = factory.factory_create_new('/Game/NewLevel001')
```

this will create a new level asset (well it is a world !)

You can access levels of a world with the new get_levels() function (it returns a list of levels)

To add a level to a world:

```py
ue.add_level_to_world(world, '/Game/name_of_the_level_asset'[, persistent])
```

(set persistent as True, if you want your level to be always loaded)


Finally to move actors between levels:

```py
ue.move_selected_actors_to_level(level)
```

well, this is annoying because it is teh same api used in the editor, so it works only for selected actors.

Lucky enough we already have the selection api:

```py
actor = world.actor_spawn(Actor)
ue.editor_select_actor(actor)
ue.move_selected_actors_to_level(level)
```

absolutely not the most handy api, but currently i do not see too much other solutions

**Comment by sinokgr** [comment]
Many thanks for all your efforts @rdeioris ! Sorry this gave you such a hard time!

The level creation bit works great! I'm having a few issues with part that moves the actors to the level though.
I couldn't find a function named **move_selected_actors_to_level** and the closest function I found was [this ](https://github.com/20tab/UnrealEnginePython/blob/0a00e906bbd3a32d0f6d5e8a70cbf80025357382/Source/UnrealEnginePython/Private/UEPyModule.cpp#L172), a function with the python name "move_actor_to_level". This function though requires two arguments and I can't figure out which.
Btw, would it be possible to have a version where you can pass the Actors without the need to select them - selecting is not the fastest approach most of the times?

Sample code I tried:
```py
import unreal_engine as ue
from unreal_engine.classes import WorldFactory, StaticMeshActor

world = ue.get_editor_world()
new_Level = WorldFactory().factory_create_new('/Game/Levels/PyLevel')
ue.add_level_to_world(world, '/Game/Levels/PyLevel')

actor = world.actor_spawn(StaticMeshActor)
ue.editor_select_actor(actor)
ue.move_actor_to_level(new_Level)
```
Returns:
TypeError: move_selected_actors_to_level() takes exactly 2 arguments (1 given)


PS. sorry if this sounds stupid, but what is the syntax to make the level persistent? Using ue.add_level_to_world(world, '/Game/Levels/PyLevel', False) or ue.add_level_to_world(world, '/Game/Levels/PyLevel', True) doesn't seem to make a difference - or I'm looking to wrong place.

**Comment by rdeioris** [comment]
Hi, i have fixed the function (both its name and the number of arguments)

**Comment by sinokgr** [comment]
Awesome! Many thanks @rdeioris, I'll go try it now. Yeah, I've noticed that about the Levels window. I keep closing it and re-opening it for now.

**Comment by sinokgr** [comment]
Hm.. I know get an error saying: 
**ue.move_selected_actors_to_level(new_Level)
Exception: argument is not a ULevelStreaming**

```py
import unreal_engine as ue
from unreal_engine.classes import WorldFactory, StaticMeshActor

world = ue.get_editor_world()
new_Level = WorldFactory().factory_create_new('/Game/Levels/PyLevel')
ue.add_level_to_world(world, '/Game/Levels/PyLevel')

actor = world.actor_spawn(StaticMeshActor)
ue.editor_select_actor(actor)
ue.move_selected_actors_to_level(new_Level)
```

**Comment by sinokgr** [comment]
Hi @rdeioris , I'm bringing up this again.
I haven't tried to assign actors to a level this time and I haven't used it since my last post, but I tried to the a level by name, but it looks like something is not working in the levels. For example, I have these three levels that have different colors and names
![image](https://user-images.githubusercontent.com/22396951/27580465-9b27d948-5b22-11e7-82de-179dd9b5ede4.png)
but when I run the following script
```python
import unreal_engine as ue
from unreal_engine.classes import WorldFactory

world = ue.get_editor_world()
levels = world.get_levels()
for level in levels:
	print ("--------------"  + level.get_name() + "--------------")
	print level.LevelColor
```
I'm getting

> --------------PersistentLevel--------------
<unreal_engine.FLinearColor {'r': 1.0, 'g': 1.0, 'b': 1.0, 'a': 1.0}>
--------------PersistentLevel--------------
<unreal_engine.FLinearColor {'r': 1.0, 'g': 1.0, 'b': 1.0, 'a': 1.0}>
--------------PersistentLevel--------------
<unreal_engine.FLinearColor {'r': 1.0, 'g': 1.0, 'b': 1.0, 'a': 1.0}>

I'm guessing it finds the number of levels - as I'm getting three as well - but it doesn't iterate and it only returns the first one.

Can you please have a look?

**Comment by rdeioris** [comment]
The level api has been added and documented: https://github.com/20tab/UnrealEnginePython/blob/master/docs/Level_API.md
