### ISSUE TITLE
keyboard input

### ISSUE THREAD

**Issue by anmol438** [20tab/UnrealEnginePython#875]
How do I detect keyboard input with python. I want do some movement when a keyboard key is detected by the script. Can anyone help in this?

Thank You

**Comment by UtkarshMoholkar** [comment]
![image](https://user-images.githubusercontent.com/67200103/147943164-5a467df8-afd5-4cca-9a41-955aeb597b5c.png)
Details > input > Auto Receive Input

Make it "Player 0" (By default it is disabled) 
Please refer screenshot.
I hope this may help.

**Comment by anmol438** [comment]
Thanks @UtkarshMoholkar,
I wanted to detect keyboard input by python scripting. I have found the solution. I installed keyboard module with pip which give some functions to detect the keyboard responses.
