### ISSUE TITLE
console command history

### ISSUE THREAD

**Issue by tuesy** [20tab/UnrealEnginePython#88]
I noticed that if you press the Up Arrow key in an "Output Log" window, you get a command history while in the Python Console, you don't get that. Is there a workaround to have that? Would save me a lot of typing. Thanks!

**Comment by rdeioris** [comment]
My dream is having IPython integration, but history would be a good start :) I will work on it pretty soon

**Comment by rdeioris** [comment]
console history has been implemented :)

**Comment by matthewkapfhammer** [comment]
I was getting frustrated by this on Friday. Nice work!!

**Comment by rdeioris** [comment]
Yeah, it has been probably the true most needed feature :)

**Comment by matthewkapfhammer** [comment]
Any chance this commit is going to make into tomorrow's binaries? : D

**Comment by rdeioris** [comment]
Yes i am preparing the binaries right now, this time i would like to release osx and python2.7 binaries too so it will require a bit more but absolutely i will issue a release in a couple of hours

**Comment by rdeioris** [comment]
First round of binary releases is available https://github.com/20tab/UnrealEnginePython/releases/tag/0.3

Check updated main README for notes in which file to download
