### ISSUE TITLE
Problem with setup on macOS Sierra

### ISSUE THREAD

**Issue by davidkhess** [20tab/UnrealEnginePython#89]
I followed the directions on how to install on macOS Sierra and Unreal Editor doesn't seem to recognize the Plugins folder nor attempt to build them.

o New MacBook Pro 2016
o Xcode 6, 7 and 8 are all on the system
o Followed the directions for a blank C++ project and it does compile and run

Any ideas?

**Comment by rdeioris** [comment]
can you paste your current project directory structure ? by the way we will start releasing binary packages even for osx soon

**Comment by davidkhess** [comment]
<img width="832" alt="screen shot 2016-12-18 at 2 05 40 pm" src="https://cloud.githubusercontent.com/assets/184167/21296174/1a6a0a66-c52b-11e6-9f6b-547d5a36f6d7.png">

**Comment by rdeioris** [comment]
All looks good, so basically your project starts without prompting you with the plugin build dialog ?

**Comment by davidkhess** [comment]
Correct. And when I look in the log, I remember the first time I tried it said that it was reading UnrealEnginePython.uplugin. Every time I open the project after that, I don't see that message.

**Comment by davidkhess** [comment]
I believe Python 3.5 is installed correctly also:

```
(flask)dhess@Tilsit-3:[~/Desktop]$ ls -al /Library/Frameworks/Python.framework/Versions/3.5/
total 12192
drwxrwxr-x   9 root  admin      306 Dec 15 20:50 .
drwxrwxr-x   3 root  wheel      102 Jun 26 12:49 ..
lrwxr-xr-x   1 root  admin       18 Dec 15 20:50 Headers -> include/python3.5m
-r-xrwxr-x   1 root  admin  6235360 Jun 26 12:48 Python
drwxrwxr-x   5 root  admin      170 Jun 26 12:49 Resources
drwxrwxr-x  21 root  admin      714 Dec 15 20:51 bin
drwxrwxr-x   3 root  admin      102 Jun 26 12:49 include
drwxrwxr-x  14 root  admin      476 Dec 15 20:50 lib
drwxrwxr-x   4 root  admin      136 Jun 26 12:49 share
(flask)dhess@Tilsit-3:[~/Desktop]$ 
```

**Comment by davidkhess** [comment]
The Epic Games Launcher is giving me Unreal Engine 4.14.1.

**Comment by davidkhess** [comment]
Well, just tried it again and this time I see this in the log:

```
LogPluginManager: Loaded Plugin UnrealEnginePython, From /Users/dhess/Documents/Unreal Projects/MyProject2/Plugins/UnrealEnginePython/UnrealEnginePython.uplugin
```

But the dialog box never pops up and nothing gets built.

**Comment by davidkhess** [comment]
Ok, every time I went to the Plugins panel, it never listed the project level plugin. This time it finally did and I was able to enable it and then restart – and it gave me the dialog to build the plugins.

So I think there was something wrong on my system and it would help to include in the directions the need to go into the Plugins panel and find and enable the plugin at the project level.

**Comment by davidkhess** [comment]
Other than the documentation addition to add a step to enable the plugin, I think this was mainly pilot error.
