### ISSUE TITLE
Setting Property "OverrideMaterials" error wth NoneType

### ISSUE THREAD

**Issue by LarsGroh** [20tab/UnrealEnginePython#90]
I am trying to set the MaterialOverrides Property of a StaticMeshComponent.

When I retrieve the value,  NoneTypes show up in the value list.
So I assumed I can also set them. But I got this error:

```
component.MaterialOverrides = [None, mat]
ValueError: invalid value for UProperty
```
NOTE: "mat" is a valid reference to a Material.

How Do I need to this in order not to set an override on a specific index?

**Comment by sinokgr** [comment]
Haven't tried it with this specific property, but normally the way to get/set values to properties is with the get_property(prop_name) and set_property(prop_name, value) functions.

```py
component.get_property("OverrideMaterials")
component.set_property("OverrideMaterials", material_list)
```

**Comment by LarsGroh** [comment]
@sinokgr : thanks for the reply, but accessing the Properties by using the setter and getter methods instead of the (python)-properties does not solve this. The issue lies within the value that is being set - in your example "material_list".
My described error occurs as my "material_list" contains None-Type values, which I do intentionally as in most cases not all materials have corresponding material overrides.

**Comment by sinokgr** [comment]
Oh sorry, I get what you mean. I played a bit and it indeed acts a bit weird.
I also tried the following and it returns **unable to convert pyobject to property Material (ObjectProperty)**
```Py
ue.editor_get_selected_actors()[0].rootComponent.SetMaterial(0, None)
```
but when I try to get the material it returns None (when material is missing)
```Py
ue.editor_get_selected_actors()[0].rootComponent.GetMaterial(0)
```

**Comment by LarsGroh** [comment]
Sorry for the lack of reply!
Could you come up with a solution for this one?

**Comment by unbit** [comment]
Latest versions have full array support:

```python
from unreal_engine.classes import MaterialFactoryNew

factory = MaterialFactoryNew()
mat001 = factory.factory_create_new('/Game/Foobar')

ue.editor_get_selected_actors()[0].rootComponent.OverrideMaterials = [mat001]
```

**Comment by LarsGroh** [comment]
Alright, I give it a try.
Just note that the initial issue was not setting an array. The issue was setting an array that contains None values. But I will test it!
Thanks for the reply and the amazing work you guys put into this plugin!
