### ISSUE TITLE
Collision + Collision complexity

### ISSUE THREAD

**Issue by sinokgr** [20tab/UnrealEnginePython#91]
Hi guys,

Does anyone has any ideas how to access those? The GUI if from the content browser of an FBX asset.
![image](https://cloud.githubusercontent.com/assets/22396951/21348636/f2ce91ee-c6a5-11e6-9645-8b6100428527.png)

**Comment by sinokgr** [comment]
found the collision complexity. For anyone interested you can found it here
```py
StaticMesh.BodySetup.CollisionTraceFlag = 3
```

**Comment by sinokgr** [comment]
for the Collision, I found that it's part of the [FMeshSectionInfo](https://docs.unrealengine.com/latest/INT/API/Runtime/Engine/Engine/FMeshSectionInfo/index.html) and I found [this](https://answers.unrealengine.com/questions/465376/access-to-mesh-data-in-object-via-c.html) that might help.
Any idea if I can change this property in Python?

**Comment by rdeioris** [comment]
Hi, added static_mesh_set_collision_for_lod  and static_mesh_set_shadow_for_lod:

```py
static_mesh_set_collision_for_lod(lod_index, material_index, bool)
static_mesh_set_shadow_for_lod(lod_index, material_index, bool)
```

Example

```py
cone = ue.load_obect(StaticMesh, '/Engine/BasicShapes/Cone')
cone.static_mesh_set_collision_for_lod(0, 0, False)
ue.editor_save_all()
```

**Comment by sinokgr** [comment]
Hey @rdeioris, I just tested and it works great!
Many thanks for that!
