### ISSUE TITLE
Plugin 'UnrealEnginePython' failed to load

### ISSUE THREAD

**Issue by pansuria** [20tab/UnrealEnginePython#92]
I added UnrealEnginePython to our UE4 project, got it building (seemingly successfully), and enabled it in the editor.  However, when launching the editor after that, I get the following error:

"Plugin 'UnrealEnginePython' failed to load because module 'UnrealEnginePython' could not be loaded.  There may be an operating system error or the module may not be properly set up."

The dll looks good and appears to be properly built for Windows: 
[dlls.zip](https://github.com/20tab/UnrealEnginePython/files/664569/dlls.zip)

Has anybody run into this before?

Thanks in advance!
Sachin

**Comment by unbit** [comment]
Hi ensure you have python35.dll in your Binaries/Win64 directory. Eventually consider using a binary distribution (feel free to propose alternative versions in addition to the ue4.14/py3.5 combo)

**Comment by pansuria** [comment]
Thanks, that was it!

**Comment by sinokgr** [comment]
@unbit if you could have py2.7 distributions as well, that would be great as most DCC apps still use 2.7.
