### ISSUE TITLE
Getting properties

### ISSUE THREAD

**Issue by CountZer0** [20tab/UnrealEnginePython#93]
Hello. I'm doing initial tests for getting and setting properties on our assets. I have 'mySkelMesh' loaded in the editor, and yet most of the properties do not return correct/any values.

A couple of the propeties return values:
`import unreal_engine`
`skelMesh = unreal_engine.find_object('mySkelMesh')`
`unreal_engine.log(skelMesh)`
<unreal_engine.UObject 'mySkelMesh' (0x000001E1064BDF00) UClass 'SkeletalMesh'>
`unreal_engine.log(skelMesh.Skeleton)`
<unreal_engine.UObject 'Base_Skeleton' (0x000001E12DC18400) UClass 'Skeleton'>
`unreal_engine.log(skelMesh.Materials)`
[<unreal_engine.UObject object at 0x000001E122EC4DB0>, <unreal_engine.UObject object at 0x000001E122EC4DB0]

But the all-important SourceFilePath does not return anything:

`unreal_engine.log(skelMesh.SourceFilePath)`

nor does .LODInfo return accurate values set to 2.0 with the editor:

`unreal_engine.log(skelMesh.LODInfo[0].ScreenSize)`

returns: 1.1674562077543703e-26

If it helps, you can use this to list the values of all the properties on this SkelMesh too:
`for property in skelMesh.properties():`
`....unreal_engine.log('{0} is: {1}'.format(property,skelMesh.get_property(property)))`

Do you have any suggestions?
Thank you.

**Comment by rdeioris** [comment]
Hi, regarding SourceFilePath (if i remember correctly) it is a field of AssetData, it does not show as a valid property of SkeletalMesh (or its parents).

What is strange is the skelMesh.LODInfo[0].ScreenSize that does not return the value you set. I'll check it.

Thanks for reporting

**Comment by rdeioris** [comment]
This has been fixed thanks to proper structs support in latest releases
