### ISSUE TITLE
Using ue_site.py to setup environment

### ISSUE THREAD

**Issue by CountZer0** [20tab/UnrealEnginePython#95]
It seems that nothing imported or defined in ue_site.py stays in the scope of the Python console. i.e. - you cannot pre-import with this line in ue_site:
`import unreal_engine as ue`

and then just be able to start using the alias "ue" in the console:
`ue.log('hello world')`

So it's pretty much just for adding to sys.path, then?

**Comment by rdeioris** [comment]
Hi, yes the scope is the one of an imported module but if you call ue.exec() in ue_site.py its scope will be the same of the console

**Comment by CountZer0** [comment]
Cool. I'll
`import unreal_engine as ue`
in another file and exec() it from ue_site.py to have that alias available in the console right away.

FYI, cannot really call most (any?) of the functions on unreal_engine module in the ue_site.py because you usually get 'Exception: unable to find classes', etc. Probably too early in boot-up cycle?
