### ISSUE TITLE
Save all

### ISSUE THREAD

**Issue by sinokgr** [20tab/UnrealEnginePython#96]
Hi there,

Last issue for this year! 😄 
Can you please expose "Save All" to Python please. By default the "Save all" gives you dialog. I would like to have the option to "Save all" without popping up a dialog. The purpose of that is to Save All and then start packaging the project.

Anyway, Merry Xmas guys! Many thanks for your efforts this year! Happy new year! 🎄

**Comment by rdeioris** [comment]
https://github.com/20tab/UnrealEnginePython/commit/18062da1a6611cecc7d440366678af0acb793157

This commit adds:

unreal_engine.editor_save_all()
unreal_engine.editor_command_save_current_level()
unreal_engine.editor_command_save_all_levels()

**Comment by sinokgr** [comment]
Awesome! Thanks @rdeioris ! I'll have a look next week when I return to the office. If you have any time, pls have a look the issues #91 and #94! Cheers

**Comment by sinokgr** [comment]
Hey @rdeioris, I tested the unreal_engine.editor_save_all() and it works fine, thanks. Do you know if and when you could check the issues #91 and #94 cause they are a bit of a show stopper for me right now (especially #91).
Cheers,
Nick

**Comment by rdeioris** [comment]
@sinokgr i should work on both tomorrow. If you are interested in speeding up things we have just opened commercial support for UnrealEnginePython plugin, just drop a mail to info at 20tab at com when you have specific requests.

**Comment by sinokgr** [comment]
@rdeioris awesome! many thanks for that! That sounds great! I'll drop you an email in a bit.
