### ISSUE TITLE
How to pass parameters?

### ISSUE THREAD

**Issue by tuesy** [20tab/UnrealEnginePython#98]
In your example:

```
import unreal_engine as ue

ue.log('Hello i am a Python module')

class Hero:

    # this is called on game start
    def begin_play(self):
        ue.log('Begin Play on Hero class')

    # this is called at every 'tick'    
    def tick(self, delta_time):
        # get current location
        location = self.uobject.get_actor_location()
        # increase Z honouring delta_time
        location.z += 100 * delta_time
        # set new location
        self.uobject.set_actor_location(location)
```

How would you parameterize the integer, 100? For example, what if I wanted 3 "Hero's" that rose at different rates? Thanks!

**Comment by unbit** [comment]
Add properties to the blueprint, you can then access them via reflection: https://github.com/20tab/UnrealEnginePython/#native-methods-vs-reflection

**Comment by tuesy** [comment]
Maybe I'm missing a concept...I created a blueprint and then tried to spawn an actor using that class rather than PyActor like this:

```
bp = ue.load_object(ue.find_class('Blueprint'), '/Game/Blueprints/BP_Mesh01')
ue.get_editor_world().actor_spawn(bp)
```
I can see that `bp` is my class and seems to have loaded properly. However, when I try to spawn the actor, the editor crashes.

**Comment by tuesy** [comment]
Took a while but got it working. I named my public blueprint variable "MyInt" and then in my python classes read/write it using `self.uobject.MyInt`. What was confusing in the documentation were two snippets:

```
        # the following two values were originally implemented as blueprint variable
        self.base_turn_rate = 45.0
        self.base_look_up_rate = 45.0
```

and 

```
class Hero(Character):

    # you can set it from the editor
    UpSpeed = FloatProperty
```

I didn't do the latter at all. When would that be used?

**Comment by unbit** [comment]
The latter is for native class support:

https://github.com/20tab/UnrealEnginePython/blob/master/docs/Subclassing_API.md

The first form instead is for pure python attributes, something not accessible natively by blueprints

**Comment by tuesy** [comment]
Ahhh...that makes more sense now. I didn't understand the distinction between Pure vs Native vs Blueprint. Thanks!
