### ISSUE TITLE
Using return nodes

### ISSUE THREAD

**Issue by Tibo669** [20tab/UnrealEnginePython#99]
Hi,

I'm having an issue using blueprint's functions. I am trying to use return nodes to get variables values in my python script. But I can't figure how to use it.

So I have created a function with a 3D Vector input and no output. It works fine when called from python script like that :
new_actor.call_function('setColor', "X=" + str(player.color_r) + " Y=" + str(player.color_g) + " Z=" + str(player.color_b))

But when I try to add an output of any kind (String, Integer ...) I get an error :
" File "E:/Puzzle/Unreal Engine/Test_python/Content/Scripts\keyboardcontrol.py", line 34, in spawn
+ " Z=" + str(player.color_b))
TypeError: not enough arguments"

When I had a parameter to my function call (just an empty string "") it seems to work (I don't understand why it needs an other parameter ?). Though the output of the function is None, so still not what I want.

Any ideas how I should do this ?

**Comment by rdeioris** [comment]
Can you try the non-keywords variant ?

```py
new_actor.call_function('setColor',  FVector(x, y, z))
```

**Comment by Tibo669** [comment]
Didn't find how to use the non keyword variant, I always get this error : 
TypeError: unable to convert pyobject to property

I called my function this way :
`new_actor.call_function('setColor',  FVector(1.0, 1.0, 1.0))`

And set the input of the blueprint function setColor to Vector and String, with reference input or not, still get this error.

**Comment by Tibo669** [comment]
Just an update after a 2 months break.
I updated my version of UnrealEnginePython, everything seems to work now. Calling a BlueprintObject's function correctly returns the variable it is supposed to.
